*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/ARANY_FELDV................................*
FORM GET_DATA_/ZAK/ARANY_FELDV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/ARANY_FELD WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/ARANY_FELDV .
/ZAK/ARANY_FELDV-MANDT =
/ZAK/ARANY_FELD-MANDT .
/ZAK/ARANY_FELDV-BUKRS =
/ZAK/ARANY_FELD-BUKRS .
/ZAK/ARANY_FELDV-GJAHR =
/ZAK/ARANY_FELD-GJAHR .
/ZAK/ARANY_FELDV-BBELNR =
/ZAK/ARANY_FELD-BBELNR .
/ZAK/ARANY_FELDV-BGJAHR =
/ZAK/ARANY_FELD-BGJAHR .
/ZAK/ARANY_FELDV-AS4USER =
/ZAK/ARANY_FELD-AS4USER .
/ZAK/ARANY_FELDV-AS4DATE =
/ZAK/ARANY_FELD-AS4DATE .
/ZAK/ARANY_FELDV-AS4TIME =
/ZAK/ARANY_FELD-AS4TIME .
<VIM_TOTAL_STRUC> = /ZAK/ARANY_FELDV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/ARANY_FELDV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/ARANY_FELDV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/ARANY_FELDV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/ARANY_FELD WHERE
  BUKRS = /ZAK/ARANY_FELDV-BUKRS AND
  GJAHR = /ZAK/ARANY_FELDV-GJAHR AND
  BBELNR = /ZAK/ARANY_FELDV-BBELNR AND
  BGJAHR = /ZAK/ARANY_FELDV-BGJAHR .
    IF SY-SUBRC = 0.
    DELETE /ZAK/ARANY_FELD .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/ARANY_FELD WHERE
  BUKRS = /ZAK/ARANY_FELDV-BUKRS AND
  GJAHR = /ZAK/ARANY_FELDV-GJAHR AND
  BBELNR = /ZAK/ARANY_FELDV-BBELNR AND
  BGJAHR = /ZAK/ARANY_FELDV-BGJAHR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/ARANY_FELD.
    ENDIF.
/ZAK/ARANY_FELD-MANDT =
/ZAK/ARANY_FELDV-MANDT .
/ZAK/ARANY_FELD-BUKRS =
/ZAK/ARANY_FELDV-BUKRS .
/ZAK/ARANY_FELD-GJAHR =
/ZAK/ARANY_FELDV-GJAHR .
/ZAK/ARANY_FELD-BBELNR =
/ZAK/ARANY_FELDV-BBELNR .
/ZAK/ARANY_FELD-BGJAHR =
/ZAK/ARANY_FELDV-BGJAHR .
/ZAK/ARANY_FELD-AS4USER =
/ZAK/ARANY_FELDV-AS4USER .
/ZAK/ARANY_FELD-AS4DATE =
/ZAK/ARANY_FELDV-AS4DATE .
/ZAK/ARANY_FELD-AS4TIME =
/ZAK/ARANY_FELDV-AS4TIME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/ARANY_FELD .
    ELSE.
    INSERT /ZAK/ARANY_FELD .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/ARANY_FELDV-UPD_FLAG,
STATUS_/ZAK/ARANY_FELDV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/ARANY_FELDV.
  SELECT SINGLE * FROM /ZAK/ARANY_FELD WHERE
BUKRS = /ZAK/ARANY_FELDV-BUKRS AND
GJAHR = /ZAK/ARANY_FELDV-GJAHR AND
BBELNR = /ZAK/ARANY_FELDV-BBELNR AND
BGJAHR = /ZAK/ARANY_FELDV-BGJAHR .
/ZAK/ARANY_FELDV-MANDT =
/ZAK/ARANY_FELD-MANDT .
/ZAK/ARANY_FELDV-BUKRS =
/ZAK/ARANY_FELD-BUKRS .
/ZAK/ARANY_FELDV-GJAHR =
/ZAK/ARANY_FELD-GJAHR .
/ZAK/ARANY_FELDV-BBELNR =
/ZAK/ARANY_FELD-BBELNR .
/ZAK/ARANY_FELDV-BGJAHR =
/ZAK/ARANY_FELD-BGJAHR .
/ZAK/ARANY_FELDV-AS4USER =
/ZAK/ARANY_FELD-AS4USER .
/ZAK/ARANY_FELDV-AS4DATE =
/ZAK/ARANY_FELD-AS4DATE .
/ZAK/ARANY_FELDV-AS4TIME =
/ZAK/ARANY_FELD-AS4TIME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/ARANY_FELDV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/ARANY_FELDV-BUKRS TO
/ZAK/ARANY_FELD-BUKRS .
MOVE /ZAK/ARANY_FELDV-GJAHR TO
/ZAK/ARANY_FELD-GJAHR .
MOVE /ZAK/ARANY_FELDV-BBELNR TO
/ZAK/ARANY_FELD-BBELNR .
MOVE /ZAK/ARANY_FELDV-BGJAHR TO
/ZAK/ARANY_FELD-BGJAHR .
MOVE /ZAK/ARANY_FELDV-MANDT TO
/ZAK/ARANY_FELD-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/ARANY_FELD'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/ARANY_FELD TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/ARANY_FELD'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
