*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 2006.02.23 at 19:03:04 by user FMCTI00DBG
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LAFA_ATV_MVTOP.               " Global Data
  INCLUDE /ZAK/LAFA_ATV_MVUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LAFA_ATV_MVF00                     . " subprograms
  INCLUDE /ZAK/LAFA_ATV_MVI00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LAFA_ATV_MVF...               " Subprograms
* INCLUDE /ZAK/LAFA_ATV_MVO...               " PBO-Modules
* INCLUDE /ZAK/LAFA_ATV_MVI...               " PAI-Modules

INCLUDE /ZAK/LAFA_ATV_MVF01.
