*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/BNYLAP_V....................................*
FORM GET_DATA_/ZAK/BNYLAP_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/BNYLAP WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/BNYLAP_V .
/ZAK/BNYLAP_V-MANDT =
/ZAK/BNYLAP-MANDT .
/ZAK/BNYLAP_V-BUKRS =
/ZAK/BNYLAP-BUKRS .
/ZAK/BNYLAP_V-BTYPART =
/ZAK/BNYLAP-BTYPART .
/ZAK/BNYLAP_V-NYLAPAZON =
/ZAK/BNYLAP-NYLAPAZON .
/ZAK/BNYLAP_V-DATBI =
/ZAK/BNYLAP-DATBI .
/ZAK/BNYLAP_V-DATAB =
/ZAK/BNYLAP-DATAB .
/ZAK/BNYLAP_V-VPOPKI =
/ZAK/BNYLAP-VPOPKI .
/ZAK/BNYLAP_V-VPOPAR =
/ZAK/BNYLAP-VPOPAR .
/ZAK/BNYLAP_V-GET_ABEVAZ =
/ZAK/BNYLAP-GET_ABEVAZ .
/ZAK/BNYLAP_V-DATUM =
/ZAK/BNYLAP-DATUM .
/ZAK/BNYLAP_V-UZEIT =
/ZAK/BNYLAP-UZEIT .
/ZAK/BNYLAP_V-UNAME =
/ZAK/BNYLAP-UNAME .
<VIM_TOTAL_STRUC> = /ZAK/BNYLAP_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/BNYLAP_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/BNYLAP_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/BNYLAP_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BNYLAP WHERE
  BUKRS = /ZAK/BNYLAP_V-BUKRS AND
  BTYPART = /ZAK/BNYLAP_V-BTYPART AND
  NYLAPAZON = /ZAK/BNYLAP_V-NYLAPAZON AND
  DATBI = /ZAK/BNYLAP_V-DATBI .
    IF SY-SUBRC = 0.
    DELETE /ZAK/BNYLAP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BNYLAP WHERE
  BUKRS = /ZAK/BNYLAP_V-BUKRS AND
  BTYPART = /ZAK/BNYLAP_V-BTYPART AND
  NYLAPAZON = /ZAK/BNYLAP_V-NYLAPAZON AND
  DATBI = /ZAK/BNYLAP_V-DATBI .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/BNYLAP.
    ENDIF.
/ZAK/BNYLAP-MANDT =
/ZAK/BNYLAP_V-MANDT .
/ZAK/BNYLAP-BUKRS =
/ZAK/BNYLAP_V-BUKRS .
/ZAK/BNYLAP-BTYPART =
/ZAK/BNYLAP_V-BTYPART .
/ZAK/BNYLAP-NYLAPAZON =
/ZAK/BNYLAP_V-NYLAPAZON .
/ZAK/BNYLAP-DATBI =
/ZAK/BNYLAP_V-DATBI .
/ZAK/BNYLAP-DATAB =
/ZAK/BNYLAP_V-DATAB .
/ZAK/BNYLAP-VPOPKI =
/ZAK/BNYLAP_V-VPOPKI .
/ZAK/BNYLAP-VPOPAR =
/ZAK/BNYLAP_V-VPOPAR .
/ZAK/BNYLAP-GET_ABEVAZ =
/ZAK/BNYLAP_V-GET_ABEVAZ .
/ZAK/BNYLAP-DATUM =
/ZAK/BNYLAP_V-DATUM .
/ZAK/BNYLAP-UZEIT =
/ZAK/BNYLAP_V-UZEIT .
/ZAK/BNYLAP-UNAME =
/ZAK/BNYLAP_V-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/BNYLAP .
    ELSE.
    INSERT /ZAK/BNYLAP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/BNYLAP_V-UPD_FLAG,
STATUS_/ZAK/BNYLAP_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/BNYLAP_V.
  SELECT SINGLE * FROM /ZAK/BNYLAP WHERE
BUKRS = /ZAK/BNYLAP_V-BUKRS AND
BTYPART = /ZAK/BNYLAP_V-BTYPART AND
NYLAPAZON = /ZAK/BNYLAP_V-NYLAPAZON AND
DATBI = /ZAK/BNYLAP_V-DATBI .
/ZAK/BNYLAP_V-MANDT =
/ZAK/BNYLAP-MANDT .
/ZAK/BNYLAP_V-BUKRS =
/ZAK/BNYLAP-BUKRS .
/ZAK/BNYLAP_V-BTYPART =
/ZAK/BNYLAP-BTYPART .
/ZAK/BNYLAP_V-NYLAPAZON =
/ZAK/BNYLAP-NYLAPAZON .
/ZAK/BNYLAP_V-DATBI =
/ZAK/BNYLAP-DATBI .
/ZAK/BNYLAP_V-DATAB =
/ZAK/BNYLAP-DATAB .
/ZAK/BNYLAP_V-VPOPKI =
/ZAK/BNYLAP-VPOPKI .
/ZAK/BNYLAP_V-VPOPAR =
/ZAK/BNYLAP-VPOPAR .
/ZAK/BNYLAP_V-GET_ABEVAZ =
/ZAK/BNYLAP-GET_ABEVAZ .
/ZAK/BNYLAP_V-DATUM =
/ZAK/BNYLAP-DATUM .
/ZAK/BNYLAP_V-UZEIT =
/ZAK/BNYLAP-UZEIT .
/ZAK/BNYLAP_V-UNAME =
/ZAK/BNYLAP-UNAME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/BNYLAP_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/BNYLAP_V-BUKRS TO
/ZAK/BNYLAP-BUKRS .
MOVE /ZAK/BNYLAP_V-BTYPART TO
/ZAK/BNYLAP-BTYPART .
MOVE /ZAK/BNYLAP_V-NYLAPAZON TO
/ZAK/BNYLAP-NYLAPAZON .
MOVE /ZAK/BNYLAP_V-DATBI TO
/ZAK/BNYLAP-DATBI .
MOVE /ZAK/BNYLAP_V-MANDT TO
/ZAK/BNYLAP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/BNYLAP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/BNYLAP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/BNYLAP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
