*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/ADONEM_ONRV................................*
FORM GET_DATA_/ZAK/ADONEM_ONRV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/ADONEM_ONR WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/ADONEM_ONRV .
/ZAK/ADONEM_ONRV-MANDT =
/ZAK/ADONEM_ONR-MANDT .
/ZAK/ADONEM_ONRV-BTYPE =
/ZAK/ADONEM_ONR-BTYPE .
/ZAK/ADONEM_ONRV-ADONEM_ONR =
/ZAK/ADONEM_ONR-ADONEM_ONR .
/ZAK/ADONEM_ONRV-ABEVAZ =
/ZAK/ADONEM_ONR-ABEVAZ .
/ZAK/ADONEM_ONRV-AS4USER =
/ZAK/ADONEM_ONR-AS4USER .
/ZAK/ADONEM_ONRV-AS4DATE =
/ZAK/ADONEM_ONR-AS4DATE .
/ZAK/ADONEM_ONRV-AS4TIME =
/ZAK/ADONEM_ONR-AS4TIME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/ADONEM_ONR-BTYPE AND
ABEVAZ = /ZAK/ADONEM_ONR-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/ADONEM_ONRV-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /ZAK/ADONEM_ONRV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/ADONEM_ONRV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/ADONEM_ONRV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/ADONEM_ONRV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/ADONEM_ONR WHERE
  BTYPE = /ZAK/ADONEM_ONRV-BTYPE AND
  ADONEM_ONR = /ZAK/ADONEM_ONRV-ADONEM_ONR .
    IF SY-SUBRC = 0.
    DELETE /ZAK/ADONEM_ONR .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/ADONEM_ONR WHERE
  BTYPE = /ZAK/ADONEM_ONRV-BTYPE AND
  ADONEM_ONR = /ZAK/ADONEM_ONRV-ADONEM_ONR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/ADONEM_ONR.
    ENDIF.
/ZAK/ADONEM_ONR-MANDT =
/ZAK/ADONEM_ONRV-MANDT .
/ZAK/ADONEM_ONR-BTYPE =
/ZAK/ADONEM_ONRV-BTYPE .
/ZAK/ADONEM_ONR-ADONEM_ONR =
/ZAK/ADONEM_ONRV-ADONEM_ONR .
/ZAK/ADONEM_ONR-ABEVAZ =
/ZAK/ADONEM_ONRV-ABEVAZ .
/ZAK/ADONEM_ONR-AS4USER =
/ZAK/ADONEM_ONRV-AS4USER .
/ZAK/ADONEM_ONR-AS4DATE =
/ZAK/ADONEM_ONRV-AS4DATE .
/ZAK/ADONEM_ONR-AS4TIME =
/ZAK/ADONEM_ONRV-AS4TIME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/ADONEM_ONR ##WARN_OK.
    ELSE.
    INSERT /ZAK/ADONEM_ONR .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/ADONEM_ONRV-UPD_FLAG,
STATUS_/ZAK/ADONEM_ONRV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/ADONEM_ONRV.
  SELECT SINGLE * FROM /ZAK/ADONEM_ONR WHERE
BTYPE = /ZAK/ADONEM_ONRV-BTYPE AND
ADONEM_ONR = /ZAK/ADONEM_ONRV-ADONEM_ONR .
/ZAK/ADONEM_ONRV-MANDT =
/ZAK/ADONEM_ONR-MANDT .
/ZAK/ADONEM_ONRV-BTYPE =
/ZAK/ADONEM_ONR-BTYPE .
/ZAK/ADONEM_ONRV-ADONEM_ONR =
/ZAK/ADONEM_ONR-ADONEM_ONR .
/ZAK/ADONEM_ONRV-ABEVAZ =
/ZAK/ADONEM_ONR-ABEVAZ .
/ZAK/ADONEM_ONRV-AS4USER =
/ZAK/ADONEM_ONR-AS4USER .
/ZAK/ADONEM_ONRV-AS4DATE =
/ZAK/ADONEM_ONR-AS4DATE .
/ZAK/ADONEM_ONRV-AS4TIME =
/ZAK/ADONEM_ONR-AS4TIME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/ADONEM_ONR-BTYPE AND
ABEVAZ = /ZAK/ADONEM_ONR-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/ADONEM_ONRV-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/ADONEM_ONRV-ABEVTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/ADONEM_ONRV-ABEVTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/ADONEM_ONRV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/ADONEM_ONRV-BTYPE TO
/ZAK/ADONEM_ONR-BTYPE .
MOVE /ZAK/ADONEM_ONRV-ADONEM_ONR TO
/ZAK/ADONEM_ONR-ADONEM_ONR .
MOVE /ZAK/ADONEM_ONRV-MANDT TO
/ZAK/ADONEM_ONR-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/ADONEM_ONR'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/ADONEM_ONR TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/ADONEM_ONR'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/ZAK/ADONEM_ONRV USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/ZAK/ADONEM_ONR-MANDT =
/ZAK/ADONEM_ONRV-MANDT .
/ZAK/ADONEM_ONR-BTYPE =
/ZAK/ADONEM_ONRV-BTYPE .
/ZAK/ADONEM_ONR-ADONEM_ONR =
/ZAK/ADONEM_ONRV-ADONEM_ONR .
/ZAK/ADONEM_ONR-ABEVAZ =
/ZAK/ADONEM_ONRV-ABEVAZ .
/ZAK/ADONEM_ONR-AS4USER =
/ZAK/ADONEM_ONRV-AS4USER .
/ZAK/ADONEM_ONR-AS4DATE =
/ZAK/ADONEM_ONRV-AS4DATE .
/ZAK/ADONEM_ONR-AS4TIME =
/ZAK/ADONEM_ONRV-AS4TIME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/ADONEM_ONR-BTYPE AND
ABEVAZ = /ZAK/ADONEM_ONR-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/ADONEM_ONRV-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/ADONEM_ONRV-ABEVTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/ADONEM_ONRV-ABEVTEXT .
    ENDIF.
ENDFORM.
