*&---------------------------------------------------------------------*
*&  Include           /ZAK/ONJTOP
*&---------------------------------------------------------------------*
TABLES: T001, /ZAK/ONJALV, /ZAK/ONJDATA.

*Előfeldogozás
CONSTANTS C_ONJSTAT_E TYPE /ZAK/ONJSTAT VALUE 'E'.
*Önellenőrzés adóneme
CONSTANTS C_ONELL TYPE /ZAK/ADONEM VALUE '#ONELL#'.

*MAKRO definiálás range feltöltéshez
DEFINE M_DEF.
  MOVE: &2      TO &1-SIGN,
        &3      TO &1-OPTION,
        &4      TO &1-LOW,
        &5      TO &1-HIGH.
  APPEND &1.
END-OF-DEFINITION.

DATA G_BTYPART TYPE /ZAK/BTYPART.

*Önellenőrzéshez adatok:
DATA  I_ONJALV TYPE STANDARD TABLE OF /ZAK/ONJALV INITIAL SIZE 0.
DATA  W_ONJALV TYPE /ZAK/ONJALV.
DATA  I_ONJALV_SAVE TYPE STANDARD TABLE OF /ZAK/ONJALV INITIAL SIZE 0.


DATA  I_TEXT TYPE STANDARD TABLE OF TLINE INITIAL SIZE 0.
DATA  I_ONELL_DATA TYPE STANDARD TABLE OF /ZAK/ONELL_DATA INITIAL SIZE 0.
DATA  W_ONELL_DATA TYPE /ZAK/ONELL_DATA.

DATA  I_MESSAGE TYPE STANDARD TABLE OF SMESG INITIAL SIZE 0.
DATA  W_MESSAGE TYPE SMESG.

DATA  I_/ZAK/ONJDATA TYPE STANDARD TABLE OF /ZAK/ONJDATA INITIAL SIZE 0.
DATA  W_/ZAK/ONJDATA TYPE /ZAK/ONJDATA.

DATA  I_/ZAK/ONJDANA TYPE STANDARD TABLE OF /ZAK/ONJDANA INITIAL SIZE 0.
DATA  W_/ZAK/ONJDANA TYPE /ZAK/ONJDANA.


*Önellenőrzéshez SMARTFORMS adatok:
DATA  W_ONJSMART_DATA LIKE /ZAK/ONJSMARTDAT.


DATA: OK_CODE LIKE SY-UCOMM,
      SAVE_OK LIKE SY-UCOMM,
      G_CONTAINER TYPE SCRFNAME VALUE 'ZSCR_100',
      G_GRID1     TYPE REF TO CL_GUI_ALV_GRID,
      G_CUSTOM_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GS_LAYOUT   TYPE LVC_S_LAYO,
      GS_VARIANT  TYPE DISVARIANT.


DATA: GT_FCAT TYPE LVC_T_FCAT.

DATA: G_REPID LIKE SY-REPID.

DATA: DEF_LAYOUT  TYPE DISVARIANT,     "default layout
      DEFAULT TYPE C VALUE ' ',
      SPEC_LAYOUT TYPE DISVARIANT.

DATA: BEGIN OF I_OUTTAB OCCURS 0.
        INCLUDE STRUCTURE /ZAK/ONJALV.
DATA: CELLTAB TYPE LVC_T_STYL.
DATA: END OF I_OUTTAB.

DATA  W_OUTTAB LIKE I_OUTTAB.

DATA: OK_CODE_101 LIKE SY-UCOMM.
DATA: OK_CODE_102 LIKE SY-UCOMM.
DATA  G_ERROR.

DATA  G_SUBRC LIKE SY-SUBRC.
