*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/PENZT_FORGV................................*
FORM GET_DATA_/ZAK/PENZT_FORGV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/PENZT_FORG WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/PENZT_FORGV .
/ZAK/PENZT_FORGV-MANDT =
/ZAK/PENZT_FORG-MANDT .
/ZAK/PENZT_FORGV-KAZON =
/ZAK/PENZT_FORG-KAZON .
/ZAK/PENZT_FORGV-ZAZON =
/ZAK/PENZT_FORG-ZAZON .
/ZAK/PENZT_FORGV-AS4USER =
/ZAK/PENZT_FORG-AS4USER .
/ZAK/PENZT_FORGV-AS4DATE =
/ZAK/PENZT_FORG-AS4DATE .
/ZAK/PENZT_FORGV-AS4TIME =
/ZAK/PENZT_FORG-AS4TIME .
    SELECT SINGLE * FROM /ZAK/PENZATV WHERE
ZAZON = /ZAK/PENZT_FORG-ZAZON .
    IF SY-SUBRC EQ 0.
/ZAK/PENZT_FORGV-NAME1 =
/ZAK/PENZATV-NAME1 .
    ENDIF.
<VIM_TOTAL_STRUC> = /ZAK/PENZT_FORGV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/PENZT_FORGV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/PENZT_FORGV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/PENZT_FORGV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/PENZT_FORG WHERE
  KAZON = /ZAK/PENZT_FORGV-KAZON .
    IF SY-SUBRC = 0.
    DELETE /ZAK/PENZT_FORG .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/PENZT_FORG WHERE
  KAZON = /ZAK/PENZT_FORGV-KAZON .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/PENZT_FORG.
    ENDIF.
/ZAK/PENZT_FORG-MANDT =
/ZAK/PENZT_FORGV-MANDT .
/ZAK/PENZT_FORG-KAZON =
/ZAK/PENZT_FORGV-KAZON .
/ZAK/PENZT_FORG-ZAZON =
/ZAK/PENZT_FORGV-ZAZON .
/ZAK/PENZT_FORG-AS4USER =
/ZAK/PENZT_FORGV-AS4USER .
/ZAK/PENZT_FORG-AS4DATE =
/ZAK/PENZT_FORGV-AS4DATE .
/ZAK/PENZT_FORG-AS4TIME =
/ZAK/PENZT_FORGV-AS4TIME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/PENZT_FORG .
    ELSE.
    INSERT /ZAK/PENZT_FORG .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/PENZT_FORGV-UPD_FLAG,
STATUS_/ZAK/PENZT_FORGV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/PENZT_FORGV.
  SELECT SINGLE * FROM /ZAK/PENZT_FORG WHERE
KAZON = /ZAK/PENZT_FORGV-KAZON .
/ZAK/PENZT_FORGV-MANDT =
/ZAK/PENZT_FORG-MANDT .
/ZAK/PENZT_FORGV-KAZON =
/ZAK/PENZT_FORG-KAZON .
/ZAK/PENZT_FORGV-ZAZON =
/ZAK/PENZT_FORG-ZAZON .
/ZAK/PENZT_FORGV-AS4USER =
/ZAK/PENZT_FORG-AS4USER .
/ZAK/PENZT_FORGV-AS4DATE =
/ZAK/PENZT_FORG-AS4DATE .
/ZAK/PENZT_FORGV-AS4TIME =
/ZAK/PENZT_FORG-AS4TIME .
    SELECT SINGLE * FROM /ZAK/PENZATV WHERE
ZAZON = /ZAK/PENZT_FORG-ZAZON .
    IF SY-SUBRC EQ 0.
/ZAK/PENZT_FORGV-NAME1 =
/ZAK/PENZATV-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/PENZT_FORGV-NAME1 .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/PENZT_FORGV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/PENZT_FORGV-KAZON TO
/ZAK/PENZT_FORG-KAZON .
MOVE /ZAK/PENZT_FORGV-MANDT TO
/ZAK/PENZT_FORG-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/PENZT_FORG'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/PENZT_FORG TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/PENZT_FORG'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/ZAK/PENZT_FORGV USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/ZAK/PENZT_FORG-MANDT =
/ZAK/PENZT_FORGV-MANDT .
/ZAK/PENZT_FORG-KAZON =
/ZAK/PENZT_FORGV-KAZON .
/ZAK/PENZT_FORG-ZAZON =
/ZAK/PENZT_FORGV-ZAZON .
/ZAK/PENZT_FORG-AS4USER =
/ZAK/PENZT_FORGV-AS4USER .
/ZAK/PENZT_FORG-AS4DATE =
/ZAK/PENZT_FORGV-AS4DATE .
/ZAK/PENZT_FORG-AS4TIME =
/ZAK/PENZT_FORGV-AS4TIME .
    SELECT SINGLE * FROM /ZAK/PENZATV WHERE
ZAZON = /ZAK/PENZT_FORG-ZAZON .
    IF SY-SUBRC EQ 0.
/ZAK/PENZT_FORGV-NAME1 =
/ZAK/PENZATV-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/PENZT_FORGV-NAME1 .
    ENDIF.
ENDFORM.
