PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/AFA_RRABEVV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/AFA_RRABEVV-BTYPE .
    FIELD /ZAK/AFA_RRABEVV-ABEVAZ .
    FIELD /ZAK/AFA_RRABEVV-ABEVTEXT .
    FIELD /ZAK/AFA_RRABEVV-DATUM .
    FIELD /ZAK/AFA_RRABEVV-UZEIT .
    FIELD /ZAK/AFA_RRABEVV-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_/ZAK/AFA_RRABEVV ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/AFA_RRABEVV-BTYPE .
    FIELD /ZAK/AFA_RRABEVV-ABEVAZ .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
