PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/IGABEV_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/IGABEV_V-BUKRS .
    FIELD /ZAK/IGABEV_V-BTYPE .
    FIELD /ZAK/IGABEV_V-BSZNUM .
    FIELD /ZAK/IGABEV_V-IGAZON .
    FIELD /ZAK/IGABEV_V-TYPE .
    FIELD /ZAK/IGABEV_V-SORREND .
    FIELD /ZAK/IGABEV_V-POZICIO .
    FIELD /ZAK/IGABEV_V-OBLIG .
    FIELD /ZAK/IGABEV_V-COLLECT .
    FIELD /ZAK/IGABEV_V-TEXT .
    FIELD /ZAK/IGABEV_V-ABEVAZ .
    FIELD /ZAK/IGABEV_V-ABEVTEXT .
    FIELD /ZAK/IGABEV_V-SUM_IGAZON .
    FIELD /ZAK/IGABEV_V-SIGN .
    FIELD /ZAK/IGABEV_V-DATUM .
    FIELD /ZAK/IGABEV_V-UZEIT .
    FIELD /ZAK/IGABEV_V-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_/ZAK/IGABEV_V ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/IGABEV_V-BUKRS .
    FIELD /ZAK/IGABEV_V-BTYPE .
    FIELD /ZAK/IGABEV_V-BSZNUM .
    FIELD /ZAK/IGABEV_V-IGAZON .
    FIELD /ZAK/IGABEV_V-TYPE .
    FIELD /ZAK/IGABEV_V-SORREND .
    FIELD /ZAK/IGABEV_V-POZICIO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
