PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/BUKRSN_MV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/BUKRSN_MV-AD_BUKRS .
    FIELD /ZAK/BUKRSN_MV-FI_BUKRS .
    FIELD /ZAK/BUKRSN_MV-SAKNR .
    FIELD /ZAK/BUKRSN_MV-SHORTNAME .
    FIELD /ZAK/BUKRSN_MV-FDATE .
    FIELD /ZAK/BUKRSN_MV-DATUM .
    FIELD /ZAK/BUKRSN_MV-UZEIT .
    FIELD /ZAK/BUKRSN_MV-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/BUKRSN_MV-AD_BUKRS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.

*++2009.10.29 BG
*----------------------------------------------------------------------
  PROCESS ON VALUE-REQUEST.
*----------------------------------------------------------------------
* Set name
  FIELD /ZAK/BUKRSN_MV-SHORTNAME MODULE D0105_INPUT_SETNR.
*++2009.10.29 BG

