*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 2006.02.27 at 15:34:51 by user FMCTI00DBG
*---------------------------------------------------------------------*
*...processing: /ZAK/AFA_ATV_V...................................*
FORM GET_DATA_/ZAK/AFA_ATV_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  SELECT * FROM /ZAK/AFA_ATV WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/AFA_ATV_V .
/ZAK/AFA_ATV_V-MANDT =
/ZAK/AFA_ATV-MANDT .
/ZAK/AFA_ATV_V-BUKRS =
/ZAK/AFA_ATV-BUKRS .
/ZAK/AFA_ATV_V-BTYPE =
/ZAK/AFA_ATV-BTYPE .
/ZAK/AFA_ATV_V-ABEV_TO =
/ZAK/AFA_ATV-ABEV_TO .
/ZAK/AFA_ATV_V-TEXT_ABEV_TO =
/ZAK/AFA_ATV-TEXT_ABEV_TO .
/ZAK/AFA_ATV_V-ABEV_FROM =
/ZAK/AFA_ATV-ABEV_FROM .
/ZAK/AFA_ATV_V-TEXT_ABEV_FROM =
/ZAK/AFA_ATV-TEXT_ABEV_FROM .
/ZAK/AFA_ATV_V-KOART =
/ZAK/AFA_ATV-KOART .
/ZAK/AFA_ATV_V-UMSKZ_FROM =
/ZAK/AFA_ATV-UMSKZ_FROM .
/ZAK/AFA_ATV_V-UMSKZ_TO =
/ZAK/AFA_ATV-UMSKZ_TO .
/ZAK/AFA_ATV_V-BSCHL =
/ZAK/AFA_ATV-BSCHL .
/ZAK/AFA_ATV_V-AUGDT_FLAG =
/ZAK/AFA_ATV-AUGDT_FLAG .
/ZAK/AFA_ATV_V-DATUM =
/ZAK/AFA_ATV-DATUM .
/ZAK/AFA_ATV_V-UZEIT =
/ZAK/AFA_ATV-UZEIT .
/ZAK/AFA_ATV_V-UNAME =
/ZAK/AFA_ATV-UNAME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/AFA_ATV-BTYPE AND
ABEVAZ = /ZAK/AFA_ATV-ABEV_FROM .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
      ENDIF.
    ENDIF.
TOTAL = /ZAK/AFA_ATV_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_TOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/AFA_ATV_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE TOTAL TO /ZAK/AFA_ATV_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/AFA_ATV_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_TOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_ATV WHERE
  BUKRS = /ZAK/AFA_ATV_V-BUKRS AND
  BTYPE = /ZAK/AFA_ATV_V-BTYPE AND
  ABEV_TO = /ZAK/AFA_ATV_V-ABEV_TO AND
  ABEV_FROM = /ZAK/AFA_ATV_V-ABEV_FROM .
    IF SY-SUBRC = 0.
    DELETE /ZAK/AFA_ATV .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY TOTAL BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_ATV WHERE
  BUKRS = /ZAK/AFA_ATV_V-BUKRS AND
  BTYPE = /ZAK/AFA_ATV_V-BTYPE AND
  ABEV_TO = /ZAK/AFA_ATV_V-ABEV_TO AND
  ABEV_FROM = /ZAK/AFA_ATV_V-ABEV_FROM .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/AFA_ATV.
    ENDIF.
/ZAK/AFA_ATV-MANDT =
/ZAK/AFA_ATV_V-MANDT .
/ZAK/AFA_ATV-BUKRS =
/ZAK/AFA_ATV_V-BUKRS .
/ZAK/AFA_ATV-BTYPE =
/ZAK/AFA_ATV_V-BTYPE .
/ZAK/AFA_ATV-ABEV_TO =
/ZAK/AFA_ATV_V-ABEV_TO .
/ZAK/AFA_ATV-TEXT_ABEV_TO =
/ZAK/AFA_ATV_V-TEXT_ABEV_TO .
/ZAK/AFA_ATV-ABEV_FROM =
/ZAK/AFA_ATV_V-ABEV_FROM .
/ZAK/AFA_ATV-TEXT_ABEV_FROM =
/ZAK/AFA_ATV_V-TEXT_ABEV_FROM .
/ZAK/AFA_ATV-KOART =
/ZAK/AFA_ATV_V-KOART .
/ZAK/AFA_ATV-UMSKZ_FROM =
/ZAK/AFA_ATV_V-UMSKZ_FROM .
/ZAK/AFA_ATV-UMSKZ_TO =
/ZAK/AFA_ATV_V-UMSKZ_TO .
/ZAK/AFA_ATV-BSCHL =
/ZAK/AFA_ATV_V-BSCHL .
/ZAK/AFA_ATV-AUGDT_FLAG =
/ZAK/AFA_ATV_V-AUGDT_FLAG .
/ZAK/AFA_ATV-DATUM =
/ZAK/AFA_ATV_V-DATUM .
/ZAK/AFA_ATV-UZEIT =
/ZAK/AFA_ATV_V-UZEIT .
/ZAK/AFA_ATV-UNAME =
/ZAK/AFA_ATV_V-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/AFA_ATV .
    ELSE.
    INSERT /ZAK/AFA_ATV .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_TOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/AFA_ATV_V-UPD_FLAG,
STATUS_/ZAK/AFA_ATV_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/AFA_ATV_V.
  SELECT SINGLE * FROM /ZAK/AFA_ATV WHERE
BUKRS = /ZAK/AFA_ATV_V-BUKRS AND
BTYPE = /ZAK/AFA_ATV_V-BTYPE AND
ABEV_TO = /ZAK/AFA_ATV_V-ABEV_TO AND
ABEV_FROM = /ZAK/AFA_ATV_V-ABEV_FROM .
/ZAK/AFA_ATV_V-MANDT =
/ZAK/AFA_ATV-MANDT .
/ZAK/AFA_ATV_V-BUKRS =
/ZAK/AFA_ATV-BUKRS .
/ZAK/AFA_ATV_V-BTYPE =
/ZAK/AFA_ATV-BTYPE .
/ZAK/AFA_ATV_V-ABEV_TO =
/ZAK/AFA_ATV-ABEV_TO .
/ZAK/AFA_ATV_V-TEXT_ABEV_TO =
/ZAK/AFA_ATV-TEXT_ABEV_TO .
/ZAK/AFA_ATV_V-ABEV_FROM =
/ZAK/AFA_ATV-ABEV_FROM .
/ZAK/AFA_ATV_V-TEXT_ABEV_FROM =
/ZAK/AFA_ATV-TEXT_ABEV_FROM .
/ZAK/AFA_ATV_V-KOART =
/ZAK/AFA_ATV-KOART .
/ZAK/AFA_ATV_V-UMSKZ_FROM =
/ZAK/AFA_ATV-UMSKZ_FROM .
/ZAK/AFA_ATV_V-UMSKZ_TO =
/ZAK/AFA_ATV-UMSKZ_TO .
/ZAK/AFA_ATV_V-BSCHL =
/ZAK/AFA_ATV-BSCHL .
/ZAK/AFA_ATV_V-AUGDT_FLAG =
/ZAK/AFA_ATV-AUGDT_FLAG .
/ZAK/AFA_ATV_V-DATUM =
/ZAK/AFA_ATV-DATUM .
/ZAK/AFA_ATV_V-UZEIT =
/ZAK/AFA_ATV-UZEIT .
/ZAK/AFA_ATV_V-UNAME =
/ZAK/AFA_ATV-UNAME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/AFA_ATV-BTYPE AND
ABEVAZ = /ZAK/AFA_ATV-ABEV_FROM .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
      ELSE.
        CLEAR SY-SUBRC.
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/AFA_ATV_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I.
  CLEAR RC.
MOVE /ZAK/AFA_ATV_V-BUKRS TO
/ZAK/AFA_ATV-BUKRS .
MOVE /ZAK/AFA_ATV_V-BTYPE TO
/ZAK/AFA_ATV-BTYPE .
MOVE /ZAK/AFA_ATV_V-ABEV_TO TO
/ZAK/AFA_ATV-ABEV_TO .
MOVE /ZAK/AFA_ATV_V-ABEV_FROM TO
/ZAK/AFA_ATV-ABEV_FROM .
MOVE /ZAK/AFA_ATV_V-MANDT TO
/ZAK/AFA_ATV-MANDT .
  CORR_KEYTAB             =  E071K.
CORR_KEYTAB-OBJNAME = '/ZAK/AFA_ATV '.
CORR_KEYTAB-TABKEY(051) = /ZAK/AFA_ATV .
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/ZAK/AFA_ATV_V USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/ZAK/AFA_ATV-MANDT =
/ZAK/AFA_ATV_V-MANDT .
/ZAK/AFA_ATV-BUKRS =
/ZAK/AFA_ATV_V-BUKRS .
/ZAK/AFA_ATV-BTYPE =
/ZAK/AFA_ATV_V-BTYPE .
/ZAK/AFA_ATV-ABEV_TO =
/ZAK/AFA_ATV_V-ABEV_TO .
/ZAK/AFA_ATV-TEXT_ABEV_TO =
/ZAK/AFA_ATV_V-TEXT_ABEV_TO .
/ZAK/AFA_ATV-ABEV_FROM =
/ZAK/AFA_ATV_V-ABEV_FROM .
/ZAK/AFA_ATV-TEXT_ABEV_FROM =
/ZAK/AFA_ATV_V-TEXT_ABEV_FROM .
/ZAK/AFA_ATV-KOART =
/ZAK/AFA_ATV_V-KOART .
/ZAK/AFA_ATV-UMSKZ_FROM =
/ZAK/AFA_ATV_V-UMSKZ_FROM .
/ZAK/AFA_ATV-UMSKZ_TO =
/ZAK/AFA_ATV_V-UMSKZ_TO .
/ZAK/AFA_ATV-BSCHL =
/ZAK/AFA_ATV_V-BSCHL .
/ZAK/AFA_ATV-AUGDT_FLAG =
/ZAK/AFA_ATV_V-AUGDT_FLAG .
/ZAK/AFA_ATV-DATUM =
/ZAK/AFA_ATV_V-DATUM .
/ZAK/AFA_ATV-UZEIT =
/ZAK/AFA_ATV_V-UZEIT .
/ZAK/AFA_ATV-UNAME =
/ZAK/AFA_ATV_V-UNAME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/AFA_ATV-BTYPE AND
ABEVAZ = /ZAK/AFA_ATV-ABEV_FROM .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
      ELSE.
        CLEAR SY-SUBRC.
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
