PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/ANALITIKA_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
 MODULE FILL_SUBSTFLDS.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/ANALITIKA_V-ZINDEX .
    FIELD /ZAK/ANALITIKA_V-ABEVAZ .
    FIELD /ZAK/ANALITIKA_V-ADOAZON .
    FIELD /ZAK/ANALITIKA_V-BSZNUM .
    FIELD /ZAK/ANALITIKA_V-PACK .
    FIELD /ZAK/ANALITIKA_V-ITEM .
    FIELD /ZAK/ANALITIKA_V-LAPSZ .
    FIELD /ZAK/ANALITIKA_V-XMANU .
    FIELD /ZAK/ANALITIKA_V-XDEFT .
    FIELD /ZAK/ANALITIKA_V-VORSTOR .
    FIELD /ZAK/ANALITIKA_V-STAPO .
    FIELD /ZAK/ANALITIKA_V-DMBTR .
    FIELD /ZAK/ANALITIKA_V-WAERS .
    FIELD /ZAK/ANALITIKA_V-KOSTL .
    FIELD /ZAK/ANALITIKA_V-ZCOMMENT .
    FIELD /ZAK/ANALITIKA_V-BSEG_GJAHR .
    FIELD /ZAK/ANALITIKA_V-BSEG_BELNR .
    FIELD /ZAK/ANALITIKA_V-BSEG_BUZEI .
    FIELD /ZAK/ANALITIKA_V-BOOK .
    FIELD /ZAK/ANALITIKA_V-KMONAT .
    FIELD /ZAK/ANALITIKA_V-KTOSL .
    FIELD /ZAK/ANALITIKA_V-MWSKZ .
    FIELD /ZAK/ANALITIKA_V-KBETR .
    FIELD /ZAK/ANALITIKA_V-BLART .
    FIELD /ZAK/ANALITIKA_V-BUDAT .
    FIELD /ZAK/ANALITIKA_V-BLDAT .
    FIELD /ZAK/ANALITIKA_V-ZFBDT .
    FIELD /ZAK/ANALITIKA_V-HKONT .
    FIELD /ZAK/ANALITIKA_V-LIFKUN .
    FIELD /ZAK/ANALITIKA_V-KOART .
    FIELD /ZAK/ANALITIKA_V-STCEG .
    FIELD /ZAK/ANALITIKA_V-STCD1 .
    FIELD /ZAK/ANALITIKA_V-STCD2 .
    FIELD /ZAK/ANALITIKA_V-STCD3 .
    FIELD /ZAK/ANALITIKA_V-XBLNR .
    FIELD /ZAK/ANALITIKA_V-LWBAS .
    FIELD /ZAK/ANALITIKA_V-FWBAS .
    FIELD /ZAK/ANALITIKA_V-LWSTE .
    FIELD /ZAK/ANALITIKA_V-FWSTE .
    FIELD /ZAK/ANALITIKA_V-HWBTR .
    FIELD /ZAK/ANALITIKA_V-FWBTR .
    FIELD /ZAK/ANALITIKA_V-FWAERS .
    FIELD /ZAK/ANALITIKA_V-AUFNR .
    FIELD /ZAK/ANALITIKA_V-UMSKZ .
    FIELD /ZAK/ANALITIKA_V-BSCHL .
    FIELD /ZAK/ANALITIKA_V-AUGDT .
    FIELD /ZAK/ANALITIKA_V-PRCTR .
    FIELD /ZAK/ANALITIKA_V-FIELD_C .
    FIELD /ZAK/ANALITIKA_V-FIELD_N .
    FIELD /ZAK/ANALITIKA_V-FIELD_A .
    FIELD /ZAK/ANALITIKA_V-TTIP .
    FIELD /ZAK/ANALITIKA_V-ADODAT .
    FIELD /ZAK/ANALITIKA_V-GSBER .
    FIELD /ZAK/ANALITIKA_V-HSZU .
    FIELD /ZAK/ANALITIKA_V-FI_BUKRS .
    FIELD /ZAK/ANALITIKA_V-ARANY_FLAG .
    FIELD /ZAK/ANALITIKA_V-NYLAPAZON .
    FIELD /ZAK/ANALITIKA_V-ONYBF .
    FIELD /ZAK/ANALITIKA_V-ONYB_PACK .
    FIELD /ZAK/ANALITIKA_V-POSID .
    FIELD /ZAK/ANALITIKA_V-XEGDR .
    FIELD /ZAK/ANALITIKA_V-USNAM .
    FIELD /ZAK/ANALITIKA_V-SZAMLAKELT .
    FIELD /ZAK/ANALITIKA_V-SZAMLASZ .
    FIELD /ZAK/ANALITIKA_V-SZAMLASZE .
    FIELD /ZAK/ANALITIKA_V-SZLATIP .
    FIELD /ZAK/ANALITIKA_V-SZAMLASZA .
    FIELD /ZAK/ANALITIKA_V-ZMWSKF .
    FIELD /ZAK/ANALITIKA_V-ZKUNNAME .
    FIELD /ZAK/ANALITIKA_V-ZKUNADRS .
    FIELD /ZAK/ANALITIKA_V-NONEED .
    FIELD /ZAK/ANALITIKA_V-VKORG .
    FIELD /ZAK/ANALITIKA_V-ZUONR .
    FIELD /ZAK/ANALITIKA_V-VMSZA .
    FIELD /ZAK/ANALITIKA_V-XREF1_HD .
    FIELD /ZAK/ANALITIKA_V-XREF2_HD .
    FIELD /ZAK/ANALITIKA_V-H_GJAHR .
    FIELD /ZAK/ANALITIKA_V-H_BELNR .
    FIELD /ZAK/ANALITIKA_V-ELSTAD .
    FIELD /ZAK/ANALITIKA_V-UGYFEL .
    FIELD /ZAK/ANALITIKA_V-VAROS .
    FIELD /ZAK/ANALITIKA_V-CIM .
    FIELD /ZAK/ANALITIKA_V-IRSZ .
    FIELD /ZAK/ANALITIKA_V-ORSZAG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/ANALITIKA_V-ZINDEX .
    FIELD /ZAK/ANALITIKA_V-ABEVAZ .
    FIELD /ZAK/ANALITIKA_V-ADOAZON .
    FIELD /ZAK/ANALITIKA_V-BSZNUM .
    FIELD /ZAK/ANALITIKA_V-PACK .
    FIELD /ZAK/ANALITIKA_V-ITEM .
    FIELD /ZAK/ANALITIKA_V-LAPSZ .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
