*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/AFA_BLARTNV................................*
FORM GET_DATA_/ZAK/AFA_BLARTNV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/AFA_BLARTNM WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/AFA_BLARTNV .
/ZAK/AFA_BLARTNV-MANDT =
/ZAK/AFA_BLARTNM-MANDT .
/ZAK/AFA_BLARTNV-BLART =
/ZAK/AFA_BLARTNM-BLART .
/ZAK/AFA_BLARTNV-AS4USER =
/ZAK/AFA_BLARTNM-AS4USER .
/ZAK/AFA_BLARTNV-AS4DATE =
/ZAK/AFA_BLARTNM-AS4DATE .
/ZAK/AFA_BLARTNV-AS4TIME =
/ZAK/AFA_BLARTNM-AS4TIME .
    SELECT SINGLE * FROM T003 WHERE
BLART = /ZAK/AFA_BLARTNM-BLART .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T003T WHERE
BLART = T003-BLART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/AFA_BLARTNV-LTEXT =
T003T-LTEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /ZAK/AFA_BLARTNV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/AFA_BLARTNV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/AFA_BLARTNV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/AFA_BLARTNV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_BLARTNM WHERE
  BLART = /ZAK/AFA_BLARTNV-BLART .
    IF SY-SUBRC = 0.
    DELETE /ZAK/AFA_BLARTNM .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_BLARTNM WHERE
  BLART = /ZAK/AFA_BLARTNV-BLART .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/AFA_BLARTNM.
    ENDIF.
/ZAK/AFA_BLARTNM-MANDT =
/ZAK/AFA_BLARTNV-MANDT .
/ZAK/AFA_BLARTNM-BLART =
/ZAK/AFA_BLARTNV-BLART .
/ZAK/AFA_BLARTNM-AS4USER =
/ZAK/AFA_BLARTNV-AS4USER .
/ZAK/AFA_BLARTNM-AS4DATE =
/ZAK/AFA_BLARTNV-AS4DATE .
/ZAK/AFA_BLARTNM-AS4TIME =
/ZAK/AFA_BLARTNV-AS4TIME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/AFA_BLARTNM .
    ELSE.
    INSERT /ZAK/AFA_BLARTNM .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/AFA_BLARTNV-UPD_FLAG,
STATUS_/ZAK/AFA_BLARTNV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/AFA_BLARTNV.
  SELECT SINGLE * FROM /ZAK/AFA_BLARTNM WHERE
BLART = /ZAK/AFA_BLARTNV-BLART .
/ZAK/AFA_BLARTNV-MANDT =
/ZAK/AFA_BLARTNM-MANDT .
/ZAK/AFA_BLARTNV-BLART =
/ZAK/AFA_BLARTNM-BLART .
/ZAK/AFA_BLARTNV-AS4USER =
/ZAK/AFA_BLARTNM-AS4USER .
/ZAK/AFA_BLARTNV-AS4DATE =
/ZAK/AFA_BLARTNM-AS4DATE .
/ZAK/AFA_BLARTNV-AS4TIME =
/ZAK/AFA_BLARTNM-AS4TIME .
    SELECT SINGLE * FROM T003 WHERE
BLART = /ZAK/AFA_BLARTNM-BLART .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T003T WHERE
BLART = T003-BLART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/AFA_BLARTNV-LTEXT =
T003T-LTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/AFA_BLARTNV-LTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/AFA_BLARTNV-LTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/AFA_BLARTNV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/AFA_BLARTNV-BLART TO
/ZAK/AFA_BLARTNM-BLART .
MOVE /ZAK/AFA_BLARTNV-MANDT TO
/ZAK/AFA_BLARTNM-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/AFA_BLARTNM'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/AFA_BLARTNM TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/AFA_BLARTNM'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/ZAK/AFA_BLARTNV USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/ZAK/AFA_BLARTNM-MANDT =
/ZAK/AFA_BLARTNV-MANDT .
/ZAK/AFA_BLARTNM-BLART =
/ZAK/AFA_BLARTNV-BLART .
/ZAK/AFA_BLARTNM-AS4USER =
/ZAK/AFA_BLARTNV-AS4USER .
/ZAK/AFA_BLARTNM-AS4DATE =
/ZAK/AFA_BLARTNV-AS4DATE .
/ZAK/AFA_BLARTNM-AS4TIME =
/ZAK/AFA_BLARTNV-AS4TIME .
    SELECT SINGLE * FROM T003 WHERE
BLART = /ZAK/AFA_BLARTNM-BLART .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T003T WHERE
BLART = T003-BLART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/AFA_BLARTNV-LTEXT =
T003T-LTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/AFA_BLARTNV-LTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/AFA_BLARTNV-LTEXT .
    ENDIF.
ENDFORM.
