PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/SZJA_CUST_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/SZJA_CUST_V-BUKRS .
    FIELD /ZAK/SZJA_CUST_V-BTYPE .
    FIELD /ZAK/SZJA_CUST_V-BSZNUM .
    FIELD /ZAK/SZJA_CUST_V-ABEVAZ .
    FIELD /ZAK/SZJA_CUST_V-SAKNR .
    FIELD /ZAK/SZJA_CUST_V-DATAB .
    FIELD /ZAK/SZJA_CUST_V-DATBI .
    FIELD /ZAK/SZJA_CUST_V-BIDOSZ .
    FIELD /ZAK/SZJA_CUST_V-ADOALAP .
    FIELD /ZAK/SZJA_CUST_V-SZJA_I .
    FIELD /ZAK/SZJA_CUST_V-SZJA_II .
    FIELD /ZAK/SZJA_CUST_V-SZJA_III .
    FIELD /ZAK/SZJA_CUST_V-SZJA_IV .
    FIELD /ZAK/SZJA_CUST_V-TB_I .
    FIELD /ZAK/SZJA_CUST_V-TB_II .
    FIELD /ZAK/SZJA_CUST_V-TB_III .
    FIELD /ZAK/SZJA_CUST_V-MUNKAA .
    FIELD /ZAK/SZJA_CUST_V-EHO_I .
    FIELD /ZAK/SZJA_CUST_V-EHO_II .
    FIELD /ZAK/SZJA_CUST_V-EHO_III .
    FIELD /ZAK/SZJA_CUST_V-SZOCHO_I .
    FIELD /ZAK/SZJA_CUST_V-SZOCHO_II .
    FIELD /ZAK/SZJA_CUST_V-SZKHJ .
    FIELD /ZAK/SZJA_CUST_V-/ZAK/EVES .
    FIELD /ZAK/SZJA_CUST_V-/ZAK/WL .
    FIELD /ZAK/SZJA_CUST_V-WLBOUT .
    FIELD /ZAK/SZJA_CUST_V-MWSKZ .
    FIELD /ZAK/SZJA_CUST_V-KOSTL .
    FIELD /ZAK/SZJA_CUST_V-/ZAK/ATKONYV .
    FIELD /ZAK/SZJA_CUST_V-ALAPKONYV .
    FIELD /ZAK/SZJA_CUST_V-DATUM .
    FIELD /ZAK/SZJA_CUST_V-UZEIT .
    FIELD /ZAK/SZJA_CUST_V-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/SZJA_CUST_V-BUKRS .
    FIELD /ZAK/SZJA_CUST_V-BTYPE .
    FIELD /ZAK/SZJA_CUST_V-BSZNUM .
    FIELD /ZAK/SZJA_CUST_V-ABEVAZ .
    FIELD /ZAK/SZJA_CUST_V-SAKNR .
    FIELD /ZAK/SZJA_CUST_V-DATAB .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
