*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/AFA_VAMT_V..................................*
FORM GET_DATA_/ZAK/AFA_VAMT_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/AFA_VAMT WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/AFA_VAMT_V .
/ZAK/AFA_VAMT_V-MANDT =
/ZAK/AFA_VAMT-MANDT .
/ZAK/AFA_VAMT_V-VMSZA =
/ZAK/AFA_VAMT-VMSZA .
/ZAK/AFA_VAMT_V-AS4USER =
/ZAK/AFA_VAMT-AS4USER .
/ZAK/AFA_VAMT_V-AS4DATE =
/ZAK/AFA_VAMT-AS4DATE .
/ZAK/AFA_VAMT_V-AS4TIME =
/ZAK/AFA_VAMT-AS4TIME .
    SELECT SINGLE * FROM /ZAK/AFA_VAMTT WHERE
VMSZA = /ZAK/AFA_VAMT-VMSZA AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
/ZAK/AFA_VAMT_V-VNAME =
/ZAK/AFA_VAMTT-VNAME .
    ENDIF.
<VIM_TOTAL_STRUC> = /ZAK/AFA_VAMT_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/AFA_VAMT_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/AFA_VAMT_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/AFA_VAMT_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_VAMT WHERE
  VMSZA = /ZAK/AFA_VAMT_V-VMSZA .
    IF SY-SUBRC = 0.
    DELETE /ZAK/AFA_VAMT .
    ENDIF.
    DELETE FROM /ZAK/AFA_VAMTT WHERE
    VMSZA = /ZAK/AFA_VAMT-VMSZA .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_VAMT WHERE
  VMSZA = /ZAK/AFA_VAMT_V-VMSZA .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/AFA_VAMT.
    ENDIF.
/ZAK/AFA_VAMT-MANDT =
/ZAK/AFA_VAMT_V-MANDT .
/ZAK/AFA_VAMT-VMSZA =
/ZAK/AFA_VAMT_V-VMSZA .
/ZAK/AFA_VAMT-AS4USER =
/ZAK/AFA_VAMT_V-AS4USER .
/ZAK/AFA_VAMT-AS4DATE =
/ZAK/AFA_VAMT_V-AS4DATE .
/ZAK/AFA_VAMT-AS4TIME =
/ZAK/AFA_VAMT_V-AS4TIME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/AFA_VAMT .
    ELSE.
    INSERT /ZAK/AFA_VAMT .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_VAMTT WHERE
    VMSZA = /ZAK/AFA_VAMT-VMSZA AND
    LANGU = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR /ZAK/AFA_VAMTT.
/ZAK/AFA_VAMTT-VMSZA =
/ZAK/AFA_VAMT-VMSZA .
/ZAK/AFA_VAMTT-LANGU =
SY-LANGU .
      ENDIF.
/ZAK/AFA_VAMTT-VNAME =
/ZAK/AFA_VAMT_V-VNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/AFA_VAMTT .
    ELSE.
    INSERT /ZAK/AFA_VAMTT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/AFA_VAMT_V-UPD_FLAG,
STATUS_/ZAK/AFA_VAMT_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/AFA_VAMT_V.
  SELECT SINGLE * FROM /ZAK/AFA_VAMT WHERE
VMSZA = /ZAK/AFA_VAMT_V-VMSZA .
/ZAK/AFA_VAMT_V-MANDT =
/ZAK/AFA_VAMT-MANDT .
/ZAK/AFA_VAMT_V-VMSZA =
/ZAK/AFA_VAMT-VMSZA .
/ZAK/AFA_VAMT_V-AS4USER =
/ZAK/AFA_VAMT-AS4USER .
/ZAK/AFA_VAMT_V-AS4DATE =
/ZAK/AFA_VAMT-AS4DATE .
/ZAK/AFA_VAMT_V-AS4TIME =
/ZAK/AFA_VAMT-AS4TIME .
    SELECT SINGLE * FROM /ZAK/AFA_VAMTT WHERE
VMSZA = /ZAK/AFA_VAMT-VMSZA AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
/ZAK/AFA_VAMT_V-VNAME =
/ZAK/AFA_VAMTT-VNAME .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/AFA_VAMT_V-VNAME .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/AFA_VAMT_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/AFA_VAMT_V-VMSZA TO
/ZAK/AFA_VAMT-VMSZA .
MOVE /ZAK/AFA_VAMT_V-MANDT TO
/ZAK/AFA_VAMT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/AFA_VAMT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/AFA_VAMT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/AFA_VAMT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE /ZAK/AFA_VAMT-VMSZA TO
/ZAK/AFA_VAMTT-VMSZA .
MOVE SY-LANGU TO
/ZAK/AFA_VAMTT-LANGU .
MOVE /ZAK/AFA_VAMT_V-MANDT TO
/ZAK/AFA_VAMTT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/AFA_VAMTT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/AFA_VAMTT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/AFA_VAMTT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
