*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/MGCIM_V.....................................*
FORM GET_DATA_/ZAK/MGCIM_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/MGCIM WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/MGCIM_V .
/ZAK/MGCIM_V-MANDT =
/ZAK/MGCIM-MANDT .
/ZAK/MGCIM_V-ADOAZON =
/ZAK/MGCIM-ADOAZON .
/ZAK/MGCIM_V-NAME =
/ZAK/MGCIM-NAME .
/ZAK/MGCIM_V-POSTCOD =
/ZAK/MGCIM-POSTCOD .
/ZAK/MGCIM_V-CITY1 =
/ZAK/MGCIM-CITY1 .
/ZAK/MGCIM_V-STREET =
/ZAK/MGCIM-STREET .
/ZAK/MGCIM_V-PUBCHAR =
/ZAK/MGCIM-PUBCHAR .
/ZAK/MGCIM_V-HOUSE =
/ZAK/MGCIM-HOUSE .
/ZAK/MGCIM_V-COUNTRY =
/ZAK/MGCIM-COUNTRY .
/ZAK/MGCIM_V-DATUM =
/ZAK/MGCIM-DATUM .
/ZAK/MGCIM_V-UZEIT =
/ZAK/MGCIM-UZEIT .
/ZAK/MGCIM_V-UNAME =
/ZAK/MGCIM-UNAME .
<VIM_TOTAL_STRUC> = /ZAK/MGCIM_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/MGCIM_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/MGCIM_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/MGCIM_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/MGCIM WHERE
  ADOAZON = /ZAK/MGCIM_V-ADOAZON .
    IF SY-SUBRC = 0.
    DELETE /ZAK/MGCIM .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/MGCIM WHERE
  ADOAZON = /ZAK/MGCIM_V-ADOAZON .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/MGCIM.
    ENDIF.
/ZAK/MGCIM-MANDT =
/ZAK/MGCIM_V-MANDT .
/ZAK/MGCIM-ADOAZON =
/ZAK/MGCIM_V-ADOAZON .
/ZAK/MGCIM-NAME =
/ZAK/MGCIM_V-NAME .
/ZAK/MGCIM-POSTCOD =
/ZAK/MGCIM_V-POSTCOD .
/ZAK/MGCIM-CITY1 =
/ZAK/MGCIM_V-CITY1 .
/ZAK/MGCIM-STREET =
/ZAK/MGCIM_V-STREET .
/ZAK/MGCIM-PUBCHAR =
/ZAK/MGCIM_V-PUBCHAR .
/ZAK/MGCIM-HOUSE =
/ZAK/MGCIM_V-HOUSE .
/ZAK/MGCIM-COUNTRY =
/ZAK/MGCIM_V-COUNTRY .
/ZAK/MGCIM-DATUM =
/ZAK/MGCIM_V-DATUM .
/ZAK/MGCIM-UZEIT =
/ZAK/MGCIM_V-UZEIT .
/ZAK/MGCIM-UNAME =
/ZAK/MGCIM_V-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/MGCIM ##WARN_OK.
    ELSE.
    INSERT /ZAK/MGCIM .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/MGCIM_V-UPD_FLAG,
STATUS_/ZAK/MGCIM_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/MGCIM_V.
  SELECT SINGLE * FROM /ZAK/MGCIM WHERE
ADOAZON = /ZAK/MGCIM_V-ADOAZON .
/ZAK/MGCIM_V-MANDT =
/ZAK/MGCIM-MANDT .
/ZAK/MGCIM_V-ADOAZON =
/ZAK/MGCIM-ADOAZON .
/ZAK/MGCIM_V-NAME =
/ZAK/MGCIM-NAME .
/ZAK/MGCIM_V-POSTCOD =
/ZAK/MGCIM-POSTCOD .
/ZAK/MGCIM_V-CITY1 =
/ZAK/MGCIM-CITY1 .
/ZAK/MGCIM_V-STREET =
/ZAK/MGCIM-STREET .
/ZAK/MGCIM_V-PUBCHAR =
/ZAK/MGCIM-PUBCHAR .
/ZAK/MGCIM_V-HOUSE =
/ZAK/MGCIM-HOUSE .
/ZAK/MGCIM_V-COUNTRY =
/ZAK/MGCIM-COUNTRY .
/ZAK/MGCIM_V-DATUM =
/ZAK/MGCIM-DATUM .
/ZAK/MGCIM_V-UZEIT =
/ZAK/MGCIM-UZEIT .
/ZAK/MGCIM_V-UNAME =
/ZAK/MGCIM-UNAME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/MGCIM_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/MGCIM_V-ADOAZON TO
/ZAK/MGCIM-ADOAZON .
MOVE /ZAK/MGCIM_V-MANDT TO
/ZAK/MGCIM-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/MGCIM'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/MGCIM TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/MGCIM'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
