*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 2006.02.22 at 10:40:29 by user FMCTI00KCT
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LSTART_MVTOP.                 " Global Data
  INCLUDE /ZAK/LSTART_MVUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LSTART_MVF00                       . " subprograms
  INCLUDE /ZAK/LSTART_MVI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LSTART_MVF...                 " Subprograms
* INCLUDE /ZAK/LSTART_MVO...                 " PBO-Modules
* INCLUDE /ZAK/LSTART_MVI...                 " PAI-Modules

INCLUDE /ZAK/LSTART_MVF01.
