PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/BEVALLSZ_MV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/BEVALLSZ_MV-BUKRS .
    FIELD /ZAK/BEVALLSZ_MV-BTYPE .
    FIELD /ZAK/BEVALLSZ_MV-BSZNUM .
    FIELD /ZAK/BEVALLSZ_MV-GJAHR .
    FIELD /ZAK/BEVALLSZ_MV-MONAT .
    FIELD /ZAK/BEVALLSZ_MV-ZINDEX .
    FIELD /ZAK/BEVALLSZ_MV-PACK .
    FIELD /ZAK/BEVALLSZ_MV-FLAG .
    FIELD /ZAK/BEVALLSZ_MV-LARUN .
    FIELD /ZAK/BEVALLSZ_MV-DATUM .
    FIELD /ZAK/BEVALLSZ_MV-UZEIT .
    FIELD /ZAK/BEVALLSZ_MV-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/BEVALLSZ_MV-BUKRS .
    FIELD /ZAK/BEVALLSZ_MV-BTYPE .
    FIELD /ZAK/BEVALLSZ_MV-BSZNUM .
    FIELD /ZAK/BEVALLSZ_MV-GJAHR .
    FIELD /ZAK/BEVALLSZ_MV-MONAT .
    FIELD /ZAK/BEVALLSZ_MV-ZINDEX .
    FIELD /ZAK/BEVALLSZ_MV-PACK .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
