*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/IGSOR_V.....................................*
FORM GET_DATA_/ZAK/IGSOR_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/IGSOR WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/IGSOR_V .
/ZAK/IGSOR_V-MANDT =
/ZAK/IGSOR-MANDT .
/ZAK/IGSOR_V-IGAZON =
/ZAK/IGSOR-IGAZON .
/ZAK/IGSOR_V-FORMATUM =
/ZAK/IGSOR-FORMATUM .
/ZAK/IGSOR_V-DATUM =
/ZAK/IGSOR-DATUM .
/ZAK/IGSOR_V-UZEIT =
/ZAK/IGSOR-UZEIT .
/ZAK/IGSOR_V-UNAME =
/ZAK/IGSOR-UNAME .
    SELECT SINGLE * FROM /ZAK/IGSORT WHERE
IGAZON = /ZAK/IGSOR-IGAZON AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
/ZAK/IGSOR_V-TEXT =
/ZAK/IGSORT-TEXT .
/ZAK/IGSOR_V-NYTEXT =
/ZAK/IGSORT-NYTEXT .
    ENDIF.
<VIM_TOTAL_STRUC> = /ZAK/IGSOR_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/IGSOR_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/IGSOR_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/IGSOR_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/IGSOR WHERE
  IGAZON = /ZAK/IGSOR_V-IGAZON .
    IF SY-SUBRC = 0.
    DELETE /ZAK/IGSOR .
    ENDIF.
    DELETE FROM /ZAK/IGSORT WHERE
    IGAZON = /ZAK/IGSOR-IGAZON .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/IGSOR WHERE
  IGAZON = /ZAK/IGSOR_V-IGAZON .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/IGSOR.
    ENDIF.
/ZAK/IGSOR-MANDT =
/ZAK/IGSOR_V-MANDT .
/ZAK/IGSOR-IGAZON =
/ZAK/IGSOR_V-IGAZON .
/ZAK/IGSOR-FORMATUM =
/ZAK/IGSOR_V-FORMATUM .
/ZAK/IGSOR-DATUM =
/ZAK/IGSOR_V-DATUM .
/ZAK/IGSOR-UZEIT =
/ZAK/IGSOR_V-UZEIT .
/ZAK/IGSOR-UNAME =
/ZAK/IGSOR_V-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/IGSOR .
    ELSE.
    INSERT /ZAK/IGSOR .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM /ZAK/IGSORT WHERE
    IGAZON = /ZAK/IGSOR-IGAZON AND
    LANGU = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR /ZAK/IGSORT.
/ZAK/IGSORT-IGAZON =
/ZAK/IGSOR-IGAZON .
/ZAK/IGSORT-LANGU =
SY-LANGU .
      ENDIF.
/ZAK/IGSORT-TEXT =
/ZAK/IGSOR_V-TEXT .
/ZAK/IGSORT-NYTEXT =
/ZAK/IGSOR_V-NYTEXT .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/IGSORT .
    ELSE.
    INSERT /ZAK/IGSORT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/IGSOR_V-UPD_FLAG,
STATUS_/ZAK/IGSOR_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/IGSOR_V.
  SELECT SINGLE * FROM /ZAK/IGSOR WHERE
IGAZON = /ZAK/IGSOR_V-IGAZON .
/ZAK/IGSOR_V-MANDT =
/ZAK/IGSOR-MANDT .
/ZAK/IGSOR_V-IGAZON =
/ZAK/IGSOR-IGAZON .
/ZAK/IGSOR_V-FORMATUM =
/ZAK/IGSOR-FORMATUM .
/ZAK/IGSOR_V-DATUM =
/ZAK/IGSOR-DATUM .
/ZAK/IGSOR_V-UZEIT =
/ZAK/IGSOR-UZEIT .
/ZAK/IGSOR_V-UNAME =
/ZAK/IGSOR-UNAME .
    SELECT SINGLE * FROM /ZAK/IGSORT WHERE
IGAZON = /ZAK/IGSOR-IGAZON AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
/ZAK/IGSOR_V-TEXT =
/ZAK/IGSORT-TEXT .
/ZAK/IGSOR_V-NYTEXT =
/ZAK/IGSORT-NYTEXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/IGSOR_V-TEXT .
      CLEAR /ZAK/IGSOR_V-NYTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/IGSOR_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/IGSOR_V-IGAZON TO
/ZAK/IGSOR-IGAZON .
MOVE /ZAK/IGSOR_V-MANDT TO
/ZAK/IGSOR-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/IGSOR'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/IGSOR TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/IGSOR'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE /ZAK/IGSOR-IGAZON TO
/ZAK/IGSORT-IGAZON .
MOVE SY-LANGU TO
/ZAK/IGSORT-LANGU .
MOVE /ZAK/IGSOR_V-MANDT TO
/ZAK/IGSORT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/IGSORT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/IGSORT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/IGSORT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
