PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/KUNNR_CST_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/KUNNR_CST_V-KUNNR .
    FIELD /ZAK/KUNNR_CST_V-NAME1 .
    FIELD /ZAK/KUNNR_CST_V-DATBI .
    FIELD /ZAK/KUNNR_CST_V-DATAB .
    FIELD /ZAK/KUNNR_CST_V-STCD3 .
    FIELD /ZAK/KUNNR_CST_V-AS4USER .
    FIELD /ZAK/KUNNR_CST_V-AS4DATE .
    FIELD /ZAK/KUNNR_CST_V-AS4TIME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_/ZAK/KUNNR_CST_V ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/KUNNR_CST_V-KUNNR .
    FIELD /ZAK/KUNNR_CST_V-DATBI .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
