*&---------------------------------------------------------------------*
*&  Include           /ZAK/IGTOP
*&---------------------------------------------------------------------*
*& /ZAK/ZAKO certificate data declaration
*&---------------------------------------------------------------------*
TABLES: T001, /ZAK/IGDATA.

CONSTANTS C_ON TYPE C VALUE 'X'.

*Formats
CONSTANTS C_FORM_D TYPE /ZAK/FORMAT VALUE 'D'.

*Macro definition for populating a range
DEFINE M_DEF.
  MOVE: &2      TO &1-SIGN,
        &3      TO &1-OPTION,
        &4      TO &1-LOW,
        &5      TO &1-HIGH.
  APPEND &1.
END-OF-DEFINITION.

DATA G_BTYPART TYPE /ZAK/BTYPART.

*Data supply identifiers:
RANGES R_BSZNUM FOR /ZAK/BEVALLD-BSZNUM.

TYPES: BEGIN OF T_BSZNUMT,
       BSZNUM TYPE /ZAK/BSZNUM,
       SZTEXT TYPE /ZAK/SZTEXT,
       END OF T_BSZNUMT.

DATA I_BSZNUMT TYPE STANDARD TABLE OF T_BSZNUMT INITIAL SIZE 0.
DATA W_BSZNUMT TYPE T_BSZNUMT.

DATA I_/ZAK/IGDATA_ALV TYPE STANDARD TABLE OF /ZAK/IGDATA_ALV INITIAL SIZE 0.
DATA W_/ZAK/IGDATA_ALV TYPE /ZAK/IGDATA_ALV.

*For currency descriptions:
TYPES: BEGIN OF T_WAERST,
       WAERS TYPE WAERS_CURC,
       KTEXT TYPE KTEXT_CURT,
       END OF T_WAERST.

DATA I_WAERST TYPE STANDARD TABLE OF T_WAERST INITIAL SIZE 0.
DATA W_WAERST TYPE T_WAERST.

TYPES: BEGIN OF T_PACK,
       PACK  TYPE /ZAK/PACK,
       GJAHR TYPE GJAHR,
       MONAT TYPE MONAT,
       END OF T_PACK.

DATA I_PACK TYPE STANDARD TABLE OF T_PACK INITIAL SIZE 0.
DATA W_PACK TYPE T_PACK.

*Upload identifiers
RANGES R_PACK FOR /ZAK/BEVALLSZ-PACK.
*Collecting tax identifiers
RANGES R_ADOAZON FOR /ZAK/ANALITIKA-ADOAZON.

DATA G_INDEX LIKE SY-TABIX.


DATA: OK_CODE LIKE SY-UCOMM,
      SAVE_OK LIKE SY-UCOMM,
      G_CONTAINER TYPE SCRFNAME VALUE 'ZSCR_100',
      G_GRID1     TYPE REF TO CL_GUI_ALV_GRID,
      G_CUSTOM_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GS_LAYOUT   TYPE LVC_S_LAYO,
      GS_VARIANT  TYPE DISVARIANT.

DATA: GT_FCAT TYPE LVC_T_FCAT.

DATA: G_REPID LIKE SY-REPID.

DATA: DEF_LAYOUT  TYPE DISVARIANT,     "default layout
      DEFAULT TYPE C VALUE ' ',
      SPEC_LAYOUT TYPE DISVARIANT.

DATA: BEGIN OF GT_OUTTAB OCCURS 0.
*        INCLUDE STRUCTURE ZRP_RS010_IM_LEVEL_ALV.
        INCLUDE STRUCTURE /ZAK/IGDATA_ALV.
DATA: CELLTAB TYPE LVC_T_STYL.
DATA: END OF GT_OUTTAB.

TYPES: BEGIN OF T_BSZNUM_SORSZ,
       BSZNUM TYPE /ZAK/BSZNUM,
       NUMBER TYPE NUMC5,
       END OF T_BSZNUM_SORSZ.

DATA I_BSZNUM_SORSZ TYPE STANDARD TABLE OF T_BSZNUM_SORSZ
                          INITIAL SIZE 0.
DATA W_BSZNUM_SORSZ TYPE T_BSZNUM_SORSZ.
