*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/BEVALLDEF_V.................................*
FORM GET_DATA_/ZAK/BEVALLDEF_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/BEVALLDEF WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/BEVALLDEF_V .
/ZAK/BEVALLDEF_V-MANDT =
/ZAK/BEVALLDEF-MANDT .
/ZAK/BEVALLDEF_V-BUKRS =
/ZAK/BEVALLDEF-BUKRS .
/ZAK/BEVALLDEF_V-BTYPE =
/ZAK/BEVALLDEF-BTYPE .
/ZAK/BEVALLDEF_V-ABEVAZ =
/ZAK/BEVALLDEF-ABEVAZ .
/ZAK/BEVALLDEF_V-FIELD_C =
/ZAK/BEVALLDEF-FIELD_C .
/ZAK/BEVALLDEF_V-OVERWRITE =
/ZAK/BEVALLDEF-OVERWRITE .
/ZAK/BEVALLDEF_V-DATBI =
/ZAK/BEVALLDEF-DATBI .
/ZAK/BEVALLDEF_V-AS4USER =
/ZAK/BEVALLDEF-AS4USER .
/ZAK/BEVALLDEF_V-AS4DATE =
/ZAK/BEVALLDEF-AS4DATE .
/ZAK/BEVALLDEF_V-AS4TIME =
/ZAK/BEVALLDEF-AS4TIME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/BEVALLDEF-BTYPE AND
ABEVAZ = /ZAK/BEVALLDEF-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/BEVALLDEF_V-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /ZAK/BEVALLDEF_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/BEVALLDEF_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/BEVALLDEF_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/BEVALLDEF_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BEVALLDEF WHERE
  BUKRS = /ZAK/BEVALLDEF_V-BUKRS AND
  BTYPE = /ZAK/BEVALLDEF_V-BTYPE AND
  ABEVAZ = /ZAK/BEVALLDEF_V-ABEVAZ .
    IF SY-SUBRC = 0.
    DELETE /ZAK/BEVALLDEF .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BEVALLDEF WHERE
  BUKRS = /ZAK/BEVALLDEF_V-BUKRS AND
  BTYPE = /ZAK/BEVALLDEF_V-BTYPE AND
  ABEVAZ = /ZAK/BEVALLDEF_V-ABEVAZ .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/BEVALLDEF.
    ENDIF.
/ZAK/BEVALLDEF-MANDT =
/ZAK/BEVALLDEF_V-MANDT .
/ZAK/BEVALLDEF-BUKRS =
/ZAK/BEVALLDEF_V-BUKRS .
/ZAK/BEVALLDEF-BTYPE =
/ZAK/BEVALLDEF_V-BTYPE .
/ZAK/BEVALLDEF-ABEVAZ =
/ZAK/BEVALLDEF_V-ABEVAZ .
/ZAK/BEVALLDEF-FIELD_C =
/ZAK/BEVALLDEF_V-FIELD_C .
/ZAK/BEVALLDEF-OVERWRITE =
/ZAK/BEVALLDEF_V-OVERWRITE .
/ZAK/BEVALLDEF-DATBI =
/ZAK/BEVALLDEF_V-DATBI .
/ZAK/BEVALLDEF-AS4USER =
/ZAK/BEVALLDEF_V-AS4USER .
/ZAK/BEVALLDEF-AS4DATE =
/ZAK/BEVALLDEF_V-AS4DATE .
/ZAK/BEVALLDEF-AS4TIME =
/ZAK/BEVALLDEF_V-AS4TIME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/BEVALLDEF ##WARN_OK.
    ELSE.
    INSERT /ZAK/BEVALLDEF .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/BEVALLDEF_V-UPD_FLAG,
STATUS_/ZAK/BEVALLDEF_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/BEVALLDEF_V.
  SELECT SINGLE * FROM /ZAK/BEVALLDEF WHERE
BUKRS = /ZAK/BEVALLDEF_V-BUKRS AND
BTYPE = /ZAK/BEVALLDEF_V-BTYPE AND
ABEVAZ = /ZAK/BEVALLDEF_V-ABEVAZ .
/ZAK/BEVALLDEF_V-MANDT =
/ZAK/BEVALLDEF-MANDT .
/ZAK/BEVALLDEF_V-BUKRS =
/ZAK/BEVALLDEF-BUKRS .
/ZAK/BEVALLDEF_V-BTYPE =
/ZAK/BEVALLDEF-BTYPE .
/ZAK/BEVALLDEF_V-ABEVAZ =
/ZAK/BEVALLDEF-ABEVAZ .
/ZAK/BEVALLDEF_V-FIELD_C =
/ZAK/BEVALLDEF-FIELD_C .
/ZAK/BEVALLDEF_V-OVERWRITE =
/ZAK/BEVALLDEF-OVERWRITE .
/ZAK/BEVALLDEF_V-DATBI =
/ZAK/BEVALLDEF-DATBI .
/ZAK/BEVALLDEF_V-AS4USER =
/ZAK/BEVALLDEF-AS4USER .
/ZAK/BEVALLDEF_V-AS4DATE =
/ZAK/BEVALLDEF-AS4DATE .
/ZAK/BEVALLDEF_V-AS4TIME =
/ZAK/BEVALLDEF-AS4TIME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/BEVALLDEF-BTYPE AND
ABEVAZ = /ZAK/BEVALLDEF-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/BEVALLDEF_V-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/BEVALLDEF_V-ABEVTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/BEVALLDEF_V-ABEVTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/BEVALLDEF_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/BEVALLDEF_V-BUKRS TO
/ZAK/BEVALLDEF-BUKRS .
MOVE /ZAK/BEVALLDEF_V-BTYPE TO
/ZAK/BEVALLDEF-BTYPE .
MOVE /ZAK/BEVALLDEF_V-ABEVAZ TO
/ZAK/BEVALLDEF-ABEVAZ .
MOVE /ZAK/BEVALLDEF_V-MANDT TO
/ZAK/BEVALLDEF-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/BEVALLDEF'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/BEVALLDEF TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/BEVALLDEF'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/ZAK/BEVALLDEF_V USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/ZAK/BEVALLDEF-MANDT =
/ZAK/BEVALLDEF_V-MANDT .
/ZAK/BEVALLDEF-BUKRS =
/ZAK/BEVALLDEF_V-BUKRS .
/ZAK/BEVALLDEF-BTYPE =
/ZAK/BEVALLDEF_V-BTYPE .
/ZAK/BEVALLDEF-ABEVAZ =
/ZAK/BEVALLDEF_V-ABEVAZ .
/ZAK/BEVALLDEF-FIELD_C =
/ZAK/BEVALLDEF_V-FIELD_C .
/ZAK/BEVALLDEF-OVERWRITE =
/ZAK/BEVALLDEF_V-OVERWRITE .
/ZAK/BEVALLDEF-DATBI =
/ZAK/BEVALLDEF_V-DATBI .
/ZAK/BEVALLDEF-AS4USER =
/ZAK/BEVALLDEF_V-AS4USER .
/ZAK/BEVALLDEF-AS4DATE =
/ZAK/BEVALLDEF_V-AS4DATE .
/ZAK/BEVALLDEF-AS4TIME =
/ZAK/BEVALLDEF_V-AS4TIME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/BEVALLDEF-BTYPE AND
ABEVAZ = /ZAK/BEVALLDEF-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/BEVALLDEF_V-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/BEVALLDEF_V-ABEVTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/BEVALLDEF_V-ABEVTEXT .
    ENDIF.
ENDFORM.
