*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LIGSOR_MVTOP.                 " Global Data
  INCLUDE /ZAK/LIGSOR_MVUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LIGSOR_MVF00                       . " subprograms
  INCLUDE /ZAK/LIGSOR_MVI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LIGSOR_MVF...                 " Subprograms
* INCLUDE /ZAK/LIGSOR_MVO...                 " PBO-Modules
* INCLUDE /ZAK/LIGSOR_MVI...                 " PAI-Modules

INCLUDE /ZAK/LIGSOR_MVF01.
