*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/AFA_RRABEVV................................*
FORM GET_DATA_/ZAK/AFA_RRABEVV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/AFA_RRABEV WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/AFA_RRABEVV .
/ZAK/AFA_RRABEVV-MANDT =
/ZAK/AFA_RRABEV-MANDT .
/ZAK/AFA_RRABEVV-BTYPE =
/ZAK/AFA_RRABEV-BTYPE .
/ZAK/AFA_RRABEVV-ABEVAZ =
/ZAK/AFA_RRABEV-ABEVAZ .
/ZAK/AFA_RRABEVV-DATUM =
/ZAK/AFA_RRABEV-DATUM .
/ZAK/AFA_RRABEVV-UZEIT =
/ZAK/AFA_RRABEV-UZEIT .
/ZAK/AFA_RRABEVV-UNAME =
/ZAK/AFA_RRABEV-UNAME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/AFA_RRABEV-BTYPE AND
ABEVAZ = /ZAK/AFA_RRABEV-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/AFA_RRABEVV-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /ZAK/AFA_RRABEVV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/AFA_RRABEVV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/AFA_RRABEVV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/AFA_RRABEVV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_RRABEV WHERE
  BTYPE = /ZAK/AFA_RRABEVV-BTYPE AND
  ABEVAZ = /ZAK/AFA_RRABEVV-ABEVAZ .
    IF SY-SUBRC = 0.
    DELETE /ZAK/AFA_RRABEV .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_RRABEV WHERE
  BTYPE = /ZAK/AFA_RRABEVV-BTYPE AND
  ABEVAZ = /ZAK/AFA_RRABEVV-ABEVAZ .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/AFA_RRABEV.
    ENDIF.
/ZAK/AFA_RRABEV-MANDT =
/ZAK/AFA_RRABEVV-MANDT .
/ZAK/AFA_RRABEV-BTYPE =
/ZAK/AFA_RRABEVV-BTYPE .
/ZAK/AFA_RRABEV-ABEVAZ =
/ZAK/AFA_RRABEVV-ABEVAZ .
/ZAK/AFA_RRABEV-DATUM =
/ZAK/AFA_RRABEVV-DATUM .
/ZAK/AFA_RRABEV-UZEIT =
/ZAK/AFA_RRABEVV-UZEIT .
/ZAK/AFA_RRABEV-UNAME =
/ZAK/AFA_RRABEVV-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/AFA_RRABEV .
    ELSE.
    INSERT /ZAK/AFA_RRABEV .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/AFA_RRABEVV-UPD_FLAG,
STATUS_/ZAK/AFA_RRABEVV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/AFA_RRABEVV.
  SELECT SINGLE * FROM /ZAK/AFA_RRABEV WHERE
BTYPE = /ZAK/AFA_RRABEVV-BTYPE AND
ABEVAZ = /ZAK/AFA_RRABEVV-ABEVAZ .
/ZAK/AFA_RRABEVV-MANDT =
/ZAK/AFA_RRABEV-MANDT .
/ZAK/AFA_RRABEVV-BTYPE =
/ZAK/AFA_RRABEV-BTYPE .
/ZAK/AFA_RRABEVV-ABEVAZ =
/ZAK/AFA_RRABEV-ABEVAZ .
/ZAK/AFA_RRABEVV-DATUM =
/ZAK/AFA_RRABEV-DATUM .
/ZAK/AFA_RRABEVV-UZEIT =
/ZAK/AFA_RRABEV-UZEIT .
/ZAK/AFA_RRABEVV-UNAME =
/ZAK/AFA_RRABEV-UNAME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/AFA_RRABEV-BTYPE AND
ABEVAZ = /ZAK/AFA_RRABEV-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/AFA_RRABEVV-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/AFA_RRABEVV-ABEVTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/AFA_RRABEVV-ABEVTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/AFA_RRABEVV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/AFA_RRABEVV-BTYPE TO
/ZAK/AFA_RRABEV-BTYPE .
MOVE /ZAK/AFA_RRABEVV-ABEVAZ TO
/ZAK/AFA_RRABEV-ABEVAZ .
MOVE /ZAK/AFA_RRABEVV-MANDT TO
/ZAK/AFA_RRABEV-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/AFA_RRABEV'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/AFA_RRABEV TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/AFA_RRABEV'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/ZAK/AFA_RRABEVV USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/ZAK/AFA_RRABEV-MANDT =
/ZAK/AFA_RRABEVV-MANDT .
/ZAK/AFA_RRABEV-BTYPE =
/ZAK/AFA_RRABEVV-BTYPE .
/ZAK/AFA_RRABEV-ABEVAZ =
/ZAK/AFA_RRABEVV-ABEVAZ .
/ZAK/AFA_RRABEV-DATUM =
/ZAK/AFA_RRABEVV-DATUM .
/ZAK/AFA_RRABEV-UZEIT =
/ZAK/AFA_RRABEVV-UZEIT .
/ZAK/AFA_RRABEV-UNAME =
/ZAK/AFA_RRABEVV-UNAME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/AFA_RRABEV-BTYPE AND
ABEVAZ = /ZAK/AFA_RRABEV-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/AFA_RRABEVV-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/AFA_RRABEVV-ABEVTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/AFA_RRABEVV-ABEVTEXT .
    ENDIF.
ENDFORM.
