PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/AFA_ARABEVV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/AFA_ARABEVV-BTYPE .
    FIELD /ZAK/AFA_ARABEVV-ATYPE .
    FIELD /ZAK/AFA_ARABEVV-VPOPF .
    FIELD /ZAK/AFA_ARABEVV-ARANYF .
    FIELD /ZAK/AFA_ARABEVV-ABEVAZ .
    FIELD /ZAK/AFA_ARABEVV-ABEVTEXT .
    FIELD /ZAK/AFA_ARABEVV-DATUM .
    FIELD /ZAK/AFA_ARABEVV-UZEIT .
    FIELD /ZAK/AFA_ARABEVV-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_/ZAK/AFA_ARABEVV ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/AFA_ARABEVV-BTYPE .
    FIELD /ZAK/AFA_ARABEVV-ATYPE .
    FIELD /ZAK/AFA_ARABEVV-VPOPF .
    FIELD /ZAK/AFA_ARABEVV-ARANYF .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
