PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/BSET_MV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/BSET_MV-BUKRS .
    FIELD /ZAK/BSET_MV-BELNR .
    FIELD /ZAK/BSET_MV-GJAHR .
    FIELD /ZAK/BSET_MV-BUZEI .
    FIELD /ZAK/BSET_MV-BUPER .
    FIELD /ZAK/BSET_MV-ZINDEX .
    FIELD /ZAK/BSET_MV-TTIP .
    FIELD /ZAK/BSET_MV-ADODAT .
    FIELD /ZAK/BSET_MV-AD_BUKRS .
    FIELD /ZAK/BSET_MV-MWSKZ .
    FIELD /ZAK/BSET_MV-KTOSL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/BSET_MV-BUKRS .
    FIELD /ZAK/BSET_MV-BELNR .
    FIELD /ZAK/BSET_MV-GJAHR .
    FIELD /ZAK/BSET_MV-BUZEI .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
