*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/VPOP_LIFNRV................................*
FORM GET_DATA_/ZAK/VPOP_LIFNRV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/VPOP_LIFNR WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/VPOP_LIFNRV .
/ZAK/VPOP_LIFNRV-MANDT =
/ZAK/VPOP_LIFNR-MANDT .
/ZAK/VPOP_LIFNRV-BUKRS =
/ZAK/VPOP_LIFNR-BUKRS .
/ZAK/VPOP_LIFNRV-LIFNR =
/ZAK/VPOP_LIFNR-LIFNR .
/ZAK/VPOP_LIFNRV-DATUM =
/ZAK/VPOP_LIFNR-DATUM .
/ZAK/VPOP_LIFNRV-UZEIT =
/ZAK/VPOP_LIFNR-UZEIT .
/ZAK/VPOP_LIFNRV-UNAME =
/ZAK/VPOP_LIFNR-UNAME .
    SELECT SINGLE * FROM LFA1 WHERE
LIFNR = /ZAK/VPOP_LIFNR-LIFNR .
    IF SY-SUBRC EQ 0.
/ZAK/VPOP_LIFNRV-NAME1 =
LFA1-NAME1 .
    ENDIF.
<VIM_TOTAL_STRUC> = /ZAK/VPOP_LIFNRV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/VPOP_LIFNRV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/VPOP_LIFNRV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/VPOP_LIFNRV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/VPOP_LIFNR WHERE
  BUKRS = /ZAK/VPOP_LIFNRV-BUKRS AND
  LIFNR = /ZAK/VPOP_LIFNRV-LIFNR .
    IF SY-SUBRC = 0.
    DELETE /ZAK/VPOP_LIFNR .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/VPOP_LIFNR WHERE
  BUKRS = /ZAK/VPOP_LIFNRV-BUKRS AND
  LIFNR = /ZAK/VPOP_LIFNRV-LIFNR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/VPOP_LIFNR.
    ENDIF.
/ZAK/VPOP_LIFNR-MANDT =
/ZAK/VPOP_LIFNRV-MANDT .
/ZAK/VPOP_LIFNR-BUKRS =
/ZAK/VPOP_LIFNRV-BUKRS .
/ZAK/VPOP_LIFNR-LIFNR =
/ZAK/VPOP_LIFNRV-LIFNR .
/ZAK/VPOP_LIFNR-DATUM =
/ZAK/VPOP_LIFNRV-DATUM .
/ZAK/VPOP_LIFNR-UZEIT =
/ZAK/VPOP_LIFNRV-UZEIT .
/ZAK/VPOP_LIFNR-UNAME =
/ZAK/VPOP_LIFNRV-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/VPOP_LIFNR .
    ELSE.
    INSERT /ZAK/VPOP_LIFNR .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/VPOP_LIFNRV-UPD_FLAG,
STATUS_/ZAK/VPOP_LIFNRV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/VPOP_LIFNRV.
  SELECT SINGLE * FROM /ZAK/VPOP_LIFNR WHERE
BUKRS = /ZAK/VPOP_LIFNRV-BUKRS AND
LIFNR = /ZAK/VPOP_LIFNRV-LIFNR .
/ZAK/VPOP_LIFNRV-MANDT =
/ZAK/VPOP_LIFNR-MANDT .
/ZAK/VPOP_LIFNRV-BUKRS =
/ZAK/VPOP_LIFNR-BUKRS .
/ZAK/VPOP_LIFNRV-LIFNR =
/ZAK/VPOP_LIFNR-LIFNR .
/ZAK/VPOP_LIFNRV-DATUM =
/ZAK/VPOP_LIFNR-DATUM .
/ZAK/VPOP_LIFNRV-UZEIT =
/ZAK/VPOP_LIFNR-UZEIT .
/ZAK/VPOP_LIFNRV-UNAME =
/ZAK/VPOP_LIFNR-UNAME .
    SELECT SINGLE * FROM LFA1 WHERE
LIFNR = /ZAK/VPOP_LIFNR-LIFNR .
    IF SY-SUBRC EQ 0.
/ZAK/VPOP_LIFNRV-NAME1 =
LFA1-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/VPOP_LIFNRV-NAME1 .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/VPOP_LIFNRV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/VPOP_LIFNRV-BUKRS TO
/ZAK/VPOP_LIFNR-BUKRS .
MOVE /ZAK/VPOP_LIFNRV-LIFNR TO
/ZAK/VPOP_LIFNR-LIFNR .
MOVE /ZAK/VPOP_LIFNRV-MANDT TO
/ZAK/VPOP_LIFNR-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/VPOP_LIFNR'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/VPOP_LIFNR TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/VPOP_LIFNR'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/ZAK/VPOP_LIFNRV USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/ZAK/VPOP_LIFNR-MANDT =
/ZAK/VPOP_LIFNRV-MANDT .
/ZAK/VPOP_LIFNR-BUKRS =
/ZAK/VPOP_LIFNRV-BUKRS .
/ZAK/VPOP_LIFNR-LIFNR =
/ZAK/VPOP_LIFNRV-LIFNR .
/ZAK/VPOP_LIFNR-DATUM =
/ZAK/VPOP_LIFNRV-DATUM .
/ZAK/VPOP_LIFNR-UZEIT =
/ZAK/VPOP_LIFNRV-UZEIT .
/ZAK/VPOP_LIFNR-UNAME =
/ZAK/VPOP_LIFNRV-UNAME .
    SELECT SINGLE * FROM LFA1 WHERE
LIFNR = /ZAK/VPOP_LIFNR-LIFNR .
    IF SY-SUBRC EQ 0.
/ZAK/VPOP_LIFNRV-NAME1 =
LFA1-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/VPOP_LIFNRV-NAME1 .
    ENDIF.
ENDFORM.
