*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/UREPI_DATAV................................*
FORM GET_DATA_/ZAK/UREPI_DATAV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/UREPIDATA WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/UREPI_DATAV .
/ZAK/UREPI_DATAV-MANDT =
/ZAK/UREPIDATA-MANDT .
/ZAK/UREPI_DATAV-BUKRS =
/ZAK/UREPIDATA-BUKRS .
/ZAK/UREPI_DATAV-GJAHR =
/ZAK/UREPIDATA-GJAHR .
/ZAK/UREPI_DATAV-UREPF =
/ZAK/UREPIDATA-UREPF .
/ZAK/UREPI_DATAV-ADOMN =
/ZAK/UREPIDATA-ADOMN .
/ZAK/UREPI_DATAV-HFORG =
/ZAK/UREPIDATA-HFORG .
/ZAK/UREPI_DATAV-WAERS =
/ZAK/UREPIDATA-WAERS .
<VIM_TOTAL_STRUC> = /ZAK/UREPI_DATAV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/UREPI_DATAV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/UREPI_DATAV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/UREPI_DATAV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/UREPIDATA WHERE
  BUKRS = /ZAK/UREPI_DATAV-BUKRS AND
  GJAHR = /ZAK/UREPI_DATAV-GJAHR AND
  UREPF = /ZAK/UREPI_DATAV-UREPF .
    IF SY-SUBRC = 0.
    DELETE /ZAK/UREPIDATA .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/UREPIDATA WHERE
  BUKRS = /ZAK/UREPI_DATAV-BUKRS AND
  GJAHR = /ZAK/UREPI_DATAV-GJAHR AND
  UREPF = /ZAK/UREPI_DATAV-UREPF .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/UREPIDATA.
    ENDIF.
/ZAK/UREPIDATA-MANDT =
/ZAK/UREPI_DATAV-MANDT .
/ZAK/UREPIDATA-BUKRS =
/ZAK/UREPI_DATAV-BUKRS .
/ZAK/UREPIDATA-GJAHR =
/ZAK/UREPI_DATAV-GJAHR .
/ZAK/UREPIDATA-UREPF =
/ZAK/UREPI_DATAV-UREPF .
/ZAK/UREPIDATA-ADOMN =
/ZAK/UREPI_DATAV-ADOMN .
/ZAK/UREPIDATA-HFORG =
/ZAK/UREPI_DATAV-HFORG .
/ZAK/UREPIDATA-WAERS =
/ZAK/UREPI_DATAV-WAERS .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/UREPIDATA .
    ELSE.
    INSERT /ZAK/UREPIDATA .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/UREPI_DATAV-UPD_FLAG,
STATUS_/ZAK/UREPI_DATAV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/UREPI_DATAV.
  SELECT SINGLE * FROM /ZAK/UREPIDATA WHERE
BUKRS = /ZAK/UREPI_DATAV-BUKRS AND
GJAHR = /ZAK/UREPI_DATAV-GJAHR AND
UREPF = /ZAK/UREPI_DATAV-UREPF .
/ZAK/UREPI_DATAV-MANDT =
/ZAK/UREPIDATA-MANDT .
/ZAK/UREPI_DATAV-BUKRS =
/ZAK/UREPIDATA-BUKRS .
/ZAK/UREPI_DATAV-GJAHR =
/ZAK/UREPIDATA-GJAHR .
/ZAK/UREPI_DATAV-UREPF =
/ZAK/UREPIDATA-UREPF .
/ZAK/UREPI_DATAV-ADOMN =
/ZAK/UREPIDATA-ADOMN .
/ZAK/UREPI_DATAV-HFORG =
/ZAK/UREPIDATA-HFORG .
/ZAK/UREPI_DATAV-WAERS =
/ZAK/UREPIDATA-WAERS .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/UREPI_DATAV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/UREPI_DATAV-BUKRS TO
/ZAK/UREPIDATA-BUKRS .
MOVE /ZAK/UREPI_DATAV-GJAHR TO
/ZAK/UREPIDATA-GJAHR .
MOVE /ZAK/UREPI_DATAV-UREPF TO
/ZAK/UREPIDATA-UREPF .
MOVE /ZAK/UREPI_DATAV-MANDT TO
/ZAK/UREPIDATA-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/UREPIDATA'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/UREPIDATA TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/UREPIDATA'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
