*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/ANALITIKA_V.................................*
FORM GET_DATA_/ZAK/ANALITIKA_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/ANALITIKA WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/ANALITIKA_V .
/ZAK/ANALITIKA_V-MANDT =
/ZAK/ANALITIKA-MANDT .
/ZAK/ANALITIKA_V-BUKRS =
/ZAK/ANALITIKA-BUKRS .
/ZAK/ANALITIKA_V-BTYPE =
/ZAK/ANALITIKA-BTYPE .
/ZAK/ANALITIKA_V-GJAHR =
/ZAK/ANALITIKA-GJAHR .
/ZAK/ANALITIKA_V-MONAT =
/ZAK/ANALITIKA-MONAT .
/ZAK/ANALITIKA_V-ZINDEX =
/ZAK/ANALITIKA-ZINDEX .
/ZAK/ANALITIKA_V-ABEVAZ =
/ZAK/ANALITIKA-ABEVAZ .
/ZAK/ANALITIKA_V-ADOAZON =
/ZAK/ANALITIKA-ADOAZON .
/ZAK/ANALITIKA_V-BSZNUM =
/ZAK/ANALITIKA-BSZNUM .
/ZAK/ANALITIKA_V-PACK =
/ZAK/ANALITIKA-PACK .
/ZAK/ANALITIKA_V-ITEM =
/ZAK/ANALITIKA-ITEM .
/ZAK/ANALITIKA_V-LAPSZ =
/ZAK/ANALITIKA-LAPSZ .
/ZAK/ANALITIKA_V-XMANU =
/ZAK/ANALITIKA-XMANU .
/ZAK/ANALITIKA_V-XDEFT =
/ZAK/ANALITIKA-XDEFT .
/ZAK/ANALITIKA_V-VORSTOR =
/ZAK/ANALITIKA-VORSTOR .
/ZAK/ANALITIKA_V-STAPO =
/ZAK/ANALITIKA-STAPO .
/ZAK/ANALITIKA_V-DMBTR =
/ZAK/ANALITIKA-DMBTR .
/ZAK/ANALITIKA_V-WAERS =
/ZAK/ANALITIKA-WAERS .
/ZAK/ANALITIKA_V-KOSTL =
/ZAK/ANALITIKA-KOSTL .
/ZAK/ANALITIKA_V-ZCOMMENT =
/ZAK/ANALITIKA-ZCOMMENT .
/ZAK/ANALITIKA_V-BSEG_GJAHR =
/ZAK/ANALITIKA-BSEG_GJAHR .
/ZAK/ANALITIKA_V-BSEG_BELNR =
/ZAK/ANALITIKA-BSEG_BELNR .
/ZAK/ANALITIKA_V-BSEG_BUZEI =
/ZAK/ANALITIKA-BSEG_BUZEI .
/ZAK/ANALITIKA_V-BOOK =
/ZAK/ANALITIKA-BOOK .
/ZAK/ANALITIKA_V-KMONAT =
/ZAK/ANALITIKA-KMONAT .
/ZAK/ANALITIKA_V-KTOSL =
/ZAK/ANALITIKA-KTOSL .
/ZAK/ANALITIKA_V-MWSKZ =
/ZAK/ANALITIKA-MWSKZ .
/ZAK/ANALITIKA_V-KBETR =
/ZAK/ANALITIKA-KBETR .
/ZAK/ANALITIKA_V-BLART =
/ZAK/ANALITIKA-BLART .
/ZAK/ANALITIKA_V-BUDAT =
/ZAK/ANALITIKA-BUDAT .
/ZAK/ANALITIKA_V-BLDAT =
/ZAK/ANALITIKA-BLDAT .
/ZAK/ANALITIKA_V-ZFBDT =
/ZAK/ANALITIKA-ZFBDT .
/ZAK/ANALITIKA_V-HKONT =
/ZAK/ANALITIKA-HKONT .
/ZAK/ANALITIKA_V-LIFKUN =
/ZAK/ANALITIKA-LIFKUN .
/ZAK/ANALITIKA_V-KOART =
/ZAK/ANALITIKA-KOART .
/ZAK/ANALITIKA_V-STCEG =
/ZAK/ANALITIKA-STCEG .
/ZAK/ANALITIKA_V-STCD1 =
/ZAK/ANALITIKA-STCD1 .
/ZAK/ANALITIKA_V-STCD2 =
/ZAK/ANALITIKA-STCD2 .
/ZAK/ANALITIKA_V-STCD3 =
/ZAK/ANALITIKA-STCD3 .
/ZAK/ANALITIKA_V-XBLNR =
/ZAK/ANALITIKA-XBLNR .
/ZAK/ANALITIKA_V-LWBAS =
/ZAK/ANALITIKA-LWBAS .
/ZAK/ANALITIKA_V-FWBAS =
/ZAK/ANALITIKA-FWBAS .
/ZAK/ANALITIKA_V-LWSTE =
/ZAK/ANALITIKA-LWSTE .
/ZAK/ANALITIKA_V-FWSTE =
/ZAK/ANALITIKA-FWSTE .
/ZAK/ANALITIKA_V-HWBTR =
/ZAK/ANALITIKA-HWBTR .
/ZAK/ANALITIKA_V-FWBTR =
/ZAK/ANALITIKA-FWBTR .
/ZAK/ANALITIKA_V-FWAERS =
/ZAK/ANALITIKA-FWAERS .
/ZAK/ANALITIKA_V-AUFNR =
/ZAK/ANALITIKA-AUFNR .
/ZAK/ANALITIKA_V-UMSKZ =
/ZAK/ANALITIKA-UMSKZ .
/ZAK/ANALITIKA_V-BSCHL =
/ZAK/ANALITIKA-BSCHL .
/ZAK/ANALITIKA_V-AUGDT =
/ZAK/ANALITIKA-AUGDT .
/ZAK/ANALITIKA_V-PRCTR =
/ZAK/ANALITIKA-PRCTR .
/ZAK/ANALITIKA_V-FIELD_C =
/ZAK/ANALITIKA-FIELD_C .
/ZAK/ANALITIKA_V-FIELD_N =
/ZAK/ANALITIKA-FIELD_N .
/ZAK/ANALITIKA_V-FIELD_A =
/ZAK/ANALITIKA-FIELD_A .
/ZAK/ANALITIKA_V-TTIP =
/ZAK/ANALITIKA-TTIP .
/ZAK/ANALITIKA_V-ADODAT =
/ZAK/ANALITIKA-ADODAT .
/ZAK/ANALITIKA_V-GSBER =
/ZAK/ANALITIKA-GSBER .
/ZAK/ANALITIKA_V-HSZU =
/ZAK/ANALITIKA-HSZU .
/ZAK/ANALITIKA_V-FI_BUKRS =
/ZAK/ANALITIKA-FI_BUKRS .
/ZAK/ANALITIKA_V-ARANY_FLAG =
/ZAK/ANALITIKA-ARANY_FLAG .
/ZAK/ANALITIKA_V-NYLAPAZON =
/ZAK/ANALITIKA-NYLAPAZON .
/ZAK/ANALITIKA_V-ONYBF =
/ZAK/ANALITIKA-ONYBF .
/ZAK/ANALITIKA_V-ONYB_PACK =
/ZAK/ANALITIKA-ONYB_PACK .
/ZAK/ANALITIKA_V-POSID =
/ZAK/ANALITIKA-POSID .
/ZAK/ANALITIKA_V-XEGDR =
/ZAK/ANALITIKA-XEGDR .
/ZAK/ANALITIKA_V-USNAM =
/ZAK/ANALITIKA-USNAM .
/ZAK/ANALITIKA_V-SZAMLAKELT =
/ZAK/ANALITIKA-SZAMLAKELT .
/ZAK/ANALITIKA_V-SZAMLASZ =
/ZAK/ANALITIKA-SZAMLASZ .
/ZAK/ANALITIKA_V-SZAMLASZE =
/ZAK/ANALITIKA-SZAMLASZE .
/ZAK/ANALITIKA_V-SZLATIP =
/ZAK/ANALITIKA-SZLATIP .
/ZAK/ANALITIKA_V-SZAMLASZA =
/ZAK/ANALITIKA-SZAMLASZA .
/ZAK/ANALITIKA_V-ZMWSKF =
/ZAK/ANALITIKA-ZMWSKF .
/ZAK/ANALITIKA_V-ZKUNNAME =
/ZAK/ANALITIKA-ZKUNNAME .
/ZAK/ANALITIKA_V-ZKUNADRS =
/ZAK/ANALITIKA-ZKUNADRS .
/ZAK/ANALITIKA_V-NONEED =
/ZAK/ANALITIKA-NONEED .
/ZAK/ANALITIKA_V-VKORG =
/ZAK/ANALITIKA-VKORG .
/ZAK/ANALITIKA_V-ZUONR =
/ZAK/ANALITIKA-ZUONR .
/ZAK/ANALITIKA_V-VMSZA =
/ZAK/ANALITIKA-VMSZA .
/ZAK/ANALITIKA_V-XREF1_HD =
/ZAK/ANALITIKA-XREF1_HD .
/ZAK/ANALITIKA_V-XREF2_HD =
/ZAK/ANALITIKA-XREF2_HD .
/ZAK/ANALITIKA_V-H_GJAHR =
/ZAK/ANALITIKA-H_GJAHR .
/ZAK/ANALITIKA_V-H_BELNR =
/ZAK/ANALITIKA-H_BELNR .
/ZAK/ANALITIKA_V-ELSTAD =
/ZAK/ANALITIKA-ELSTAD .
/ZAK/ANALITIKA_V-UGYFEL =
/ZAK/ANALITIKA-UGYFEL .
/ZAK/ANALITIKA_V-VAROS =
/ZAK/ANALITIKA-VAROS .
/ZAK/ANALITIKA_V-CIM =
/ZAK/ANALITIKA-CIM .
/ZAK/ANALITIKA_V-IRSZ =
/ZAK/ANALITIKA-IRSZ .
/ZAK/ANALITIKA_V-ORSZAG =
/ZAK/ANALITIKA-ORSZAG .
<VIM_TOTAL_STRUC> = /ZAK/ANALITIKA_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/ANALITIKA_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/ANALITIKA_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/ANALITIKA_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/ANALITIKA WHERE
  BUKRS = /ZAK/ANALITIKA_V-BUKRS AND
  BTYPE = /ZAK/ANALITIKA_V-BTYPE AND
  GJAHR = /ZAK/ANALITIKA_V-GJAHR AND
  MONAT = /ZAK/ANALITIKA_V-MONAT AND
  ZINDEX = /ZAK/ANALITIKA_V-ZINDEX AND
  ABEVAZ = /ZAK/ANALITIKA_V-ABEVAZ AND
  ADOAZON = /ZAK/ANALITIKA_V-ADOAZON AND
  BSZNUM = /ZAK/ANALITIKA_V-BSZNUM AND
  PACK = /ZAK/ANALITIKA_V-PACK AND
  ITEM = /ZAK/ANALITIKA_V-ITEM AND
  LAPSZ = /ZAK/ANALITIKA_V-LAPSZ .
    IF SY-SUBRC = 0.
    DELETE /ZAK/ANALITIKA .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/ANALITIKA WHERE
  BUKRS = /ZAK/ANALITIKA_V-BUKRS AND
  BTYPE = /ZAK/ANALITIKA_V-BTYPE AND
  GJAHR = /ZAK/ANALITIKA_V-GJAHR AND
  MONAT = /ZAK/ANALITIKA_V-MONAT AND
  ZINDEX = /ZAK/ANALITIKA_V-ZINDEX AND
  ABEVAZ = /ZAK/ANALITIKA_V-ABEVAZ AND
  ADOAZON = /ZAK/ANALITIKA_V-ADOAZON AND
  BSZNUM = /ZAK/ANALITIKA_V-BSZNUM AND
  PACK = /ZAK/ANALITIKA_V-PACK AND
  ITEM = /ZAK/ANALITIKA_V-ITEM AND
  LAPSZ = /ZAK/ANALITIKA_V-LAPSZ .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/ANALITIKA.
    ENDIF.
/ZAK/ANALITIKA-MANDT =
/ZAK/ANALITIKA_V-MANDT .
/ZAK/ANALITIKA-BUKRS =
/ZAK/ANALITIKA_V-BUKRS .
/ZAK/ANALITIKA-BTYPE =
/ZAK/ANALITIKA_V-BTYPE .
/ZAK/ANALITIKA-GJAHR =
/ZAK/ANALITIKA_V-GJAHR .
/ZAK/ANALITIKA-MONAT =
/ZAK/ANALITIKA_V-MONAT .
/ZAK/ANALITIKA-ZINDEX =
/ZAK/ANALITIKA_V-ZINDEX .
/ZAK/ANALITIKA-ABEVAZ =
/ZAK/ANALITIKA_V-ABEVAZ .
/ZAK/ANALITIKA-ADOAZON =
/ZAK/ANALITIKA_V-ADOAZON .
/ZAK/ANALITIKA-BSZNUM =
/ZAK/ANALITIKA_V-BSZNUM .
/ZAK/ANALITIKA-PACK =
/ZAK/ANALITIKA_V-PACK .
/ZAK/ANALITIKA-ITEM =
/ZAK/ANALITIKA_V-ITEM .
/ZAK/ANALITIKA-LAPSZ =
/ZAK/ANALITIKA_V-LAPSZ .
/ZAK/ANALITIKA-XMANU =
/ZAK/ANALITIKA_V-XMANU .
/ZAK/ANALITIKA-XDEFT =
/ZAK/ANALITIKA_V-XDEFT .
/ZAK/ANALITIKA-VORSTOR =
/ZAK/ANALITIKA_V-VORSTOR .
/ZAK/ANALITIKA-STAPO =
/ZAK/ANALITIKA_V-STAPO .
/ZAK/ANALITIKA-DMBTR =
/ZAK/ANALITIKA_V-DMBTR .
/ZAK/ANALITIKA-WAERS =
/ZAK/ANALITIKA_V-WAERS .
/ZAK/ANALITIKA-KOSTL =
/ZAK/ANALITIKA_V-KOSTL .
/ZAK/ANALITIKA-ZCOMMENT =
/ZAK/ANALITIKA_V-ZCOMMENT .
/ZAK/ANALITIKA-BSEG_GJAHR =
/ZAK/ANALITIKA_V-BSEG_GJAHR .
/ZAK/ANALITIKA-BSEG_BELNR =
/ZAK/ANALITIKA_V-BSEG_BELNR .
/ZAK/ANALITIKA-BSEG_BUZEI =
/ZAK/ANALITIKA_V-BSEG_BUZEI .
/ZAK/ANALITIKA-BOOK =
/ZAK/ANALITIKA_V-BOOK .
/ZAK/ANALITIKA-KMONAT =
/ZAK/ANALITIKA_V-KMONAT .
/ZAK/ANALITIKA-KTOSL =
/ZAK/ANALITIKA_V-KTOSL .
/ZAK/ANALITIKA-MWSKZ =
/ZAK/ANALITIKA_V-MWSKZ .
/ZAK/ANALITIKA-KBETR =
/ZAK/ANALITIKA_V-KBETR .
/ZAK/ANALITIKA-BLART =
/ZAK/ANALITIKA_V-BLART .
/ZAK/ANALITIKA-BUDAT =
/ZAK/ANALITIKA_V-BUDAT .
/ZAK/ANALITIKA-BLDAT =
/ZAK/ANALITIKA_V-BLDAT .
/ZAK/ANALITIKA-ZFBDT =
/ZAK/ANALITIKA_V-ZFBDT .
/ZAK/ANALITIKA-HKONT =
/ZAK/ANALITIKA_V-HKONT .
/ZAK/ANALITIKA-LIFKUN =
/ZAK/ANALITIKA_V-LIFKUN .
/ZAK/ANALITIKA-KOART =
/ZAK/ANALITIKA_V-KOART .
/ZAK/ANALITIKA-STCEG =
/ZAK/ANALITIKA_V-STCEG .
/ZAK/ANALITIKA-STCD1 =
/ZAK/ANALITIKA_V-STCD1 .
/ZAK/ANALITIKA-STCD2 =
/ZAK/ANALITIKA_V-STCD2 .
/ZAK/ANALITIKA-STCD3 =
/ZAK/ANALITIKA_V-STCD3 .
/ZAK/ANALITIKA-XBLNR =
/ZAK/ANALITIKA_V-XBLNR .
/ZAK/ANALITIKA-LWBAS =
/ZAK/ANALITIKA_V-LWBAS .
/ZAK/ANALITIKA-FWBAS =
/ZAK/ANALITIKA_V-FWBAS .
/ZAK/ANALITIKA-LWSTE =
/ZAK/ANALITIKA_V-LWSTE .
/ZAK/ANALITIKA-FWSTE =
/ZAK/ANALITIKA_V-FWSTE .
/ZAK/ANALITIKA-HWBTR =
/ZAK/ANALITIKA_V-HWBTR .
/ZAK/ANALITIKA-FWBTR =
/ZAK/ANALITIKA_V-FWBTR .
/ZAK/ANALITIKA-FWAERS =
/ZAK/ANALITIKA_V-FWAERS .
/ZAK/ANALITIKA-AUFNR =
/ZAK/ANALITIKA_V-AUFNR .
/ZAK/ANALITIKA-UMSKZ =
/ZAK/ANALITIKA_V-UMSKZ .
/ZAK/ANALITIKA-BSCHL =
/ZAK/ANALITIKA_V-BSCHL .
/ZAK/ANALITIKA-AUGDT =
/ZAK/ANALITIKA_V-AUGDT .
/ZAK/ANALITIKA-PRCTR =
/ZAK/ANALITIKA_V-PRCTR .
/ZAK/ANALITIKA-FIELD_C =
/ZAK/ANALITIKA_V-FIELD_C .
/ZAK/ANALITIKA-FIELD_N =
/ZAK/ANALITIKA_V-FIELD_N .
/ZAK/ANALITIKA-FIELD_A =
/ZAK/ANALITIKA_V-FIELD_A .
/ZAK/ANALITIKA-TTIP =
/ZAK/ANALITIKA_V-TTIP .
/ZAK/ANALITIKA-ADODAT =
/ZAK/ANALITIKA_V-ADODAT .
/ZAK/ANALITIKA-GSBER =
/ZAK/ANALITIKA_V-GSBER .
/ZAK/ANALITIKA-HSZU =
/ZAK/ANALITIKA_V-HSZU .
/ZAK/ANALITIKA-FI_BUKRS =
/ZAK/ANALITIKA_V-FI_BUKRS .
/ZAK/ANALITIKA-ARANY_FLAG =
/ZAK/ANALITIKA_V-ARANY_FLAG .
/ZAK/ANALITIKA-NYLAPAZON =
/ZAK/ANALITIKA_V-NYLAPAZON .
/ZAK/ANALITIKA-ONYBF =
/ZAK/ANALITIKA_V-ONYBF .
/ZAK/ANALITIKA-ONYB_PACK =
/ZAK/ANALITIKA_V-ONYB_PACK .
/ZAK/ANALITIKA-POSID =
/ZAK/ANALITIKA_V-POSID .
/ZAK/ANALITIKA-XEGDR =
/ZAK/ANALITIKA_V-XEGDR .
/ZAK/ANALITIKA-USNAM =
/ZAK/ANALITIKA_V-USNAM .
/ZAK/ANALITIKA-SZAMLAKELT =
/ZAK/ANALITIKA_V-SZAMLAKELT .
/ZAK/ANALITIKA-SZAMLASZ =
/ZAK/ANALITIKA_V-SZAMLASZ .
/ZAK/ANALITIKA-SZAMLASZE =
/ZAK/ANALITIKA_V-SZAMLASZE .
/ZAK/ANALITIKA-SZLATIP =
/ZAK/ANALITIKA_V-SZLATIP .
/ZAK/ANALITIKA-SZAMLASZA =
/ZAK/ANALITIKA_V-SZAMLASZA .
/ZAK/ANALITIKA-ZMWSKF =
/ZAK/ANALITIKA_V-ZMWSKF .
/ZAK/ANALITIKA-ZKUNNAME =
/ZAK/ANALITIKA_V-ZKUNNAME .
/ZAK/ANALITIKA-ZKUNADRS =
/ZAK/ANALITIKA_V-ZKUNADRS .
/ZAK/ANALITIKA-NONEED =
/ZAK/ANALITIKA_V-NONEED .
/ZAK/ANALITIKA-VKORG =
/ZAK/ANALITIKA_V-VKORG .
/ZAK/ANALITIKA-ZUONR =
/ZAK/ANALITIKA_V-ZUONR .
/ZAK/ANALITIKA-VMSZA =
/ZAK/ANALITIKA_V-VMSZA .
/ZAK/ANALITIKA-XREF1_HD =
/ZAK/ANALITIKA_V-XREF1_HD .
/ZAK/ANALITIKA-XREF2_HD =
/ZAK/ANALITIKA_V-XREF2_HD .
/ZAK/ANALITIKA-H_GJAHR =
/ZAK/ANALITIKA_V-H_GJAHR .
/ZAK/ANALITIKA-H_BELNR =
/ZAK/ANALITIKA_V-H_BELNR .
/ZAK/ANALITIKA-ELSTAD =
/ZAK/ANALITIKA_V-ELSTAD .
/ZAK/ANALITIKA-UGYFEL =
/ZAK/ANALITIKA_V-UGYFEL .
/ZAK/ANALITIKA-VAROS =
/ZAK/ANALITIKA_V-VAROS .
/ZAK/ANALITIKA-CIM =
/ZAK/ANALITIKA_V-CIM .
/ZAK/ANALITIKA-IRSZ =
/ZAK/ANALITIKA_V-IRSZ .
/ZAK/ANALITIKA-ORSZAG =
/ZAK/ANALITIKA_V-ORSZAG .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/ANALITIKA ##WARN_OK.
    ELSE.
    INSERT /ZAK/ANALITIKA .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/ANALITIKA_V-UPD_FLAG,
STATUS_/ZAK/ANALITIKA_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/ANALITIKA_V.
  SELECT SINGLE * FROM /ZAK/ANALITIKA WHERE
BUKRS = /ZAK/ANALITIKA_V-BUKRS AND
BTYPE = /ZAK/ANALITIKA_V-BTYPE AND
GJAHR = /ZAK/ANALITIKA_V-GJAHR AND
MONAT = /ZAK/ANALITIKA_V-MONAT AND
ZINDEX = /ZAK/ANALITIKA_V-ZINDEX AND
ABEVAZ = /ZAK/ANALITIKA_V-ABEVAZ AND
ADOAZON = /ZAK/ANALITIKA_V-ADOAZON AND
BSZNUM = /ZAK/ANALITIKA_V-BSZNUM AND
PACK = /ZAK/ANALITIKA_V-PACK AND
ITEM = /ZAK/ANALITIKA_V-ITEM AND
LAPSZ = /ZAK/ANALITIKA_V-LAPSZ .
/ZAK/ANALITIKA_V-MANDT =
/ZAK/ANALITIKA-MANDT .
/ZAK/ANALITIKA_V-BUKRS =
/ZAK/ANALITIKA-BUKRS .
/ZAK/ANALITIKA_V-BTYPE =
/ZAK/ANALITIKA-BTYPE .
/ZAK/ANALITIKA_V-GJAHR =
/ZAK/ANALITIKA-GJAHR .
/ZAK/ANALITIKA_V-MONAT =
/ZAK/ANALITIKA-MONAT .
/ZAK/ANALITIKA_V-ZINDEX =
/ZAK/ANALITIKA-ZINDEX .
/ZAK/ANALITIKA_V-ABEVAZ =
/ZAK/ANALITIKA-ABEVAZ .
/ZAK/ANALITIKA_V-ADOAZON =
/ZAK/ANALITIKA-ADOAZON .
/ZAK/ANALITIKA_V-BSZNUM =
/ZAK/ANALITIKA-BSZNUM .
/ZAK/ANALITIKA_V-PACK =
/ZAK/ANALITIKA-PACK .
/ZAK/ANALITIKA_V-ITEM =
/ZAK/ANALITIKA-ITEM .
/ZAK/ANALITIKA_V-LAPSZ =
/ZAK/ANALITIKA-LAPSZ .
/ZAK/ANALITIKA_V-XMANU =
/ZAK/ANALITIKA-XMANU .
/ZAK/ANALITIKA_V-XDEFT =
/ZAK/ANALITIKA-XDEFT .
/ZAK/ANALITIKA_V-VORSTOR =
/ZAK/ANALITIKA-VORSTOR .
/ZAK/ANALITIKA_V-STAPO =
/ZAK/ANALITIKA-STAPO .
/ZAK/ANALITIKA_V-DMBTR =
/ZAK/ANALITIKA-DMBTR .
/ZAK/ANALITIKA_V-WAERS =
/ZAK/ANALITIKA-WAERS .
/ZAK/ANALITIKA_V-KOSTL =
/ZAK/ANALITIKA-KOSTL .
/ZAK/ANALITIKA_V-ZCOMMENT =
/ZAK/ANALITIKA-ZCOMMENT .
/ZAK/ANALITIKA_V-BSEG_GJAHR =
/ZAK/ANALITIKA-BSEG_GJAHR .
/ZAK/ANALITIKA_V-BSEG_BELNR =
/ZAK/ANALITIKA-BSEG_BELNR .
/ZAK/ANALITIKA_V-BSEG_BUZEI =
/ZAK/ANALITIKA-BSEG_BUZEI .
/ZAK/ANALITIKA_V-BOOK =
/ZAK/ANALITIKA-BOOK .
/ZAK/ANALITIKA_V-KMONAT =
/ZAK/ANALITIKA-KMONAT .
/ZAK/ANALITIKA_V-KTOSL =
/ZAK/ANALITIKA-KTOSL .
/ZAK/ANALITIKA_V-MWSKZ =
/ZAK/ANALITIKA-MWSKZ .
/ZAK/ANALITIKA_V-KBETR =
/ZAK/ANALITIKA-KBETR .
/ZAK/ANALITIKA_V-BLART =
/ZAK/ANALITIKA-BLART .
/ZAK/ANALITIKA_V-BUDAT =
/ZAK/ANALITIKA-BUDAT .
/ZAK/ANALITIKA_V-BLDAT =
/ZAK/ANALITIKA-BLDAT .
/ZAK/ANALITIKA_V-ZFBDT =
/ZAK/ANALITIKA-ZFBDT .
/ZAK/ANALITIKA_V-HKONT =
/ZAK/ANALITIKA-HKONT .
/ZAK/ANALITIKA_V-LIFKUN =
/ZAK/ANALITIKA-LIFKUN .
/ZAK/ANALITIKA_V-KOART =
/ZAK/ANALITIKA-KOART .
/ZAK/ANALITIKA_V-STCEG =
/ZAK/ANALITIKA-STCEG .
/ZAK/ANALITIKA_V-STCD1 =
/ZAK/ANALITIKA-STCD1 .
/ZAK/ANALITIKA_V-STCD2 =
/ZAK/ANALITIKA-STCD2 .
/ZAK/ANALITIKA_V-STCD3 =
/ZAK/ANALITIKA-STCD3 .
/ZAK/ANALITIKA_V-XBLNR =
/ZAK/ANALITIKA-XBLNR .
/ZAK/ANALITIKA_V-LWBAS =
/ZAK/ANALITIKA-LWBAS .
/ZAK/ANALITIKA_V-FWBAS =
/ZAK/ANALITIKA-FWBAS .
/ZAK/ANALITIKA_V-LWSTE =
/ZAK/ANALITIKA-LWSTE .
/ZAK/ANALITIKA_V-FWSTE =
/ZAK/ANALITIKA-FWSTE .
/ZAK/ANALITIKA_V-HWBTR =
/ZAK/ANALITIKA-HWBTR .
/ZAK/ANALITIKA_V-FWBTR =
/ZAK/ANALITIKA-FWBTR .
/ZAK/ANALITIKA_V-FWAERS =
/ZAK/ANALITIKA-FWAERS .
/ZAK/ANALITIKA_V-AUFNR =
/ZAK/ANALITIKA-AUFNR .
/ZAK/ANALITIKA_V-UMSKZ =
/ZAK/ANALITIKA-UMSKZ .
/ZAK/ANALITIKA_V-BSCHL =
/ZAK/ANALITIKA-BSCHL .
/ZAK/ANALITIKA_V-AUGDT =
/ZAK/ANALITIKA-AUGDT .
/ZAK/ANALITIKA_V-PRCTR =
/ZAK/ANALITIKA-PRCTR .
/ZAK/ANALITIKA_V-FIELD_C =
/ZAK/ANALITIKA-FIELD_C .
/ZAK/ANALITIKA_V-FIELD_N =
/ZAK/ANALITIKA-FIELD_N .
/ZAK/ANALITIKA_V-FIELD_A =
/ZAK/ANALITIKA-FIELD_A .
/ZAK/ANALITIKA_V-TTIP =
/ZAK/ANALITIKA-TTIP .
/ZAK/ANALITIKA_V-ADODAT =
/ZAK/ANALITIKA-ADODAT .
/ZAK/ANALITIKA_V-GSBER =
/ZAK/ANALITIKA-GSBER .
/ZAK/ANALITIKA_V-HSZU =
/ZAK/ANALITIKA-HSZU .
/ZAK/ANALITIKA_V-FI_BUKRS =
/ZAK/ANALITIKA-FI_BUKRS .
/ZAK/ANALITIKA_V-ARANY_FLAG =
/ZAK/ANALITIKA-ARANY_FLAG .
/ZAK/ANALITIKA_V-NYLAPAZON =
/ZAK/ANALITIKA-NYLAPAZON .
/ZAK/ANALITIKA_V-ONYBF =
/ZAK/ANALITIKA-ONYBF .
/ZAK/ANALITIKA_V-ONYB_PACK =
/ZAK/ANALITIKA-ONYB_PACK .
/ZAK/ANALITIKA_V-POSID =
/ZAK/ANALITIKA-POSID .
/ZAK/ANALITIKA_V-XEGDR =
/ZAK/ANALITIKA-XEGDR .
/ZAK/ANALITIKA_V-USNAM =
/ZAK/ANALITIKA-USNAM .
/ZAK/ANALITIKA_V-SZAMLAKELT =
/ZAK/ANALITIKA-SZAMLAKELT .
/ZAK/ANALITIKA_V-SZAMLASZ =
/ZAK/ANALITIKA-SZAMLASZ .
/ZAK/ANALITIKA_V-SZAMLASZE =
/ZAK/ANALITIKA-SZAMLASZE .
/ZAK/ANALITIKA_V-SZLATIP =
/ZAK/ANALITIKA-SZLATIP .
/ZAK/ANALITIKA_V-SZAMLASZA =
/ZAK/ANALITIKA-SZAMLASZA .
/ZAK/ANALITIKA_V-ZMWSKF =
/ZAK/ANALITIKA-ZMWSKF .
/ZAK/ANALITIKA_V-ZKUNNAME =
/ZAK/ANALITIKA-ZKUNNAME .
/ZAK/ANALITIKA_V-ZKUNADRS =
/ZAK/ANALITIKA-ZKUNADRS .
/ZAK/ANALITIKA_V-NONEED =
/ZAK/ANALITIKA-NONEED .
/ZAK/ANALITIKA_V-VKORG =
/ZAK/ANALITIKA-VKORG .
/ZAK/ANALITIKA_V-ZUONR =
/ZAK/ANALITIKA-ZUONR .
/ZAK/ANALITIKA_V-VMSZA =
/ZAK/ANALITIKA-VMSZA .
/ZAK/ANALITIKA_V-XREF1_HD =
/ZAK/ANALITIKA-XREF1_HD .
/ZAK/ANALITIKA_V-XREF2_HD =
/ZAK/ANALITIKA-XREF2_HD .
/ZAK/ANALITIKA_V-H_GJAHR =
/ZAK/ANALITIKA-H_GJAHR .
/ZAK/ANALITIKA_V-H_BELNR =
/ZAK/ANALITIKA-H_BELNR .
/ZAK/ANALITIKA_V-ELSTAD =
/ZAK/ANALITIKA-ELSTAD .
/ZAK/ANALITIKA_V-UGYFEL =
/ZAK/ANALITIKA-UGYFEL .
/ZAK/ANALITIKA_V-VAROS =
/ZAK/ANALITIKA-VAROS .
/ZAK/ANALITIKA_V-CIM =
/ZAK/ANALITIKA-CIM .
/ZAK/ANALITIKA_V-IRSZ =
/ZAK/ANALITIKA-IRSZ .
/ZAK/ANALITIKA_V-ORSZAG =
/ZAK/ANALITIKA-ORSZAG .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/ANALITIKA_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/ANALITIKA_V-BUKRS TO
/ZAK/ANALITIKA-BUKRS .
MOVE /ZAK/ANALITIKA_V-BTYPE TO
/ZAK/ANALITIKA-BTYPE .
MOVE /ZAK/ANALITIKA_V-GJAHR TO
/ZAK/ANALITIKA-GJAHR .
MOVE /ZAK/ANALITIKA_V-MONAT TO
/ZAK/ANALITIKA-MONAT .
MOVE /ZAK/ANALITIKA_V-ZINDEX TO
/ZAK/ANALITIKA-ZINDEX .
MOVE /ZAK/ANALITIKA_V-ABEVAZ TO
/ZAK/ANALITIKA-ABEVAZ .
MOVE /ZAK/ANALITIKA_V-ADOAZON TO
/ZAK/ANALITIKA-ADOAZON .
MOVE /ZAK/ANALITIKA_V-BSZNUM TO
/ZAK/ANALITIKA-BSZNUM .
MOVE /ZAK/ANALITIKA_V-PACK TO
/ZAK/ANALITIKA-PACK .
MOVE /ZAK/ANALITIKA_V-ITEM TO
/ZAK/ANALITIKA-ITEM .
MOVE /ZAK/ANALITIKA_V-LAPSZ TO
/ZAK/ANALITIKA-LAPSZ .
MOVE /ZAK/ANALITIKA_V-MANDT TO
/ZAK/ANALITIKA-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/ANALITIKA'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/ANALITIKA TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/ANALITIKA'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
