*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/ARANY_CUSTV................................*
FORM GET_DATA_/ZAK/ARANY_CUSTV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/ARANY_CUST WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/ARANY_CUSTV .
/ZAK/ARANY_CUSTV-MANDT =
/ZAK/ARANY_CUST-MANDT .
/ZAK/ARANY_CUSTV-MWSKZ =
/ZAK/ARANY_CUST-MWSKZ .
/ZAK/ARANY_CUSTV-KTOSL =
/ZAK/ARANY_CUST-KTOSL .
/ZAK/ARANY_CUSTV-DATUM =
/ZAK/ARANY_CUST-DATUM .
/ZAK/ARANY_CUSTV-UZEIT =
/ZAK/ARANY_CUST-UZEIT .
/ZAK/ARANY_CUSTV-UNAME =
/ZAK/ARANY_CUST-UNAME .
<VIM_TOTAL_STRUC> = /ZAK/ARANY_CUSTV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/ARANY_CUSTV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/ARANY_CUSTV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/ARANY_CUSTV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/ARANY_CUST WHERE
  MWSKZ = /ZAK/ARANY_CUSTV-MWSKZ AND
  KTOSL = /ZAK/ARANY_CUSTV-KTOSL .
    IF SY-SUBRC = 0.
    DELETE /ZAK/ARANY_CUST .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/ARANY_CUST WHERE
  MWSKZ = /ZAK/ARANY_CUSTV-MWSKZ AND
  KTOSL = /ZAK/ARANY_CUSTV-KTOSL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/ARANY_CUST.
    ENDIF.
/ZAK/ARANY_CUST-MANDT =
/ZAK/ARANY_CUSTV-MANDT .
/ZAK/ARANY_CUST-MWSKZ =
/ZAK/ARANY_CUSTV-MWSKZ .
/ZAK/ARANY_CUST-KTOSL =
/ZAK/ARANY_CUSTV-KTOSL .
/ZAK/ARANY_CUST-DATUM =
/ZAK/ARANY_CUSTV-DATUM .
/ZAK/ARANY_CUST-UZEIT =
/ZAK/ARANY_CUSTV-UZEIT .
/ZAK/ARANY_CUST-UNAME =
/ZAK/ARANY_CUSTV-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/ARANY_CUST .
    ELSE.
    INSERT /ZAK/ARANY_CUST .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/ARANY_CUSTV-UPD_FLAG,
STATUS_/ZAK/ARANY_CUSTV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/ARANY_CUSTV.
  SELECT SINGLE * FROM /ZAK/ARANY_CUST WHERE
MWSKZ = /ZAK/ARANY_CUSTV-MWSKZ AND
KTOSL = /ZAK/ARANY_CUSTV-KTOSL .
/ZAK/ARANY_CUSTV-MANDT =
/ZAK/ARANY_CUST-MANDT .
/ZAK/ARANY_CUSTV-MWSKZ =
/ZAK/ARANY_CUST-MWSKZ .
/ZAK/ARANY_CUSTV-KTOSL =
/ZAK/ARANY_CUST-KTOSL .
/ZAK/ARANY_CUSTV-DATUM =
/ZAK/ARANY_CUST-DATUM .
/ZAK/ARANY_CUSTV-UZEIT =
/ZAK/ARANY_CUST-UZEIT .
/ZAK/ARANY_CUSTV-UNAME =
/ZAK/ARANY_CUST-UNAME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/ARANY_CUSTV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/ARANY_CUSTV-MWSKZ TO
/ZAK/ARANY_CUST-MWSKZ .
MOVE /ZAK/ARANY_CUSTV-KTOSL TO
/ZAK/ARANY_CUST-KTOSL .
MOVE /ZAK/ARANY_CUSTV-MANDT TO
/ZAK/ARANY_CUST-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/ARANY_CUST'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/ARANY_CUST TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/ARANY_CUST'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
