*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/ABEVK_V.....................................*
FORM GET_DATA_/ZAK/ABEVK_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/ABEVK WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/ABEVK_V .
/ZAK/ABEVK_V-MANDT =
/ZAK/ABEVK-MANDT .
/ZAK/ABEVK_V-BTYPE =
/ZAK/ABEVK-BTYPE .
/ZAK/ABEVK_V-ABEVAZ =
/ZAK/ABEVK-ABEVAZ .
/ZAK/ABEVK_V-BTYPEE =
/ZAK/ABEVK-BTYPEE .
/ZAK/ABEVK_V-ABEVAZE =
/ZAK/ABEVK-ABEVAZE .
/ZAK/ABEVK_V-DATUM =
/ZAK/ABEVK-DATUM .
/ZAK/ABEVK_V-UZEIT =
/ZAK/ABEVK-UZEIT .
/ZAK/ABEVK_V-UNAME =
/ZAK/ABEVK-UNAME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/ABEVK-BTYPE AND
ABEVAZ = /ZAK/ABEVK-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/ABEVK_V-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /ZAK/ABEVK_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/ABEVK_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/ABEVK_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/ABEVK_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/ABEVK WHERE
  BTYPE = /ZAK/ABEVK_V-BTYPE AND
  ABEVAZ = /ZAK/ABEVK_V-ABEVAZ .
    IF SY-SUBRC = 0.
    DELETE /ZAK/ABEVK .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/ABEVK WHERE
  BTYPE = /ZAK/ABEVK_V-BTYPE AND
  ABEVAZ = /ZAK/ABEVK_V-ABEVAZ .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/ABEVK.
    ENDIF.
/ZAK/ABEVK-MANDT =
/ZAK/ABEVK_V-MANDT .
/ZAK/ABEVK-BTYPE =
/ZAK/ABEVK_V-BTYPE .
/ZAK/ABEVK-ABEVAZ =
/ZAK/ABEVK_V-ABEVAZ .
/ZAK/ABEVK-BTYPEE =
/ZAK/ABEVK_V-BTYPEE .
/ZAK/ABEVK-ABEVAZE =
/ZAK/ABEVK_V-ABEVAZE .
/ZAK/ABEVK-DATUM =
/ZAK/ABEVK_V-DATUM .
/ZAK/ABEVK-UZEIT =
/ZAK/ABEVK_V-UZEIT .
/ZAK/ABEVK-UNAME =
/ZAK/ABEVK_V-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/ABEVK .
    ELSE.
    INSERT /ZAK/ABEVK .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/ABEVK_V-UPD_FLAG,
STATUS_/ZAK/ABEVK_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/ABEVK_V.
  SELECT SINGLE * FROM /ZAK/ABEVK WHERE
BTYPE = /ZAK/ABEVK_V-BTYPE AND
ABEVAZ = /ZAK/ABEVK_V-ABEVAZ .
/ZAK/ABEVK_V-MANDT =
/ZAK/ABEVK-MANDT .
/ZAK/ABEVK_V-BTYPE =
/ZAK/ABEVK-BTYPE .
/ZAK/ABEVK_V-ABEVAZ =
/ZAK/ABEVK-ABEVAZ .
/ZAK/ABEVK_V-BTYPEE =
/ZAK/ABEVK-BTYPEE .
/ZAK/ABEVK_V-ABEVAZE =
/ZAK/ABEVK-ABEVAZE .
/ZAK/ABEVK_V-DATUM =
/ZAK/ABEVK-DATUM .
/ZAK/ABEVK_V-UZEIT =
/ZAK/ABEVK-UZEIT .
/ZAK/ABEVK_V-UNAME =
/ZAK/ABEVK-UNAME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/ABEVK-BTYPE AND
ABEVAZ = /ZAK/ABEVK-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/ABEVK_V-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/ABEVK_V-ABEVTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/ABEVK_V-ABEVTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/ABEVK_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/ABEVK_V-BTYPE TO
/ZAK/ABEVK-BTYPE .
MOVE /ZAK/ABEVK_V-ABEVAZ TO
/ZAK/ABEVK-ABEVAZ .
MOVE /ZAK/ABEVK_V-MANDT TO
/ZAK/ABEVK-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/ABEVK'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/ABEVK TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/ABEVK'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/ZAK/ABEVK_V USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/ZAK/ABEVK-MANDT =
/ZAK/ABEVK_V-MANDT .
/ZAK/ABEVK-BTYPE =
/ZAK/ABEVK_V-BTYPE .
/ZAK/ABEVK-ABEVAZ =
/ZAK/ABEVK_V-ABEVAZ .
/ZAK/ABEVK-BTYPEE =
/ZAK/ABEVK_V-BTYPEE .
/ZAK/ABEVK-ABEVAZE =
/ZAK/ABEVK_V-ABEVAZE .
/ZAK/ABEVK-DATUM =
/ZAK/ABEVK_V-DATUM .
/ZAK/ABEVK-UZEIT =
/ZAK/ABEVK_V-UZEIT .
/ZAK/ABEVK-UNAME =
/ZAK/ABEVK_V-UNAME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/ABEVK-BTYPE AND
ABEVAZ = /ZAK/ABEVK-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/ABEVK_V-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/ABEVK_V-ABEVTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/ABEVK_V-ABEVTEXT .
    ENDIF.
ENDFORM.
