
PROCESS BEFORE OUTPUT.

  MODULE PBO9003.

  MODULE SET_DYNP9003.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND AT EXIT-COMMAND .

  CHAIN.
    FIELD: /ZAK/ANALITIKA-MONAT,
           /ZAK/ANALITIKA-GJAHR,
           /ZAK/ANALITIKA-BSZNUM,
           V_FULL.
*++2465 #03.
    MODULE GET_BUKCS.
*--2465 #03.
*++1565 #03.
    MODULE CHECK_BUKCS.
*--1565 #03.
    MODULE CHECK_BPART.

    MODULE USER_COMMAND_9003.
  ENDCHAIN.


