PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/BEVALL_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/BEVALL_V-BUKRS .
    FIELD /ZAK/BEVALL_V-BTYPE .
    FIELD /ZAK/BEVALL_V-DATBI .
    FIELD /ZAK/BEVALL_V-DATAB .
    FIELD /ZAK/BEVALL_V-BTYPEE .
    FIELD /ZAK/BEVALL_V-BTYPEA .
    FIELD /ZAK/BEVALL_V-BTEXT .
    FIELD /ZAK/BEVALL_V-BIDOSZ .
    FIELD /ZAK/BEVALL_V-BTYPART .
    FIELD /ZAK/BEVALL_V-STRANS .
    FIELD /ZAK/BEVALL_V-OMREL .
    FIELD /ZAK/BEVALL_V-OLWSTE .
    FIELD /ZAK/BEVALL_V-KATASZ .
    FIELD /ZAK/BEVALL_V-M02KNO .
    FIELD /ZAK/BEVALL_V-BLART .
    FIELD /ZAK/BEVALL_V-BDAY .
    FIELD /ZAK/BEVALL_V-KIUTALAS .
    FIELD /ZAK/BEVALL_V-ARTYPE .
    FIELD /ZAK/BEVALL_V-ARKONT .
    FIELD /ZAK/BEVALL_V-ARKOSTL .
    FIELD /ZAK/BEVALL_V-ARAUFNR .
    FIELD /ZAK/BEVALL_V-PADOSZ .
    FIELD /ZAK/BEVALL_V-DATUM .
    FIELD /ZAK/BEVALL_V-UZEIT .
    FIELD /ZAK/BEVALL_V-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/BEVALL_V-BUKRS .
    FIELD /ZAK/BEVALL_V-BTYPE .
    FIELD /ZAK/BEVALL_V-DATBI .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
