PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/BEVALLD_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/BEVALLD_V-BUKRS .
    FIELD /ZAK/BEVALLD_V-BTYPE .
    FIELD /ZAK/BEVALLD_V-BSZNUM .
    FIELD /ZAK/BEVALLD_V-SZTEXT .
    FIELD /ZAK/BEVALLD_V-XSPEC .
    FIELD /ZAK/BEVALLD_V-XFULL .
    FIELD /ZAK/BEVALLD_V-STRNAME .
    FIELD /ZAK/BEVALLD_V-FILETYPE .
    FIELD /ZAK/BEVALLD_V-PROGRAMM .
    FIELD /ZAK/BEVALLD_V-MGIF .
    FIELD /ZAK/BEVALLD_V-OMREL .
    FIELD /ZAK/BEVALLD_V-DATUM .
    FIELD /ZAK/BEVALLD_V-UZEIT .
    FIELD /ZAK/BEVALLD_V-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/BEVALLD_V-BUKRS .
    FIELD /ZAK/BEVALLD_V-BTYPE .
    FIELD /ZAK/BEVALLD_V-BSZNUM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
