PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/AFA_ATV_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/AFA_ATV_V-BUKRS .
    FIELD /ZAK/AFA_ATV_V-BTYPE .
    FIELD /ZAK/AFA_ATV_V-ABEV_TO .
    FIELD /ZAK/AFA_ATV_V-TEXT_ABEV_TO .
    FIELD /ZAK/AFA_ATV_V-ABEV_FROM .
    FIELD /ZAK/AFA_ATV_V-TEXT_ABEV_FROM .
    FIELD /ZAK/AFA_ATV_V-KOART .
    FIELD /ZAK/AFA_ATV_V-UMSKZ_FROM .
    FIELD /ZAK/AFA_ATV_V-UMSKZ_TO .
    FIELD /ZAK/AFA_ATV_V-BSCHL .
    FIELD /ZAK/AFA_ATV_V-AUGDT_FLAG .
    FIELD /ZAK/AFA_ATV_V-DATUM .
    FIELD /ZAK/AFA_ATV_V-UZEIT .
    FIELD /ZAK/AFA_ATV_V-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/AFA_ATV_V-BUKRS .
    FIELD /ZAK/AFA_ATV_V-BTYPE .
    FIELD /ZAK/AFA_ATV_V-ABEV_TO .
    FIELD /ZAK/AFA_ATV_V-ABEV_FROM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
