PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/UREPI_LOG_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/UREPI_LOG_V-BUKRS .
    FIELD /ZAK/UREPI_LOG_V-BELNR .
    FIELD /ZAK/UREPI_LOG_V-GJAHR .
    FIELD /ZAK/UREPI_LOG_V-MONAT .
    FIELD /ZAK/UREPI_LOG_V-CPUDT .
    FIELD /ZAK/UREPI_LOG_V-CPUTM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/UREPI_LOG_V-BUKRS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
