
PROCESS BEFORE OUTPUT.

  MODULE STATUS_9100.

  MODULE INIT_9100.
*
PROCESS AFTER INPUT.
*++BG 2006/08/31
  MODULE EXIT AT EXIT-COMMAND.
*--BG 2006/08/31
  FIELD /ZAK/ANALITIKA_S-FIELD_N MODULE SET_SUM.
  FIELD /ZAK/ANALITIKA_S-KOSTL   MODULE CHECK_KOSTL.
  FIELD /ZAK/ANALITIKA_S-AUFNR   MODULE CHECK_AUFNR.
  FIELD /ZAK/ANALITIKA_S-PRCTR   MODULE CHECK_PRCTR.
*++0017 BG 2012.02.07
* Validation for recording the counterpart
  CHAIN.
    FIELD /ZAK/ANALITIKA_S-BOOK.
    FIELD /ZAK/ANALITIKA_S-VORSTOR.
    FIELD /ZAK/ANALITIKA_S-STAPO.
    FIELD /ZAK/ANALITIKA_S-FIELD_N.
    FIELD /ZAK/ANALITIKA_S-ZCOMMENT.
    FIELD /ZAK/ANALITIKA_S-KOSTL.
    FIELD /ZAK/ANALITIKA_S-AUFNR.
    FIELD /ZAK/ANALITIKA_S-PRCTR.
    FIELD /ZAK/ANAL_MS-MSFLAG.
    FIELD /ZAK/ANAL_MS-BTYPE.
    FIELD /ZAK/ANAL_MS-ABEVAZ.
    FIELD /ZAK/ANAL_MS-GJAHR.
    FIELD /ZAK/ANAL_MS-MONAT.
    MODULE CHECK_ANALITIKA_MS.
  ENDCHAIN.
*--0017 BG 2012.02.07

  MODULE USER_COMMAND_9100.
