*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/SZJA_ABEV_V.................................*
FORM GET_DATA_/ZAK/SZJA_ABEV_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/SZJA_ABEV WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/SZJA_ABEV_V .
/ZAK/SZJA_ABEV_V-MANDT =
/ZAK/SZJA_ABEV-MANDT .
/ZAK/SZJA_ABEV_V-BUKRS =
/ZAK/SZJA_ABEV-BUKRS .
/ZAK/SZJA_ABEV_V-BTYPE =
/ZAK/SZJA_ABEV-BTYPE .
/ZAK/SZJA_ABEV_V-BSZNUM =
/ZAK/SZJA_ABEV-BSZNUM .
/ZAK/SZJA_ABEV_V-FIELDNAME =
/ZAK/SZJA_ABEV-FIELDNAME .
/ZAK/SZJA_ABEV_V-ABEVAZ =
/ZAK/SZJA_ABEV-ABEVAZ .
/ZAK/SZJA_ABEV_V-TARTOZIK =
/ZAK/SZJA_ABEV-TARTOZIK .
/ZAK/SZJA_ABEV_V-KOVETEL =
/ZAK/SZJA_ABEV-KOVETEL .
/ZAK/SZJA_ABEV_V-MWSKZ =
/ZAK/SZJA_ABEV-MWSKZ .
/ZAK/SZJA_ABEV_V-AS4USER =
/ZAK/SZJA_ABEV-AS4USER .
/ZAK/SZJA_ABEV_V-AS4DATE =
/ZAK/SZJA_ABEV-AS4DATE .
/ZAK/SZJA_ABEV_V-AS4TIME =
/ZAK/SZJA_ABEV-AS4TIME .
<VIM_TOTAL_STRUC> = /ZAK/SZJA_ABEV_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/SZJA_ABEV_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/SZJA_ABEV_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/SZJA_ABEV_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/SZJA_ABEV WHERE
  BUKRS = /ZAK/SZJA_ABEV_V-BUKRS AND
  BTYPE = /ZAK/SZJA_ABEV_V-BTYPE AND
  BSZNUM = /ZAK/SZJA_ABEV_V-BSZNUM AND
  FIELDNAME = /ZAK/SZJA_ABEV_V-FIELDNAME .
    IF SY-SUBRC = 0.
    DELETE /ZAK/SZJA_ABEV .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/SZJA_ABEV WHERE
  BUKRS = /ZAK/SZJA_ABEV_V-BUKRS AND
  BTYPE = /ZAK/SZJA_ABEV_V-BTYPE AND
  BSZNUM = /ZAK/SZJA_ABEV_V-BSZNUM AND
  FIELDNAME = /ZAK/SZJA_ABEV_V-FIELDNAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/SZJA_ABEV.
    ENDIF.
/ZAK/SZJA_ABEV-MANDT =
/ZAK/SZJA_ABEV_V-MANDT .
/ZAK/SZJA_ABEV-BUKRS =
/ZAK/SZJA_ABEV_V-BUKRS .
/ZAK/SZJA_ABEV-BTYPE =
/ZAK/SZJA_ABEV_V-BTYPE .
/ZAK/SZJA_ABEV-BSZNUM =
/ZAK/SZJA_ABEV_V-BSZNUM .
/ZAK/SZJA_ABEV-FIELDNAME =
/ZAK/SZJA_ABEV_V-FIELDNAME .
/ZAK/SZJA_ABEV-ABEVAZ =
/ZAK/SZJA_ABEV_V-ABEVAZ .
/ZAK/SZJA_ABEV-TARTOZIK =
/ZAK/SZJA_ABEV_V-TARTOZIK .
/ZAK/SZJA_ABEV-KOVETEL =
/ZAK/SZJA_ABEV_V-KOVETEL .
/ZAK/SZJA_ABEV-MWSKZ =
/ZAK/SZJA_ABEV_V-MWSKZ .
/ZAK/SZJA_ABEV-AS4USER =
/ZAK/SZJA_ABEV_V-AS4USER .
/ZAK/SZJA_ABEV-AS4DATE =
/ZAK/SZJA_ABEV_V-AS4DATE .
/ZAK/SZJA_ABEV-AS4TIME =
/ZAK/SZJA_ABEV_V-AS4TIME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/SZJA_ABEV .
    ELSE.
    INSERT /ZAK/SZJA_ABEV .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/SZJA_ABEV_V-UPD_FLAG,
STATUS_/ZAK/SZJA_ABEV_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/SZJA_ABEV_V.
  SELECT SINGLE * FROM /ZAK/SZJA_ABEV WHERE
BUKRS = /ZAK/SZJA_ABEV_V-BUKRS AND
BTYPE = /ZAK/SZJA_ABEV_V-BTYPE AND
BSZNUM = /ZAK/SZJA_ABEV_V-BSZNUM AND
FIELDNAME = /ZAK/SZJA_ABEV_V-FIELDNAME .
/ZAK/SZJA_ABEV_V-MANDT =
/ZAK/SZJA_ABEV-MANDT .
/ZAK/SZJA_ABEV_V-BUKRS =
/ZAK/SZJA_ABEV-BUKRS .
/ZAK/SZJA_ABEV_V-BTYPE =
/ZAK/SZJA_ABEV-BTYPE .
/ZAK/SZJA_ABEV_V-BSZNUM =
/ZAK/SZJA_ABEV-BSZNUM .
/ZAK/SZJA_ABEV_V-FIELDNAME =
/ZAK/SZJA_ABEV-FIELDNAME .
/ZAK/SZJA_ABEV_V-ABEVAZ =
/ZAK/SZJA_ABEV-ABEVAZ .
/ZAK/SZJA_ABEV_V-TARTOZIK =
/ZAK/SZJA_ABEV-TARTOZIK .
/ZAK/SZJA_ABEV_V-KOVETEL =
/ZAK/SZJA_ABEV-KOVETEL .
/ZAK/SZJA_ABEV_V-MWSKZ =
/ZAK/SZJA_ABEV-MWSKZ .
/ZAK/SZJA_ABEV_V-AS4USER =
/ZAK/SZJA_ABEV-AS4USER .
/ZAK/SZJA_ABEV_V-AS4DATE =
/ZAK/SZJA_ABEV-AS4DATE .
/ZAK/SZJA_ABEV_V-AS4TIME =
/ZAK/SZJA_ABEV-AS4TIME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/SZJA_ABEV_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/SZJA_ABEV_V-BUKRS TO
/ZAK/SZJA_ABEV-BUKRS .
MOVE /ZAK/SZJA_ABEV_V-BTYPE TO
/ZAK/SZJA_ABEV-BTYPE .
MOVE /ZAK/SZJA_ABEV_V-BSZNUM TO
/ZAK/SZJA_ABEV-BSZNUM .
MOVE /ZAK/SZJA_ABEV_V-FIELDNAME TO
/ZAK/SZJA_ABEV-FIELDNAME .
MOVE /ZAK/SZJA_ABEV_V-MANDT TO
/ZAK/SZJA_ABEV-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/SZJA_ABEV'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/SZJA_ABEV TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/SZJA_ABEV'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
