
PROCESS BEFORE OUTPUT.

  MODULE PBO9001.

  MODULE SET_DYNP9001.

PROCESS AFTER INPUT.

  MODULE USER_COMMAND AT EXIT-COMMAND .

  CHAIN.
    FIELD: /ZAK/ANALITIKA-MONAT,
           /ZAK/ANALITIKA-GJAHR,
           RADIO1,
           RADIO2.
*++2465 #03.
    MODULE GET_BUKCS.
*--2465 #03.
*++1565 #03.
    MODULE CHECK_BUKCS.
*--1565 #03.
    MODULE CHECK_BPART.

    MODULE CHECK_MONAT.

    MODULE CHECK_ANALITIKA.

    MODULE USER_COMMAND_9001.

  ENDCHAIN.

