
PROCESS BEFORE OUTPUT.

  MODULE PBO9000.

  MODULE SET_DYNP9000.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND AT EXIT-COMMAND .

  FIELD V_DATBI_T MODULE SET_V_DATAB_T.
  CHAIN.
    FIELD: /ZAK/BEVALL-BUKRS,
           /ZAK/BEVALL-BTYPE,
           /ZAK/BEVALL-DATBI,
           /ZAK/BEVALL-DATAB.
    MODULE CHECK_INP.

    MODULE USER_COMMAND_9000.


  ENDCHAIN.
