*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LNOSTAPOTOP.                  " Global Data
  INCLUDE /ZAK/LNOSTAPOUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LNOSTAPOF00                        . " subprograms
  INCLUDE /ZAK/LNOSTAPOI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LNOSTAPOF...                  " Subprograms
* INCLUDE /ZAK/LNOSTAPOO...                  " PBO-Modules
* INCLUDE /ZAK/LNOSTAPOI...                  " PAI-Modules
