PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/BUKRS_MV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/BUKRS_MV-FI_BUKRS .
    FIELD /ZAK/BUKRS_MV-GSBER .
    FIELD /ZAK/BUKRS_MV-PRCTR .
    FIELD /ZAK/BUKRS_MV-AD_BUKRS .
    FIELD /ZAK/BUKRS_MV-FDATE .
    FIELD /ZAK/BUKRS_MV-DATUM .
    FIELD /ZAK/BUKRS_MV-UZEIT .
    FIELD /ZAK/BUKRS_MV-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/BUKRS_MV-FI_BUKRS .
    FIELD /ZAK/BUKRS_MV-GSBER .
    FIELD /ZAK/BUKRS_MV-PRCTR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
