*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/BEVALLI_MV..................................*
FORM GET_DATA_/ZAK/BEVALLI_MV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/BEVALLI WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/BEVALLI_MV .
/ZAK/BEVALLI_MV-MANDT =
/ZAK/BEVALLI-MANDT .
/ZAK/BEVALLI_MV-BUKRS =
/ZAK/BEVALLI-BUKRS .
/ZAK/BEVALLI_MV-BTYPE =
/ZAK/BEVALLI-BTYPE .
/ZAK/BEVALLI_MV-GJAHR =
/ZAK/BEVALLI-GJAHR .
/ZAK/BEVALLI_MV-MONAT =
/ZAK/BEVALLI-MONAT .
/ZAK/BEVALLI_MV-ZINDEX =
/ZAK/BEVALLI-ZINDEX .
/ZAK/BEVALLI_MV-FLAG =
/ZAK/BEVALLI-FLAG .
/ZAK/BEVALLI_MV-DWNDT =
/ZAK/BEVALLI-DWNDT .
/ZAK/BEVALLI_MV-DATUM =
/ZAK/BEVALLI-DATUM .
/ZAK/BEVALLI_MV-UZEIT =
/ZAK/BEVALLI-UZEIT .
/ZAK/BEVALLI_MV-UNAME =
/ZAK/BEVALLI-UNAME .
/ZAK/BEVALLI_MV-ONJF =
/ZAK/BEVALLI-ONJF .
<VIM_TOTAL_STRUC> = /ZAK/BEVALLI_MV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/BEVALLI_MV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/BEVALLI_MV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/BEVALLI_MV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BEVALLI WHERE
  BUKRS = /ZAK/BEVALLI_MV-BUKRS AND
  BTYPE = /ZAK/BEVALLI_MV-BTYPE AND
  GJAHR = /ZAK/BEVALLI_MV-GJAHR AND
  MONAT = /ZAK/BEVALLI_MV-MONAT AND
  ZINDEX = /ZAK/BEVALLI_MV-ZINDEX .
    IF SY-SUBRC = 0.
    DELETE /ZAK/BEVALLI .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BEVALLI WHERE
  BUKRS = /ZAK/BEVALLI_MV-BUKRS AND
  BTYPE = /ZAK/BEVALLI_MV-BTYPE AND
  GJAHR = /ZAK/BEVALLI_MV-GJAHR AND
  MONAT = /ZAK/BEVALLI_MV-MONAT AND
  ZINDEX = /ZAK/BEVALLI_MV-ZINDEX .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/BEVALLI.
    ENDIF.
/ZAK/BEVALLI-MANDT =
/ZAK/BEVALLI_MV-MANDT .
/ZAK/BEVALLI-BUKRS =
/ZAK/BEVALLI_MV-BUKRS .
/ZAK/BEVALLI-BTYPE =
/ZAK/BEVALLI_MV-BTYPE .
/ZAK/BEVALLI-GJAHR =
/ZAK/BEVALLI_MV-GJAHR .
/ZAK/BEVALLI-MONAT =
/ZAK/BEVALLI_MV-MONAT .
/ZAK/BEVALLI-ZINDEX =
/ZAK/BEVALLI_MV-ZINDEX .
/ZAK/BEVALLI-FLAG =
/ZAK/BEVALLI_MV-FLAG .
/ZAK/BEVALLI-DWNDT =
/ZAK/BEVALLI_MV-DWNDT .
/ZAK/BEVALLI-DATUM =
/ZAK/BEVALLI_MV-DATUM .
/ZAK/BEVALLI-UZEIT =
/ZAK/BEVALLI_MV-UZEIT .
/ZAK/BEVALLI-UNAME =
/ZAK/BEVALLI_MV-UNAME .
/ZAK/BEVALLI-ONJF =
/ZAK/BEVALLI_MV-ONJF .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/BEVALLI .
    ELSE.
    INSERT /ZAK/BEVALLI .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/BEVALLI_MV-UPD_FLAG,
STATUS_/ZAK/BEVALLI_MV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/BEVALLI_MV.
  SELECT SINGLE * FROM /ZAK/BEVALLI WHERE
BUKRS = /ZAK/BEVALLI_MV-BUKRS AND
BTYPE = /ZAK/BEVALLI_MV-BTYPE AND
GJAHR = /ZAK/BEVALLI_MV-GJAHR AND
MONAT = /ZAK/BEVALLI_MV-MONAT AND
ZINDEX = /ZAK/BEVALLI_MV-ZINDEX .
/ZAK/BEVALLI_MV-MANDT =
/ZAK/BEVALLI-MANDT .
/ZAK/BEVALLI_MV-BUKRS =
/ZAK/BEVALLI-BUKRS .
/ZAK/BEVALLI_MV-BTYPE =
/ZAK/BEVALLI-BTYPE .
/ZAK/BEVALLI_MV-GJAHR =
/ZAK/BEVALLI-GJAHR .
/ZAK/BEVALLI_MV-MONAT =
/ZAK/BEVALLI-MONAT .
/ZAK/BEVALLI_MV-ZINDEX =
/ZAK/BEVALLI-ZINDEX .
/ZAK/BEVALLI_MV-FLAG =
/ZAK/BEVALLI-FLAG .
/ZAK/BEVALLI_MV-DWNDT =
/ZAK/BEVALLI-DWNDT .
/ZAK/BEVALLI_MV-DATUM =
/ZAK/BEVALLI-DATUM .
/ZAK/BEVALLI_MV-UZEIT =
/ZAK/BEVALLI-UZEIT .
/ZAK/BEVALLI_MV-UNAME =
/ZAK/BEVALLI-UNAME .
/ZAK/BEVALLI_MV-ONJF =
/ZAK/BEVALLI-ONJF .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/BEVALLI_MV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/BEVALLI_MV-BUKRS TO
/ZAK/BEVALLI-BUKRS .
MOVE /ZAK/BEVALLI_MV-BTYPE TO
/ZAK/BEVALLI-BTYPE .
MOVE /ZAK/BEVALLI_MV-GJAHR TO
/ZAK/BEVALLI-GJAHR .
MOVE /ZAK/BEVALLI_MV-MONAT TO
/ZAK/BEVALLI-MONAT .
MOVE /ZAK/BEVALLI_MV-ZINDEX TO
/ZAK/BEVALLI-ZINDEX .
MOVE /ZAK/BEVALLI_MV-MANDT TO
/ZAK/BEVALLI-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/BEVALLI'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/BEVALLI TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/BEVALLI'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
