*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LBUKRSN_MVTOP.                " Global Data
  INCLUDE /ZAK/LBUKRSN_MVUXX.                " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LBUKRSN_MVF00                      . " subprograms
  INCLUDE /ZAK/LBUKRSN_MVI00                      . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LBUKRSN_MVF...                " Subprograms
* INCLUDE /ZAK/LBUKRSN_MVO...                " PBO-Modules
* INCLUDE /ZAK/LBUKRSN_MVI...                " PAI-Modules

INCLUDE /ZAK/LBUKRSN_MVF01.

INCLUDE /ZAK/LBUKRSN_MVI01.
