*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 2006.02.27 at 18:31:59 by user FMCTI00DBG
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LKFILE_MVTOP.                 " Global Data
  INCLUDE /ZAK/LKFILE_MVUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LKFILE_MVF00                       . " subprograms
  INCLUDE /ZAK/LKFILE_MVI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LKFILE_MVF...                 " Subprograms
* INCLUDE /ZAK/LKFILE_MVO...                 " PBO-Modules
* INCLUDE /ZAK/LKFILE_MVI...                 " PAI-Modules
