PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/ABEVK_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/ABEVK_V-BTYPE .
    FIELD /ZAK/ABEVK_V-ABEVAZ .
    FIELD /ZAK/ABEVK_V-BTYPEE .
    FIELD /ZAK/ABEVK_V-ABEVAZE .
    FIELD /ZAK/ABEVK_V-ABEVTEXT .
    FIELD /ZAK/ABEVK_V-DATUM .
    FIELD /ZAK/ABEVK_V-UZEIT .
    FIELD /ZAK/ABEVK_V-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_/ZAK/ABEVK_V ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/ABEVK_V-BTYPE .
    FIELD /ZAK/ABEVK_V-ABEVAZ .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
