*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/BUKRS_SEGMV................................*
FORM GET_DATA_/ZAK/BUKRS_SEGMV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/BUKRS_SEGM WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/BUKRS_SEGMV .
/ZAK/BUKRS_SEGMV-MANDT =
/ZAK/BUKRS_SEGM-MANDT .
/ZAK/BUKRS_SEGMV-BUKRS =
/ZAK/BUKRS_SEGM-BUKRS .
/ZAK/BUKRS_SEGMV-SEGMENT =
/ZAK/BUKRS_SEGM-SEGMENT .
/ZAK/BUKRS_SEGMV-AS4USER =
/ZAK/BUKRS_SEGM-AS4USER .
/ZAK/BUKRS_SEGMV-AS4DATE =
/ZAK/BUKRS_SEGM-AS4DATE .
/ZAK/BUKRS_SEGMV-AS4TIME =
/ZAK/BUKRS_SEGM-AS4TIME .
<VIM_TOTAL_STRUC> = /ZAK/BUKRS_SEGMV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/BUKRS_SEGMV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/BUKRS_SEGMV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/BUKRS_SEGMV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BUKRS_SEGM WHERE
  BUKRS = /ZAK/BUKRS_SEGMV-BUKRS .
    IF SY-SUBRC = 0.
    DELETE /ZAK/BUKRS_SEGM .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BUKRS_SEGM WHERE
  BUKRS = /ZAK/BUKRS_SEGMV-BUKRS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/BUKRS_SEGM.
    ENDIF.
/ZAK/BUKRS_SEGM-MANDT =
/ZAK/BUKRS_SEGMV-MANDT .
/ZAK/BUKRS_SEGM-BUKRS =
/ZAK/BUKRS_SEGMV-BUKRS .
/ZAK/BUKRS_SEGM-SEGMENT =
/ZAK/BUKRS_SEGMV-SEGMENT .
/ZAK/BUKRS_SEGM-AS4USER =
/ZAK/BUKRS_SEGMV-AS4USER .
/ZAK/BUKRS_SEGM-AS4DATE =
/ZAK/BUKRS_SEGMV-AS4DATE .
/ZAK/BUKRS_SEGM-AS4TIME =
/ZAK/BUKRS_SEGMV-AS4TIME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/BUKRS_SEGM .
    ELSE.
    INSERT /ZAK/BUKRS_SEGM .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/BUKRS_SEGMV-UPD_FLAG,
STATUS_/ZAK/BUKRS_SEGMV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/BUKRS_SEGMV.
  SELECT SINGLE * FROM /ZAK/BUKRS_SEGM WHERE
BUKRS = /ZAK/BUKRS_SEGMV-BUKRS .
/ZAK/BUKRS_SEGMV-MANDT =
/ZAK/BUKRS_SEGM-MANDT .
/ZAK/BUKRS_SEGMV-BUKRS =
/ZAK/BUKRS_SEGM-BUKRS .
/ZAK/BUKRS_SEGMV-SEGMENT =
/ZAK/BUKRS_SEGM-SEGMENT .
/ZAK/BUKRS_SEGMV-AS4USER =
/ZAK/BUKRS_SEGM-AS4USER .
/ZAK/BUKRS_SEGMV-AS4DATE =
/ZAK/BUKRS_SEGM-AS4DATE .
/ZAK/BUKRS_SEGMV-AS4TIME =
/ZAK/BUKRS_SEGM-AS4TIME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/BUKRS_SEGMV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/BUKRS_SEGMV-BUKRS TO
/ZAK/BUKRS_SEGM-BUKRS .
MOVE /ZAK/BUKRS_SEGMV-MANDT TO
/ZAK/BUKRS_SEGM-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/BUKRS_SEGM'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/BUKRS_SEGM TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/BUKRS_SEGM'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
