*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/BUKRSN_MV...................................*
FORM GET_DATA_/ZAK/BUKRSN_MV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/BUKRSN WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/BUKRSN_MV .
/ZAK/BUKRSN_MV-MANDT =
/ZAK/BUKRSN-MANDT .
/ZAK/BUKRSN_MV-AD_BUKRS =
/ZAK/BUKRSN-AD_BUKRS .
/ZAK/BUKRSN_MV-FI_BUKRS =
/ZAK/BUKRSN-FI_BUKRS .
/ZAK/BUKRSN_MV-SAKNR =
/ZAK/BUKRSN-SAKNR .
/ZAK/BUKRSN_MV-SHORTNAME =
/ZAK/BUKRSN-SHORTNAME .
/ZAK/BUKRSN_MV-FDATE =
/ZAK/BUKRSN-FDATE .
/ZAK/BUKRSN_MV-DATUM =
/ZAK/BUKRSN-DATUM .
/ZAK/BUKRSN_MV-UZEIT =
/ZAK/BUKRSN-UZEIT .
/ZAK/BUKRSN_MV-UNAME =
/ZAK/BUKRSN-UNAME .
<VIM_TOTAL_STRUC> = /ZAK/BUKRSN_MV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/BUKRSN_MV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/BUKRSN_MV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/BUKRSN_MV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BUKRSN WHERE
  AD_BUKRS = /ZAK/BUKRSN_MV-AD_BUKRS .
    IF SY-SUBRC = 0.
    DELETE /ZAK/BUKRSN .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BUKRSN WHERE
  AD_BUKRS = /ZAK/BUKRSN_MV-AD_BUKRS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/BUKRSN.
    ENDIF.
/ZAK/BUKRSN-MANDT =
/ZAK/BUKRSN_MV-MANDT .
/ZAK/BUKRSN-AD_BUKRS =
/ZAK/BUKRSN_MV-AD_BUKRS .
/ZAK/BUKRSN-FI_BUKRS =
/ZAK/BUKRSN_MV-FI_BUKRS .
/ZAK/BUKRSN-SAKNR =
/ZAK/BUKRSN_MV-SAKNR .
/ZAK/BUKRSN-SHORTNAME =
/ZAK/BUKRSN_MV-SHORTNAME .
/ZAK/BUKRSN-FDATE =
/ZAK/BUKRSN_MV-FDATE .
/ZAK/BUKRSN-DATUM =
/ZAK/BUKRSN_MV-DATUM .
/ZAK/BUKRSN-UZEIT =
/ZAK/BUKRSN_MV-UZEIT .
/ZAK/BUKRSN-UNAME =
/ZAK/BUKRSN_MV-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/BUKRSN .
    ELSE.
    INSERT /ZAK/BUKRSN .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/BUKRSN_MV-UPD_FLAG,
STATUS_/ZAK/BUKRSN_MV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/BUKRSN_MV.
  SELECT SINGLE * FROM /ZAK/BUKRSN WHERE
AD_BUKRS = /ZAK/BUKRSN_MV-AD_BUKRS .
/ZAK/BUKRSN_MV-MANDT =
/ZAK/BUKRSN-MANDT .
/ZAK/BUKRSN_MV-AD_BUKRS =
/ZAK/BUKRSN-AD_BUKRS .
/ZAK/BUKRSN_MV-FI_BUKRS =
/ZAK/BUKRSN-FI_BUKRS .
/ZAK/BUKRSN_MV-SAKNR =
/ZAK/BUKRSN-SAKNR .
/ZAK/BUKRSN_MV-SHORTNAME =
/ZAK/BUKRSN-SHORTNAME .
/ZAK/BUKRSN_MV-FDATE =
/ZAK/BUKRSN-FDATE .
/ZAK/BUKRSN_MV-DATUM =
/ZAK/BUKRSN-DATUM .
/ZAK/BUKRSN_MV-UZEIT =
/ZAK/BUKRSN-UZEIT .
/ZAK/BUKRSN_MV-UNAME =
/ZAK/BUKRSN-UNAME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/BUKRSN_MV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/BUKRSN_MV-AD_BUKRS TO
/ZAK/BUKRSN-AD_BUKRS .
MOVE /ZAK/BUKRSN_MV-MANDT TO
/ZAK/BUKRSN-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/BUKRSN'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/BUKRSN TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/BUKRSN'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
