*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 2006.03.28 at 17:11:39 by user FMCTI00DBG
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LONELL_MVTOP.                 " Global Data
  INCLUDE /ZAK/LONELL_MVUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LONELL_MVF00                       . " subprograms
  INCLUDE /ZAK/LONELL_MVI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LONELL_MVF...                 " Subprograms
* INCLUDE /ZAK/LONELL_MVO...                 " PBO-Modules
* INCLUDE /ZAK/LONELL_MVI...                 " PAI-Modules

INCLUDE /ZAK/LONELL_MVF01.
