FUNCTION /ZAK/CHECK_ADOAZON.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  EXPORTING
*"     REFERENCE(E_HIBA) TYPE  /ZAK/ADAT_HIBA
*"  TABLES
*"      INTERN STRUCTURE  ALSMEX_TABLINE
*"      CHECK_TAB STRUCTURE  DD03P
*"----------------------------------------------------------------------
  DATA L_TABIX LIKE SY-TABIX.
  DATA L_INPUT TYPE STRING.
  DATA L_SZIDO TYPE DATUM.
  DATA L_RETURN TYPE CHAR_55.
  DATA LW_XLS TYPE ALSMEX_TABLINE.

* Tax identifier
  CONSTANTS LC_ADOAZON TYPE ROLLNAME VALUE '/ZAK/ADOAZON'.
* Date of birth
  CONSTANTS LC_SZULDAT TYPE ROLLNAME VALUE '/ZAK/SZULDAT'.


  DEFINE LM_GET_DATA.
    READ TABLE CHECK_TAB
               WITH KEY ROLLNAME = &1.
    IF SY-SUBRC EQ 0.
      L_TABIX = SY-TABIX.
      READ TABLE INTERN INTO LW_XLS
           WITH KEY COL = L_TABIX.
      IF SY-SUBRC EQ 0.
        MOVE LW_XLS-VALUE TO &2.
      ENDIF.
    ENDIF.
  END-OF-DEFINITION.

* Determine data
  LM_GET_DATA LC_ADOAZON L_INPUT.
  LM_GET_DATA LC_SZULDAT L_SZIDO.

* Tax identifier check
  CALL FUNCTION '/ZAK/READ_ADOAZON_EXIT'
    EXPORTING
      INPUT  = L_INPUT
      SZIDO  = L_SZIDO
    IMPORTING
      RETURN = L_RETURN.
* Populate the error
  IF NOT L_RETURN IS INITIAL.
    CLEAR: E_HIBA.
    E_HIBA-SOR          = LW_XLS-ROW.
    E_HIBA-OSZLOP       = LW_XLS-COL.
    E_HIBA-/ZAK/F_VALUE  = LW_XLS-VALUE.
    E_HIBA-TABNAME      = CHECK_TAB-TABNAME.
    E_HIBA-FIELDNAME    = CHECK_TAB-FIELDNAME.
    E_HIBA-ZA_HIBA      = L_RETURN.
    E_HIBA-/ZAK/ATTRIB   = CHECK_TAB-DDTEXT.
  ENDIF.

ENDFUNCTION.
