PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/IGSOR_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/IGSOR_V-IGAZON .
    FIELD /ZAK/IGSOR_V-FORMATUM .
    FIELD /ZAK/IGSOR_V-TEXT .
    FIELD /ZAK/IGSOR_V-NYTEXT .
    FIELD /ZAK/IGSOR_V-DATUM .
    FIELD /ZAK/IGSOR_V-UZEIT .
    FIELD /ZAK/IGSOR_V-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/IGSOR_V-IGAZON .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
