PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/EGYKORR CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/EGYKORR-BUKRS .
    FIELD /ZAK/EGYKORR-BTYPE .
    FIELD /ZAK/EGYKORR-GJAHR .
    FIELD /ZAK/EGYKORR-MONAT .
    FIELD /ZAK/EGYKORR-ZINDEX .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/EGYKORR-BUKRS .
    FIELD /ZAK/EGYKORR-BTYPE .
    FIELD /ZAK/EGYKORR-GJAHR .
    FIELD /ZAK/EGYKORR-MONAT .
    FIELD /ZAK/EGYKORR-ZINDEX .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
