PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/PENZT_FORGV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/PENZT_FORGV-KAZON .
    FIELD /ZAK/PENZT_FORGV-ZAZON .
    FIELD /ZAK/PENZT_FORGV-NAME1 .
    FIELD /ZAK/PENZT_FORGV-AS4USER .
    FIELD /ZAK/PENZT_FORGV-AS4DATE .
    FIELD /ZAK/PENZT_FORGV-AS4TIME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_/ZAK/PENZT_FORGV ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/PENZT_FORGV-KAZON .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
