PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/ARANY_FELDV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/ARANY_FELDV-BUKRS .
    FIELD /ZAK/ARANY_FELDV-GJAHR .
    FIELD /ZAK/ARANY_FELDV-BBELNR .
    FIELD /ZAK/ARANY_FELDV-BGJAHR .
    FIELD /ZAK/ARANY_FELDV-AS4USER .
    FIELD /ZAK/ARANY_FELDV-AS4DATE .
    FIELD /ZAK/ARANY_FELDV-AS4TIME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/ARANY_FELDV-BUKRS .
    FIELD /ZAK/ARANY_FELDV-GJAHR .
    FIELD /ZAK/ARANY_FELDV-BBELNR .
    FIELD /ZAK/ARANY_FELDV-BGJAHR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
