*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LAFA_FKABEVTOP.               " Global Data
  INCLUDE /ZAK/LAFA_FKABEVUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LAFA_FKABEVF00                     . " subprograms
  INCLUDE /ZAK/LAFA_FKABEVI00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LAFA_FKABEVF...               " Subprograms
* INCLUDE /ZAK/LAFA_FKABEVO...               " PBO-Modules
* INCLUDE /ZAK/LAFA_FKABEVI...               " PAI-Modules

INCLUDE /ZAK/LAFA_FKABEVF01.
