*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LUREPLOG_MVTOP.               " Global Data
  INCLUDE /ZAK/LUREPLOG_MVUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LUREPLOG_MVF00                     . " subprograms
  INCLUDE /ZAK/LUREPLOG_MVI00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LUREPLOG_MVF...               " Subprograms
* INCLUDE /ZAK/LUREPLOG_MVO...               " PBO-Modules
* INCLUDE /ZAK/LUREPLOG_MVI...               " PAI-Modules
