PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/PENZATV_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/PENZATV_V-ZAZON .
    FIELD /ZAK/PENZATV_V-NAME1 .
    FIELD /ZAK/PENZATV_V-POST_CODE1 .
    FIELD /ZAK/PENZATV_V-CITY1 .
    FIELD /ZAK/PENZATV_V-STREET .
    FIELD /ZAK/PENZATV_V-HOUSE_NUM2 .
    FIELD /ZAK/PENZATV_V-HOUSE_NUM1 .
    FIELD /ZAK/PENZATV_V-BUILDING .
    FIELD /ZAK/PENZATV_V-HOUSE_NUM3 .
    FIELD /ZAK/PENZATV_V-FLOOR .
    FIELD /ZAK/PENZATV_V-ROOMNUMBER .
    FIELD /ZAK/PENZATV_V-AS4USER .
    FIELD /ZAK/PENZATV_V-AS4DATE .
    FIELD /ZAK/PENZATV_V-AS4TIME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/PENZATV_V-ZAZON .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
