PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/VPOP_LIFNRV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/VPOP_LIFNRV-BUKRS .
    FIELD /ZAK/VPOP_LIFNRV-LIFNR .
    FIELD /ZAK/VPOP_LIFNRV-NAME1 .
    FIELD /ZAK/VPOP_LIFNRV-DATUM .
    FIELD /ZAK/VPOP_LIFNRV-UZEIT .
    FIELD /ZAK/VPOP_LIFNRV-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_/ZAK/VPOP_LIFNRV ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/VPOP_LIFNRV-BUKRS .
    FIELD /ZAK/VPOP_LIFNRV-LIFNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
