*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/NAV_ELL_V...................................*
FORM GET_DATA_/ZAK/NAV_ELL_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/NAV_ELL WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/NAV_ELL_V .
/ZAK/NAV_ELL_V-MANDT =
/ZAK/NAV_ELL-MANDT .
/ZAK/NAV_ELL_V-BUKRS =
/ZAK/NAV_ELL-BUKRS .
/ZAK/NAV_ELL_V-BTYPART =
/ZAK/NAV_ELL-BTYPART .
/ZAK/NAV_ELL_V-GJAHR =
/ZAK/NAV_ELL-GJAHR .
/ZAK/NAV_ELL_V-MONAT_FROM =
/ZAK/NAV_ELL-MONAT_FROM .
/ZAK/NAV_ELL_V-MONAT_TO =
/ZAK/NAV_ELL-MONAT_TO .
/ZAK/NAV_ELL_V-AS4USER =
/ZAK/NAV_ELL-AS4USER .
/ZAK/NAV_ELL_V-AS4DATE =
/ZAK/NAV_ELL-AS4DATE .
/ZAK/NAV_ELL_V-AS4TIME =
/ZAK/NAV_ELL-AS4TIME .
<VIM_TOTAL_STRUC> = /ZAK/NAV_ELL_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/NAV_ELL_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/NAV_ELL_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/NAV_ELL_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/NAV_ELL WHERE
  BUKRS = /ZAK/NAV_ELL_V-BUKRS AND
  BTYPART = /ZAK/NAV_ELL_V-BTYPART AND
  GJAHR = /ZAK/NAV_ELL_V-GJAHR .
    IF SY-SUBRC = 0.
    DELETE /ZAK/NAV_ELL .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/NAV_ELL WHERE
  BUKRS = /ZAK/NAV_ELL_V-BUKRS AND
  BTYPART = /ZAK/NAV_ELL_V-BTYPART AND
  GJAHR = /ZAK/NAV_ELL_V-GJAHR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/NAV_ELL.
    ENDIF.
/ZAK/NAV_ELL-MANDT =
/ZAK/NAV_ELL_V-MANDT .
/ZAK/NAV_ELL-BUKRS =
/ZAK/NAV_ELL_V-BUKRS .
/ZAK/NAV_ELL-BTYPART =
/ZAK/NAV_ELL_V-BTYPART .
/ZAK/NAV_ELL-GJAHR =
/ZAK/NAV_ELL_V-GJAHR .
/ZAK/NAV_ELL-MONAT_FROM =
/ZAK/NAV_ELL_V-MONAT_FROM .
/ZAK/NAV_ELL-MONAT_TO =
/ZAK/NAV_ELL_V-MONAT_TO .
/ZAK/NAV_ELL-AS4USER =
/ZAK/NAV_ELL_V-AS4USER .
/ZAK/NAV_ELL-AS4DATE =
/ZAK/NAV_ELL_V-AS4DATE .
/ZAK/NAV_ELL-AS4TIME =
/ZAK/NAV_ELL_V-AS4TIME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/NAV_ELL ##WARN_OK.
    ELSE.
    INSERT /ZAK/NAV_ELL .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/NAV_ELL_V-UPD_FLAG,
STATUS_/ZAK/NAV_ELL_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/NAV_ELL_V.
  SELECT SINGLE * FROM /ZAK/NAV_ELL WHERE
BUKRS = /ZAK/NAV_ELL_V-BUKRS AND
BTYPART = /ZAK/NAV_ELL_V-BTYPART AND
GJAHR = /ZAK/NAV_ELL_V-GJAHR .
/ZAK/NAV_ELL_V-MANDT =
/ZAK/NAV_ELL-MANDT .
/ZAK/NAV_ELL_V-BUKRS =
/ZAK/NAV_ELL-BUKRS .
/ZAK/NAV_ELL_V-BTYPART =
/ZAK/NAV_ELL-BTYPART .
/ZAK/NAV_ELL_V-GJAHR =
/ZAK/NAV_ELL-GJAHR .
/ZAK/NAV_ELL_V-MONAT_FROM =
/ZAK/NAV_ELL-MONAT_FROM .
/ZAK/NAV_ELL_V-MONAT_TO =
/ZAK/NAV_ELL-MONAT_TO .
/ZAK/NAV_ELL_V-AS4USER =
/ZAK/NAV_ELL-AS4USER .
/ZAK/NAV_ELL_V-AS4DATE =
/ZAK/NAV_ELL-AS4DATE .
/ZAK/NAV_ELL_V-AS4TIME =
/ZAK/NAV_ELL-AS4TIME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/NAV_ELL_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/NAV_ELL_V-BUKRS TO
/ZAK/NAV_ELL-BUKRS .
MOVE /ZAK/NAV_ELL_V-BTYPART TO
/ZAK/NAV_ELL-BTYPART .
MOVE /ZAK/NAV_ELL_V-GJAHR TO
/ZAK/NAV_ELL-GJAHR .
MOVE /ZAK/NAV_ELL_V-MANDT TO
/ZAK/NAV_ELL-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/NAV_ELL'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/NAV_ELL TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/NAV_ELL'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
