PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/AFA_ELV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/AFA_ELV-BUKRS .
    FIELD /ZAK/AFA_ELV-BTYPE .
    FIELD /ZAK/AFA_ELV-ABEVAZ .
    FIELD /ZAK/AFA_ELV-ABEVTEXT .
    FIELD /ZAK/AFA_ELV-HKONT_FROM .
    FIELD /ZAK/AFA_ELV-HKONT_TO .
    FIELD /ZAK/AFA_ELV-BLART .
    FIELD /ZAK/AFA_ELV-MWSKZ .
    FIELD /ZAK/AFA_ELV-ATYPE .
    FIELD /ZAK/AFA_ELV-SIGN .
    FIELD /ZAK/AFA_ELV-AS4USER .
    FIELD /ZAK/AFA_ELV-AS4DATE .
    FIELD /ZAK/AFA_ELV-AS4TIME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_/ZAK/AFA_ELV ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/AFA_ELV-BUKRS .
    FIELD /ZAK/AFA_ELV-BTYPE .
    FIELD /ZAK/AFA_ELV-ABEVAZ .
    FIELD /ZAK/AFA_ELV-HKONT_FROM .
    FIELD /ZAK/AFA_ELV-HKONT_TO .
    FIELD /ZAK/AFA_ELV-BLART .
    FIELD /ZAK/AFA_ELV-MWSKZ .
    FIELD /ZAK/AFA_ELV-ATYPE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
