*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/AFA_CUST_V..................................*
FORM GET_DATA_/ZAK/AFA_CUST_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/AFA_CUST WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/AFA_CUST_V .
/ZAK/AFA_CUST_V-MANDT =
/ZAK/AFA_CUST-MANDT .
/ZAK/AFA_CUST_V-BTYPE =
/ZAK/AFA_CUST-BTYPE .
/ZAK/AFA_CUST_V-MWSKZ =
/ZAK/AFA_CUST-MWSKZ .
/ZAK/AFA_CUST_V-KTOSL =
/ZAK/AFA_CUST-KTOSL .
/ZAK/AFA_CUST_V-ATYPE =
/ZAK/AFA_CUST-ATYPE .
/ZAK/AFA_CUST_V-ABEVAZ =
/ZAK/AFA_CUST-ABEVAZ .
/ZAK/AFA_CUST_V-XEGDR =
/ZAK/AFA_CUST-XEGDR .
/ZAK/AFA_CUST_V-SIGN =
/ZAK/AFA_CUST-SIGN .
/ZAK/AFA_CUST_V-MSIGN =
/ZAK/AFA_CUST-MSIGN .
/ZAK/AFA_CUST_V-KATA =
/ZAK/AFA_CUST-KATA .
/ZAK/AFA_CUST_V-TAXDIFF =
/ZAK/AFA_CUST-TAXDIFF .
/ZAK/AFA_CUST_V-DATUM =
/ZAK/AFA_CUST-DATUM .
/ZAK/AFA_CUST_V-UZEIT =
/ZAK/AFA_CUST-UZEIT .
/ZAK/AFA_CUST_V-UNAME =
/ZAK/AFA_CUST-UNAME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/AFA_CUST-BTYPE AND
ABEVAZ = /ZAK/AFA_CUST-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/AFA_CUST_V-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /ZAK/AFA_CUST_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/AFA_CUST_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/AFA_CUST_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/AFA_CUST_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_CUST WHERE
  BTYPE = /ZAK/AFA_CUST_V-BTYPE AND
  MWSKZ = /ZAK/AFA_CUST_V-MWSKZ AND
  KTOSL = /ZAK/AFA_CUST_V-KTOSL AND
  ATYPE = /ZAK/AFA_CUST_V-ATYPE AND
  XEGDR = /ZAK/AFA_CUST_V-XEGDR AND
  ABEVAZ = /ZAK/AFA_CUST_V-ABEVAZ .
    IF SY-SUBRC = 0.
    DELETE /ZAK/AFA_CUST .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_CUST WHERE
  BTYPE = /ZAK/AFA_CUST_V-BTYPE AND
  MWSKZ = /ZAK/AFA_CUST_V-MWSKZ AND
  KTOSL = /ZAK/AFA_CUST_V-KTOSL AND
  ATYPE = /ZAK/AFA_CUST_V-ATYPE AND
  XEGDR = /ZAK/AFA_CUST_V-XEGDR AND
  ABEVAZ = /ZAK/AFA_CUST_V-ABEVAZ .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/AFA_CUST.
    ENDIF.
/ZAK/AFA_CUST-MANDT =
/ZAK/AFA_CUST_V-MANDT .
/ZAK/AFA_CUST-BTYPE =
/ZAK/AFA_CUST_V-BTYPE .
/ZAK/AFA_CUST-MWSKZ =
/ZAK/AFA_CUST_V-MWSKZ .
/ZAK/AFA_CUST-KTOSL =
/ZAK/AFA_CUST_V-KTOSL .
/ZAK/AFA_CUST-ATYPE =
/ZAK/AFA_CUST_V-ATYPE .
/ZAK/AFA_CUST-ABEVAZ =
/ZAK/AFA_CUST_V-ABEVAZ .
/ZAK/AFA_CUST-XEGDR =
/ZAK/AFA_CUST_V-XEGDR .
/ZAK/AFA_CUST-SIGN =
/ZAK/AFA_CUST_V-SIGN .
/ZAK/AFA_CUST-MSIGN =
/ZAK/AFA_CUST_V-MSIGN .
/ZAK/AFA_CUST-KATA =
/ZAK/AFA_CUST_V-KATA .
/ZAK/AFA_CUST-TAXDIFF =
/ZAK/AFA_CUST_V-TAXDIFF .
/ZAK/AFA_CUST-DATUM =
/ZAK/AFA_CUST_V-DATUM .
/ZAK/AFA_CUST-UZEIT =
/ZAK/AFA_CUST_V-UZEIT .
/ZAK/AFA_CUST-UNAME =
/ZAK/AFA_CUST_V-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/AFA_CUST ##WARN_OK.
    ELSE.
    INSERT /ZAK/AFA_CUST .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/AFA_CUST_V-UPD_FLAG,
STATUS_/ZAK/AFA_CUST_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/AFA_CUST_V.
  SELECT SINGLE * FROM /ZAK/AFA_CUST WHERE
BTYPE = /ZAK/AFA_CUST_V-BTYPE AND
MWSKZ = /ZAK/AFA_CUST_V-MWSKZ AND
KTOSL = /ZAK/AFA_CUST_V-KTOSL AND
ATYPE = /ZAK/AFA_CUST_V-ATYPE AND
XEGDR = /ZAK/AFA_CUST_V-XEGDR AND
ABEVAZ = /ZAK/AFA_CUST_V-ABEVAZ .
/ZAK/AFA_CUST_V-MANDT =
/ZAK/AFA_CUST-MANDT .
/ZAK/AFA_CUST_V-BTYPE =
/ZAK/AFA_CUST-BTYPE .
/ZAK/AFA_CUST_V-MWSKZ =
/ZAK/AFA_CUST-MWSKZ .
/ZAK/AFA_CUST_V-KTOSL =
/ZAK/AFA_CUST-KTOSL .
/ZAK/AFA_CUST_V-ATYPE =
/ZAK/AFA_CUST-ATYPE .
/ZAK/AFA_CUST_V-ABEVAZ =
/ZAK/AFA_CUST-ABEVAZ .
/ZAK/AFA_CUST_V-XEGDR =
/ZAK/AFA_CUST-XEGDR .
/ZAK/AFA_CUST_V-SIGN =
/ZAK/AFA_CUST-SIGN .
/ZAK/AFA_CUST_V-MSIGN =
/ZAK/AFA_CUST-MSIGN .
/ZAK/AFA_CUST_V-KATA =
/ZAK/AFA_CUST-KATA .
/ZAK/AFA_CUST_V-TAXDIFF =
/ZAK/AFA_CUST-TAXDIFF .
/ZAK/AFA_CUST_V-DATUM =
/ZAK/AFA_CUST-DATUM .
/ZAK/AFA_CUST_V-UZEIT =
/ZAK/AFA_CUST-UZEIT .
/ZAK/AFA_CUST_V-UNAME =
/ZAK/AFA_CUST-UNAME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/AFA_CUST-BTYPE AND
ABEVAZ = /ZAK/AFA_CUST-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/AFA_CUST_V-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/AFA_CUST_V-ABEVTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/AFA_CUST_V-ABEVTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/AFA_CUST_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/AFA_CUST_V-BTYPE TO
/ZAK/AFA_CUST-BTYPE .
MOVE /ZAK/AFA_CUST_V-MWSKZ TO
/ZAK/AFA_CUST-MWSKZ .
MOVE /ZAK/AFA_CUST_V-KTOSL TO
/ZAK/AFA_CUST-KTOSL .
MOVE /ZAK/AFA_CUST_V-ATYPE TO
/ZAK/AFA_CUST-ATYPE .
MOVE /ZAK/AFA_CUST_V-XEGDR TO
/ZAK/AFA_CUST-XEGDR .
MOVE /ZAK/AFA_CUST_V-ABEVAZ TO
/ZAK/AFA_CUST-ABEVAZ .
MOVE /ZAK/AFA_CUST_V-MANDT TO
/ZAK/AFA_CUST-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/AFA_CUST'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/AFA_CUST TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/AFA_CUST'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/ZAK/AFA_CUST_V USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/ZAK/AFA_CUST-MANDT =
/ZAK/AFA_CUST_V-MANDT .
/ZAK/AFA_CUST-BTYPE =
/ZAK/AFA_CUST_V-BTYPE .
/ZAK/AFA_CUST-MWSKZ =
/ZAK/AFA_CUST_V-MWSKZ .
/ZAK/AFA_CUST-KTOSL =
/ZAK/AFA_CUST_V-KTOSL .
/ZAK/AFA_CUST-ATYPE =
/ZAK/AFA_CUST_V-ATYPE .
/ZAK/AFA_CUST-ABEVAZ =
/ZAK/AFA_CUST_V-ABEVAZ .
/ZAK/AFA_CUST-XEGDR =
/ZAK/AFA_CUST_V-XEGDR .
/ZAK/AFA_CUST-SIGN =
/ZAK/AFA_CUST_V-SIGN .
/ZAK/AFA_CUST-MSIGN =
/ZAK/AFA_CUST_V-MSIGN .
/ZAK/AFA_CUST-KATA =
/ZAK/AFA_CUST_V-KATA .
/ZAK/AFA_CUST-TAXDIFF =
/ZAK/AFA_CUST_V-TAXDIFF .
/ZAK/AFA_CUST-DATUM =
/ZAK/AFA_CUST_V-DATUM .
/ZAK/AFA_CUST-UZEIT =
/ZAK/AFA_CUST_V-UZEIT .
/ZAK/AFA_CUST-UNAME =
/ZAK/AFA_CUST_V-UNAME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/AFA_CUST-BTYPE AND
ABEVAZ = /ZAK/AFA_CUST-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/AFA_CUST_V-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/AFA_CUST_V-ABEVTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/AFA_CUST_V-ABEVTEXT .
    ENDIF.
ENDFORM.
