*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/IGABEV_V....................................*
FORM GET_DATA_/ZAK/IGABEV_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/IGABEV WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/IGABEV_V .
/ZAK/IGABEV_V-MANDT =
/ZAK/IGABEV-MANDT .
/ZAK/IGABEV_V-BUKRS =
/ZAK/IGABEV-BUKRS .
/ZAK/IGABEV_V-BTYPE =
/ZAK/IGABEV-BTYPE .
/ZAK/IGABEV_V-BSZNUM =
/ZAK/IGABEV-BSZNUM .
/ZAK/IGABEV_V-IGAZON =
/ZAK/IGABEV-IGAZON .
/ZAK/IGABEV_V-TYPE =
/ZAK/IGABEV-TYPE .
/ZAK/IGABEV_V-SORREND =
/ZAK/IGABEV-SORREND .
/ZAK/IGABEV_V-POZICIO =
/ZAK/IGABEV-POZICIO .
/ZAK/IGABEV_V-OBLIG =
/ZAK/IGABEV-OBLIG .
/ZAK/IGABEV_V-COLLECT =
/ZAK/IGABEV-COLLECT .
/ZAK/IGABEV_V-ABEVAZ =
/ZAK/IGABEV-ABEVAZ .
/ZAK/IGABEV_V-SUM_IGAZON =
/ZAK/IGABEV-SUM_IGAZON .
/ZAK/IGABEV_V-SIGN =
/ZAK/IGABEV-SIGN .
/ZAK/IGABEV_V-DATUM =
/ZAK/IGABEV-DATUM .
/ZAK/IGABEV_V-UZEIT =
/ZAK/IGABEV-UZEIT .
/ZAK/IGABEV_V-UNAME =
/ZAK/IGABEV-UNAME .
    SELECT SINGLE * FROM /ZAK/IGSOR WHERE
IGAZON = /ZAK/IGABEV-IGAZON .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/IGSORT WHERE
IGAZON = /ZAK/IGSOR-IGAZON AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/IGABEV_V-TEXT =
/ZAK/IGSORT-TEXT .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/IGABEV-BTYPE AND
ABEVAZ = /ZAK/IGABEV-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/IGABEV_V-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /ZAK/IGABEV_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/IGABEV_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/IGABEV_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/IGABEV_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/IGABEV WHERE
  BUKRS = /ZAK/IGABEV_V-BUKRS AND
  BTYPE = /ZAK/IGABEV_V-BTYPE AND
  BSZNUM = /ZAK/IGABEV_V-BSZNUM AND
  IGAZON = /ZAK/IGABEV_V-IGAZON AND
  TYPE = /ZAK/IGABEV_V-TYPE AND
  SORREND = /ZAK/IGABEV_V-SORREND AND
  POZICIO = /ZAK/IGABEV_V-POZICIO .
    IF SY-SUBRC = 0.
    DELETE /ZAK/IGABEV .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/IGABEV WHERE
  BUKRS = /ZAK/IGABEV_V-BUKRS AND
  BTYPE = /ZAK/IGABEV_V-BTYPE AND
  BSZNUM = /ZAK/IGABEV_V-BSZNUM AND
  IGAZON = /ZAK/IGABEV_V-IGAZON AND
  TYPE = /ZAK/IGABEV_V-TYPE AND
  SORREND = /ZAK/IGABEV_V-SORREND AND
  POZICIO = /ZAK/IGABEV_V-POZICIO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/IGABEV.
    ENDIF.
/ZAK/IGABEV-MANDT =
/ZAK/IGABEV_V-MANDT .
/ZAK/IGABEV-BUKRS =
/ZAK/IGABEV_V-BUKRS .
/ZAK/IGABEV-BTYPE =
/ZAK/IGABEV_V-BTYPE .
/ZAK/IGABEV-BSZNUM =
/ZAK/IGABEV_V-BSZNUM .
/ZAK/IGABEV-IGAZON =
/ZAK/IGABEV_V-IGAZON .
/ZAK/IGABEV-TYPE =
/ZAK/IGABEV_V-TYPE .
/ZAK/IGABEV-SORREND =
/ZAK/IGABEV_V-SORREND .
/ZAK/IGABEV-POZICIO =
/ZAK/IGABEV_V-POZICIO .
/ZAK/IGABEV-OBLIG =
/ZAK/IGABEV_V-OBLIG .
/ZAK/IGABEV-COLLECT =
/ZAK/IGABEV_V-COLLECT .
/ZAK/IGABEV-ABEVAZ =
/ZAK/IGABEV_V-ABEVAZ .
/ZAK/IGABEV-SUM_IGAZON =
/ZAK/IGABEV_V-SUM_IGAZON .
/ZAK/IGABEV-SIGN =
/ZAK/IGABEV_V-SIGN .
/ZAK/IGABEV-DATUM =
/ZAK/IGABEV_V-DATUM .
/ZAK/IGABEV-UZEIT =
/ZAK/IGABEV_V-UZEIT .
/ZAK/IGABEV-UNAME =
/ZAK/IGABEV_V-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/IGABEV .
    ELSE.
    INSERT /ZAK/IGABEV .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/IGABEV_V-UPD_FLAG,
STATUS_/ZAK/IGABEV_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/IGABEV_V.
  SELECT SINGLE * FROM /ZAK/IGABEV WHERE
BUKRS = /ZAK/IGABEV_V-BUKRS AND
BTYPE = /ZAK/IGABEV_V-BTYPE AND
BSZNUM = /ZAK/IGABEV_V-BSZNUM AND
IGAZON = /ZAK/IGABEV_V-IGAZON AND
TYPE = /ZAK/IGABEV_V-TYPE AND
SORREND = /ZAK/IGABEV_V-SORREND AND
POZICIO = /ZAK/IGABEV_V-POZICIO .
/ZAK/IGABEV_V-MANDT =
/ZAK/IGABEV-MANDT .
/ZAK/IGABEV_V-BUKRS =
/ZAK/IGABEV-BUKRS .
/ZAK/IGABEV_V-BTYPE =
/ZAK/IGABEV-BTYPE .
/ZAK/IGABEV_V-BSZNUM =
/ZAK/IGABEV-BSZNUM .
/ZAK/IGABEV_V-IGAZON =
/ZAK/IGABEV-IGAZON .
/ZAK/IGABEV_V-TYPE =
/ZAK/IGABEV-TYPE .
/ZAK/IGABEV_V-SORREND =
/ZAK/IGABEV-SORREND .
/ZAK/IGABEV_V-POZICIO =
/ZAK/IGABEV-POZICIO .
/ZAK/IGABEV_V-OBLIG =
/ZAK/IGABEV-OBLIG .
/ZAK/IGABEV_V-COLLECT =
/ZAK/IGABEV-COLLECT .
/ZAK/IGABEV_V-ABEVAZ =
/ZAK/IGABEV-ABEVAZ .
/ZAK/IGABEV_V-SUM_IGAZON =
/ZAK/IGABEV-SUM_IGAZON .
/ZAK/IGABEV_V-SIGN =
/ZAK/IGABEV-SIGN .
/ZAK/IGABEV_V-DATUM =
/ZAK/IGABEV-DATUM .
/ZAK/IGABEV_V-UZEIT =
/ZAK/IGABEV-UZEIT .
/ZAK/IGABEV_V-UNAME =
/ZAK/IGABEV-UNAME .
    SELECT SINGLE * FROM /ZAK/IGSOR WHERE
IGAZON = /ZAK/IGABEV-IGAZON .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/IGSORT WHERE
IGAZON = /ZAK/IGSOR-IGAZON AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/IGABEV_V-TEXT =
/ZAK/IGSORT-TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/IGABEV_V-TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/IGABEV_V-TEXT .
    ENDIF.
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/IGABEV-BTYPE AND
ABEVAZ = /ZAK/IGABEV-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/IGABEV_V-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/IGABEV_V-ABEVTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/IGABEV_V-ABEVTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/IGABEV_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/IGABEV_V-BUKRS TO
/ZAK/IGABEV-BUKRS .
MOVE /ZAK/IGABEV_V-BTYPE TO
/ZAK/IGABEV-BTYPE .
MOVE /ZAK/IGABEV_V-BSZNUM TO
/ZAK/IGABEV-BSZNUM .
MOVE /ZAK/IGABEV_V-IGAZON TO
/ZAK/IGABEV-IGAZON .
MOVE /ZAK/IGABEV_V-TYPE TO
/ZAK/IGABEV-TYPE .
MOVE /ZAK/IGABEV_V-SORREND TO
/ZAK/IGABEV-SORREND .
MOVE /ZAK/IGABEV_V-POZICIO TO
/ZAK/IGABEV-POZICIO .
MOVE /ZAK/IGABEV_V-MANDT TO
/ZAK/IGABEV-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/IGABEV'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/IGABEV TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/IGABEV'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/ZAK/IGABEV_V USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/ZAK/IGABEV-MANDT =
/ZAK/IGABEV_V-MANDT .
/ZAK/IGABEV-BUKRS =
/ZAK/IGABEV_V-BUKRS .
/ZAK/IGABEV-BTYPE =
/ZAK/IGABEV_V-BTYPE .
/ZAK/IGABEV-BSZNUM =
/ZAK/IGABEV_V-BSZNUM .
/ZAK/IGABEV-IGAZON =
/ZAK/IGABEV_V-IGAZON .
/ZAK/IGABEV-TYPE =
/ZAK/IGABEV_V-TYPE .
/ZAK/IGABEV-SORREND =
/ZAK/IGABEV_V-SORREND .
/ZAK/IGABEV-POZICIO =
/ZAK/IGABEV_V-POZICIO .
/ZAK/IGABEV-OBLIG =
/ZAK/IGABEV_V-OBLIG .
/ZAK/IGABEV-COLLECT =
/ZAK/IGABEV_V-COLLECT .
/ZAK/IGABEV-ABEVAZ =
/ZAK/IGABEV_V-ABEVAZ .
/ZAK/IGABEV-SUM_IGAZON =
/ZAK/IGABEV_V-SUM_IGAZON .
/ZAK/IGABEV-SIGN =
/ZAK/IGABEV_V-SIGN .
/ZAK/IGABEV-DATUM =
/ZAK/IGABEV_V-DATUM .
/ZAK/IGABEV-UZEIT =
/ZAK/IGABEV_V-UZEIT .
/ZAK/IGABEV-UNAME =
/ZAK/IGABEV_V-UNAME .
    SELECT SINGLE * FROM /ZAK/IGSOR WHERE
IGAZON = /ZAK/IGABEV-IGAZON .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/IGSORT WHERE
IGAZON = /ZAK/IGSOR-IGAZON AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/IGABEV_V-TEXT =
/ZAK/IGSORT-TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/IGABEV_V-TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/IGABEV_V-TEXT .
    ENDIF.
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/IGABEV-BTYPE AND
ABEVAZ = /ZAK/IGABEV-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/IGABEV_V-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/IGABEV_V-ABEVTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/IGABEV_V-ABEVTEXT .
    ENDIF.
ENDFORM.
