*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/AFA_ELV...................................*
FORM GET_DATA_/ZAK/AFA_ELV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/AFA_ELO WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/AFA_ELV .
/ZAK/AFA_ELV-MANDT =
/ZAK/AFA_ELO-MANDT .
/ZAK/AFA_ELV-BUKRS =
/ZAK/AFA_ELO-BUKRS .
/ZAK/AFA_ELV-BTYPE =
/ZAK/AFA_ELO-BTYPE .
/ZAK/AFA_ELV-ABEVAZ =
/ZAK/AFA_ELO-ABEVAZ .
/ZAK/AFA_ELV-HKONT_FROM =
/ZAK/AFA_ELO-HKONT_FROM .
/ZAK/AFA_ELV-HKONT_TO =
/ZAK/AFA_ELO-HKONT_TO .
/ZAK/AFA_ELV-BLART =
/ZAK/AFA_ELO-BLART .
/ZAK/AFA_ELV-MWSKZ =
/ZAK/AFA_ELO-MWSKZ .
/ZAK/AFA_ELV-ATYPE =
/ZAK/AFA_ELO-ATYPE .
/ZAK/AFA_ELV-SIGN =
/ZAK/AFA_ELO-SIGN .
/ZAK/AFA_ELV-AS4USER =
/ZAK/AFA_ELO-AS4USER .
/ZAK/AFA_ELV-AS4DATE =
/ZAK/AFA_ELO-AS4DATE .
/ZAK/AFA_ELV-AS4TIME =
/ZAK/AFA_ELO-AS4TIME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/AFA_ELO-BTYPE AND
ABEVAZ = /ZAK/AFA_ELO-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/AFA_ELV-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /ZAK/AFA_ELV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/AFA_ELV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/AFA_ELV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/AFA_ELV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_ELO WHERE
  BUKRS = /ZAK/AFA_ELV-BUKRS AND
  BTYPE = /ZAK/AFA_ELV-BTYPE AND
  ABEVAZ = /ZAK/AFA_ELV-ABEVAZ AND
  HKONT_FROM = /ZAK/AFA_ELV-HKONT_FROM AND
  HKONT_TO = /ZAK/AFA_ELV-HKONT_TO AND
  BLART = /ZAK/AFA_ELV-BLART AND
  MWSKZ = /ZAK/AFA_ELV-MWSKZ AND
  ATYPE = /ZAK/AFA_ELV-ATYPE .
    IF SY-SUBRC = 0.
    DELETE /ZAK/AFA_ELO .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_ELO WHERE
  BUKRS = /ZAK/AFA_ELV-BUKRS AND
  BTYPE = /ZAK/AFA_ELV-BTYPE AND
  ABEVAZ = /ZAK/AFA_ELV-ABEVAZ AND
  HKONT_FROM = /ZAK/AFA_ELV-HKONT_FROM AND
  HKONT_TO = /ZAK/AFA_ELV-HKONT_TO AND
  BLART = /ZAK/AFA_ELV-BLART AND
  MWSKZ = /ZAK/AFA_ELV-MWSKZ AND
  ATYPE = /ZAK/AFA_ELV-ATYPE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/AFA_ELO.
    ENDIF.
/ZAK/AFA_ELO-MANDT =
/ZAK/AFA_ELV-MANDT .
/ZAK/AFA_ELO-BUKRS =
/ZAK/AFA_ELV-BUKRS .
/ZAK/AFA_ELO-BTYPE =
/ZAK/AFA_ELV-BTYPE .
/ZAK/AFA_ELO-ABEVAZ =
/ZAK/AFA_ELV-ABEVAZ .
/ZAK/AFA_ELO-HKONT_FROM =
/ZAK/AFA_ELV-HKONT_FROM .
/ZAK/AFA_ELO-HKONT_TO =
/ZAK/AFA_ELV-HKONT_TO .
/ZAK/AFA_ELO-BLART =
/ZAK/AFA_ELV-BLART .
/ZAK/AFA_ELO-MWSKZ =
/ZAK/AFA_ELV-MWSKZ .
/ZAK/AFA_ELO-ATYPE =
/ZAK/AFA_ELV-ATYPE .
/ZAK/AFA_ELO-SIGN =
/ZAK/AFA_ELV-SIGN .
/ZAK/AFA_ELO-AS4USER =
/ZAK/AFA_ELV-AS4USER .
/ZAK/AFA_ELO-AS4DATE =
/ZAK/AFA_ELV-AS4DATE .
/ZAK/AFA_ELO-AS4TIME =
/ZAK/AFA_ELV-AS4TIME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/AFA_ELO .
    ELSE.
    INSERT /ZAK/AFA_ELO .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/AFA_ELV-UPD_FLAG,
STATUS_/ZAK/AFA_ELV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/AFA_ELV.
  SELECT SINGLE * FROM /ZAK/AFA_ELO WHERE
BUKRS = /ZAK/AFA_ELV-BUKRS AND
BTYPE = /ZAK/AFA_ELV-BTYPE AND
ABEVAZ = /ZAK/AFA_ELV-ABEVAZ AND
HKONT_FROM = /ZAK/AFA_ELV-HKONT_FROM AND
HKONT_TO = /ZAK/AFA_ELV-HKONT_TO AND
BLART = /ZAK/AFA_ELV-BLART AND
MWSKZ = /ZAK/AFA_ELV-MWSKZ AND
ATYPE = /ZAK/AFA_ELV-ATYPE .
/ZAK/AFA_ELV-MANDT =
/ZAK/AFA_ELO-MANDT .
/ZAK/AFA_ELV-BUKRS =
/ZAK/AFA_ELO-BUKRS .
/ZAK/AFA_ELV-BTYPE =
/ZAK/AFA_ELO-BTYPE .
/ZAK/AFA_ELV-ABEVAZ =
/ZAK/AFA_ELO-ABEVAZ .
/ZAK/AFA_ELV-HKONT_FROM =
/ZAK/AFA_ELO-HKONT_FROM .
/ZAK/AFA_ELV-HKONT_TO =
/ZAK/AFA_ELO-HKONT_TO .
/ZAK/AFA_ELV-BLART =
/ZAK/AFA_ELO-BLART .
/ZAK/AFA_ELV-MWSKZ =
/ZAK/AFA_ELO-MWSKZ .
/ZAK/AFA_ELV-ATYPE =
/ZAK/AFA_ELO-ATYPE .
/ZAK/AFA_ELV-SIGN =
/ZAK/AFA_ELO-SIGN .
/ZAK/AFA_ELV-AS4USER =
/ZAK/AFA_ELO-AS4USER .
/ZAK/AFA_ELV-AS4DATE =
/ZAK/AFA_ELO-AS4DATE .
/ZAK/AFA_ELV-AS4TIME =
/ZAK/AFA_ELO-AS4TIME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/AFA_ELO-BTYPE AND
ABEVAZ = /ZAK/AFA_ELO-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/AFA_ELV-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/AFA_ELV-ABEVTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/AFA_ELV-ABEVTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/AFA_ELV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/AFA_ELV-BUKRS TO
/ZAK/AFA_ELO-BUKRS .
MOVE /ZAK/AFA_ELV-BTYPE TO
/ZAK/AFA_ELO-BTYPE .
MOVE /ZAK/AFA_ELV-ABEVAZ TO
/ZAK/AFA_ELO-ABEVAZ .
MOVE /ZAK/AFA_ELV-HKONT_FROM TO
/ZAK/AFA_ELO-HKONT_FROM .
MOVE /ZAK/AFA_ELV-HKONT_TO TO
/ZAK/AFA_ELO-HKONT_TO .
MOVE /ZAK/AFA_ELV-BLART TO
/ZAK/AFA_ELO-BLART .
MOVE /ZAK/AFA_ELV-MWSKZ TO
/ZAK/AFA_ELO-MWSKZ .
MOVE /ZAK/AFA_ELV-ATYPE TO
/ZAK/AFA_ELO-ATYPE .
MOVE /ZAK/AFA_ELV-MANDT TO
/ZAK/AFA_ELO-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/AFA_ELO'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/AFA_ELO TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/AFA_ELO'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/ZAK/AFA_ELV USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/ZAK/AFA_ELO-MANDT =
/ZAK/AFA_ELV-MANDT .
/ZAK/AFA_ELO-BUKRS =
/ZAK/AFA_ELV-BUKRS .
/ZAK/AFA_ELO-BTYPE =
/ZAK/AFA_ELV-BTYPE .
/ZAK/AFA_ELO-ABEVAZ =
/ZAK/AFA_ELV-ABEVAZ .
/ZAK/AFA_ELO-HKONT_FROM =
/ZAK/AFA_ELV-HKONT_FROM .
/ZAK/AFA_ELO-HKONT_TO =
/ZAK/AFA_ELV-HKONT_TO .
/ZAK/AFA_ELO-BLART =
/ZAK/AFA_ELV-BLART .
/ZAK/AFA_ELO-MWSKZ =
/ZAK/AFA_ELV-MWSKZ .
/ZAK/AFA_ELO-ATYPE =
/ZAK/AFA_ELV-ATYPE .
/ZAK/AFA_ELO-SIGN =
/ZAK/AFA_ELV-SIGN .
/ZAK/AFA_ELO-AS4USER =
/ZAK/AFA_ELV-AS4USER .
/ZAK/AFA_ELO-AS4DATE =
/ZAK/AFA_ELV-AS4DATE .
/ZAK/AFA_ELO-AS4TIME =
/ZAK/AFA_ELV-AS4TIME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/AFA_ELO-BTYPE AND
ABEVAZ = /ZAK/AFA_ELO-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/AFA_ELV-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/AFA_ELV-ABEVTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/AFA_ELV-ABEVTEXT .
    ENDIF.
ENDFORM.
