*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LAFA_ELMVTOP.               " Global Data
  INCLUDE /ZAK/LAFA_ELMVUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LAFA_ELMVF00                     . " subprograms
  INCLUDE /ZAK/LAFA_ELMVI00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LAFA_ELMVF...               " Subprograms
* INCLUDE /ZAK/LAFA_ELMVO...               " PBO-Modules
* INCLUDE /ZAK/LAFA_ELMVI...               " PAI-Modules

INCLUDE /ZAK/LAFA_ELMVF01.
