
PROCESS BEFORE OUTPUT.

  MODULE STATUS_9000.

  MODULE INIT_9000.
*
  LOOP AT I_LINES WITH CONTROL TC_9000 CURSOR TC_9000-CURRENT_LINE.
  ENDLOOP.

PROCESS AFTER INPUT.

  LOOP AT I_LINES.
*++BG
    CHAIN.
      FIELD I_LINES-ADONEM_SRC.
      FIELD I_LINES-WRBTR_SRC.
      FIELD I_LINES-ADONEM_DES.
      FIELD I_LINES-WRBTR_DES.

      MODULE MODIFY_I_LINES.
    ENDCHAIN.
*--BG

*   MODULE MODIFY_I_LINES.
  ENDLOOP.

  MODULE USER_COMMAND_9000.
