*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LAFACS_VTOP.                  " Global Data
  INCLUDE /ZAK/LAFACS_VUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LAFACS_VF00                        . " subprograms
  INCLUDE /ZAK/LAFACS_VI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LAFACS_VF...                  " Subprograms
* INCLUDE /ZAK/LAFACS_VO...                  " PBO-Modules
* INCLUDE /ZAK/LAFACS_VI...                  " PAI-Modules

INCLUDE /ZAK/LAFACS_VF01.
