PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/TEL_AFA_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/TEL_AFA_V-BTYPE .
    FIELD /ZAK/TEL_AFA_V-MWSKZ .
    FIELD /ZAK/TEL_AFA_V-MWSKZ_T .
    FIELD /ZAK/TEL_AFA_V-AS4USER .
    FIELD /ZAK/TEL_AFA_V-AS4DATE .
    FIELD /ZAK/TEL_AFA_V-AS4TIME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/TEL_AFA_V-BTYPE .
    FIELD /ZAK/TEL_AFA_V-MWSKZ .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
