*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/AFA_ARANY_V.................................*
FORM GET_DATA_/ZAK/AFA_ARANY_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/AFA_ARANY WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/AFA_ARANY_V .
/ZAK/AFA_ARANY_V-MANDT =
/ZAK/AFA_ARANY-MANDT .
/ZAK/AFA_ARANY_V-BUKRS =
/ZAK/AFA_ARANY-BUKRS .
/ZAK/AFA_ARANY_V-GJAHR =
/ZAK/AFA_ARANY-GJAHR .
/ZAK/AFA_ARANY_V-MONAT =
/ZAK/AFA_ARANY-MONAT .
/ZAK/AFA_ARANY_V-LWBAS_NMT =
/ZAK/AFA_ARANY-LWBAS_NMT .
/ZAK/AFA_ARANY_V-LWBAS_SUM =
/ZAK/AFA_ARANY-LWBAS_SUM .
/ZAK/AFA_ARANY_V-WAERS =
/ZAK/AFA_ARANY-WAERS .
/ZAK/AFA_ARANY_V-ARANY =
/ZAK/AFA_ARANY-ARANY .
<VIM_TOTAL_STRUC> = /ZAK/AFA_ARANY_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/AFA_ARANY_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/AFA_ARANY_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/AFA_ARANY_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_ARANY WHERE
  BUKRS = /ZAK/AFA_ARANY_V-BUKRS AND
  GJAHR = /ZAK/AFA_ARANY_V-GJAHR AND
  MONAT = /ZAK/AFA_ARANY_V-MONAT .
    IF SY-SUBRC = 0.
    DELETE /ZAK/AFA_ARANY .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_ARANY WHERE
  BUKRS = /ZAK/AFA_ARANY_V-BUKRS AND
  GJAHR = /ZAK/AFA_ARANY_V-GJAHR AND
  MONAT = /ZAK/AFA_ARANY_V-MONAT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/AFA_ARANY.
    ENDIF.
/ZAK/AFA_ARANY-MANDT =
/ZAK/AFA_ARANY_V-MANDT .
/ZAK/AFA_ARANY-BUKRS =
/ZAK/AFA_ARANY_V-BUKRS .
/ZAK/AFA_ARANY-GJAHR =
/ZAK/AFA_ARANY_V-GJAHR .
/ZAK/AFA_ARANY-MONAT =
/ZAK/AFA_ARANY_V-MONAT .
/ZAK/AFA_ARANY-LWBAS_NMT =
/ZAK/AFA_ARANY_V-LWBAS_NMT .
/ZAK/AFA_ARANY-LWBAS_SUM =
/ZAK/AFA_ARANY_V-LWBAS_SUM .
/ZAK/AFA_ARANY-WAERS =
/ZAK/AFA_ARANY_V-WAERS .
/ZAK/AFA_ARANY-ARANY =
/ZAK/AFA_ARANY_V-ARANY .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/AFA_ARANY .
    ELSE.
    INSERT /ZAK/AFA_ARANY .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/AFA_ARANY_V-UPD_FLAG,
STATUS_/ZAK/AFA_ARANY_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/AFA_ARANY_V.
  SELECT SINGLE * FROM /ZAK/AFA_ARANY WHERE
BUKRS = /ZAK/AFA_ARANY_V-BUKRS AND
GJAHR = /ZAK/AFA_ARANY_V-GJAHR AND
MONAT = /ZAK/AFA_ARANY_V-MONAT .
/ZAK/AFA_ARANY_V-MANDT =
/ZAK/AFA_ARANY-MANDT .
/ZAK/AFA_ARANY_V-BUKRS =
/ZAK/AFA_ARANY-BUKRS .
/ZAK/AFA_ARANY_V-GJAHR =
/ZAK/AFA_ARANY-GJAHR .
/ZAK/AFA_ARANY_V-MONAT =
/ZAK/AFA_ARANY-MONAT .
/ZAK/AFA_ARANY_V-LWBAS_NMT =
/ZAK/AFA_ARANY-LWBAS_NMT .
/ZAK/AFA_ARANY_V-LWBAS_SUM =
/ZAK/AFA_ARANY-LWBAS_SUM .
/ZAK/AFA_ARANY_V-WAERS =
/ZAK/AFA_ARANY-WAERS .
/ZAK/AFA_ARANY_V-ARANY =
/ZAK/AFA_ARANY-ARANY .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/AFA_ARANY_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/AFA_ARANY_V-BUKRS TO
/ZAK/AFA_ARANY-BUKRS .
MOVE /ZAK/AFA_ARANY_V-GJAHR TO
/ZAK/AFA_ARANY-GJAHR .
MOVE /ZAK/AFA_ARANY_V-MONAT TO
/ZAK/AFA_ARANY-MONAT .
MOVE /ZAK/AFA_ARANY_V-MANDT TO
/ZAK/AFA_ARANY-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/AFA_ARANY'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/AFA_ARANY TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/AFA_ARANY'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
