*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/HRSZU_V.....................................*
FORM GET_DATA_/ZAK/HRSZU_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/HRSZU WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/HRSZU_V .
/ZAK/HRSZU_V-MANDT =
/ZAK/HRSZU-MANDT .
/ZAK/HRSZU_V-BUKRS =
/ZAK/HRSZU-BUKRS .
/ZAK/HRSZU_V-MWSKZ =
/ZAK/HRSZU-MWSKZ .
/ZAK/HRSZU_V-XEGDR =
/ZAK/HRSZU-XEGDR .
/ZAK/HRSZU_V-HSZU =
/ZAK/HRSZU-HSZU .
/ZAK/HRSZU_V-DATUM =
/ZAK/HRSZU-DATUM .
/ZAK/HRSZU_V-UZEIT =
/ZAK/HRSZU-UZEIT .
/ZAK/HRSZU_V-UNAME =
/ZAK/HRSZU-UNAME .
<VIM_TOTAL_STRUC> = /ZAK/HRSZU_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/HRSZU_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/HRSZU_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/HRSZU_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/HRSZU WHERE
  BUKRS = /ZAK/HRSZU_V-BUKRS AND
  MWSKZ = /ZAK/HRSZU_V-MWSKZ AND
  XEGDR = /ZAK/HRSZU_V-XEGDR .
    IF SY-SUBRC = 0.
    DELETE /ZAK/HRSZU .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/HRSZU WHERE
  BUKRS = /ZAK/HRSZU_V-BUKRS AND
  MWSKZ = /ZAK/HRSZU_V-MWSKZ AND
  XEGDR = /ZAK/HRSZU_V-XEGDR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/HRSZU.
    ENDIF.
/ZAK/HRSZU-MANDT =
/ZAK/HRSZU_V-MANDT .
/ZAK/HRSZU-BUKRS =
/ZAK/HRSZU_V-BUKRS .
/ZAK/HRSZU-MWSKZ =
/ZAK/HRSZU_V-MWSKZ .
/ZAK/HRSZU-XEGDR =
/ZAK/HRSZU_V-XEGDR .
/ZAK/HRSZU-HSZU =
/ZAK/HRSZU_V-HSZU .
/ZAK/HRSZU-DATUM =
/ZAK/HRSZU_V-DATUM .
/ZAK/HRSZU-UZEIT =
/ZAK/HRSZU_V-UZEIT .
/ZAK/HRSZU-UNAME =
/ZAK/HRSZU_V-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/HRSZU .
    ELSE.
    INSERT /ZAK/HRSZU .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/HRSZU_V-UPD_FLAG,
STATUS_/ZAK/HRSZU_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/HRSZU_V.
  SELECT SINGLE * FROM /ZAK/HRSZU WHERE
BUKRS = /ZAK/HRSZU_V-BUKRS AND
MWSKZ = /ZAK/HRSZU_V-MWSKZ AND
XEGDR = /ZAK/HRSZU_V-XEGDR .
/ZAK/HRSZU_V-MANDT =
/ZAK/HRSZU-MANDT .
/ZAK/HRSZU_V-BUKRS =
/ZAK/HRSZU-BUKRS .
/ZAK/HRSZU_V-MWSKZ =
/ZAK/HRSZU-MWSKZ .
/ZAK/HRSZU_V-XEGDR =
/ZAK/HRSZU-XEGDR .
/ZAK/HRSZU_V-HSZU =
/ZAK/HRSZU-HSZU .
/ZAK/HRSZU_V-DATUM =
/ZAK/HRSZU-DATUM .
/ZAK/HRSZU_V-UZEIT =
/ZAK/HRSZU-UZEIT .
/ZAK/HRSZU_V-UNAME =
/ZAK/HRSZU-UNAME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/HRSZU_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/HRSZU_V-BUKRS TO
/ZAK/HRSZU-BUKRS .
MOVE /ZAK/HRSZU_V-MWSKZ TO
/ZAK/HRSZU-MWSKZ .
MOVE /ZAK/HRSZU_V-XEGDR TO
/ZAK/HRSZU-XEGDR .
MOVE /ZAK/HRSZU_V-MANDT TO
/ZAK/HRSZU-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/HRSZU'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/HRSZU TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/HRSZU'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
