PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/ADONEM_ONRV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/ADONEM_ONRV-BTYPE .
    FIELD /ZAK/ADONEM_ONRV-ADONEM_ONR .
    FIELD /ZAK/ADONEM_ONRV-ABEVAZ .
    FIELD /ZAK/ADONEM_ONRV-ABEVTEXT .
    FIELD /ZAK/ADONEM_ONRV-AS4USER .
    FIELD /ZAK/ADONEM_ONRV-AS4DATE .
    FIELD /ZAK/ADONEM_ONRV-AS4TIME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_/ZAK/ADONEM_ONRV ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/ADONEM_ONRV-BTYPE .
    FIELD /ZAK/ADONEM_ONRV-ADONEM_ONR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
