*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LEGYKORRTOP.                  " Global Data
  INCLUDE /ZAK/LEGYKORRUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LEGYKORRF00                        . " subprograms
  INCLUDE /ZAK/LEGYKORRI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LEGYKORRF...                  " Subprograms
* INCLUDE /ZAK/LEGYKORRO...                  " PBO-Modules
* INCLUDE /ZAK/LEGYKORRI...                  " PAI-Modules
