*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/BEVALLB_V...................................*
FORM GET_DATA_/ZAK/BEVALLB_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/BEVALLB WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/BEVALLB_V .
/ZAK/BEVALLB_V-MANDT =
/ZAK/BEVALLB-MANDT .
/ZAK/BEVALLB_V-BTYPE =
/ZAK/BEVALLB-BTYPE .
/ZAK/BEVALLB_V-ABEVAZ =
/ZAK/BEVALLB-ABEVAZ .
/ZAK/BEVALLB_V-MANUAL =
/ZAK/BEVALLB-MANUAL .
/ZAK/BEVALLB_V-COLLECT =
/ZAK/BEVALLB-COLLECT .
/ZAK/BEVALLB_V-COLLN =
/ZAK/BEVALLB-COLLN .
/ZAK/BEVALLB_V-ASZKOT =
/ZAK/BEVALLB-ASZKOT .
/ZAK/BEVALLB_V-ABEV_NO =
/ZAK/BEVALLB-ABEV_NO .
/ZAK/BEVALLB_V-ESDAT_FLAG =
/ZAK/BEVALLB-ESDAT_FLAG .
/ZAK/BEVALLB_V-ELOJEL =
/ZAK/BEVALLB-ELOJEL .
/ZAK/BEVALLB_V-ONYBF =
/ZAK/BEVALLB-ONYBF .
/ZAK/BEVALLB_V-ONYLAPAZON =
/ZAK/BEVALLB-ONYLAPAZON .
/ZAK/BEVALLB_V-FOSOR =
/ZAK/BEVALLB-FOSOR .
/ZAK/BEVALLB_V-ADONEM =
/ZAK/BEVALLB-ADONEM .
/ZAK/BEVALLB_V-ADONEM_ONR =
/ZAK/BEVALLB-ADONEM_ONR .
/ZAK/BEVALLB_V-ONRPOTL =
/ZAK/BEVALLB-ONRPOTL .
/ZAK/BEVALLB_V-ELF_ADONSZA =
/ZAK/BEVALLB-ELF_ADONSZA .
/ZAK/BEVALLB_V-FIELDTYPE =
/ZAK/BEVALLB-FIELDTYPE .
/ZAK/BEVALLB_V-ROUND =
/ZAK/BEVALLB-ROUND .
/ZAK/BEVALLB_V-SAKNR =
/ZAK/BEVALLB-SAKNR .
/ZAK/BEVALLB_V-SUM_ABEVAZ =
/ZAK/BEVALLB-SUM_ABEVAZ .
/ZAK/BEVALLB_V-GET_ABEVAZ =
/ZAK/BEVALLB-GET_ABEVAZ .
/ZAK/BEVALLB_V-NYLAPAZON =
/ZAK/BEVALLB-NYLAPAZON .
/ZAK/BEVALLB_V-SORINDEX =
/ZAK/BEVALLB-SORINDEX .
/ZAK/BEVALLB_V-ALKMIN =
/ZAK/BEVALLB-ALKMIN .
/ZAK/BEVALLB_V-ACTREAD =
/ZAK/BEVALLB-ACTREAD .
/ZAK/BEVALLB_V-XMLALL =
/ZAK/BEVALLB-XMLALL .
/ZAK/BEVALLB_V-ONYBE =
/ZAK/BEVALLB-ONYBE .
/ZAK/BEVALLB_V-AFATYP =
/ZAK/BEVALLB-AFATYP .
    SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
/ZAK/BEVALLB_V-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
    ENDIF.
<VIM_TOTAL_STRUC> = /ZAK/BEVALLB_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/BEVALLB_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/BEVALLB_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/BEVALLB_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BEVALLB WHERE
  BTYPE = /ZAK/BEVALLB_V-BTYPE AND
  ABEVAZ = /ZAK/BEVALLB_V-ABEVAZ .
    IF SY-SUBRC = 0.
    DELETE /ZAK/BEVALLB .
    ENDIF.
    DELETE FROM /ZAK/BEVALLBT WHERE
    BTYPE = /ZAK/BEVALLB-BTYPE AND
    ABEVAZ = /ZAK/BEVALLB-ABEVAZ .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BEVALLB WHERE
  BTYPE = /ZAK/BEVALLB_V-BTYPE AND
  ABEVAZ = /ZAK/BEVALLB_V-ABEVAZ .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/BEVALLB.
    ENDIF.
/ZAK/BEVALLB-MANDT =
/ZAK/BEVALLB_V-MANDT .
/ZAK/BEVALLB-BTYPE =
/ZAK/BEVALLB_V-BTYPE .
/ZAK/BEVALLB-ABEVAZ =
/ZAK/BEVALLB_V-ABEVAZ .
/ZAK/BEVALLB-MANUAL =
/ZAK/BEVALLB_V-MANUAL .
/ZAK/BEVALLB-COLLECT =
/ZAK/BEVALLB_V-COLLECT .
/ZAK/BEVALLB-COLLN =
/ZAK/BEVALLB_V-COLLN .
/ZAK/BEVALLB-ASZKOT =
/ZAK/BEVALLB_V-ASZKOT .
/ZAK/BEVALLB-ABEV_NO =
/ZAK/BEVALLB_V-ABEV_NO .
/ZAK/BEVALLB-ESDAT_FLAG =
/ZAK/BEVALLB_V-ESDAT_FLAG .
/ZAK/BEVALLB-ELOJEL =
/ZAK/BEVALLB_V-ELOJEL .
/ZAK/BEVALLB-ONYBF =
/ZAK/BEVALLB_V-ONYBF .
/ZAK/BEVALLB-ONYLAPAZON =
/ZAK/BEVALLB_V-ONYLAPAZON .
/ZAK/BEVALLB-FOSOR =
/ZAK/BEVALLB_V-FOSOR .
/ZAK/BEVALLB-ADONEM =
/ZAK/BEVALLB_V-ADONEM .
/ZAK/BEVALLB-ADONEM_ONR =
/ZAK/BEVALLB_V-ADONEM_ONR .
/ZAK/BEVALLB-ONRPOTL =
/ZAK/BEVALLB_V-ONRPOTL .
/ZAK/BEVALLB-ELF_ADONSZA =
/ZAK/BEVALLB_V-ELF_ADONSZA .
/ZAK/BEVALLB-FIELDTYPE =
/ZAK/BEVALLB_V-FIELDTYPE .
/ZAK/BEVALLB-ROUND =
/ZAK/BEVALLB_V-ROUND .
/ZAK/BEVALLB-SAKNR =
/ZAK/BEVALLB_V-SAKNR .
/ZAK/BEVALLB-SUM_ABEVAZ =
/ZAK/BEVALLB_V-SUM_ABEVAZ .
/ZAK/BEVALLB-GET_ABEVAZ =
/ZAK/BEVALLB_V-GET_ABEVAZ .
/ZAK/BEVALLB-NYLAPAZON =
/ZAK/BEVALLB_V-NYLAPAZON .
/ZAK/BEVALLB-SORINDEX =
/ZAK/BEVALLB_V-SORINDEX .
/ZAK/BEVALLB-ALKMIN =
/ZAK/BEVALLB_V-ALKMIN .
/ZAK/BEVALLB-ACTREAD =
/ZAK/BEVALLB_V-ACTREAD .
/ZAK/BEVALLB-XMLALL =
/ZAK/BEVALLB_V-XMLALL .
/ZAK/BEVALLB-ONYBE =
/ZAK/BEVALLB_V-ONYBE .
/ZAK/BEVALLB-AFATYP =
/ZAK/BEVALLB_V-AFATYP .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/BEVALLB .
    ELSE.
    INSERT /ZAK/BEVALLB .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM /ZAK/BEVALLBT WHERE
    BTYPE = /ZAK/BEVALLB-BTYPE AND
    ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
    LANGU = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR /ZAK/BEVALLBT.
/ZAK/BEVALLBT-BTYPE =
/ZAK/BEVALLB-BTYPE .
/ZAK/BEVALLBT-ABEVAZ =
/ZAK/BEVALLB-ABEVAZ .
/ZAK/BEVALLBT-LANGU =
SY-LANGU .
      ENDIF.
/ZAK/BEVALLBT-ABEVTEXT =
/ZAK/BEVALLB_V-ABEVTEXT .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/BEVALLBT .
    ELSE.
    INSERT /ZAK/BEVALLBT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/BEVALLB_V-UPD_FLAG,
STATUS_/ZAK/BEVALLB_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/BEVALLB_V.
  SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/BEVALLB_V-BTYPE AND
ABEVAZ = /ZAK/BEVALLB_V-ABEVAZ .
/ZAK/BEVALLB_V-MANDT =
/ZAK/BEVALLB-MANDT .
/ZAK/BEVALLB_V-BTYPE =
/ZAK/BEVALLB-BTYPE .
/ZAK/BEVALLB_V-ABEVAZ =
/ZAK/BEVALLB-ABEVAZ .
/ZAK/BEVALLB_V-MANUAL =
/ZAK/BEVALLB-MANUAL .
/ZAK/BEVALLB_V-COLLECT =
/ZAK/BEVALLB-COLLECT .
/ZAK/BEVALLB_V-COLLN =
/ZAK/BEVALLB-COLLN .
/ZAK/BEVALLB_V-ASZKOT =
/ZAK/BEVALLB-ASZKOT .
/ZAK/BEVALLB_V-ABEV_NO =
/ZAK/BEVALLB-ABEV_NO .
/ZAK/BEVALLB_V-ESDAT_FLAG =
/ZAK/BEVALLB-ESDAT_FLAG .
/ZAK/BEVALLB_V-ELOJEL =
/ZAK/BEVALLB-ELOJEL .
/ZAK/BEVALLB_V-ONYBF =
/ZAK/BEVALLB-ONYBF .
/ZAK/BEVALLB_V-ONYLAPAZON =
/ZAK/BEVALLB-ONYLAPAZON .
/ZAK/BEVALLB_V-FOSOR =
/ZAK/BEVALLB-FOSOR .
/ZAK/BEVALLB_V-ADONEM =
/ZAK/BEVALLB-ADONEM .
/ZAK/BEVALLB_V-ADONEM_ONR =
/ZAK/BEVALLB-ADONEM_ONR .
/ZAK/BEVALLB_V-ONRPOTL =
/ZAK/BEVALLB-ONRPOTL .
/ZAK/BEVALLB_V-ELF_ADONSZA =
/ZAK/BEVALLB-ELF_ADONSZA .
/ZAK/BEVALLB_V-FIELDTYPE =
/ZAK/BEVALLB-FIELDTYPE .
/ZAK/BEVALLB_V-ROUND =
/ZAK/BEVALLB-ROUND .
/ZAK/BEVALLB_V-SAKNR =
/ZAK/BEVALLB-SAKNR .
/ZAK/BEVALLB_V-SUM_ABEVAZ =
/ZAK/BEVALLB-SUM_ABEVAZ .
/ZAK/BEVALLB_V-GET_ABEVAZ =
/ZAK/BEVALLB-GET_ABEVAZ .
/ZAK/BEVALLB_V-NYLAPAZON =
/ZAK/BEVALLB-NYLAPAZON .
/ZAK/BEVALLB_V-SORINDEX =
/ZAK/BEVALLB-SORINDEX .
/ZAK/BEVALLB_V-ALKMIN =
/ZAK/BEVALLB-ALKMIN .
/ZAK/BEVALLB_V-ACTREAD =
/ZAK/BEVALLB-ACTREAD .
/ZAK/BEVALLB_V-XMLALL =
/ZAK/BEVALLB-XMLALL .
/ZAK/BEVALLB_V-ONYBE =
/ZAK/BEVALLB-ONYBE .
/ZAK/BEVALLB_V-AFATYP =
/ZAK/BEVALLB-AFATYP .
    SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
/ZAK/BEVALLB_V-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/BEVALLB_V-ABEVTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/BEVALLB_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/BEVALLB_V-BTYPE TO
/ZAK/BEVALLB-BTYPE .
MOVE /ZAK/BEVALLB_V-ABEVAZ TO
/ZAK/BEVALLB-ABEVAZ .
MOVE /ZAK/BEVALLB_V-MANDT TO
/ZAK/BEVALLB-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/BEVALLB'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/BEVALLB TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/BEVALLB'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE /ZAK/BEVALLB-BTYPE TO
/ZAK/BEVALLBT-BTYPE .
MOVE /ZAK/BEVALLB-ABEVAZ TO
/ZAK/BEVALLBT-ABEVAZ .
MOVE SY-LANGU TO
/ZAK/BEVALLBT-LANGU .
MOVE /ZAK/BEVALLB_V-MANDT TO
/ZAK/BEVALLBT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/BEVALLBT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/BEVALLBT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/BEVALLBT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
