*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LBEVALLMVTOP.               " Global Data
  INCLUDE /ZAK/LBEVALLMVUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LBEVALLMVF00                     . " subprograms
  INCLUDE /ZAK/LBEVALLMVI00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LBEVALLMVF...               " Subprograms
* INCLUDE /ZAK/LBEVALLMVO...               " PBO-Modules
* INCLUDE /ZAK/LBEVALLMVI...               " PAI-Modules
