*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/BSET_BELNRV................................*
FORM GET_DATA_/ZAK/BSET_BELNRV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/BSET_BELNR WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/BSET_BELNRV .
/ZAK/BSET_BELNRV-MANDT =
/ZAK/BSET_BELNR-MANDT .
/ZAK/BSET_BELNRV-BUKRS =
/ZAK/BSET_BELNR-BUKRS .
/ZAK/BSET_BELNRV-BELNR =
/ZAK/BSET_BELNR-BELNR .
/ZAK/BSET_BELNRV-GJAHR =
/ZAK/BSET_BELNR-GJAHR .
/ZAK/BSET_BELNRV-BUZEI =
/ZAK/BSET_BELNR-BUZEI .
/ZAK/BSET_BELNRV-BLDAT =
/ZAK/BSET_BELNR-BLDAT .
<VIM_TOTAL_STRUC> = /ZAK/BSET_BELNRV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/BSET_BELNRV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/BSET_BELNRV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/BSET_BELNRV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BSET_BELNR WHERE
  BUKRS = /ZAK/BSET_BELNRV-BUKRS AND
  BELNR = /ZAK/BSET_BELNRV-BELNR AND
  GJAHR = /ZAK/BSET_BELNRV-GJAHR AND
  BUZEI = /ZAK/BSET_BELNRV-BUZEI .
    IF SY-SUBRC = 0.
    DELETE /ZAK/BSET_BELNR .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BSET_BELNR WHERE
  BUKRS = /ZAK/BSET_BELNRV-BUKRS AND
  BELNR = /ZAK/BSET_BELNRV-BELNR AND
  GJAHR = /ZAK/BSET_BELNRV-GJAHR AND
  BUZEI = /ZAK/BSET_BELNRV-BUZEI .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/BSET_BELNR.
    ENDIF.
/ZAK/BSET_BELNR-MANDT =
/ZAK/BSET_BELNRV-MANDT .
/ZAK/BSET_BELNR-BUKRS =
/ZAK/BSET_BELNRV-BUKRS .
/ZAK/BSET_BELNR-BELNR =
/ZAK/BSET_BELNRV-BELNR .
/ZAK/BSET_BELNR-GJAHR =
/ZAK/BSET_BELNRV-GJAHR .
/ZAK/BSET_BELNR-BUZEI =
/ZAK/BSET_BELNRV-BUZEI .
/ZAK/BSET_BELNR-BLDAT =
/ZAK/BSET_BELNRV-BLDAT .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/BSET_BELNR .
    ELSE.
    INSERT /ZAK/BSET_BELNR .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/BSET_BELNRV-UPD_FLAG,
STATUS_/ZAK/BSET_BELNRV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/BSET_BELNRV.
  SELECT SINGLE * FROM /ZAK/BSET_BELNR WHERE
BUKRS = /ZAK/BSET_BELNRV-BUKRS AND
BELNR = /ZAK/BSET_BELNRV-BELNR AND
GJAHR = /ZAK/BSET_BELNRV-GJAHR AND
BUZEI = /ZAK/BSET_BELNRV-BUZEI .
/ZAK/BSET_BELNRV-MANDT =
/ZAK/BSET_BELNR-MANDT .
/ZAK/BSET_BELNRV-BUKRS =
/ZAK/BSET_BELNR-BUKRS .
/ZAK/BSET_BELNRV-BELNR =
/ZAK/BSET_BELNR-BELNR .
/ZAK/BSET_BELNRV-GJAHR =
/ZAK/BSET_BELNR-GJAHR .
/ZAK/BSET_BELNRV-BUZEI =
/ZAK/BSET_BELNR-BUZEI .
/ZAK/BSET_BELNRV-BLDAT =
/ZAK/BSET_BELNR-BLDAT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/BSET_BELNRV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/BSET_BELNRV-BUKRS TO
/ZAK/BSET_BELNR-BUKRS .
MOVE /ZAK/BSET_BELNRV-BELNR TO
/ZAK/BSET_BELNR-BELNR .
MOVE /ZAK/BSET_BELNRV-GJAHR TO
/ZAK/BSET_BELNR-GJAHR .
MOVE /ZAK/BSET_BELNRV-BUZEI TO
/ZAK/BSET_BELNR-BUZEI .
MOVE /ZAK/BSET_BELNRV-MANDT TO
/ZAK/BSET_BELNR-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/BSET_BELNR'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/BSET_BELNR TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/BSET_BELNR'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
