PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/ADONEM_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/ADONEM_V-BUKRS .
    FIELD /ZAK/ADONEM_V-ADONEM .
    FIELD /ZAK/ADONEM_V-ADONEM_TXT .
    FIELD /ZAK/ADONEM_V-LIFNR .
    FIELD /ZAK/ADONEM_V-FIZHAT .
    FIELD /ZAK/ADONEM_V-BANKL .
    FIELD /ZAK/ADONEM_V-BANKN .
    FIELD /ZAK/ADONEM_V-SAKNR .
    FIELD /ZAK/ADONEM_V-ONREL .
    FIELD /ZAK/ADONEM_V-DATUM .
    FIELD /ZAK/ADONEM_V-UZEIT .
    FIELD /ZAK/ADONEM_V-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/ADONEM_V-BUKRS .
    FIELD /ZAK/ADONEM_V-ADONEM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
