*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LONY_NYLAP_VTOP.               " Global Data
  INCLUDE /ZAK/LONY_NYLAP_VUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LONY_NYLAP_VF00                     . " subprograms
  INCLUDE /ZAK/LONY_NYLAP_VI00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LONY_NYLAP_VF...               " Subprograms
* INCLUDE /ZAK/LONY_NYLAP_VO...               " PBO-Modules
* INCLUDE /ZAK/LONY_NYLAP_VI...               " PAI-Modules

INCLUDE /ZAK/LONY_NYLAP_VF01.
