*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LBUKRS_SEGMTOP.               " Global Data
  INCLUDE /ZAK/LBUKRS_SEGMUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LBUKRS_SEGMF00                     . " subprograms
  INCLUDE /ZAK/LBUKRS_SEGMI00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LBUKRS_SEGMF...               " Subprograms
* INCLUDE /ZAK/LBUKRS_SEGMO...               " PBO-Modules
* INCLUDE /ZAK/LBUKRS_SEGMI...               " PAI-Modules

INCLUDE /ZAK/LBUKRS_SEGMF01.
