*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/BEVALL_V....................................*
FORM GET_DATA_/ZAK/BEVALL_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/BEVALL WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/BEVALL_V .
/ZAK/BEVALL_V-MANDT =
/ZAK/BEVALL-MANDT .
/ZAK/BEVALL_V-BUKRS =
/ZAK/BEVALL-BUKRS .
/ZAK/BEVALL_V-BTYPE =
/ZAK/BEVALL-BTYPE .
/ZAK/BEVALL_V-DATBI =
/ZAK/BEVALL-DATBI .
/ZAK/BEVALL_V-DATAB =
/ZAK/BEVALL-DATAB .
/ZAK/BEVALL_V-BTYPEE =
/ZAK/BEVALL-BTYPEE .
/ZAK/BEVALL_V-BTYPEA =
/ZAK/BEVALL-BTYPEA .
/ZAK/BEVALL_V-BIDOSZ =
/ZAK/BEVALL-BIDOSZ .
/ZAK/BEVALL_V-BTYPART =
/ZAK/BEVALL-BTYPART .
/ZAK/BEVALL_V-STRANS =
/ZAK/BEVALL-STRANS .
/ZAK/BEVALL_V-OMREL =
/ZAK/BEVALL-OMREL .
/ZAK/BEVALL_V-OLWSTE =
/ZAK/BEVALL-OLWSTE .
/ZAK/BEVALL_V-KATASZ =
/ZAK/BEVALL-KATASZ .
/ZAK/BEVALL_V-M02KNO =
/ZAK/BEVALL-M02KNO .
/ZAK/BEVALL_V-BLART =
/ZAK/BEVALL-BLART .
/ZAK/BEVALL_V-BDAY =
/ZAK/BEVALL-BDAY .
/ZAK/BEVALL_V-KIUTALAS =
/ZAK/BEVALL-KIUTALAS .
/ZAK/BEVALL_V-ARTYPE =
/ZAK/BEVALL-ARTYPE .
/ZAK/BEVALL_V-ARKONT =
/ZAK/BEVALL-ARKONT .
/ZAK/BEVALL_V-ARKOSTL =
/ZAK/BEVALL-ARKOSTL .
/ZAK/BEVALL_V-ARAUFNR =
/ZAK/BEVALL-ARAUFNR .
/ZAK/BEVALL_V-PADOSZ =
/ZAK/BEVALL-PADOSZ .
/ZAK/BEVALL_V-DATUM =
/ZAK/BEVALL-DATUM .
/ZAK/BEVALL_V-UZEIT =
/ZAK/BEVALL-UZEIT .
/ZAK/BEVALL_V-UNAME =
/ZAK/BEVALL-UNAME .
    SELECT SINGLE * FROM /ZAK/BEVALLT WHERE
BUKRS = /ZAK/BEVALL-BUKRS AND
BTYPE = /ZAK/BEVALL-BTYPE AND
DATBI = /ZAK/BEVALL-DATBI AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
/ZAK/BEVALL_V-BTEXT =
/ZAK/BEVALLT-BTEXT .
    ENDIF.
<VIM_TOTAL_STRUC> = /ZAK/BEVALL_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/BEVALL_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/BEVALL_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/BEVALL_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BEVALL WHERE
  BUKRS = /ZAK/BEVALL_V-BUKRS AND
  BTYPE = /ZAK/BEVALL_V-BTYPE AND
  DATBI = /ZAK/BEVALL_V-DATBI .
    IF SY-SUBRC = 0.
    DELETE /ZAK/BEVALL .
    ENDIF.
    DELETE FROM /ZAK/BEVALLT WHERE
    BUKRS = /ZAK/BEVALL-BUKRS AND
    BTYPE = /ZAK/BEVALL-BTYPE AND
    DATBI = /ZAK/BEVALL-DATBI .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BEVALL WHERE
  BUKRS = /ZAK/BEVALL_V-BUKRS AND
  BTYPE = /ZAK/BEVALL_V-BTYPE AND
  DATBI = /ZAK/BEVALL_V-DATBI .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/BEVALL.
    ENDIF.
/ZAK/BEVALL-MANDT =
/ZAK/BEVALL_V-MANDT .
/ZAK/BEVALL-BUKRS =
/ZAK/BEVALL_V-BUKRS .
/ZAK/BEVALL-BTYPE =
/ZAK/BEVALL_V-BTYPE .
/ZAK/BEVALL-DATBI =
/ZAK/BEVALL_V-DATBI .
/ZAK/BEVALL-DATAB =
/ZAK/BEVALL_V-DATAB .
/ZAK/BEVALL-BTYPEE =
/ZAK/BEVALL_V-BTYPEE .
/ZAK/BEVALL-BTYPEA =
/ZAK/BEVALL_V-BTYPEA .
/ZAK/BEVALL-BIDOSZ =
/ZAK/BEVALL_V-BIDOSZ .
/ZAK/BEVALL-BTYPART =
/ZAK/BEVALL_V-BTYPART .
/ZAK/BEVALL-STRANS =
/ZAK/BEVALL_V-STRANS .
/ZAK/BEVALL-OMREL =
/ZAK/BEVALL_V-OMREL .
/ZAK/BEVALL-OLWSTE =
/ZAK/BEVALL_V-OLWSTE .
/ZAK/BEVALL-KATASZ =
/ZAK/BEVALL_V-KATASZ .
/ZAK/BEVALL-M02KNO =
/ZAK/BEVALL_V-M02KNO .
/ZAK/BEVALL-BLART =
/ZAK/BEVALL_V-BLART .
/ZAK/BEVALL-BDAY =
/ZAK/BEVALL_V-BDAY .
/ZAK/BEVALL-KIUTALAS =
/ZAK/BEVALL_V-KIUTALAS .
/ZAK/BEVALL-ARTYPE =
/ZAK/BEVALL_V-ARTYPE .
/ZAK/BEVALL-ARKONT =
/ZAK/BEVALL_V-ARKONT .
/ZAK/BEVALL-ARKOSTL =
/ZAK/BEVALL_V-ARKOSTL .
/ZAK/BEVALL-ARAUFNR =
/ZAK/BEVALL_V-ARAUFNR .
/ZAK/BEVALL-PADOSZ =
/ZAK/BEVALL_V-PADOSZ .
/ZAK/BEVALL-DATUM =
/ZAK/BEVALL_V-DATUM .
/ZAK/BEVALL-UZEIT =
/ZAK/BEVALL_V-UZEIT .
/ZAK/BEVALL-UNAME =
/ZAK/BEVALL_V-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/BEVALL ##WARN_OK.
    ELSE.
    INSERT /ZAK/BEVALL .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM /ZAK/BEVALLT WHERE
    BUKRS = /ZAK/BEVALL-BUKRS AND
    BTYPE = /ZAK/BEVALL-BTYPE AND
    DATBI = /ZAK/BEVALL-DATBI AND
    LANGU = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR /ZAK/BEVALLT.
/ZAK/BEVALLT-BUKRS =
/ZAK/BEVALL-BUKRS .
/ZAK/BEVALLT-BTYPE =
/ZAK/BEVALL-BTYPE .
/ZAK/BEVALLT-DATBI =
/ZAK/BEVALL-DATBI .
/ZAK/BEVALLT-LANGU =
SY-LANGU .
      ENDIF.
/ZAK/BEVALLT-BTEXT =
/ZAK/BEVALL_V-BTEXT .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/BEVALLT ##WARN_OK.
    ELSE.
    INSERT /ZAK/BEVALLT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/BEVALL_V-UPD_FLAG,
STATUS_/ZAK/BEVALL_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/BEVALL_V.
  SELECT SINGLE * FROM /ZAK/BEVALL WHERE
BUKRS = /ZAK/BEVALL_V-BUKRS AND
BTYPE = /ZAK/BEVALL_V-BTYPE AND
DATBI = /ZAK/BEVALL_V-DATBI .
/ZAK/BEVALL_V-MANDT =
/ZAK/BEVALL-MANDT .
/ZAK/BEVALL_V-BUKRS =
/ZAK/BEVALL-BUKRS .
/ZAK/BEVALL_V-BTYPE =
/ZAK/BEVALL-BTYPE .
/ZAK/BEVALL_V-DATBI =
/ZAK/BEVALL-DATBI .
/ZAK/BEVALL_V-DATAB =
/ZAK/BEVALL-DATAB .
/ZAK/BEVALL_V-BTYPEE =
/ZAK/BEVALL-BTYPEE .
/ZAK/BEVALL_V-BTYPEA =
/ZAK/BEVALL-BTYPEA .
/ZAK/BEVALL_V-BIDOSZ =
/ZAK/BEVALL-BIDOSZ .
/ZAK/BEVALL_V-BTYPART =
/ZAK/BEVALL-BTYPART .
/ZAK/BEVALL_V-STRANS =
/ZAK/BEVALL-STRANS .
/ZAK/BEVALL_V-OMREL =
/ZAK/BEVALL-OMREL .
/ZAK/BEVALL_V-OLWSTE =
/ZAK/BEVALL-OLWSTE .
/ZAK/BEVALL_V-KATASZ =
/ZAK/BEVALL-KATASZ .
/ZAK/BEVALL_V-M02KNO =
/ZAK/BEVALL-M02KNO .
/ZAK/BEVALL_V-BLART =
/ZAK/BEVALL-BLART .
/ZAK/BEVALL_V-BDAY =
/ZAK/BEVALL-BDAY .
/ZAK/BEVALL_V-KIUTALAS =
/ZAK/BEVALL-KIUTALAS .
/ZAK/BEVALL_V-ARTYPE =
/ZAK/BEVALL-ARTYPE .
/ZAK/BEVALL_V-ARKONT =
/ZAK/BEVALL-ARKONT .
/ZAK/BEVALL_V-ARKOSTL =
/ZAK/BEVALL-ARKOSTL .
/ZAK/BEVALL_V-ARAUFNR =
/ZAK/BEVALL-ARAUFNR .
/ZAK/BEVALL_V-PADOSZ =
/ZAK/BEVALL-PADOSZ .
/ZAK/BEVALL_V-DATUM =
/ZAK/BEVALL-DATUM .
/ZAK/BEVALL_V-UZEIT =
/ZAK/BEVALL-UZEIT .
/ZAK/BEVALL_V-UNAME =
/ZAK/BEVALL-UNAME .
    SELECT SINGLE * FROM /ZAK/BEVALLT WHERE
BUKRS = /ZAK/BEVALL-BUKRS AND
BTYPE = /ZAK/BEVALL-BTYPE AND
DATBI = /ZAK/BEVALL-DATBI AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
/ZAK/BEVALL_V-BTEXT =
/ZAK/BEVALLT-BTEXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/BEVALL_V-BTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/BEVALL_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/BEVALL_V-BUKRS TO
/ZAK/BEVALL-BUKRS .
MOVE /ZAK/BEVALL_V-BTYPE TO
/ZAK/BEVALL-BTYPE .
MOVE /ZAK/BEVALL_V-DATBI TO
/ZAK/BEVALL-DATBI .
MOVE /ZAK/BEVALL_V-MANDT TO
/ZAK/BEVALL-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/BEVALL'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/BEVALL TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/BEVALL'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE /ZAK/BEVALL-BUKRS TO
/ZAK/BEVALLT-BUKRS .
MOVE /ZAK/BEVALL-BTYPE TO
/ZAK/BEVALLT-BTYPE .
MOVE /ZAK/BEVALL-DATBI TO
/ZAK/BEVALLT-DATBI .
MOVE SY-LANGU TO
/ZAK/BEVALLT-LANGU .
MOVE /ZAK/BEVALL_V-MANDT TO
/ZAK/BEVALLT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/BEVALLT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/BEVALLT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/BEVALLT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
