*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LUREPFELD_MVTOP.              " Global Data
  INCLUDE /ZAK/LUREPFELD_MVUXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LUREPFELD_MVF00                    . " subprograms
  INCLUDE /ZAK/LUREPFELD_MVI00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LUREPFELD_MVF...              " Subprograms
* INCLUDE /ZAK/LUREPFELD_MVO...              " PBO-Modules
* INCLUDE /ZAK/LUREPFELD_MVI...              " PAI-Modules
