
PROCESS BEFORE OUTPUT.

  MODULE PBO_9001.
*
PROCESS AFTER INPUT.

  MODULE EXIT_9001 AT EXIT-COMMAND.
  CHAIN.
    FIELD /ZAK/ADONSZA-BUDAT   MODULE CHECK_BUDAT.
*++BG 2006/06/23
    FIELD /ZAK/ADONSZA-BTYPE   MODULE CHECK_BTYPE.
*--BG 2006/06/23
    FIELD /ZAK/ADONSZA-ADONEM  MODULE CHECK_ADONEM.
    FIELD /ZAK/ADONSZA-ESDAT   MODULE CHECK_ESDAT.
    FIELD /ZAK/ADONSZA-WRBTR   MODULE CHECK_WRBTR.
    FIELD /ZAK/ADONSZA-KOTEL   MODULE CHECK_KOTEL.
  ENDCHAIN.

  MODULE PAI_9001.
