*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/ONY_NYLAP_V.................................*
FORM GET_DATA_/ZAK/ONY_NYLAP_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/ONY_NYLAP WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/ONY_NYLAP_V .
/ZAK/ONY_NYLAP_V-MANDT =
/ZAK/ONY_NYLAP-MANDT .
/ZAK/ONY_NYLAP_V-BTYPE =
/ZAK/ONY_NYLAP-BTYPE .
/ZAK/ONY_NYLAP_V-MWSKZ =
/ZAK/ONY_NYLAP-MWSKZ .
/ZAK/ONY_NYLAP_V-KTOSL =
/ZAK/ONY_NYLAP-KTOSL .
/ZAK/ONY_NYLAP_V-NYLAP =
/ZAK/ONY_NYLAP-NYLAP .
/ZAK/ONY_NYLAP_V-AS4USER =
/ZAK/ONY_NYLAP-AS4USER .
/ZAK/ONY_NYLAP_V-AS4DATE =
/ZAK/ONY_NYLAP-AS4DATE .
/ZAK/ONY_NYLAP_V-AS4TIME =
/ZAK/ONY_NYLAP-AS4TIME .
<VIM_TOTAL_STRUC> = /ZAK/ONY_NYLAP_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/ONY_NYLAP_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/ONY_NYLAP_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/ONY_NYLAP_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/ONY_NYLAP WHERE
  BTYPE = /ZAK/ONY_NYLAP_V-BTYPE AND
  MWSKZ = /ZAK/ONY_NYLAP_V-MWSKZ AND
  KTOSL = /ZAK/ONY_NYLAP_V-KTOSL .
    IF SY-SUBRC = 0.
    DELETE /ZAK/ONY_NYLAP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/ONY_NYLAP WHERE
  BTYPE = /ZAK/ONY_NYLAP_V-BTYPE AND
  MWSKZ = /ZAK/ONY_NYLAP_V-MWSKZ AND
  KTOSL = /ZAK/ONY_NYLAP_V-KTOSL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/ONY_NYLAP.
    ENDIF.
/ZAK/ONY_NYLAP-MANDT =
/ZAK/ONY_NYLAP_V-MANDT .
/ZAK/ONY_NYLAP-BTYPE =
/ZAK/ONY_NYLAP_V-BTYPE .
/ZAK/ONY_NYLAP-MWSKZ =
/ZAK/ONY_NYLAP_V-MWSKZ .
/ZAK/ONY_NYLAP-KTOSL =
/ZAK/ONY_NYLAP_V-KTOSL .
/ZAK/ONY_NYLAP-NYLAP =
/ZAK/ONY_NYLAP_V-NYLAP .
/ZAK/ONY_NYLAP-AS4USER =
/ZAK/ONY_NYLAP_V-AS4USER .
/ZAK/ONY_NYLAP-AS4DATE =
/ZAK/ONY_NYLAP_V-AS4DATE .
/ZAK/ONY_NYLAP-AS4TIME =
/ZAK/ONY_NYLAP_V-AS4TIME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/ONY_NYLAP .
    ELSE.
    INSERT /ZAK/ONY_NYLAP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/ONY_NYLAP_V-UPD_FLAG,
STATUS_/ZAK/ONY_NYLAP_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/ONY_NYLAP_V.
  SELECT SINGLE * FROM /ZAK/ONY_NYLAP WHERE
BTYPE = /ZAK/ONY_NYLAP_V-BTYPE AND
MWSKZ = /ZAK/ONY_NYLAP_V-MWSKZ AND
KTOSL = /ZAK/ONY_NYLAP_V-KTOSL .
/ZAK/ONY_NYLAP_V-MANDT =
/ZAK/ONY_NYLAP-MANDT .
/ZAK/ONY_NYLAP_V-BTYPE =
/ZAK/ONY_NYLAP-BTYPE .
/ZAK/ONY_NYLAP_V-MWSKZ =
/ZAK/ONY_NYLAP-MWSKZ .
/ZAK/ONY_NYLAP_V-KTOSL =
/ZAK/ONY_NYLAP-KTOSL .
/ZAK/ONY_NYLAP_V-NYLAP =
/ZAK/ONY_NYLAP-NYLAP .
/ZAK/ONY_NYLAP_V-AS4USER =
/ZAK/ONY_NYLAP-AS4USER .
/ZAK/ONY_NYLAP_V-AS4DATE =
/ZAK/ONY_NYLAP-AS4DATE .
/ZAK/ONY_NYLAP_V-AS4TIME =
/ZAK/ONY_NYLAP-AS4TIME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/ONY_NYLAP_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/ONY_NYLAP_V-BTYPE TO
/ZAK/ONY_NYLAP-BTYPE .
MOVE /ZAK/ONY_NYLAP_V-MWSKZ TO
/ZAK/ONY_NYLAP-MWSKZ .
MOVE /ZAK/ONY_NYLAP_V-KTOSL TO
/ZAK/ONY_NYLAP-KTOSL .
MOVE /ZAK/ONY_NYLAP_V-MANDT TO
/ZAK/ONY_NYLAP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/ONY_NYLAP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/ONY_NYLAP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/ONY_NYLAP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
