FUNCTION /ZAK/CONV_DATE_USER_2_INTERNAL.
*"----------------------------------------------------------------------
*"*"Lokális interfész:
*"  IMPORTING
*"     REFERENCE(I_INPUT) TYPE  CHAR50
*"     REFERENCE(I_USER) TYPE  UNAME
*"  EXPORTING
*"     REFERENCE(E_DATE) TYPE  DATE
*"----------------------------------------------------------------------

  DATA LT_USERS LIKE USDEF OCCURS 0 WITH HEADER LINE.
  DATA L_INPUT TYPE CHAR40.


  REFRESH LT_USERS.
  MOVE SY-MANDT TO LT_USERS-MANDT.
  MOVE I_USER   TO LT_USERS-BNAME.
  APPEND LT_USERS.

  CALL FUNCTION 'SUSR_GET_USER_DEFAULTS'
    EXPORTING
      LANGU = 'E'
    TABLES
      USERS = LT_USERS.

  MOVE I_INPUT TO L_INPUT.
  REPLACE ALL OCCURRENCES OF '.' IN L_INPUT WITH ''.
  REPLACE ALL OCCURRENCES OF '/' IN L_INPUT WITH ''.
  REPLACE ALL OCCURRENCES OF '-' IN L_INPUT WITH ''.

  READ TABLE LT_USERS INDEX 1.
  CLEAR E_DATE.
* Nap
  IF LT_USERS-DATFM(2) EQ 'DD'.
    E_DATE+6(2) = L_INPUT(2).
  ELSEIF LT_USERS-DATFM+3(2) EQ 'DD'.
    E_DATE+6(2) = L_INPUT+2(2).
  ELSEIF LT_USERS-DATFM+8(2) EQ 'DD'.
    E_DATE+6(2) = L_INPUT+6(2).
  ENDIF.
* Hónap
  IF LT_USERS-DATFM(2) EQ 'MM'.
    E_DATE+4(2) = L_INPUT(2).
  ELSEIF LT_USERS-DATFM+3(2) EQ 'MM'.
    E_DATE+4(2) = L_INPUT+2(2).
  ELSEIF LT_USERS-DATFM+5(2) EQ 'MM'.
    E_DATE+4(2) = L_INPUT+4(2).
  ENDIF.
* Év
  IF LT_USERS-DATFM(4) EQ 'YYYY'.
    E_DATE(4) = L_INPUT(4).
  ELSEIF LT_USERS-DATFM+6(4) EQ 'YYYY'.
    E_DATE(4) = L_INPUT+4(4).
  ENDIF.


ENDFUNCTION.
