PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/GET_IDSZ_MV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/GET_IDSZ_MV-BUKRS .
    FIELD /ZAK/GET_IDSZ_MV-GSBER .
    FIELD /ZAK/GET_IDSZ_MV-PRCTR .
    FIELD /ZAK/GET_IDSZ_MV-AFABK .
    FIELD /ZAK/GET_IDSZ_MV-EUFLG .
    FIELD /ZAK/GET_IDSZ_MV-GJAHR .
    FIELD /ZAK/GET_IDSZ_MV-MONAT .
    FIELD /ZAK/GET_IDSZ_MV-DATUM .
    FIELD /ZAK/GET_IDSZ_MV-UZEIT .
    FIELD /ZAK/GET_IDSZ_MV-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/GET_IDSZ_MV-BUKRS .
    FIELD /ZAK/GET_IDSZ_MV-GSBER .
    FIELD /ZAK/GET_IDSZ_MV-PRCTR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
