*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/LIFNR_CST_V.................................*
FORM GET_DATA_/ZAK/LIFNR_CST_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/LIFNR_CST WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/LIFNR_CST_V .
/ZAK/LIFNR_CST_V-MANDT =
/ZAK/LIFNR_CST-MANDT .
/ZAK/LIFNR_CST_V-LIFNR =
/ZAK/LIFNR_CST-LIFNR .
/ZAK/LIFNR_CST_V-DATBI =
/ZAK/LIFNR_CST-DATBI .
/ZAK/LIFNR_CST_V-DATAB =
/ZAK/LIFNR_CST-DATAB .
/ZAK/LIFNR_CST_V-AS4USER =
/ZAK/LIFNR_CST-AS4USER .
/ZAK/LIFNR_CST_V-AS4DATE =
/ZAK/LIFNR_CST-AS4DATE .
/ZAK/LIFNR_CST_V-AS4TIME =
/ZAK/LIFNR_CST-AS4TIME .
    SELECT SINGLE * FROM LFA1 WHERE
LIFNR = /ZAK/LIFNR_CST-LIFNR .
    IF SY-SUBRC EQ 0.
/ZAK/LIFNR_CST_V-NAME1 =
LFA1-NAME1 .
/ZAK/LIFNR_CST_V-STCD3 =
LFA1-STCD3 .
    ENDIF.
<VIM_TOTAL_STRUC> = /ZAK/LIFNR_CST_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/LIFNR_CST_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/LIFNR_CST_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/LIFNR_CST_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/LIFNR_CST WHERE
  LIFNR = /ZAK/LIFNR_CST_V-LIFNR AND
  DATBI = /ZAK/LIFNR_CST_V-DATBI .
    IF SY-SUBRC = 0.
    DELETE /ZAK/LIFNR_CST .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/LIFNR_CST WHERE
  LIFNR = /ZAK/LIFNR_CST_V-LIFNR AND
  DATBI = /ZAK/LIFNR_CST_V-DATBI .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/LIFNR_CST.
    ENDIF.
/ZAK/LIFNR_CST-MANDT =
/ZAK/LIFNR_CST_V-MANDT .
/ZAK/LIFNR_CST-LIFNR =
/ZAK/LIFNR_CST_V-LIFNR .
/ZAK/LIFNR_CST-DATBI =
/ZAK/LIFNR_CST_V-DATBI .
/ZAK/LIFNR_CST-DATAB =
/ZAK/LIFNR_CST_V-DATAB .
/ZAK/LIFNR_CST-AS4USER =
/ZAK/LIFNR_CST_V-AS4USER .
/ZAK/LIFNR_CST-AS4DATE =
/ZAK/LIFNR_CST_V-AS4DATE .
/ZAK/LIFNR_CST-AS4TIME =
/ZAK/LIFNR_CST_V-AS4TIME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/LIFNR_CST .
    ELSE.
    INSERT /ZAK/LIFNR_CST .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/LIFNR_CST_V-UPD_FLAG,
STATUS_/ZAK/LIFNR_CST_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/LIFNR_CST_V.
  SELECT SINGLE * FROM /ZAK/LIFNR_CST WHERE
LIFNR = /ZAK/LIFNR_CST_V-LIFNR AND
DATBI = /ZAK/LIFNR_CST_V-DATBI .
/ZAK/LIFNR_CST_V-MANDT =
/ZAK/LIFNR_CST-MANDT .
/ZAK/LIFNR_CST_V-LIFNR =
/ZAK/LIFNR_CST-LIFNR .
/ZAK/LIFNR_CST_V-DATBI =
/ZAK/LIFNR_CST-DATBI .
/ZAK/LIFNR_CST_V-DATAB =
/ZAK/LIFNR_CST-DATAB .
/ZAK/LIFNR_CST_V-AS4USER =
/ZAK/LIFNR_CST-AS4USER .
/ZAK/LIFNR_CST_V-AS4DATE =
/ZAK/LIFNR_CST-AS4DATE .
/ZAK/LIFNR_CST_V-AS4TIME =
/ZAK/LIFNR_CST-AS4TIME .
    SELECT SINGLE * FROM LFA1 WHERE
LIFNR = /ZAK/LIFNR_CST-LIFNR .
    IF SY-SUBRC EQ 0.
/ZAK/LIFNR_CST_V-NAME1 =
LFA1-NAME1 .
/ZAK/LIFNR_CST_V-STCD3 =
LFA1-STCD3 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/LIFNR_CST_V-NAME1 .
      CLEAR /ZAK/LIFNR_CST_V-STCD3 .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/LIFNR_CST_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/LIFNR_CST_V-LIFNR TO
/ZAK/LIFNR_CST-LIFNR .
MOVE /ZAK/LIFNR_CST_V-DATBI TO
/ZAK/LIFNR_CST-DATBI .
MOVE /ZAK/LIFNR_CST_V-MANDT TO
/ZAK/LIFNR_CST-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/LIFNR_CST'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/LIFNR_CST TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/LIFNR_CST'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/ZAK/LIFNR_CST_V USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/ZAK/LIFNR_CST-MANDT =
/ZAK/LIFNR_CST_V-MANDT .
/ZAK/LIFNR_CST-LIFNR =
/ZAK/LIFNR_CST_V-LIFNR .
/ZAK/LIFNR_CST-DATBI =
/ZAK/LIFNR_CST_V-DATBI .
/ZAK/LIFNR_CST-DATAB =
/ZAK/LIFNR_CST_V-DATAB .
/ZAK/LIFNR_CST-AS4USER =
/ZAK/LIFNR_CST_V-AS4USER .
/ZAK/LIFNR_CST-AS4DATE =
/ZAK/LIFNR_CST_V-AS4DATE .
/ZAK/LIFNR_CST-AS4TIME =
/ZAK/LIFNR_CST_V-AS4TIME .
    SELECT SINGLE * FROM LFA1 WHERE
LIFNR = /ZAK/LIFNR_CST-LIFNR .
    IF SY-SUBRC EQ 0.
/ZAK/LIFNR_CST_V-NAME1 =
LFA1-NAME1 .
/ZAK/LIFNR_CST_V-STCD3 =
LFA1-STCD3 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/LIFNR_CST_V-NAME1 .
      CLEAR /ZAK/LIFNR_CST_V-STCD3 .
    ENDIF.
ENDFORM.
