FUNCTION /ZAK/AFAR_BOOK_EXCEL.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(I_BUKRS) TYPE  BUKRS OPTIONAL
*"     VALUE(I_BTYPE) TYPE  /ZAK/BTYPE OPTIONAL
*"     VALUE(I_GJAHR) TYPE  GJAHR OPTIONAL
*"     VALUE(I_MONAT) TYPE  MONAT OPTIONAL
*"     VALUE(I_INDEX) TYPE  /ZAK/INDEX OPTIONAL
*"  EXCEPTIONS
*"      MISSING_INPUT
*"      ERROR_AFAR_BOOK
*"      ERROR_DOWNLOAD_FILE
*"      EMPTY_FILE
*"      ERROR_DATUM
*"----------------------------------------------------------------------

  CONSTANTS C_BIZ_AZON TYPE /ZAK/EXCE_BIZ_AZON VALUE '1'.
  CONSTANTS C_BF_SA    TYPE /ZAK/EXCE_BIZ_FAJTA VALUE 'SP'.
  CONSTANTS C_BF_E1    TYPE /ZAK/EXCE_BIZ_FAJTA VALUE 'E1'.
  CONSTANTS C_SZOVEG   TYPE /ZAK/EXCE_FEJSZOVEG VALUE 'ÁFA arányosítás'.

  DATA: BEGIN OF I_EXCEL OCCURS 20.
*++S4HANA#01.
*          INCLUDE STRUCTURE /ZAK/SZJAEXCELV2.
          INCLUDE TYPE /ZAK/SZJAEXCELV2.
*--S4HANA#01.
  DATA: END OF I_EXCEL.

  DATA: V_SUBRC LIKE SY-SUBRC.

*++S4HANA#01.
*  DATA I_AFA_ARBOOK LIKE /ZAK/AFA_ARBOOK OCCURS 0.
  DATA LT_I_AFA_ARBOOK TYPE STANDARD TABLE OF /ZAK/AFA_ARBOOK .
*--S4HANA#01.
  DATA W_AFA_ARBOOK LIKE /ZAK/AFA_ARBOOK.


  TYPES: BEGIN OF T_BOOK,
           HKONT   TYPE HKONT,
           FIELD_N TYPE /ZAK/FIELDN,
           WAERS   TYPE WAERS,
         END OF T_BOOK.

*++S4HANA#01.
*  DATA I_BOOK TYPE T_BOOK OCCURS 0.
  DATA LT_I_BOOK TYPE STANDARD TABLE OF T_BOOK .
*--S4HANA#01.
  DATA W_BOOK TYPE T_BOOK.

  DATA V_FIRST_DAY LIKE SY-DATUM.
  DATA V_LAST_DAY LIKE SY-DATUM.

  DATA: W_EXCEL1 TYPE /ZAK/SZJAEXCELV2,
        W_EXCEL2 TYPE /ZAK/SZJAEXCELV2.

  DATA V_BIZ_TETEL TYPE /ZAK/EXCE_BIZ_TETEL.

  DATA V_NEXT_MONTH(6).

* If any parameter is empty raise an error
  IF I_BUKRS IS INITIAL OR
     I_BTYPE IS INITIAL OR
     I_GJAHR IS INITIAL OR
     I_MONAT IS INITIAL OR
     I_INDEX IS INITIAL.
    MESSAGE E251(/ZAK/ZAK) RAISING MISSING_INPUT.
*   Missing import parameter for proportional posting!
  ELSE.
*++S4HANA#01.
*    SELECT * INTO TABLE I_AFA_ARBOOK FROM  /ZAK/AFA_ARBOOK
    SELECT * INTO TABLE LT_I_AFA_ARBOOK FROM  /ZAK/AFA_ARBOOK
*--S4HANA#01.
          WHERE  BUKRS   = I_BUKRS
          AND    BTYPE   = I_BTYPE
          AND    GJAHR   = I_GJAHR
          AND    MONAT   = I_MONAT
          AND    ZINDEX  = I_INDEX.
    IF SY-SUBRC NE 0.
      EXIT.
    ELSE.
*++S4HANA#01.
*      LOOP AT I_AFA_ARBOOK INTO W_AFA_ARBOOK.
      LOOP AT LT_I_AFA_ARBOOK INTO W_AFA_ARBOOK.
*--S4HANA#01.
        CLEAR W_BOOK.
        MOVE-CORRESPONDING W_AFA_ARBOOK TO W_BOOK.
*++S4HANA#01.
*        COLLECT W_BOOK INTO I_BOOK.
        COLLECT W_BOOK INTO LT_I_BOOK.
*--S4HANA#01.
      ENDLOOP.
*++S4HANA#01.
*      DELETE I_BOOK WHERE FIELD_N IS INITIAL.
*      IF I_BOOK[] IS INITIAL.
      DELETE LT_I_BOOK WHERE FIELD_N IS INITIAL.
      IF LT_I_BOOK[] IS INITIAL.
*--S4HANA#01.
        EXIT.
      ENDIF.
    ENDIF.
  ENDIF.

* Determine the first and last day
  CONCATENATE I_GJAHR I_MONAT '01' INTO V_FIRST_DAY.
  CALL FUNCTION 'LAST_DAY_OF_MONTHS'  "#EC CI_USAGE_OK[2296016]
    EXPORTING
      DAY_IN            = V_FIRST_DAY
    IMPORTING
      LAST_DAY_OF_MONTH = V_LAST_DAY
    EXCEPTIONS
      DAY_IN_NO_DATE    = 1
      OTHERS            = 2.

  IF SY-SUBRC <> 0.
    MESSAGE E252(/ZAK/ZAK) WITH V_FIRST_DAY RAISING ERROR_DATUM.
*   Error while determining the last day of the month! (&)
  ENDIF.

* Determine whether a setting exists for the offset account:
*++S4HANA#01.
*  SELECT SINGLE * INTO W_/ZAK/BEVALL
*                  FROM /ZAK/BEVALL
*                 WHERE BUKRS EQ I_BUKRS
*                   AND BTYPE EQ I_BTYPE
*                   AND DATBI GE V_LAST_DAY.
  SELECT * INTO W_/ZAK/BEVALL
              FROM /ZAK/BEVALL UP TO 1 ROWS
             WHERE BUKRS EQ I_BUKRS
               AND BTYPE EQ I_BTYPE
               AND DATBI GE V_LAST_DAY
             ORDER BY PRIMARY KEY.
  ENDSELECT.
*--S4HANA#01.
  IF SY-SUBRC NE 0 OR W_/ZAK/BEVALL-ARKONT IS INITIAL.
    MESSAGE E253(/ZAK/ZAK) RAISING ERROR_AFAR_BOOK.
*   Missing configuration for VAT proportion posting!
  ENDIF.

* If December, determine the next period
  IF I_MONAT EQ '12'.
    V_NEXT_MONTH = I_GJAHR + 1.
    V_NEXT_MONTH+4(2) = '01'.
  ENDIF.

  CLEAR V_BIZ_TETEL.

*++S4HANA#01.
*  LOOP AT I_BOOK INTO W_BOOK.
  LOOP AT LT_I_BOOK INTO W_BOOK.
*--S4HANA#01.
    CLEAR: W_EXCEL1, W_EXCEL2.
*   Document identifier
    MOVE C_BIZ_AZON TO W_EXCEL1-BIZ_AZON.
    MOVE C_BIZ_AZON TO W_EXCEL2-BIZ_AZON.
*   Document/Item number
    ADD 1 TO V_BIZ_TETEL.
    MOVE V_BIZ_TETEL TO W_EXCEL1-BIZ_TETEL.
    ADD 1 TO V_BIZ_TETEL.
    MOVE V_BIZ_TETEL TO W_EXCEL2-BIZ_TETEL.
*   Document date
    WRITE V_LAST_DAY TO W_EXCEL1-BIZ_DATUM.
    WRITE V_LAST_DAY TO W_EXCEL2-BIZ_DATUM.
*   Posting date
    WRITE SY-DATUM TO  W_EXCEL1-KONYV_DAT.
    WRITE SY-DATUM TO  W_EXCEL2-KONYV_DAT.
*   Bizonylat fajta
    IF I_MONAT EQ '12' AND W_EXCEL1-KONYV_DAT(6) EQ V_NEXT_MONTH.
      MOVE C_BF_E1 TO  W_EXCEL1-BF.
      MOVE C_BF_E1 TO  W_EXCEL2-BF.
    ELSE.
      MOVE C_BF_SA TO  W_EXCEL1-BF.
      MOVE C_BF_SA TO  W_EXCEL2-BF.
    ENDIF.
*   Period
    MOVE SY-DATUM+4(2) TO W_EXCEL1-HO.
    MOVE SY-DATUM+4(2) TO W_EXCEL2-HO.
*   Currency
    MOVE W_BOOK-WAERS TO W_EXCEL1-PENZNEM.
    MOVE W_BOOK-WAERS TO W_EXCEL2-PENZNEM.
*   Header and item text:
    MOVE C_SZOVEG TO W_EXCEL1-FEJSZOVEG.
    MOVE C_SZOVEG TO W_EXCEL2-FEJSZOVEG.
    MOVE C_SZOVEG TO W_EXCEL1-SZOVEG.
    MOVE C_SZOVEG TO W_EXCEL2-SZOVEG.

*   Amount
    WRITE W_BOOK-FIELD_N CURRENCY W_BOOK-WAERS  TO W_EXCEL1-OSSZEG
                             NO-GROUPING
                             NO-SIGN.
    W_EXCEL2-OSSZEG = W_EXCEL1-OSSZEG.

*   D/C code
    IF W_BOOK-FIELD_N > 0.
      MOVE '40' TO W_EXCEL1-KK.
      MOVE W_/ZAK/BEVALL-ARKONT TO W_EXCEL1-FOKONYV.
*++1065 2010.02.04 BG
      MOVE W_/ZAK/BEVALL-ARKOSTL TO W_EXCEL1-KTGH.
      MOVE W_/ZAK/BEVALL-ARAUFNR TO W_EXCEL1-RENDELES.
*--1065 2010.02.04 BG
      MOVE '50' TO W_EXCEL2-KK.
      MOVE W_BOOK-HKONT TO W_EXCEL2-FOKONYV.
    ELSE.
      MOVE '50' TO W_EXCEL2-KK.
      MOVE W_/ZAK/BEVALL-ARKONT TO W_EXCEL2-FOKONYV.
*++1065 2010.02.04 BG
      MOVE W_/ZAK/BEVALL-ARKOSTL TO W_EXCEL2-KTGH.
      MOVE W_/ZAK/BEVALL-ARAUFNR TO W_EXCEL2-RENDELES.
*--1065 2010.02.04 BG
      MOVE '40' TO W_EXCEL1-KK.
      MOVE W_BOOK-HKONT TO W_EXCEL1-FOKONYV.
    ENDIF.

*   Save rows
    APPEND W_EXCEL1 TO I_EXCEL.
    APPEND W_EXCEL2 TO I_EXCEL.
  ENDLOOP.

*++1065 2010.02.04 BG
* Rotate the posting file (cost center, order, PC)
  PERFORM ROTATION_DATA(/ZAK/SZJA_SAP_SEL)
                        TABLES I_EXCEL
                        USING  I_BUKRS.
*--1065 2010.02.04 BG


* If there is data, download it
  IF NOT I_EXCEL[] IS INITIAL.
*   Create Excel file
    PERFORM DOWNLOAD_FILE_ARBOOK TABLES I_EXCEL
                                 USING  I_BUKRS
                                        I_BTYPE
                                        I_GJAHR
                                        I_MONAT
                                        I_INDEX
                                 CHANGING V_SUBRC.
    IF NOT V_SUBRC IS INITIAL.
      MESSAGE E175(/ZAK/ZAK) WITH '&'  RAISING ERROR_DOWNLOAD_FILE.
*     Error while downloading the & file.
    ENDIF.

  ENDIF.

ENDFUNCTION.
