*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/BEVALLV...................................*
FORM GET_DATA_/ZAK/BEVALLV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/BEVALLO WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/BEVALLV .
/ZAK/BEVALLV-MANDT =
/ZAK/BEVALLO-MANDT .
/ZAK/BEVALLV-BUKRS =
/ZAK/BEVALLO-BUKRS .
/ZAK/BEVALLV-BTYPE =
/ZAK/BEVALLO-BTYPE .
/ZAK/BEVALLV-GJAHR =
/ZAK/BEVALLO-GJAHR .
/ZAK/BEVALLV-MONAT =
/ZAK/BEVALLO-MONAT .
/ZAK/BEVALLV-ZINDEX =
/ZAK/BEVALLO-ZINDEX .
/ZAK/BEVALLV-ABEVAZ =
/ZAK/BEVALLO-ABEVAZ .
/ZAK/BEVALLV-ADOAZON =
/ZAK/BEVALLO-ADOAZON .
/ZAK/BEVALLV-LAPSZ =
/ZAK/BEVALLO-LAPSZ .
/ZAK/BEVALLV-BTYPE_DISP =
/ZAK/BEVALLO-BTYPE_DISP .
/ZAK/BEVALLV-ABEVAZ_DISP =
/ZAK/BEVALLO-ABEVAZ_DISP .
/ZAK/BEVALLV-FIELD_C =
/ZAK/BEVALLO-FIELD_C .
/ZAK/BEVALLV-FIELD_N =
/ZAK/BEVALLO-FIELD_N .
/ZAK/BEVALLV-ROUND =
/ZAK/BEVALLO-ROUND .
/ZAK/BEVALLV-FIELD_NR =
/ZAK/BEVALLO-FIELD_NR .
/ZAK/BEVALLV-FIELD_NRK =
/ZAK/BEVALLO-FIELD_NRK .
/ZAK/BEVALLV-WAERS =
/ZAK/BEVALLO-WAERS .
/ZAK/BEVALLV-GET_ABEVAZ =
/ZAK/BEVALLO-GET_ABEVAZ .
/ZAK/BEVALLV-OFLAG =
/ZAK/BEVALLO-OFLAG .
/ZAK/BEVALLV-FIELD_ON =
/ZAK/BEVALLO-FIELD_ON .
/ZAK/BEVALLV-FIELD_ONR =
/ZAK/BEVALLO-FIELD_ONR .
/ZAK/BEVALLV-FIELD_ONRK =
/ZAK/BEVALLO-FIELD_ONRK .
/ZAK/BEVALLV-NULL_FLAG =
/ZAK/BEVALLO-NULL_FLAG .
<VIM_TOTAL_STRUC> = /ZAK/BEVALLV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/BEVALLV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/BEVALLV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/BEVALLV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BEVALLO WHERE
  BUKRS = /ZAK/BEVALLV-BUKRS AND
  BTYPE = /ZAK/BEVALLV-BTYPE AND
  GJAHR = /ZAK/BEVALLV-GJAHR AND
  MONAT = /ZAK/BEVALLV-MONAT AND
  ZINDEX = /ZAK/BEVALLV-ZINDEX AND
  ABEVAZ = /ZAK/BEVALLV-ABEVAZ AND
  ADOAZON = /ZAK/BEVALLV-ADOAZON AND
  LAPSZ = /ZAK/BEVALLV-LAPSZ .
    IF SY-SUBRC = 0.
    DELETE /ZAK/BEVALLO .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BEVALLO WHERE
  BUKRS = /ZAK/BEVALLV-BUKRS AND
  BTYPE = /ZAK/BEVALLV-BTYPE AND
  GJAHR = /ZAK/BEVALLV-GJAHR AND
  MONAT = /ZAK/BEVALLV-MONAT AND
  ZINDEX = /ZAK/BEVALLV-ZINDEX AND
  ABEVAZ = /ZAK/BEVALLV-ABEVAZ AND
  ADOAZON = /ZAK/BEVALLV-ADOAZON AND
  LAPSZ = /ZAK/BEVALLV-LAPSZ .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/BEVALLO.
    ENDIF.
/ZAK/BEVALLO-MANDT =
/ZAK/BEVALLV-MANDT .
/ZAK/BEVALLO-BUKRS =
/ZAK/BEVALLV-BUKRS .
/ZAK/BEVALLO-BTYPE =
/ZAK/BEVALLV-BTYPE .
/ZAK/BEVALLO-GJAHR =
/ZAK/BEVALLV-GJAHR .
/ZAK/BEVALLO-MONAT =
/ZAK/BEVALLV-MONAT .
/ZAK/BEVALLO-ZINDEX =
/ZAK/BEVALLV-ZINDEX .
/ZAK/BEVALLO-ABEVAZ =
/ZAK/BEVALLV-ABEVAZ .
/ZAK/BEVALLO-ADOAZON =
/ZAK/BEVALLV-ADOAZON .
/ZAK/BEVALLO-LAPSZ =
/ZAK/BEVALLV-LAPSZ .
/ZAK/BEVALLO-BTYPE_DISP =
/ZAK/BEVALLV-BTYPE_DISP .
/ZAK/BEVALLO-ABEVAZ_DISP =
/ZAK/BEVALLV-ABEVAZ_DISP .
/ZAK/BEVALLO-FIELD_C =
/ZAK/BEVALLV-FIELD_C .
/ZAK/BEVALLO-FIELD_N =
/ZAK/BEVALLV-FIELD_N .
/ZAK/BEVALLO-ROUND =
/ZAK/BEVALLV-ROUND .
/ZAK/BEVALLO-FIELD_NR =
/ZAK/BEVALLV-FIELD_NR .
/ZAK/BEVALLO-FIELD_NRK =
/ZAK/BEVALLV-FIELD_NRK .
/ZAK/BEVALLO-WAERS =
/ZAK/BEVALLV-WAERS .
/ZAK/BEVALLO-GET_ABEVAZ =
/ZAK/BEVALLV-GET_ABEVAZ .
/ZAK/BEVALLO-OFLAG =
/ZAK/BEVALLV-OFLAG .
/ZAK/BEVALLO-FIELD_ON =
/ZAK/BEVALLV-FIELD_ON .
/ZAK/BEVALLO-FIELD_ONR =
/ZAK/BEVALLV-FIELD_ONR .
/ZAK/BEVALLO-FIELD_ONRK =
/ZAK/BEVALLV-FIELD_ONRK .
/ZAK/BEVALLO-NULL_FLAG =
/ZAK/BEVALLV-NULL_FLAG .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/BEVALLO .
    ELSE.
    INSERT /ZAK/BEVALLO .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/BEVALLV-UPD_FLAG,
STATUS_/ZAK/BEVALLV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/BEVALLV.
  SELECT SINGLE * FROM /ZAK/BEVALLO WHERE
BUKRS = /ZAK/BEVALLV-BUKRS AND
BTYPE = /ZAK/BEVALLV-BTYPE AND
GJAHR = /ZAK/BEVALLV-GJAHR AND
MONAT = /ZAK/BEVALLV-MONAT AND
ZINDEX = /ZAK/BEVALLV-ZINDEX AND
ABEVAZ = /ZAK/BEVALLV-ABEVAZ AND
ADOAZON = /ZAK/BEVALLV-ADOAZON AND
LAPSZ = /ZAK/BEVALLV-LAPSZ .
/ZAK/BEVALLV-MANDT =
/ZAK/BEVALLO-MANDT .
/ZAK/BEVALLV-BUKRS =
/ZAK/BEVALLO-BUKRS .
/ZAK/BEVALLV-BTYPE =
/ZAK/BEVALLO-BTYPE .
/ZAK/BEVALLV-GJAHR =
/ZAK/BEVALLO-GJAHR .
/ZAK/BEVALLV-MONAT =
/ZAK/BEVALLO-MONAT .
/ZAK/BEVALLV-ZINDEX =
/ZAK/BEVALLO-ZINDEX .
/ZAK/BEVALLV-ABEVAZ =
/ZAK/BEVALLO-ABEVAZ .
/ZAK/BEVALLV-ADOAZON =
/ZAK/BEVALLO-ADOAZON .
/ZAK/BEVALLV-LAPSZ =
/ZAK/BEVALLO-LAPSZ .
/ZAK/BEVALLV-BTYPE_DISP =
/ZAK/BEVALLO-BTYPE_DISP .
/ZAK/BEVALLV-ABEVAZ_DISP =
/ZAK/BEVALLO-ABEVAZ_DISP .
/ZAK/BEVALLV-FIELD_C =
/ZAK/BEVALLO-FIELD_C .
/ZAK/BEVALLV-FIELD_N =
/ZAK/BEVALLO-FIELD_N .
/ZAK/BEVALLV-ROUND =
/ZAK/BEVALLO-ROUND .
/ZAK/BEVALLV-FIELD_NR =
/ZAK/BEVALLO-FIELD_NR .
/ZAK/BEVALLV-FIELD_NRK =
/ZAK/BEVALLO-FIELD_NRK .
/ZAK/BEVALLV-WAERS =
/ZAK/BEVALLO-WAERS .
/ZAK/BEVALLV-GET_ABEVAZ =
/ZAK/BEVALLO-GET_ABEVAZ .
/ZAK/BEVALLV-OFLAG =
/ZAK/BEVALLO-OFLAG .
/ZAK/BEVALLV-FIELD_ON =
/ZAK/BEVALLO-FIELD_ON .
/ZAK/BEVALLV-FIELD_ONR =
/ZAK/BEVALLO-FIELD_ONR .
/ZAK/BEVALLV-FIELD_ONRK =
/ZAK/BEVALLO-FIELD_ONRK .
/ZAK/BEVALLV-NULL_FLAG =
/ZAK/BEVALLO-NULL_FLAG .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/BEVALLV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/BEVALLV-BUKRS TO
/ZAK/BEVALLO-BUKRS .
MOVE /ZAK/BEVALLV-BTYPE TO
/ZAK/BEVALLO-BTYPE .
MOVE /ZAK/BEVALLV-GJAHR TO
/ZAK/BEVALLO-GJAHR .
MOVE /ZAK/BEVALLV-MONAT TO
/ZAK/BEVALLO-MONAT .
MOVE /ZAK/BEVALLV-ZINDEX TO
/ZAK/BEVALLO-ZINDEX .
MOVE /ZAK/BEVALLV-ABEVAZ TO
/ZAK/BEVALLO-ABEVAZ .
MOVE /ZAK/BEVALLV-ADOAZON TO
/ZAK/BEVALLO-ADOAZON .
MOVE /ZAK/BEVALLV-LAPSZ TO
/ZAK/BEVALLO-LAPSZ .
MOVE /ZAK/BEVALLV-MANDT TO
/ZAK/BEVALLO-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/BEVALLO'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/BEVALLO TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/BEVALLO'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
