*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 2006.02.27 at 16:59:32 by user FMCTI00DBG
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LSZJA_AB_MVTOP.               " Global Data
  INCLUDE /ZAK/LSZJA_AB_MVUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LSZJA_AB_MVF00                     . " subprograms
  INCLUDE /ZAK/LSZJA_AB_MVI00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LSZJA_AB_MVF...               " Subprograms
* INCLUDE /ZAK/LSZJA_AB_MVO...               " PBO-Modules
* INCLUDE /ZAK/LSZJA_AB_MVI...               " PAI-Modules

INCLUDE /ZAK/LSZJA_AB_MVF01.
