*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/PENZATV_V...................................*
FORM GET_DATA_/ZAK/PENZATV_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/PENZATV WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/PENZATV_V .
/ZAK/PENZATV_V-MANDT =
/ZAK/PENZATV-MANDT .
/ZAK/PENZATV_V-ZAZON =
/ZAK/PENZATV-ZAZON .
/ZAK/PENZATV_V-NAME1 =
/ZAK/PENZATV-NAME1 .
/ZAK/PENZATV_V-POST_CODE1 =
/ZAK/PENZATV-POST_CODE1 .
/ZAK/PENZATV_V-CITY1 =
/ZAK/PENZATV-CITY1 .
/ZAK/PENZATV_V-STREET =
/ZAK/PENZATV-STREET .
/ZAK/PENZATV_V-HOUSE_NUM2 =
/ZAK/PENZATV-HOUSE_NUM2 .
/ZAK/PENZATV_V-HOUSE_NUM1 =
/ZAK/PENZATV-HOUSE_NUM1 .
/ZAK/PENZATV_V-BUILDING =
/ZAK/PENZATV-BUILDING .
/ZAK/PENZATV_V-HOUSE_NUM3 =
/ZAK/PENZATV-HOUSE_NUM3 .
/ZAK/PENZATV_V-FLOOR =
/ZAK/PENZATV-FLOOR .
/ZAK/PENZATV_V-ROOMNUMBER =
/ZAK/PENZATV-ROOMNUMBER .
/ZAK/PENZATV_V-AS4USER =
/ZAK/PENZATV-AS4USER .
/ZAK/PENZATV_V-AS4DATE =
/ZAK/PENZATV-AS4DATE .
/ZAK/PENZATV_V-AS4TIME =
/ZAK/PENZATV-AS4TIME .
<VIM_TOTAL_STRUC> = /ZAK/PENZATV_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/PENZATV_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/PENZATV_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/PENZATV_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/PENZATV WHERE
  ZAZON = /ZAK/PENZATV_V-ZAZON .
    IF SY-SUBRC = 0.
    DELETE /ZAK/PENZATV .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/PENZATV WHERE
  ZAZON = /ZAK/PENZATV_V-ZAZON .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/PENZATV.
    ENDIF.
/ZAK/PENZATV-MANDT =
/ZAK/PENZATV_V-MANDT .
/ZAK/PENZATV-ZAZON =
/ZAK/PENZATV_V-ZAZON .
/ZAK/PENZATV-NAME1 =
/ZAK/PENZATV_V-NAME1 .
/ZAK/PENZATV-POST_CODE1 =
/ZAK/PENZATV_V-POST_CODE1 .
/ZAK/PENZATV-CITY1 =
/ZAK/PENZATV_V-CITY1 .
/ZAK/PENZATV-STREET =
/ZAK/PENZATV_V-STREET .
/ZAK/PENZATV-HOUSE_NUM2 =
/ZAK/PENZATV_V-HOUSE_NUM2 .
/ZAK/PENZATV-HOUSE_NUM1 =
/ZAK/PENZATV_V-HOUSE_NUM1 .
/ZAK/PENZATV-BUILDING =
/ZAK/PENZATV_V-BUILDING .
/ZAK/PENZATV-HOUSE_NUM3 =
/ZAK/PENZATV_V-HOUSE_NUM3 .
/ZAK/PENZATV-FLOOR =
/ZAK/PENZATV_V-FLOOR .
/ZAK/PENZATV-ROOMNUMBER =
/ZAK/PENZATV_V-ROOMNUMBER .
/ZAK/PENZATV-AS4USER =
/ZAK/PENZATV_V-AS4USER .
/ZAK/PENZATV-AS4DATE =
/ZAK/PENZATV_V-AS4DATE .
/ZAK/PENZATV-AS4TIME =
/ZAK/PENZATV_V-AS4TIME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/PENZATV .
    ELSE.
    INSERT /ZAK/PENZATV .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/PENZATV_V-UPD_FLAG,
STATUS_/ZAK/PENZATV_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/PENZATV_V.
  SELECT SINGLE * FROM /ZAK/PENZATV WHERE
ZAZON = /ZAK/PENZATV_V-ZAZON .
/ZAK/PENZATV_V-MANDT =
/ZAK/PENZATV-MANDT .
/ZAK/PENZATV_V-ZAZON =
/ZAK/PENZATV-ZAZON .
/ZAK/PENZATV_V-NAME1 =
/ZAK/PENZATV-NAME1 .
/ZAK/PENZATV_V-POST_CODE1 =
/ZAK/PENZATV-POST_CODE1 .
/ZAK/PENZATV_V-CITY1 =
/ZAK/PENZATV-CITY1 .
/ZAK/PENZATV_V-STREET =
/ZAK/PENZATV-STREET .
/ZAK/PENZATV_V-HOUSE_NUM2 =
/ZAK/PENZATV-HOUSE_NUM2 .
/ZAK/PENZATV_V-HOUSE_NUM1 =
/ZAK/PENZATV-HOUSE_NUM1 .
/ZAK/PENZATV_V-BUILDING =
/ZAK/PENZATV-BUILDING .
/ZAK/PENZATV_V-HOUSE_NUM3 =
/ZAK/PENZATV-HOUSE_NUM3 .
/ZAK/PENZATV_V-FLOOR =
/ZAK/PENZATV-FLOOR .
/ZAK/PENZATV_V-ROOMNUMBER =
/ZAK/PENZATV-ROOMNUMBER .
/ZAK/PENZATV_V-AS4USER =
/ZAK/PENZATV-AS4USER .
/ZAK/PENZATV_V-AS4DATE =
/ZAK/PENZATV-AS4DATE .
/ZAK/PENZATV_V-AS4TIME =
/ZAK/PENZATV-AS4TIME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/PENZATV_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/PENZATV_V-ZAZON TO
/ZAK/PENZATV-ZAZON .
MOVE /ZAK/PENZATV_V-MANDT TO
/ZAK/PENZATV-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/PENZATV'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/PENZATV TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/PENZATV'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
