PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/ONELL_BOOKV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/ONELL_BOOKV-BUKRS .
    FIELD /ZAK/ONELL_BOOKV-BLART .
    FIELD /ZAK/ONELL_BOOKV-SZAMLA1 .
    FIELD /ZAK/ONELL_BOOKV-SZAMLA2 .
    FIELD /ZAK/ONELL_BOOKV-PRCTR .
    FIELD /ZAK/ONELL_BOOKV-GSBER .
    FIELD /ZAK/ONELL_BOOKV-AUFNR .
    FIELD /ZAK/ONELL_BOOKV-KOSTL .
    FIELD /ZAK/ONELL_BOOKV-DATUM .
    FIELD /ZAK/ONELL_BOOKV-UZEIT .
    FIELD /ZAK/ONELL_BOOKV-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/ONELL_BOOKV-BUKRS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
