PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/AFA_CUST_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/AFA_CUST_V-BTYPE .
    FIELD /ZAK/AFA_CUST_V-MWSKZ .
    FIELD /ZAK/AFA_CUST_V-KTOSL .
    FIELD /ZAK/AFA_CUST_V-ATYPE .
    FIELD /ZAK/AFA_CUST_V-ABEVAZ .
    FIELD /ZAK/AFA_CUST_V-ABEVTEXT .
    FIELD /ZAK/AFA_CUST_V-SIGN .
    FIELD /ZAK/AFA_CUST_V-MSIGN .
    FIELD /ZAK/AFA_CUST_V-KATA .
    FIELD /ZAK/AFA_CUST_V-TAXDIFF .
    FIELD /ZAK/AFA_CUST_V-DATUM .
    FIELD /ZAK/AFA_CUST_V-UZEIT .
    FIELD /ZAK/AFA_CUST_V-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_/ZAK/AFA_CUST_V ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/AFA_CUST_V-BTYPE .
    FIELD /ZAK/AFA_CUST_V-MWSKZ .
    FIELD /ZAK/AFA_CUST_V-KTOSL .
    FIELD /ZAK/AFA_CUST_V-ATYPE .
    FIELD /ZAK/AFA_CUST_V-ABEVAZ .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
