PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/KATA_SEL_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
 MODULE FILL_SUBSTFLDS.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/KATA_SEL_V-ADOAZON .
    FIELD /ZAK/KATA_SEL_V-PACK .
    FIELD /ZAK/KATA_SEL_V-BSEG_GJAHR .
    FIELD /ZAK/KATA_SEL_V-BSEG_BELNR .
    FIELD /ZAK/KATA_SEL_V-BSEG_BUZEI .
    FIELD /ZAK/KATA_SEL_V-GJAHR .
    FIELD /ZAK/KATA_SEL_V-MONAT .
    FIELD /ZAK/KATA_SEL_V-BUDAT .
    FIELD /ZAK/KATA_SEL_V-SZAMLASZ .
    FIELD /ZAK/KATA_SEL_V-LWBAS .
    FIELD /ZAK/KATA_SEL_V-LWSTE .
    FIELD /ZAK/KATA_SEL_V-WAERS .
    FIELD /ZAK/KATA_SEL_V-KOSTL .
    FIELD /ZAK/KATA_SEL_V-PRCTR .
    FIELD /ZAK/KATA_SEL_V-POSID .
    FIELD /ZAK/KATA_SEL_V-RELEVANT .
    FIELD /ZAK/KATA_SEL_V-PROCESS .
    FIELD /ZAK/KATA_SEL_V-BOOK .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/KATA_SEL_V-ADOAZON .
    FIELD /ZAK/KATA_SEL_V-PACK .
    FIELD /ZAK/KATA_SEL_V-BSEG_GJAHR .
    FIELD /ZAK/KATA_SEL_V-BSEG_BELNR .
    FIELD /ZAK/KATA_SEL_V-BSEG_BUZEI .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
