*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/BEVALLP_MV.................................*
FORM GET_DATA_/ZAK/BEVALLP_MV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/BEVALLP WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/BEVALLP_MV .
/ZAK/BEVALLP_MV-MANDT =
/ZAK/BEVALLP-MANDT .
/ZAK/BEVALLP_MV-BUKRS =
/ZAK/BEVALLP-BUKRS .
/ZAK/BEVALLP_MV-PACK =
/ZAK/BEVALLP-PACK .
/ZAK/BEVALLP_MV-DATUM =
/ZAK/BEVALLP-DATUM .
/ZAK/BEVALLP_MV-UZEIT =
/ZAK/BEVALLP-UZEIT .
/ZAK/BEVALLP_MV-UNAME =
/ZAK/BEVALLP-UNAME .
/ZAK/BEVALLP_MV-XLOEK =
/ZAK/BEVALLP-XLOEK .
/ZAK/BEVALLP_MV-DELUSER =
/ZAK/BEVALLP-DELUSER .
/ZAK/BEVALLP_MV-DELDATE =
/ZAK/BEVALLP-DELDATE .
/ZAK/BEVALLP_MV-SPACK =
/ZAK/BEVALLP-SPACK .
/ZAK/BEVALLP_MV-ZFILE =
/ZAK/BEVALLP-ZFILE .
/ZAK/BEVALLP_MV-MGIF =
/ZAK/BEVALLP-MGIF .
/ZAK/BEVALLP_MV-KATA =
/ZAK/BEVALLP-KATA .
/ZAK/BEVALLP_MV-DELTIME =
/ZAK/BEVALLP-DELTIME .
/ZAK/BEVALLP_MV-ALOADED =
/ZAK/BEVALLP-ALOADED .
<VIM_TOTAL_STRUC> = /ZAK/BEVALLP_MV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/BEVALLP_MV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/BEVALLP_MV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/BEVALLP_MV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BEVALLP WHERE
  BUKRS = /ZAK/BEVALLP_MV-BUKRS AND
  PACK = /ZAK/BEVALLP_MV-PACK .
    IF SY-SUBRC = 0.
    DELETE /ZAK/BEVALLP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BEVALLP WHERE
  BUKRS = /ZAK/BEVALLP_MV-BUKRS AND
  PACK = /ZAK/BEVALLP_MV-PACK .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/BEVALLP.
    ENDIF.
/ZAK/BEVALLP-MANDT =
/ZAK/BEVALLP_MV-MANDT .
/ZAK/BEVALLP-BUKRS =
/ZAK/BEVALLP_MV-BUKRS .
/ZAK/BEVALLP-PACK =
/ZAK/BEVALLP_MV-PACK .
/ZAK/BEVALLP-DATUM =
/ZAK/BEVALLP_MV-DATUM .
/ZAK/BEVALLP-UZEIT =
/ZAK/BEVALLP_MV-UZEIT .
/ZAK/BEVALLP-UNAME =
/ZAK/BEVALLP_MV-UNAME .
/ZAK/BEVALLP-XLOEK =
/ZAK/BEVALLP_MV-XLOEK .
/ZAK/BEVALLP-DELUSER =
/ZAK/BEVALLP_MV-DELUSER .
/ZAK/BEVALLP-DELDATE =
/ZAK/BEVALLP_MV-DELDATE .
/ZAK/BEVALLP-SPACK =
/ZAK/BEVALLP_MV-SPACK .
/ZAK/BEVALLP-ZFILE =
/ZAK/BEVALLP_MV-ZFILE .
/ZAK/BEVALLP-MGIF =
/ZAK/BEVALLP_MV-MGIF .
/ZAK/BEVALLP-KATA =
/ZAK/BEVALLP_MV-KATA .
/ZAK/BEVALLP-DELTIME =
/ZAK/BEVALLP_MV-DELTIME .
/ZAK/BEVALLP-ALOADED =
/ZAK/BEVALLP_MV-ALOADED .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/BEVALLP ##WARN_OK.
    ELSE.
    INSERT /ZAK/BEVALLP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/BEVALLP_MV-UPD_FLAG,
STATUS_/ZAK/BEVALLP_MV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/BEVALLP_MV.
  SELECT SINGLE * FROM /ZAK/BEVALLP WHERE
BUKRS = /ZAK/BEVALLP_MV-BUKRS AND
PACK = /ZAK/BEVALLP_MV-PACK .
/ZAK/BEVALLP_MV-MANDT =
/ZAK/BEVALLP-MANDT .
/ZAK/BEVALLP_MV-BUKRS =
/ZAK/BEVALLP-BUKRS .
/ZAK/BEVALLP_MV-PACK =
/ZAK/BEVALLP-PACK .
/ZAK/BEVALLP_MV-DATUM =
/ZAK/BEVALLP-DATUM .
/ZAK/BEVALLP_MV-UZEIT =
/ZAK/BEVALLP-UZEIT .
/ZAK/BEVALLP_MV-UNAME =
/ZAK/BEVALLP-UNAME .
/ZAK/BEVALLP_MV-XLOEK =
/ZAK/BEVALLP-XLOEK .
/ZAK/BEVALLP_MV-DELUSER =
/ZAK/BEVALLP-DELUSER .
/ZAK/BEVALLP_MV-DELDATE =
/ZAK/BEVALLP-DELDATE .
/ZAK/BEVALLP_MV-SPACK =
/ZAK/BEVALLP-SPACK .
/ZAK/BEVALLP_MV-ZFILE =
/ZAK/BEVALLP-ZFILE .
/ZAK/BEVALLP_MV-MGIF =
/ZAK/BEVALLP-MGIF .
/ZAK/BEVALLP_MV-KATA =
/ZAK/BEVALLP-KATA .
/ZAK/BEVALLP_MV-DELTIME =
/ZAK/BEVALLP-DELTIME .
/ZAK/BEVALLP_MV-ALOADED =
/ZAK/BEVALLP-ALOADED .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/BEVALLP_MV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/BEVALLP_MV-BUKRS TO
/ZAK/BEVALLP-BUKRS .
MOVE /ZAK/BEVALLP_MV-PACK TO
/ZAK/BEVALLP-PACK .
MOVE /ZAK/BEVALLP_MV-MANDT TO
/ZAK/BEVALLP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/BEVALLP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/BEVALLP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/BEVALLP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
