*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LBSET_MVTOP.                  " Global Data
  INCLUDE /ZAK/LBSET_MVUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LBSET_MVF00                        . " subprograms
  INCLUDE /ZAK/LBSET_MVI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LBSET_MVF...                  " Subprograms
* INCLUDE /ZAK/LBSET_MVO...                  " PBO-Modules
* INCLUDE /ZAK/LBSET_MVI...                  " PAI-Modules
