PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/AFA_FKABEVV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/AFA_FKABEVV-BUKRS .
    FIELD /ZAK/AFA_FKABEVV-BTYPE .
    FIELD /ZAK/AFA_FKABEVV-HKONT .
    FIELD /ZAK/AFA_FKABEVV-ATYPE .
    FIELD /ZAK/AFA_FKABEVV-AFABK .
    FIELD /ZAK/AFA_FKABEVV-ABEVAZ .
    FIELD /ZAK/AFA_FKABEVV-ABEVTEXT .
    FIELD /ZAK/AFA_FKABEVV-DATUM .
    FIELD /ZAK/AFA_FKABEVV-UZEIT .
    FIELD /ZAK/AFA_FKABEVV-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_/ZAK/AFA_FKABEVV ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/AFA_FKABEVV-BUKRS .
    FIELD /ZAK/AFA_FKABEVV-BTYPE .
    FIELD /ZAK/AFA_FKABEVV-HKONT .
    FIELD /ZAK/AFA_FKABEVV-ATYPE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
