PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/AFA_RARANYV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/AFA_RARANYV-BUKRS .
    FIELD /ZAK/AFA_RARANYV-MWSKZ .
    FIELD /ZAK/AFA_RARANYV-KTOSL .
    FIELD /ZAK/AFA_RARANYV-DATUM .
    FIELD /ZAK/AFA_RARANYV-UZEIT .
    FIELD /ZAK/AFA_RARANYV-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/AFA_RARANYV-BUKRS .
    FIELD /ZAK/AFA_RARANYV-MWSKZ .
    FIELD /ZAK/AFA_RARANYV-KTOSL .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
