PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/BEVALLP_MV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/BEVALLP_MV-BUKRS .
    FIELD /ZAK/BEVALLP_MV-PACK .
    FIELD /ZAK/BEVALLP_MV-DATUM .
    FIELD /ZAK/BEVALLP_MV-UZEIT .
    FIELD /ZAK/BEVALLP_MV-UNAME .
    FIELD /ZAK/BEVALLP_MV-XLOEK .
    FIELD /ZAK/BEVALLP_MV-DELUSER .
    FIELD /ZAK/BEVALLP_MV-DELDATE .
    FIELD /ZAK/BEVALLP_MV-SPACK .
    FIELD /ZAK/BEVALLP_MV-ZFILE .
    FIELD /ZAK/BEVALLP_MV-MGIF .
    FIELD /ZAK/BEVALLP_MV-KATA .
    FIELD /ZAK/BEVALLP_MV-DELTIME .
    FIELD /ZAK/BEVALLP_MV-ALOADED .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/BEVALLP_MV-BUKRS .
    FIELD /ZAK/BEVALLP_MV-PACK .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
