*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/BEVALLSZ_MV.................................*
FORM GET_DATA_/ZAK/BEVALLSZ_MV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/BEVALLSZ WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/BEVALLSZ_MV .
/ZAK/BEVALLSZ_MV-MANDT =
/ZAK/BEVALLSZ-MANDT .
/ZAK/BEVALLSZ_MV-BUKRS =
/ZAK/BEVALLSZ-BUKRS .
/ZAK/BEVALLSZ_MV-BTYPE =
/ZAK/BEVALLSZ-BTYPE .
/ZAK/BEVALLSZ_MV-BSZNUM =
/ZAK/BEVALLSZ-BSZNUM .
/ZAK/BEVALLSZ_MV-GJAHR =
/ZAK/BEVALLSZ-GJAHR .
/ZAK/BEVALLSZ_MV-MONAT =
/ZAK/BEVALLSZ-MONAT .
/ZAK/BEVALLSZ_MV-ZINDEX =
/ZAK/BEVALLSZ-ZINDEX .
/ZAK/BEVALLSZ_MV-PACK =
/ZAK/BEVALLSZ-PACK .
/ZAK/BEVALLSZ_MV-FLAG =
/ZAK/BEVALLSZ-FLAG .
/ZAK/BEVALLSZ_MV-LARUN =
/ZAK/BEVALLSZ-LARUN .
/ZAK/BEVALLSZ_MV-DATUM =
/ZAK/BEVALLSZ-DATUM .
/ZAK/BEVALLSZ_MV-UZEIT =
/ZAK/BEVALLSZ-UZEIT .
/ZAK/BEVALLSZ_MV-UNAME =
/ZAK/BEVALLSZ-UNAME .
<VIM_TOTAL_STRUC> = /ZAK/BEVALLSZ_MV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/BEVALLSZ_MV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/BEVALLSZ_MV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/BEVALLSZ_MV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BEVALLSZ WHERE
  BUKRS = /ZAK/BEVALLSZ_MV-BUKRS AND
  BTYPE = /ZAK/BEVALLSZ_MV-BTYPE AND
  BSZNUM = /ZAK/BEVALLSZ_MV-BSZNUM AND
  GJAHR = /ZAK/BEVALLSZ_MV-GJAHR AND
  MONAT = /ZAK/BEVALLSZ_MV-MONAT AND
  ZINDEX = /ZAK/BEVALLSZ_MV-ZINDEX AND
  PACK = /ZAK/BEVALLSZ_MV-PACK .
    IF SY-SUBRC = 0.
    DELETE /ZAK/BEVALLSZ .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BEVALLSZ WHERE
  BUKRS = /ZAK/BEVALLSZ_MV-BUKRS AND
  BTYPE = /ZAK/BEVALLSZ_MV-BTYPE AND
  BSZNUM = /ZAK/BEVALLSZ_MV-BSZNUM AND
  GJAHR = /ZAK/BEVALLSZ_MV-GJAHR AND
  MONAT = /ZAK/BEVALLSZ_MV-MONAT AND
  ZINDEX = /ZAK/BEVALLSZ_MV-ZINDEX AND
  PACK = /ZAK/BEVALLSZ_MV-PACK .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/BEVALLSZ.
    ENDIF.
/ZAK/BEVALLSZ-MANDT =
/ZAK/BEVALLSZ_MV-MANDT .
/ZAK/BEVALLSZ-BUKRS =
/ZAK/BEVALLSZ_MV-BUKRS .
/ZAK/BEVALLSZ-BTYPE =
/ZAK/BEVALLSZ_MV-BTYPE .
/ZAK/BEVALLSZ-BSZNUM =
/ZAK/BEVALLSZ_MV-BSZNUM .
/ZAK/BEVALLSZ-GJAHR =
/ZAK/BEVALLSZ_MV-GJAHR .
/ZAK/BEVALLSZ-MONAT =
/ZAK/BEVALLSZ_MV-MONAT .
/ZAK/BEVALLSZ-ZINDEX =
/ZAK/BEVALLSZ_MV-ZINDEX .
/ZAK/BEVALLSZ-PACK =
/ZAK/BEVALLSZ_MV-PACK .
/ZAK/BEVALLSZ-FLAG =
/ZAK/BEVALLSZ_MV-FLAG .
/ZAK/BEVALLSZ-LARUN =
/ZAK/BEVALLSZ_MV-LARUN .
/ZAK/BEVALLSZ-DATUM =
/ZAK/BEVALLSZ_MV-DATUM .
/ZAK/BEVALLSZ-UZEIT =
/ZAK/BEVALLSZ_MV-UZEIT .
/ZAK/BEVALLSZ-UNAME =
/ZAK/BEVALLSZ_MV-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/BEVALLSZ .
    ELSE.
    INSERT /ZAK/BEVALLSZ .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/BEVALLSZ_MV-UPD_FLAG,
STATUS_/ZAK/BEVALLSZ_MV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/BEVALLSZ_MV.
  SELECT SINGLE * FROM /ZAK/BEVALLSZ WHERE
BUKRS = /ZAK/BEVALLSZ_MV-BUKRS AND
BTYPE = /ZAK/BEVALLSZ_MV-BTYPE AND
BSZNUM = /ZAK/BEVALLSZ_MV-BSZNUM AND
GJAHR = /ZAK/BEVALLSZ_MV-GJAHR AND
MONAT = /ZAK/BEVALLSZ_MV-MONAT AND
ZINDEX = /ZAK/BEVALLSZ_MV-ZINDEX AND
PACK = /ZAK/BEVALLSZ_MV-PACK .
/ZAK/BEVALLSZ_MV-MANDT =
/ZAK/BEVALLSZ-MANDT .
/ZAK/BEVALLSZ_MV-BUKRS =
/ZAK/BEVALLSZ-BUKRS .
/ZAK/BEVALLSZ_MV-BTYPE =
/ZAK/BEVALLSZ-BTYPE .
/ZAK/BEVALLSZ_MV-BSZNUM =
/ZAK/BEVALLSZ-BSZNUM .
/ZAK/BEVALLSZ_MV-GJAHR =
/ZAK/BEVALLSZ-GJAHR .
/ZAK/BEVALLSZ_MV-MONAT =
/ZAK/BEVALLSZ-MONAT .
/ZAK/BEVALLSZ_MV-ZINDEX =
/ZAK/BEVALLSZ-ZINDEX .
/ZAK/BEVALLSZ_MV-PACK =
/ZAK/BEVALLSZ-PACK .
/ZAK/BEVALLSZ_MV-FLAG =
/ZAK/BEVALLSZ-FLAG .
/ZAK/BEVALLSZ_MV-LARUN =
/ZAK/BEVALLSZ-LARUN .
/ZAK/BEVALLSZ_MV-DATUM =
/ZAK/BEVALLSZ-DATUM .
/ZAK/BEVALLSZ_MV-UZEIT =
/ZAK/BEVALLSZ-UZEIT .
/ZAK/BEVALLSZ_MV-UNAME =
/ZAK/BEVALLSZ-UNAME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/BEVALLSZ_MV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/BEVALLSZ_MV-BUKRS TO
/ZAK/BEVALLSZ-BUKRS .
MOVE /ZAK/BEVALLSZ_MV-BTYPE TO
/ZAK/BEVALLSZ-BTYPE .
MOVE /ZAK/BEVALLSZ_MV-BSZNUM TO
/ZAK/BEVALLSZ-BSZNUM .
MOVE /ZAK/BEVALLSZ_MV-GJAHR TO
/ZAK/BEVALLSZ-GJAHR .
MOVE /ZAK/BEVALLSZ_MV-MONAT TO
/ZAK/BEVALLSZ-MONAT .
MOVE /ZAK/BEVALLSZ_MV-ZINDEX TO
/ZAK/BEVALLSZ-ZINDEX .
MOVE /ZAK/BEVALLSZ_MV-PACK TO
/ZAK/BEVALLSZ-PACK .
MOVE /ZAK/BEVALLSZ_MV-MANDT TO
/ZAK/BEVALLSZ-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/BEVALLSZ'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/BEVALLSZ TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/BEVALLSZ'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
