PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/MGCIM_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/MGCIM_V-ADOAZON .
    FIELD /ZAK/MGCIM_V-NAME .
    FIELD /ZAK/MGCIM_V-POSTCOD .
    FIELD /ZAK/MGCIM_V-CITY1 .
    FIELD /ZAK/MGCIM_V-STREET .
    FIELD /ZAK/MGCIM_V-PUBCHAR .
    FIELD /ZAK/MGCIM_V-HOUSE .
    FIELD /ZAK/MGCIM_V-COUNTRY .
    FIELD /ZAK/MGCIM_V-DATUM .
    FIELD /ZAK/MGCIM_V-UZEIT .
    FIELD /ZAK/MGCIM_V-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/MGCIM_V-ADOAZON .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
