
PROCESS BEFORE OUTPUT.

  MODULE STATUS_9100.

  MODULE INIT_9100.
*
PROCESS AFTER INPUT.

*++BG 2006/08/31
  MODULE EXIT AT EXIT-COMMAND.
*--BG 2006/08/31

  FIELD /ZAK/ANALITIKA_S-FIELD_N MODULE SET_SUM.
  FIELD /ZAK/ANALITIKA_S-KOSTL   MODULE CHECK_KOSTL.
  FIELD /ZAK/ANALITIKA_S-AUFNR   MODULE CHECK_AUFNR.
  FIELD /ZAK/ANALITIKA_S-PRCTR   MODULE CHECK_PRCTR.

  MODULE USER_COMMAND_9100.

