FUNCTION /ZAK/GET_ANAL.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(I_BUKRS) TYPE  BUKRS
*"     VALUE(I_PACK) TYPE  /ZAK/PACK
*"     VALUE(I_TEST) TYPE  XFELD DEFAULT 'X'
*"  TABLES
*"      T_ANALITIKA STRUCTURE  /ZAK/ANALITIKA
*"      T_AFA_SZLA STRUCTURE  /ZAK/AFA_SZLA
*"----------------------------------------------------------------------
  DATA:
      LS_BEVALLP TYPE /ZAK/BEVALLP,

      LI_ANALITIKA TYPE TABLE OF /ZAK/ANALITIKA,
      LS_ANALITIKA LIKE LINE OF LI_ANALITIKA.
*++1765 #13.
  DATA LS_AFA_SZLA TYPE /ZAK/AFA_SZLA.
*--1765 #13.
  REFRESH T_ANALITIKA.
  SELECT SINGLE * FROM /ZAK/BEVALLP
           INTO LS_BEVALLP
          WHERE BUKRS EQ I_BUKRS
            AND PACK  EQ I_PACK
            AND ALOADED NE 'X'
            AND XLOEK   NE 'X'.

  CHECK NOT LS_BEVALLP IS INITIAL.

  SELECT * FROM /ZAK/AFA_SZLA
     INTO TABLE T_AFA_SZLA
          WHERE BUKRS EQ I_BUKRS
            AND PACK  EQ I_PACK.

  SELECT * FROM /ZAK/ANALITIKA
     INTO TABLE T_ANALITIKA
          WHERE BUKRS EQ I_BUKRS
            AND PACK  EQ I_PACK.

*++1765 #13.
* Amount conversions
  LOOP AT T_AFA_SZLA INTO LS_AFA_SZLA.
    M_CONV_CURR_EXTERNAL LS_AFA_SZLA-LWBAS LS_AFA_SZLA-WAERS.
    M_CONV_CURR_EXTERNAL LS_AFA_SZLA-LWSTE LS_AFA_SZLA-WAERS.
    MODIFY T_AFA_SZLA FROM LS_AFA_SZLA TRANSPORTING LWBAS LWSTE.
  ENDLOOP.

  LOOP AT T_ANALITIKA INTO LS_ANALITIKA.
    M_CONV_CURR_EXTERNAL LS_ANALITIKA-DMBTR LS_ANALITIKA-WAERS.
    M_CONV_CURR_EXTERNAL LS_ANALITIKA-LWBAS LS_ANALITIKA-WAERS.
    M_CONV_CURR_EXTERNAL LS_ANALITIKA-LWSTE LS_ANALITIKA-WAERS.
    M_CONV_CURR_EXTERNAL LS_ANALITIKA-HWBTR LS_ANALITIKA-WAERS.
    M_CONV_CURR_EXTERNAL LS_ANALITIKA-FIELD_N LS_ANALITIKA-WAERS.
    MODIFY T_ANALITIKA FROM LS_ANALITIKA TRANSPORTING DMBTR LWBAS LWSTE HWBTR FIELD_N.
  ENDLOOP.
*--1765 #13.
  IF I_TEST   NE 'X' AND
     SY-SUBRC EQ  0.

    GET TIME.
    UPDATE /ZAK/BEVALLP SET ALOADED = 'X'
                           ADATUM   = SY-DATUM
                           AUZEIT   = SY-UZEIT
                           AUNAME   = SY-UNAME
                       WHERE
                           BUKRS    =  I_BUKRS  AND
                           PACK     =  I_PACK   AND
                           ALOADED  <> 'X'      AND
                           XLOEK    <> 'X'.
  ENDIF.
ENDFUNCTION.
