*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/AFA_ARABEVV................................*
FORM GET_DATA_/ZAK/AFA_ARABEVV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/AFA_ARABEV WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/AFA_ARABEVV .
/ZAK/AFA_ARABEVV-MANDT =
/ZAK/AFA_ARABEV-MANDT .
/ZAK/AFA_ARABEVV-BTYPE =
/ZAK/AFA_ARABEV-BTYPE .
/ZAK/AFA_ARABEVV-ATYPE =
/ZAK/AFA_ARABEV-ATYPE .
/ZAK/AFA_ARABEVV-VPOPF =
/ZAK/AFA_ARABEV-VPOPF .
/ZAK/AFA_ARABEVV-ARANYF =
/ZAK/AFA_ARABEV-ARANYF .
/ZAK/AFA_ARABEVV-ABEVAZ =
/ZAK/AFA_ARABEV-ABEVAZ .
/ZAK/AFA_ARABEVV-DATUM =
/ZAK/AFA_ARABEV-DATUM .
/ZAK/AFA_ARABEVV-UZEIT =
/ZAK/AFA_ARABEV-UZEIT .
/ZAK/AFA_ARABEVV-UNAME =
/ZAK/AFA_ARABEV-UNAME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/AFA_ARABEV-BTYPE AND
ABEVAZ = /ZAK/AFA_ARABEV-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/AFA_ARABEVV-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /ZAK/AFA_ARABEVV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/AFA_ARABEVV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/AFA_ARABEVV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/AFA_ARABEVV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_ARABEV WHERE
  BTYPE = /ZAK/AFA_ARABEVV-BTYPE AND
  ATYPE = /ZAK/AFA_ARABEVV-ATYPE AND
  VPOPF = /ZAK/AFA_ARABEVV-VPOPF AND
  ARANYF = /ZAK/AFA_ARABEVV-ARANYF .
    IF SY-SUBRC = 0.
    DELETE /ZAK/AFA_ARABEV .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_ARABEV WHERE
  BTYPE = /ZAK/AFA_ARABEVV-BTYPE AND
  ATYPE = /ZAK/AFA_ARABEVV-ATYPE AND
  VPOPF = /ZAK/AFA_ARABEVV-VPOPF AND
  ARANYF = /ZAK/AFA_ARABEVV-ARANYF .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/AFA_ARABEV.
    ENDIF.
/ZAK/AFA_ARABEV-MANDT =
/ZAK/AFA_ARABEVV-MANDT .
/ZAK/AFA_ARABEV-BTYPE =
/ZAK/AFA_ARABEVV-BTYPE .
/ZAK/AFA_ARABEV-ATYPE =
/ZAK/AFA_ARABEVV-ATYPE .
/ZAK/AFA_ARABEV-VPOPF =
/ZAK/AFA_ARABEVV-VPOPF .
/ZAK/AFA_ARABEV-ARANYF =
/ZAK/AFA_ARABEVV-ARANYF .
/ZAK/AFA_ARABEV-ABEVAZ =
/ZAK/AFA_ARABEVV-ABEVAZ .
/ZAK/AFA_ARABEV-DATUM =
/ZAK/AFA_ARABEVV-DATUM .
/ZAK/AFA_ARABEV-UZEIT =
/ZAK/AFA_ARABEVV-UZEIT .
/ZAK/AFA_ARABEV-UNAME =
/ZAK/AFA_ARABEVV-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/AFA_ARABEV .
    ELSE.
    INSERT /ZAK/AFA_ARABEV .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/AFA_ARABEVV-UPD_FLAG,
STATUS_/ZAK/AFA_ARABEVV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/AFA_ARABEVV.
  SELECT SINGLE * FROM /ZAK/AFA_ARABEV WHERE
BTYPE = /ZAK/AFA_ARABEVV-BTYPE AND
ATYPE = /ZAK/AFA_ARABEVV-ATYPE AND
VPOPF = /ZAK/AFA_ARABEVV-VPOPF AND
ARANYF = /ZAK/AFA_ARABEVV-ARANYF .
/ZAK/AFA_ARABEVV-MANDT =
/ZAK/AFA_ARABEV-MANDT .
/ZAK/AFA_ARABEVV-BTYPE =
/ZAK/AFA_ARABEV-BTYPE .
/ZAK/AFA_ARABEVV-ATYPE =
/ZAK/AFA_ARABEV-ATYPE .
/ZAK/AFA_ARABEVV-VPOPF =
/ZAK/AFA_ARABEV-VPOPF .
/ZAK/AFA_ARABEVV-ARANYF =
/ZAK/AFA_ARABEV-ARANYF .
/ZAK/AFA_ARABEVV-ABEVAZ =
/ZAK/AFA_ARABEV-ABEVAZ .
/ZAK/AFA_ARABEVV-DATUM =
/ZAK/AFA_ARABEV-DATUM .
/ZAK/AFA_ARABEVV-UZEIT =
/ZAK/AFA_ARABEV-UZEIT .
/ZAK/AFA_ARABEVV-UNAME =
/ZAK/AFA_ARABEV-UNAME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/AFA_ARABEV-BTYPE AND
ABEVAZ = /ZAK/AFA_ARABEV-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/AFA_ARABEVV-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/AFA_ARABEVV-ABEVTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/AFA_ARABEVV-ABEVTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/AFA_ARABEVV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/AFA_ARABEVV-BTYPE TO
/ZAK/AFA_ARABEV-BTYPE .
MOVE /ZAK/AFA_ARABEVV-ATYPE TO
/ZAK/AFA_ARABEV-ATYPE .
MOVE /ZAK/AFA_ARABEVV-VPOPF TO
/ZAK/AFA_ARABEV-VPOPF .
MOVE /ZAK/AFA_ARABEVV-ARANYF TO
/ZAK/AFA_ARABEV-ARANYF .
MOVE /ZAK/AFA_ARABEVV-MANDT TO
/ZAK/AFA_ARABEV-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/AFA_ARABEV'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/AFA_ARABEV TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/AFA_ARABEV'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/ZAK/AFA_ARABEVV USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/ZAK/AFA_ARABEV-MANDT =
/ZAK/AFA_ARABEVV-MANDT .
/ZAK/AFA_ARABEV-BTYPE =
/ZAK/AFA_ARABEVV-BTYPE .
/ZAK/AFA_ARABEV-ATYPE =
/ZAK/AFA_ARABEVV-ATYPE .
/ZAK/AFA_ARABEV-VPOPF =
/ZAK/AFA_ARABEVV-VPOPF .
/ZAK/AFA_ARABEV-ARANYF =
/ZAK/AFA_ARABEVV-ARANYF .
/ZAK/AFA_ARABEV-ABEVAZ =
/ZAK/AFA_ARABEVV-ABEVAZ .
/ZAK/AFA_ARABEV-DATUM =
/ZAK/AFA_ARABEVV-DATUM .
/ZAK/AFA_ARABEV-UZEIT =
/ZAK/AFA_ARABEVV-UZEIT .
/ZAK/AFA_ARABEV-UNAME =
/ZAK/AFA_ARABEVV-UNAME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/AFA_ARABEV-BTYPE AND
ABEVAZ = /ZAK/AFA_ARABEV-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/AFA_ARABEVV-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/AFA_ARABEVV-ABEVTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/AFA_ARABEVV-ABEVTEXT .
    ENDIF.
ENDFORM.
