*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/AFA_FKABEVV................................*
FORM GET_DATA_/ZAK/AFA_FKABEVV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/AFA_FKABEV WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/AFA_FKABEVV .
/ZAK/AFA_FKABEVV-MANDT =
/ZAK/AFA_FKABEV-MANDT .
/ZAK/AFA_FKABEVV-BUKRS =
/ZAK/AFA_FKABEV-BUKRS .
/ZAK/AFA_FKABEVV-BTYPE =
/ZAK/AFA_FKABEV-BTYPE .
/ZAK/AFA_FKABEVV-HKONT =
/ZAK/AFA_FKABEV-HKONT .
/ZAK/AFA_FKABEVV-ATYPE =
/ZAK/AFA_FKABEV-ATYPE .
/ZAK/AFA_FKABEVV-AFABK =
/ZAK/AFA_FKABEV-AFABK .
/ZAK/AFA_FKABEVV-ABEVAZ =
/ZAK/AFA_FKABEV-ABEVAZ .
/ZAK/AFA_FKABEVV-DATUM =
/ZAK/AFA_FKABEV-DATUM .
/ZAK/AFA_FKABEVV-UZEIT =
/ZAK/AFA_FKABEV-UZEIT .
/ZAK/AFA_FKABEVV-UNAME =
/ZAK/AFA_FKABEV-UNAME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/AFA_FKABEV-BTYPE AND
ABEVAZ = /ZAK/AFA_FKABEV-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/AFA_FKABEVV-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = /ZAK/AFA_FKABEVV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/AFA_FKABEVV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/AFA_FKABEVV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/AFA_FKABEVV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_FKABEV WHERE
  BUKRS = /ZAK/AFA_FKABEVV-BUKRS AND
  BTYPE = /ZAK/AFA_FKABEVV-BTYPE AND
  HKONT = /ZAK/AFA_FKABEVV-HKONT AND
  ATYPE = /ZAK/AFA_FKABEVV-ATYPE .
    IF SY-SUBRC = 0.
    DELETE /ZAK/AFA_FKABEV .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_FKABEV WHERE
  BUKRS = /ZAK/AFA_FKABEVV-BUKRS AND
  BTYPE = /ZAK/AFA_FKABEVV-BTYPE AND
  HKONT = /ZAK/AFA_FKABEVV-HKONT AND
  ATYPE = /ZAK/AFA_FKABEVV-ATYPE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/AFA_FKABEV.
    ENDIF.
/ZAK/AFA_FKABEV-MANDT =
/ZAK/AFA_FKABEVV-MANDT .
/ZAK/AFA_FKABEV-BUKRS =
/ZAK/AFA_FKABEVV-BUKRS .
/ZAK/AFA_FKABEV-BTYPE =
/ZAK/AFA_FKABEVV-BTYPE .
/ZAK/AFA_FKABEV-HKONT =
/ZAK/AFA_FKABEVV-HKONT .
/ZAK/AFA_FKABEV-ATYPE =
/ZAK/AFA_FKABEVV-ATYPE .
/ZAK/AFA_FKABEV-AFABK =
/ZAK/AFA_FKABEVV-AFABK .
/ZAK/AFA_FKABEV-ABEVAZ =
/ZAK/AFA_FKABEVV-ABEVAZ .
/ZAK/AFA_FKABEV-DATUM =
/ZAK/AFA_FKABEVV-DATUM .
/ZAK/AFA_FKABEV-UZEIT =
/ZAK/AFA_FKABEVV-UZEIT .
/ZAK/AFA_FKABEV-UNAME =
/ZAK/AFA_FKABEVV-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/AFA_FKABEV .
    ELSE.
    INSERT /ZAK/AFA_FKABEV .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/AFA_FKABEVV-UPD_FLAG,
STATUS_/ZAK/AFA_FKABEVV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/AFA_FKABEVV.
  SELECT SINGLE * FROM /ZAK/AFA_FKABEV WHERE
BUKRS = /ZAK/AFA_FKABEVV-BUKRS AND
BTYPE = /ZAK/AFA_FKABEVV-BTYPE AND
HKONT = /ZAK/AFA_FKABEVV-HKONT AND
ATYPE = /ZAK/AFA_FKABEVV-ATYPE .
/ZAK/AFA_FKABEVV-MANDT =
/ZAK/AFA_FKABEV-MANDT .
/ZAK/AFA_FKABEVV-BUKRS =
/ZAK/AFA_FKABEV-BUKRS .
/ZAK/AFA_FKABEVV-BTYPE =
/ZAK/AFA_FKABEV-BTYPE .
/ZAK/AFA_FKABEVV-HKONT =
/ZAK/AFA_FKABEV-HKONT .
/ZAK/AFA_FKABEVV-ATYPE =
/ZAK/AFA_FKABEV-ATYPE .
/ZAK/AFA_FKABEVV-AFABK =
/ZAK/AFA_FKABEV-AFABK .
/ZAK/AFA_FKABEVV-ABEVAZ =
/ZAK/AFA_FKABEV-ABEVAZ .
/ZAK/AFA_FKABEVV-DATUM =
/ZAK/AFA_FKABEV-DATUM .
/ZAK/AFA_FKABEVV-UZEIT =
/ZAK/AFA_FKABEV-UZEIT .
/ZAK/AFA_FKABEVV-UNAME =
/ZAK/AFA_FKABEV-UNAME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/AFA_FKABEV-BTYPE AND
ABEVAZ = /ZAK/AFA_FKABEV-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/AFA_FKABEVV-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/AFA_FKABEVV-ABEVTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/AFA_FKABEVV-ABEVTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/AFA_FKABEVV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/AFA_FKABEVV-BUKRS TO
/ZAK/AFA_FKABEV-BUKRS .
MOVE /ZAK/AFA_FKABEVV-BTYPE TO
/ZAK/AFA_FKABEV-BTYPE .
MOVE /ZAK/AFA_FKABEVV-HKONT TO
/ZAK/AFA_FKABEV-HKONT .
MOVE /ZAK/AFA_FKABEVV-ATYPE TO
/ZAK/AFA_FKABEV-ATYPE .
MOVE /ZAK/AFA_FKABEVV-MANDT TO
/ZAK/AFA_FKABEV-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/AFA_FKABEV'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/AFA_FKABEV TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/AFA_FKABEV'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_/ZAK/AFA_FKABEVV USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
/ZAK/AFA_FKABEV-MANDT =
/ZAK/AFA_FKABEVV-MANDT .
/ZAK/AFA_FKABEV-BUKRS =
/ZAK/AFA_FKABEVV-BUKRS .
/ZAK/AFA_FKABEV-BTYPE =
/ZAK/AFA_FKABEVV-BTYPE .
/ZAK/AFA_FKABEV-HKONT =
/ZAK/AFA_FKABEVV-HKONT .
/ZAK/AFA_FKABEV-ATYPE =
/ZAK/AFA_FKABEVV-ATYPE .
/ZAK/AFA_FKABEV-AFABK =
/ZAK/AFA_FKABEVV-AFABK .
/ZAK/AFA_FKABEV-ABEVAZ =
/ZAK/AFA_FKABEVV-ABEVAZ .
/ZAK/AFA_FKABEV-DATUM =
/ZAK/AFA_FKABEVV-DATUM .
/ZAK/AFA_FKABEV-UZEIT =
/ZAK/AFA_FKABEVV-UZEIT .
/ZAK/AFA_FKABEV-UNAME =
/ZAK/AFA_FKABEVV-UNAME .
    SELECT SINGLE * FROM /ZAK/BEVALLB WHERE
BTYPE = /ZAK/AFA_FKABEV-BTYPE AND
ABEVAZ = /ZAK/AFA_FKABEV-ABEVAZ .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /ZAK/BEVALLBT WHERE
BTYPE = /ZAK/BEVALLB-BTYPE AND
ABEVAZ = /ZAK/BEVALLB-ABEVAZ AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
/ZAK/AFA_FKABEVV-ABEVTEXT =
/ZAK/BEVALLBT-ABEVTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR /ZAK/AFA_FKABEVV-ABEVTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/AFA_FKABEVV-ABEVTEXT .
    ENDIF.
ENDFORM.
