*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/BEVALLC_V...................................*
FORM GET_DATA_/ZAK/BEVALLC_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/BEVALLC WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/BEVALLC_V .
/ZAK/BEVALLC_V-MANDT =
/ZAK/BEVALLC-MANDT .
/ZAK/BEVALLC_V-BTYPE =
/ZAK/BEVALLC-BTYPE .
/ZAK/BEVALLC_V-BSZNUM =
/ZAK/BEVALLC-BSZNUM .
/ZAK/BEVALLC_V-ABEVAZ =
/ZAK/BEVALLC-ABEVAZ .
/ZAK/BEVALLC_V-SZTABLE =
/ZAK/BEVALLC-SZTABLE .
/ZAK/BEVALLC_V-SZFIELD =
/ZAK/BEVALLC-SZFIELD .
/ZAK/BEVALLC_V-OBLIG =
/ZAK/BEVALLC-OBLIG .
/ZAK/BEVALLC_V-DATUM =
/ZAK/BEVALLC-DATUM .
/ZAK/BEVALLC_V-UZEIT =
/ZAK/BEVALLC-UZEIT .
/ZAK/BEVALLC_V-UNAME =
/ZAK/BEVALLC-UNAME .
<VIM_TOTAL_STRUC> = /ZAK/BEVALLC_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/BEVALLC_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/BEVALLC_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/BEVALLC_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BEVALLC WHERE
  BTYPE = /ZAK/BEVALLC_V-BTYPE AND
  BSZNUM = /ZAK/BEVALLC_V-BSZNUM AND
  ABEVAZ = /ZAK/BEVALLC_V-ABEVAZ .
    IF SY-SUBRC = 0.
    DELETE /ZAK/BEVALLC .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BEVALLC WHERE
  BTYPE = /ZAK/BEVALLC_V-BTYPE AND
  BSZNUM = /ZAK/BEVALLC_V-BSZNUM AND
  ABEVAZ = /ZAK/BEVALLC_V-ABEVAZ .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/BEVALLC.
    ENDIF.
/ZAK/BEVALLC-MANDT =
/ZAK/BEVALLC_V-MANDT .
/ZAK/BEVALLC-BTYPE =
/ZAK/BEVALLC_V-BTYPE .
/ZAK/BEVALLC-BSZNUM =
/ZAK/BEVALLC_V-BSZNUM .
/ZAK/BEVALLC-ABEVAZ =
/ZAK/BEVALLC_V-ABEVAZ .
/ZAK/BEVALLC-SZTABLE =
/ZAK/BEVALLC_V-SZTABLE .
/ZAK/BEVALLC-SZFIELD =
/ZAK/BEVALLC_V-SZFIELD .
/ZAK/BEVALLC-OBLIG =
/ZAK/BEVALLC_V-OBLIG .
/ZAK/BEVALLC-DATUM =
/ZAK/BEVALLC_V-DATUM .
/ZAK/BEVALLC-UZEIT =
/ZAK/BEVALLC_V-UZEIT .
/ZAK/BEVALLC-UNAME =
/ZAK/BEVALLC_V-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/BEVALLC .
    ELSE.
    INSERT /ZAK/BEVALLC .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/BEVALLC_V-UPD_FLAG,
STATUS_/ZAK/BEVALLC_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/BEVALLC_V.
  SELECT SINGLE * FROM /ZAK/BEVALLC WHERE
BTYPE = /ZAK/BEVALLC_V-BTYPE AND
BSZNUM = /ZAK/BEVALLC_V-BSZNUM AND
ABEVAZ = /ZAK/BEVALLC_V-ABEVAZ .
/ZAK/BEVALLC_V-MANDT =
/ZAK/BEVALLC-MANDT .
/ZAK/BEVALLC_V-BTYPE =
/ZAK/BEVALLC-BTYPE .
/ZAK/BEVALLC_V-BSZNUM =
/ZAK/BEVALLC-BSZNUM .
/ZAK/BEVALLC_V-ABEVAZ =
/ZAK/BEVALLC-ABEVAZ .
/ZAK/BEVALLC_V-SZTABLE =
/ZAK/BEVALLC-SZTABLE .
/ZAK/BEVALLC_V-SZFIELD =
/ZAK/BEVALLC-SZFIELD .
/ZAK/BEVALLC_V-OBLIG =
/ZAK/BEVALLC-OBLIG .
/ZAK/BEVALLC_V-DATUM =
/ZAK/BEVALLC-DATUM .
/ZAK/BEVALLC_V-UZEIT =
/ZAK/BEVALLC-UZEIT .
/ZAK/BEVALLC_V-UNAME =
/ZAK/BEVALLC-UNAME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/BEVALLC_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/BEVALLC_V-BTYPE TO
/ZAK/BEVALLC-BTYPE .
MOVE /ZAK/BEVALLC_V-BSZNUM TO
/ZAK/BEVALLC-BSZNUM .
MOVE /ZAK/BEVALLC_V-ABEVAZ TO
/ZAK/BEVALLC-ABEVAZ .
MOVE /ZAK/BEVALLC_V-MANDT TO
/ZAK/BEVALLC-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/BEVALLC'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/BEVALLC TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/BEVALLC'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
