*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/GET_IDSZ_MV.................................*
FORM GET_DATA_/ZAK/GET_IDSZ_MV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/GET_IDSZ WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/GET_IDSZ_MV .
/ZAK/GET_IDSZ_MV-MANDT =
/ZAK/GET_IDSZ-MANDT .
/ZAK/GET_IDSZ_MV-BUKRS =
/ZAK/GET_IDSZ-BUKRS .
/ZAK/GET_IDSZ_MV-GSBER =
/ZAK/GET_IDSZ-GSBER .
/ZAK/GET_IDSZ_MV-PRCTR =
/ZAK/GET_IDSZ-PRCTR .
/ZAK/GET_IDSZ_MV-AFABK =
/ZAK/GET_IDSZ-AFABK .
/ZAK/GET_IDSZ_MV-EUFLG =
/ZAK/GET_IDSZ-EUFLG .
/ZAK/GET_IDSZ_MV-GJAHR =
/ZAK/GET_IDSZ-GJAHR .
/ZAK/GET_IDSZ_MV-MONAT =
/ZAK/GET_IDSZ-MONAT .
/ZAK/GET_IDSZ_MV-DATUM =
/ZAK/GET_IDSZ-DATUM .
/ZAK/GET_IDSZ_MV-UZEIT =
/ZAK/GET_IDSZ-UZEIT .
/ZAK/GET_IDSZ_MV-UNAME =
/ZAK/GET_IDSZ-UNAME .
<VIM_TOTAL_STRUC> = /ZAK/GET_IDSZ_MV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/GET_IDSZ_MV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/GET_IDSZ_MV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/GET_IDSZ_MV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/GET_IDSZ WHERE
  BUKRS = /ZAK/GET_IDSZ_MV-BUKRS AND
  GSBER = /ZAK/GET_IDSZ_MV-GSBER AND
  PRCTR = /ZAK/GET_IDSZ_MV-PRCTR .
    IF SY-SUBRC = 0.
    DELETE /ZAK/GET_IDSZ .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/GET_IDSZ WHERE
  BUKRS = /ZAK/GET_IDSZ_MV-BUKRS AND
  GSBER = /ZAK/GET_IDSZ_MV-GSBER AND
  PRCTR = /ZAK/GET_IDSZ_MV-PRCTR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/GET_IDSZ.
    ENDIF.
/ZAK/GET_IDSZ-MANDT =
/ZAK/GET_IDSZ_MV-MANDT .
/ZAK/GET_IDSZ-BUKRS =
/ZAK/GET_IDSZ_MV-BUKRS .
/ZAK/GET_IDSZ-GSBER =
/ZAK/GET_IDSZ_MV-GSBER .
/ZAK/GET_IDSZ-PRCTR =
/ZAK/GET_IDSZ_MV-PRCTR .
/ZAK/GET_IDSZ-AFABK =
/ZAK/GET_IDSZ_MV-AFABK .
/ZAK/GET_IDSZ-EUFLG =
/ZAK/GET_IDSZ_MV-EUFLG .
/ZAK/GET_IDSZ-GJAHR =
/ZAK/GET_IDSZ_MV-GJAHR .
/ZAK/GET_IDSZ-MONAT =
/ZAK/GET_IDSZ_MV-MONAT .
/ZAK/GET_IDSZ-DATUM =
/ZAK/GET_IDSZ_MV-DATUM .
/ZAK/GET_IDSZ-UZEIT =
/ZAK/GET_IDSZ_MV-UZEIT .
/ZAK/GET_IDSZ-UNAME =
/ZAK/GET_IDSZ_MV-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/GET_IDSZ .
    ELSE.
    INSERT /ZAK/GET_IDSZ .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/GET_IDSZ_MV-UPD_FLAG,
STATUS_/ZAK/GET_IDSZ_MV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/GET_IDSZ_MV.
  SELECT SINGLE * FROM /ZAK/GET_IDSZ WHERE
BUKRS = /ZAK/GET_IDSZ_MV-BUKRS AND
GSBER = /ZAK/GET_IDSZ_MV-GSBER AND
PRCTR = /ZAK/GET_IDSZ_MV-PRCTR .
/ZAK/GET_IDSZ_MV-MANDT =
/ZAK/GET_IDSZ-MANDT .
/ZAK/GET_IDSZ_MV-BUKRS =
/ZAK/GET_IDSZ-BUKRS .
/ZAK/GET_IDSZ_MV-GSBER =
/ZAK/GET_IDSZ-GSBER .
/ZAK/GET_IDSZ_MV-PRCTR =
/ZAK/GET_IDSZ-PRCTR .
/ZAK/GET_IDSZ_MV-AFABK =
/ZAK/GET_IDSZ-AFABK .
/ZAK/GET_IDSZ_MV-EUFLG =
/ZAK/GET_IDSZ-EUFLG .
/ZAK/GET_IDSZ_MV-GJAHR =
/ZAK/GET_IDSZ-GJAHR .
/ZAK/GET_IDSZ_MV-MONAT =
/ZAK/GET_IDSZ-MONAT .
/ZAK/GET_IDSZ_MV-DATUM =
/ZAK/GET_IDSZ-DATUM .
/ZAK/GET_IDSZ_MV-UZEIT =
/ZAK/GET_IDSZ-UZEIT .
/ZAK/GET_IDSZ_MV-UNAME =
/ZAK/GET_IDSZ-UNAME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/GET_IDSZ_MV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/GET_IDSZ_MV-BUKRS TO
/ZAK/GET_IDSZ-BUKRS .
MOVE /ZAK/GET_IDSZ_MV-GSBER TO
/ZAK/GET_IDSZ-GSBER .
MOVE /ZAK/GET_IDSZ_MV-PRCTR TO
/ZAK/GET_IDSZ-PRCTR .
MOVE /ZAK/GET_IDSZ_MV-MANDT TO
/ZAK/GET_IDSZ-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/GET_IDSZ'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/GET_IDSZ TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/GET_IDSZ'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
