*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 2006.01.05 at 13:33:49 by user P000000234
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LBEVD_MVTOP.                  " Global Data
  INCLUDE /ZAK/LBEVD_MVUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LBEVD_MVF00                        . " subprograms
  INCLUDE /ZAK/LBEVD_MVI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LBEVD_MVF...                  " Subprograms
* INCLUDE /ZAK/LBEVD_MVO...                  " PBO-Modules
* INCLUDE /ZAK/LBEVD_MVI...                  " PAI-Modules

INCLUDE /ZAK/LBEVD_MVF01.
