PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/BEVALLC_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/BEVALLC_V-BTYPE .
    FIELD /ZAK/BEVALLC_V-BSZNUM .
    FIELD /ZAK/BEVALLC_V-ABEVAZ .
    FIELD /ZAK/BEVALLC_V-SZTABLE .
    FIELD /ZAK/BEVALLC_V-SZFIELD .
    FIELD /ZAK/BEVALLC_V-OBLIG .
    FIELD /ZAK/BEVALLC_V-DATUM .
    FIELD /ZAK/BEVALLC_V-UZEIT .
    FIELD /ZAK/BEVALLC_V-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/BEVALLC_V-BTYPE .
    FIELD /ZAK/BEVALLC_V-BSZNUM .
    FIELD /ZAK/BEVALLC_V-ABEVAZ .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
