*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/UREPI_LOG_V.................................*
FORM GET_DATA_/ZAK/UREPI_LOG_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/UREPI_LOG WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/UREPI_LOG_V .
/ZAK/UREPI_LOG_V-MANDT =
/ZAK/UREPI_LOG-MANDT .
/ZAK/UREPI_LOG_V-BUKRS =
/ZAK/UREPI_LOG-BUKRS .
/ZAK/UREPI_LOG_V-BELNR =
/ZAK/UREPI_LOG-BELNR .
/ZAK/UREPI_LOG_V-GJAHR =
/ZAK/UREPI_LOG-GJAHR .
/ZAK/UREPI_LOG_V-MONAT =
/ZAK/UREPI_LOG-MONAT .
/ZAK/UREPI_LOG_V-CPUDT =
/ZAK/UREPI_LOG-CPUDT .
/ZAK/UREPI_LOG_V-CPUTM =
/ZAK/UREPI_LOG-CPUTM .
<VIM_TOTAL_STRUC> = /ZAK/UREPI_LOG_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/UREPI_LOG_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/UREPI_LOG_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/UREPI_LOG_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/UREPI_LOG WHERE
  BUKRS = /ZAK/UREPI_LOG_V-BUKRS .
    IF SY-SUBRC = 0.
    DELETE /ZAK/UREPI_LOG .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/UREPI_LOG WHERE
  BUKRS = /ZAK/UREPI_LOG_V-BUKRS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/UREPI_LOG.
    ENDIF.
/ZAK/UREPI_LOG-MANDT =
/ZAK/UREPI_LOG_V-MANDT .
/ZAK/UREPI_LOG-BUKRS =
/ZAK/UREPI_LOG_V-BUKRS .
/ZAK/UREPI_LOG-BELNR =
/ZAK/UREPI_LOG_V-BELNR .
/ZAK/UREPI_LOG-GJAHR =
/ZAK/UREPI_LOG_V-GJAHR .
/ZAK/UREPI_LOG-MONAT =
/ZAK/UREPI_LOG_V-MONAT .
/ZAK/UREPI_LOG-CPUDT =
/ZAK/UREPI_LOG_V-CPUDT .
/ZAK/UREPI_LOG-CPUTM =
/ZAK/UREPI_LOG_V-CPUTM .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/UREPI_LOG .
    ELSE.
    INSERT /ZAK/UREPI_LOG .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/UREPI_LOG_V-UPD_FLAG,
STATUS_/ZAK/UREPI_LOG_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/UREPI_LOG_V.
  SELECT SINGLE * FROM /ZAK/UREPI_LOG WHERE
BUKRS = /ZAK/UREPI_LOG_V-BUKRS .
/ZAK/UREPI_LOG_V-MANDT =
/ZAK/UREPI_LOG-MANDT .
/ZAK/UREPI_LOG_V-BUKRS =
/ZAK/UREPI_LOG-BUKRS .
/ZAK/UREPI_LOG_V-BELNR =
/ZAK/UREPI_LOG-BELNR .
/ZAK/UREPI_LOG_V-GJAHR =
/ZAK/UREPI_LOG-GJAHR .
/ZAK/UREPI_LOG_V-MONAT =
/ZAK/UREPI_LOG-MONAT .
/ZAK/UREPI_LOG_V-CPUDT =
/ZAK/UREPI_LOG-CPUDT .
/ZAK/UREPI_LOG_V-CPUTM =
/ZAK/UREPI_LOG-CPUTM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/UREPI_LOG_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/UREPI_LOG_V-BUKRS TO
/ZAK/UREPI_LOG-BUKRS .
MOVE /ZAK/UREPI_LOG_V-MANDT TO
/ZAK/UREPI_LOG-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/UREPI_LOG'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/UREPI_LOG TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/UREPI_LOG'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
