*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/ADONEM_V....................................*
FORM GET_DATA_/ZAK/ADONEM_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/ADONEM WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/ADONEM_V .
/ZAK/ADONEM_V-MANDT =
/ZAK/ADONEM-MANDT .
/ZAK/ADONEM_V-BUKRS =
/ZAK/ADONEM-BUKRS .
/ZAK/ADONEM_V-ADONEM =
/ZAK/ADONEM-ADONEM .
/ZAK/ADONEM_V-LIFNR =
/ZAK/ADONEM-LIFNR .
/ZAK/ADONEM_V-FIZHAT =
/ZAK/ADONEM-FIZHAT .
/ZAK/ADONEM_V-BANKL =
/ZAK/ADONEM-BANKL .
/ZAK/ADONEM_V-BANKN =
/ZAK/ADONEM-BANKN .
/ZAK/ADONEM_V-SAKNR =
/ZAK/ADONEM-SAKNR .
/ZAK/ADONEM_V-ONREL =
/ZAK/ADONEM-ONREL .
/ZAK/ADONEM_V-DATUM =
/ZAK/ADONEM-DATUM .
/ZAK/ADONEM_V-UZEIT =
/ZAK/ADONEM-UZEIT .
/ZAK/ADONEM_V-UNAME =
/ZAK/ADONEM-UNAME .
    SELECT SINGLE * FROM /ZAK/ADONEMT WHERE
BUKRS = /ZAK/ADONEM-BUKRS AND
ADONEM = /ZAK/ADONEM-ADONEM AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
/ZAK/ADONEM_V-ADONEM_TXT =
/ZAK/ADONEMT-ADONEM_TXT .
    ENDIF.
<VIM_TOTAL_STRUC> = /ZAK/ADONEM_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/ADONEM_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/ADONEM_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/ADONEM_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/ADONEM WHERE
  BUKRS = /ZAK/ADONEM_V-BUKRS AND
  ADONEM = /ZAK/ADONEM_V-ADONEM .
    IF SY-SUBRC = 0.
    DELETE /ZAK/ADONEM .
    ENDIF.
    DELETE FROM /ZAK/ADONEMT WHERE
    BUKRS = /ZAK/ADONEM-BUKRS AND
    ADONEM = /ZAK/ADONEM-ADONEM .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/ADONEM WHERE
  BUKRS = /ZAK/ADONEM_V-BUKRS AND
  ADONEM = /ZAK/ADONEM_V-ADONEM .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/ADONEM.
    ENDIF.
/ZAK/ADONEM-MANDT =
/ZAK/ADONEM_V-MANDT .
/ZAK/ADONEM-BUKRS =
/ZAK/ADONEM_V-BUKRS .
/ZAK/ADONEM-ADONEM =
/ZAK/ADONEM_V-ADONEM .
/ZAK/ADONEM-LIFNR =
/ZAK/ADONEM_V-LIFNR .
/ZAK/ADONEM-FIZHAT =
/ZAK/ADONEM_V-FIZHAT .
/ZAK/ADONEM-BANKL =
/ZAK/ADONEM_V-BANKL .
/ZAK/ADONEM-BANKN =
/ZAK/ADONEM_V-BANKN .
/ZAK/ADONEM-SAKNR =
/ZAK/ADONEM_V-SAKNR .
/ZAK/ADONEM-ONREL =
/ZAK/ADONEM_V-ONREL .
/ZAK/ADONEM-DATUM =
/ZAK/ADONEM_V-DATUM .
/ZAK/ADONEM-UZEIT =
/ZAK/ADONEM_V-UZEIT .
/ZAK/ADONEM-UNAME =
/ZAK/ADONEM_V-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/ADONEM .
    ELSE.
    INSERT /ZAK/ADONEM .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM /ZAK/ADONEMT WHERE
    BUKRS = /ZAK/ADONEM-BUKRS AND
    ADONEM = /ZAK/ADONEM-ADONEM AND
    LANGU = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR /ZAK/ADONEMT.
/ZAK/ADONEMT-BUKRS =
/ZAK/ADONEM-BUKRS .
/ZAK/ADONEMT-ADONEM =
/ZAK/ADONEM-ADONEM .
/ZAK/ADONEMT-LANGU =
SY-LANGU .
      ENDIF.
/ZAK/ADONEMT-ADONEM_TXT =
/ZAK/ADONEM_V-ADONEM_TXT .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/ADONEMT .
    ELSE.
    INSERT /ZAK/ADONEMT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/ADONEM_V-UPD_FLAG,
STATUS_/ZAK/ADONEM_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/ADONEM_V.
  SELECT SINGLE * FROM /ZAK/ADONEM WHERE
BUKRS = /ZAK/ADONEM_V-BUKRS AND
ADONEM = /ZAK/ADONEM_V-ADONEM .
/ZAK/ADONEM_V-MANDT =
/ZAK/ADONEM-MANDT .
/ZAK/ADONEM_V-BUKRS =
/ZAK/ADONEM-BUKRS .
/ZAK/ADONEM_V-ADONEM =
/ZAK/ADONEM-ADONEM .
/ZAK/ADONEM_V-LIFNR =
/ZAK/ADONEM-LIFNR .
/ZAK/ADONEM_V-FIZHAT =
/ZAK/ADONEM-FIZHAT .
/ZAK/ADONEM_V-BANKL =
/ZAK/ADONEM-BANKL .
/ZAK/ADONEM_V-BANKN =
/ZAK/ADONEM-BANKN .
/ZAK/ADONEM_V-SAKNR =
/ZAK/ADONEM-SAKNR .
/ZAK/ADONEM_V-ONREL =
/ZAK/ADONEM-ONREL .
/ZAK/ADONEM_V-DATUM =
/ZAK/ADONEM-DATUM .
/ZAK/ADONEM_V-UZEIT =
/ZAK/ADONEM-UZEIT .
/ZAK/ADONEM_V-UNAME =
/ZAK/ADONEM-UNAME .
    SELECT SINGLE * FROM /ZAK/ADONEMT WHERE
BUKRS = /ZAK/ADONEM-BUKRS AND
ADONEM = /ZAK/ADONEM-ADONEM AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
/ZAK/ADONEM_V-ADONEM_TXT =
/ZAK/ADONEMT-ADONEM_TXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ZAK/ADONEM_V-ADONEM_TXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/ADONEM_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/ADONEM_V-BUKRS TO
/ZAK/ADONEM-BUKRS .
MOVE /ZAK/ADONEM_V-ADONEM TO
/ZAK/ADONEM-ADONEM .
MOVE /ZAK/ADONEM_V-MANDT TO
/ZAK/ADONEM-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/ADONEM'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/ADONEM TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/ADONEM'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE /ZAK/ADONEM-BUKRS TO
/ZAK/ADONEMT-BUKRS .
MOVE /ZAK/ADONEM-ADONEM TO
/ZAK/ADONEMT-ADONEM .
MOVE SY-LANGU TO
/ZAK/ADONEMT-LANGU .
MOVE /ZAK/ADONEM_V-MANDT TO
/ZAK/ADONEMT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/ADONEMT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/ADONEMT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/ADONEMT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
