*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 2006.06.09 at 16:15:12 by user FMCTI00DBG
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LBEVI_MVTOP.                  " Global Data
  INCLUDE /ZAK/LBEVI_MVUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LBEVI_MVF00                        . " subprograms
  INCLUDE /ZAK/LBEVI_MVI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LBEVI_MVF...                  " Subprograms
* INCLUDE /ZAK/LBEVI_MVO...                  " PBO-Modules
* INCLUDE /ZAK/LBEVI_MVI...                  " PAI-Modules
