*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/AFA_SZLA_V..................................*
FORM GET_DATA_/ZAK/AFA_SZLA_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/AFA_SZLA WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/AFA_SZLA_V .
/ZAK/AFA_SZLA_V-MANDT =
/ZAK/AFA_SZLA-MANDT .
/ZAK/AFA_SZLA_V-BUKRS =
/ZAK/AFA_SZLA-BUKRS .
/ZAK/AFA_SZLA_V-ADOAZON =
/ZAK/AFA_SZLA-ADOAZON .
/ZAK/AFA_SZLA_V-PACK =
/ZAK/AFA_SZLA-PACK .
/ZAK/AFA_SZLA_V-BSEG_GJAHR =
/ZAK/AFA_SZLA-BSEG_GJAHR .
/ZAK/AFA_SZLA_V-BSEG_BELNR =
/ZAK/AFA_SZLA-BSEG_BELNR .
/ZAK/AFA_SZLA_V-BSEG_BUZEI =
/ZAK/AFA_SZLA-BSEG_BUZEI .
/ZAK/AFA_SZLA_V-SZAMLASZA =
/ZAK/AFA_SZLA-SZAMLASZA .
/ZAK/AFA_SZLA_V-GJAHR =
/ZAK/AFA_SZLA-GJAHR .
/ZAK/AFA_SZLA_V-MONAT =
/ZAK/AFA_SZLA-MONAT .
/ZAK/AFA_SZLA_V-ZINDEX =
/ZAK/AFA_SZLA-ZINDEX .
/ZAK/AFA_SZLA_V-BLDAT =
/ZAK/AFA_SZLA-BLDAT .
/ZAK/AFA_SZLA_V-SZAMLASZ =
/ZAK/AFA_SZLA-SZAMLASZ .
/ZAK/AFA_SZLA_V-SZAMLASZE =
/ZAK/AFA_SZLA-SZAMLASZE .
/ZAK/AFA_SZLA_V-SZAMLAKELT =
/ZAK/AFA_SZLA-SZAMLAKELT .
/ZAK/AFA_SZLA_V-NYLAPAZON =
/ZAK/AFA_SZLA-NYLAPAZON .
/ZAK/AFA_SZLA_V-SZLATIP =
/ZAK/AFA_SZLA-SZLATIP .
/ZAK/AFA_SZLA_V-LWBAS =
/ZAK/AFA_SZLA-LWBAS .
/ZAK/AFA_SZLA_V-LWSTE =
/ZAK/AFA_SZLA-LWSTE .
/ZAK/AFA_SZLA_V-WAERS =
/ZAK/AFA_SZLA-WAERS .
/ZAK/AFA_SZLA_V-NONEED =
/ZAK/AFA_SZLA-NONEED .
<VIM_TOTAL_STRUC> = /ZAK/AFA_SZLA_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/AFA_SZLA_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/AFA_SZLA_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/AFA_SZLA_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_SZLA WHERE
  BUKRS = /ZAK/AFA_SZLA_V-BUKRS AND
  ADOAZON = /ZAK/AFA_SZLA_V-ADOAZON AND
  PACK = /ZAK/AFA_SZLA_V-PACK AND
  BSEG_GJAHR = /ZAK/AFA_SZLA_V-BSEG_GJAHR AND
  BSEG_BELNR = /ZAK/AFA_SZLA_V-BSEG_BELNR AND
  BSEG_BUZEI = /ZAK/AFA_SZLA_V-BSEG_BUZEI AND
  SZAMLASZA = /ZAK/AFA_SZLA_V-SZAMLASZA .
    IF SY-SUBRC = 0.
    DELETE /ZAK/AFA_SZLA .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_SZLA WHERE
  BUKRS = /ZAK/AFA_SZLA_V-BUKRS AND
  ADOAZON = /ZAK/AFA_SZLA_V-ADOAZON AND
  PACK = /ZAK/AFA_SZLA_V-PACK AND
  BSEG_GJAHR = /ZAK/AFA_SZLA_V-BSEG_GJAHR AND
  BSEG_BELNR = /ZAK/AFA_SZLA_V-BSEG_BELNR AND
  BSEG_BUZEI = /ZAK/AFA_SZLA_V-BSEG_BUZEI AND
  SZAMLASZA = /ZAK/AFA_SZLA_V-SZAMLASZA .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/AFA_SZLA.
    ENDIF.
/ZAK/AFA_SZLA-MANDT =
/ZAK/AFA_SZLA_V-MANDT .
/ZAK/AFA_SZLA-BUKRS =
/ZAK/AFA_SZLA_V-BUKRS .
/ZAK/AFA_SZLA-ADOAZON =
/ZAK/AFA_SZLA_V-ADOAZON .
/ZAK/AFA_SZLA-PACK =
/ZAK/AFA_SZLA_V-PACK .
/ZAK/AFA_SZLA-BSEG_GJAHR =
/ZAK/AFA_SZLA_V-BSEG_GJAHR .
/ZAK/AFA_SZLA-BSEG_BELNR =
/ZAK/AFA_SZLA_V-BSEG_BELNR .
/ZAK/AFA_SZLA-BSEG_BUZEI =
/ZAK/AFA_SZLA_V-BSEG_BUZEI .
/ZAK/AFA_SZLA-SZAMLASZA =
/ZAK/AFA_SZLA_V-SZAMLASZA .
/ZAK/AFA_SZLA-GJAHR =
/ZAK/AFA_SZLA_V-GJAHR .
/ZAK/AFA_SZLA-MONAT =
/ZAK/AFA_SZLA_V-MONAT .
/ZAK/AFA_SZLA-ZINDEX =
/ZAK/AFA_SZLA_V-ZINDEX .
/ZAK/AFA_SZLA-BLDAT =
/ZAK/AFA_SZLA_V-BLDAT .
/ZAK/AFA_SZLA-SZAMLASZ =
/ZAK/AFA_SZLA_V-SZAMLASZ .
/ZAK/AFA_SZLA-SZAMLASZE =
/ZAK/AFA_SZLA_V-SZAMLASZE .
/ZAK/AFA_SZLA-SZAMLAKELT =
/ZAK/AFA_SZLA_V-SZAMLAKELT .
/ZAK/AFA_SZLA-NYLAPAZON =
/ZAK/AFA_SZLA_V-NYLAPAZON .
/ZAK/AFA_SZLA-SZLATIP =
/ZAK/AFA_SZLA_V-SZLATIP .
/ZAK/AFA_SZLA-LWBAS =
/ZAK/AFA_SZLA_V-LWBAS .
/ZAK/AFA_SZLA-LWSTE =
/ZAK/AFA_SZLA_V-LWSTE .
/ZAK/AFA_SZLA-WAERS =
/ZAK/AFA_SZLA_V-WAERS .
/ZAK/AFA_SZLA-NONEED =
/ZAK/AFA_SZLA_V-NONEED .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/AFA_SZLA .
    ELSE.
    INSERT /ZAK/AFA_SZLA .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/AFA_SZLA_V-UPD_FLAG,
STATUS_/ZAK/AFA_SZLA_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/AFA_SZLA_V.
  SELECT SINGLE * FROM /ZAK/AFA_SZLA WHERE
BUKRS = /ZAK/AFA_SZLA_V-BUKRS AND
ADOAZON = /ZAK/AFA_SZLA_V-ADOAZON AND
PACK = /ZAK/AFA_SZLA_V-PACK AND
BSEG_GJAHR = /ZAK/AFA_SZLA_V-BSEG_GJAHR AND
BSEG_BELNR = /ZAK/AFA_SZLA_V-BSEG_BELNR AND
BSEG_BUZEI = /ZAK/AFA_SZLA_V-BSEG_BUZEI AND
SZAMLASZA = /ZAK/AFA_SZLA_V-SZAMLASZA .
/ZAK/AFA_SZLA_V-MANDT =
/ZAK/AFA_SZLA-MANDT .
/ZAK/AFA_SZLA_V-BUKRS =
/ZAK/AFA_SZLA-BUKRS .
/ZAK/AFA_SZLA_V-ADOAZON =
/ZAK/AFA_SZLA-ADOAZON .
/ZAK/AFA_SZLA_V-PACK =
/ZAK/AFA_SZLA-PACK .
/ZAK/AFA_SZLA_V-BSEG_GJAHR =
/ZAK/AFA_SZLA-BSEG_GJAHR .
/ZAK/AFA_SZLA_V-BSEG_BELNR =
/ZAK/AFA_SZLA-BSEG_BELNR .
/ZAK/AFA_SZLA_V-BSEG_BUZEI =
/ZAK/AFA_SZLA-BSEG_BUZEI .
/ZAK/AFA_SZLA_V-SZAMLASZA =
/ZAK/AFA_SZLA-SZAMLASZA .
/ZAK/AFA_SZLA_V-GJAHR =
/ZAK/AFA_SZLA-GJAHR .
/ZAK/AFA_SZLA_V-MONAT =
/ZAK/AFA_SZLA-MONAT .
/ZAK/AFA_SZLA_V-ZINDEX =
/ZAK/AFA_SZLA-ZINDEX .
/ZAK/AFA_SZLA_V-BLDAT =
/ZAK/AFA_SZLA-BLDAT .
/ZAK/AFA_SZLA_V-SZAMLASZ =
/ZAK/AFA_SZLA-SZAMLASZ .
/ZAK/AFA_SZLA_V-SZAMLASZE =
/ZAK/AFA_SZLA-SZAMLASZE .
/ZAK/AFA_SZLA_V-SZAMLAKELT =
/ZAK/AFA_SZLA-SZAMLAKELT .
/ZAK/AFA_SZLA_V-NYLAPAZON =
/ZAK/AFA_SZLA-NYLAPAZON .
/ZAK/AFA_SZLA_V-SZLATIP =
/ZAK/AFA_SZLA-SZLATIP .
/ZAK/AFA_SZLA_V-LWBAS =
/ZAK/AFA_SZLA-LWBAS .
/ZAK/AFA_SZLA_V-LWSTE =
/ZAK/AFA_SZLA-LWSTE .
/ZAK/AFA_SZLA_V-WAERS =
/ZAK/AFA_SZLA-WAERS .
/ZAK/AFA_SZLA_V-NONEED =
/ZAK/AFA_SZLA-NONEED .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/AFA_SZLA_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/AFA_SZLA_V-BUKRS TO
/ZAK/AFA_SZLA-BUKRS .
MOVE /ZAK/AFA_SZLA_V-ADOAZON TO
/ZAK/AFA_SZLA-ADOAZON .
MOVE /ZAK/AFA_SZLA_V-PACK TO
/ZAK/AFA_SZLA-PACK .
MOVE /ZAK/AFA_SZLA_V-BSEG_GJAHR TO
/ZAK/AFA_SZLA-BSEG_GJAHR .
MOVE /ZAK/AFA_SZLA_V-BSEG_BELNR TO
/ZAK/AFA_SZLA-BSEG_BELNR .
MOVE /ZAK/AFA_SZLA_V-BSEG_BUZEI TO
/ZAK/AFA_SZLA-BSEG_BUZEI .
MOVE /ZAK/AFA_SZLA_V-SZAMLASZA TO
/ZAK/AFA_SZLA-SZAMLASZA .
MOVE /ZAK/AFA_SZLA_V-MANDT TO
/ZAK/AFA_SZLA-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/AFA_SZLA'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/AFA_SZLA TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/AFA_SZLA'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
