*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LAFA_MVTOP.                   " Global Data
  INCLUDE /ZAK/LAFA_MVUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LAFA_MVF00                         . " subprograms
  INCLUDE /ZAK/LAFA_MVI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LAFA_MVF...                   " Subprograms
* INCLUDE /ZAK/LAFA_MVO...                   " PBO-Modules
* INCLUDE /ZAK/LAFA_MVI...                   " PAI-Modules

INCLUDE /ZAK/LAFA_MVF01.
