*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 2006.01.18 at 12:11:26 by user FMCTI00KCT
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LBEVB_MVTOP.                  " Global Data
  INCLUDE /ZAK/LBEVB_MVUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LBEVB_MVF00                        . " subprograms
  INCLUDE /ZAK/LBEVB_MVI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LBEVB_MVF...                  " Subprograms
* INCLUDE /ZAK/LBEVB_MVO...                  " PBO-Modules
* INCLUDE /ZAK/LBEVB_MVI...                  " PAI-Modules

INCLUDE /ZAK/LBEVB_MVF01.
