PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/BEVALLV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
 MODULE FILL_SUBSTFLDS.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/BEVALLV-ZINDEX .
    FIELD /ZAK/BEVALLV-ABEVAZ .
    FIELD /ZAK/BEVALLV-ADOAZON .
    FIELD /ZAK/BEVALLV-LAPSZ .
    FIELD /ZAK/BEVALLV-BTYPE_DISP .
    FIELD /ZAK/BEVALLV-ABEVAZ_DISP .
    FIELD /ZAK/BEVALLV-FIELD_C .
    FIELD /ZAK/BEVALLV-FIELD_N .
    FIELD /ZAK/BEVALLV-ROUND .
    FIELD /ZAK/BEVALLV-FIELD_NR .
    FIELD /ZAK/BEVALLV-FIELD_NRK .
    FIELD /ZAK/BEVALLV-WAERS .
    FIELD /ZAK/BEVALLV-GET_ABEVAZ .
    FIELD /ZAK/BEVALLV-OFLAG .
    FIELD /ZAK/BEVALLV-FIELD_ON .
    FIELD /ZAK/BEVALLV-FIELD_ONR .
    FIELD /ZAK/BEVALLV-FIELD_ONRK .
    FIELD /ZAK/BEVALLV-NULL_FLAG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/BEVALLV-ZINDEX .
    FIELD /ZAK/BEVALLV-ABEVAZ .
    FIELD /ZAK/BEVALLV-ADOAZON .
    FIELD /ZAK/BEVALLV-LAPSZ .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
