*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/KATA_SEL_V..................................*
FORM GET_DATA_/ZAK/KATA_SEL_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/KATA_SEL WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/KATA_SEL_V .
/ZAK/KATA_SEL_V-MANDT =
/ZAK/KATA_SEL-MANDT .
/ZAK/KATA_SEL_V-BUKRS =
/ZAK/KATA_SEL-BUKRS .
/ZAK/KATA_SEL_V-ADOAZON =
/ZAK/KATA_SEL-ADOAZON .
/ZAK/KATA_SEL_V-PACK =
/ZAK/KATA_SEL-PACK .
/ZAK/KATA_SEL_V-BSEG_GJAHR =
/ZAK/KATA_SEL-BSEG_GJAHR .
/ZAK/KATA_SEL_V-BSEG_BELNR =
/ZAK/KATA_SEL-BSEG_BELNR .
/ZAK/KATA_SEL_V-BSEG_BUZEI =
/ZAK/KATA_SEL-BSEG_BUZEI .
/ZAK/KATA_SEL_V-GJAHR =
/ZAK/KATA_SEL-GJAHR .
/ZAK/KATA_SEL_V-MONAT =
/ZAK/KATA_SEL-MONAT .
/ZAK/KATA_SEL_V-BUDAT =
/ZAK/KATA_SEL-BUDAT .
/ZAK/KATA_SEL_V-SZAMLASZ =
/ZAK/KATA_SEL-SZAMLASZ .
/ZAK/KATA_SEL_V-LWBAS =
/ZAK/KATA_SEL-LWBAS .
/ZAK/KATA_SEL_V-LWSTE =
/ZAK/KATA_SEL-LWSTE .
/ZAK/KATA_SEL_V-WAERS =
/ZAK/KATA_SEL-WAERS .
/ZAK/KATA_SEL_V-KOSTL =
/ZAK/KATA_SEL-KOSTL .
/ZAK/KATA_SEL_V-PRCTR =
/ZAK/KATA_SEL-PRCTR .
/ZAK/KATA_SEL_V-POSID =
/ZAK/KATA_SEL-POSID .
/ZAK/KATA_SEL_V-RELEVANT =
/ZAK/KATA_SEL-RELEVANT .
/ZAK/KATA_SEL_V-PROCESS =
/ZAK/KATA_SEL-PROCESS .
/ZAK/KATA_SEL_V-BOOK =
/ZAK/KATA_SEL-BOOK .
<VIM_TOTAL_STRUC> = /ZAK/KATA_SEL_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/KATA_SEL_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/KATA_SEL_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/KATA_SEL_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/KATA_SEL WHERE
  BUKRS = /ZAK/KATA_SEL_V-BUKRS AND
  ADOAZON = /ZAK/KATA_SEL_V-ADOAZON AND
  PACK = /ZAK/KATA_SEL_V-PACK AND
  BSEG_GJAHR = /ZAK/KATA_SEL_V-BSEG_GJAHR AND
  BSEG_BELNR = /ZAK/KATA_SEL_V-BSEG_BELNR AND
  BSEG_BUZEI = /ZAK/KATA_SEL_V-BSEG_BUZEI .
    IF SY-SUBRC = 0.
    DELETE /ZAK/KATA_SEL .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/KATA_SEL WHERE
  BUKRS = /ZAK/KATA_SEL_V-BUKRS AND
  ADOAZON = /ZAK/KATA_SEL_V-ADOAZON AND
  PACK = /ZAK/KATA_SEL_V-PACK AND
  BSEG_GJAHR = /ZAK/KATA_SEL_V-BSEG_GJAHR AND
  BSEG_BELNR = /ZAK/KATA_SEL_V-BSEG_BELNR AND
  BSEG_BUZEI = /ZAK/KATA_SEL_V-BSEG_BUZEI .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/KATA_SEL.
    ENDIF.
/ZAK/KATA_SEL-MANDT =
/ZAK/KATA_SEL_V-MANDT .
/ZAK/KATA_SEL-BUKRS =
/ZAK/KATA_SEL_V-BUKRS .
/ZAK/KATA_SEL-ADOAZON =
/ZAK/KATA_SEL_V-ADOAZON .
/ZAK/KATA_SEL-PACK =
/ZAK/KATA_SEL_V-PACK .
/ZAK/KATA_SEL-BSEG_GJAHR =
/ZAK/KATA_SEL_V-BSEG_GJAHR .
/ZAK/KATA_SEL-BSEG_BELNR =
/ZAK/KATA_SEL_V-BSEG_BELNR .
/ZAK/KATA_SEL-BSEG_BUZEI =
/ZAK/KATA_SEL_V-BSEG_BUZEI .
/ZAK/KATA_SEL-GJAHR =
/ZAK/KATA_SEL_V-GJAHR .
/ZAK/KATA_SEL-MONAT =
/ZAK/KATA_SEL_V-MONAT .
/ZAK/KATA_SEL-BUDAT =
/ZAK/KATA_SEL_V-BUDAT .
/ZAK/KATA_SEL-SZAMLASZ =
/ZAK/KATA_SEL_V-SZAMLASZ .
/ZAK/KATA_SEL-LWBAS =
/ZAK/KATA_SEL_V-LWBAS .
/ZAK/KATA_SEL-LWSTE =
/ZAK/KATA_SEL_V-LWSTE .
/ZAK/KATA_SEL-WAERS =
/ZAK/KATA_SEL_V-WAERS .
/ZAK/KATA_SEL-KOSTL =
/ZAK/KATA_SEL_V-KOSTL .
/ZAK/KATA_SEL-PRCTR =
/ZAK/KATA_SEL_V-PRCTR .
/ZAK/KATA_SEL-POSID =
/ZAK/KATA_SEL_V-POSID .
/ZAK/KATA_SEL-RELEVANT =
/ZAK/KATA_SEL_V-RELEVANT .
/ZAK/KATA_SEL-PROCESS =
/ZAK/KATA_SEL_V-PROCESS .
/ZAK/KATA_SEL-BOOK =
/ZAK/KATA_SEL_V-BOOK .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/KATA_SEL ##WARN_OK.
    ELSE.
    INSERT /ZAK/KATA_SEL .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/KATA_SEL_V-UPD_FLAG,
STATUS_/ZAK/KATA_SEL_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/KATA_SEL_V.
  SELECT SINGLE * FROM /ZAK/KATA_SEL WHERE
BUKRS = /ZAK/KATA_SEL_V-BUKRS AND
ADOAZON = /ZAK/KATA_SEL_V-ADOAZON AND
PACK = /ZAK/KATA_SEL_V-PACK AND
BSEG_GJAHR = /ZAK/KATA_SEL_V-BSEG_GJAHR AND
BSEG_BELNR = /ZAK/KATA_SEL_V-BSEG_BELNR AND
BSEG_BUZEI = /ZAK/KATA_SEL_V-BSEG_BUZEI .
/ZAK/KATA_SEL_V-MANDT =
/ZAK/KATA_SEL-MANDT .
/ZAK/KATA_SEL_V-BUKRS =
/ZAK/KATA_SEL-BUKRS .
/ZAK/KATA_SEL_V-ADOAZON =
/ZAK/KATA_SEL-ADOAZON .
/ZAK/KATA_SEL_V-PACK =
/ZAK/KATA_SEL-PACK .
/ZAK/KATA_SEL_V-BSEG_GJAHR =
/ZAK/KATA_SEL-BSEG_GJAHR .
/ZAK/KATA_SEL_V-BSEG_BELNR =
/ZAK/KATA_SEL-BSEG_BELNR .
/ZAK/KATA_SEL_V-BSEG_BUZEI =
/ZAK/KATA_SEL-BSEG_BUZEI .
/ZAK/KATA_SEL_V-GJAHR =
/ZAK/KATA_SEL-GJAHR .
/ZAK/KATA_SEL_V-MONAT =
/ZAK/KATA_SEL-MONAT .
/ZAK/KATA_SEL_V-BUDAT =
/ZAK/KATA_SEL-BUDAT .
/ZAK/KATA_SEL_V-SZAMLASZ =
/ZAK/KATA_SEL-SZAMLASZ .
/ZAK/KATA_SEL_V-LWBAS =
/ZAK/KATA_SEL-LWBAS .
/ZAK/KATA_SEL_V-LWSTE =
/ZAK/KATA_SEL-LWSTE .
/ZAK/KATA_SEL_V-WAERS =
/ZAK/KATA_SEL-WAERS .
/ZAK/KATA_SEL_V-KOSTL =
/ZAK/KATA_SEL-KOSTL .
/ZAK/KATA_SEL_V-PRCTR =
/ZAK/KATA_SEL-PRCTR .
/ZAK/KATA_SEL_V-POSID =
/ZAK/KATA_SEL-POSID .
/ZAK/KATA_SEL_V-RELEVANT =
/ZAK/KATA_SEL-RELEVANT .
/ZAK/KATA_SEL_V-PROCESS =
/ZAK/KATA_SEL-PROCESS .
/ZAK/KATA_SEL_V-BOOK =
/ZAK/KATA_SEL-BOOK .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/KATA_SEL_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/KATA_SEL_V-BUKRS TO
/ZAK/KATA_SEL-BUKRS .
MOVE /ZAK/KATA_SEL_V-ADOAZON TO
/ZAK/KATA_SEL-ADOAZON .
MOVE /ZAK/KATA_SEL_V-PACK TO
/ZAK/KATA_SEL-PACK .
MOVE /ZAK/KATA_SEL_V-BSEG_GJAHR TO
/ZAK/KATA_SEL-BSEG_GJAHR .
MOVE /ZAK/KATA_SEL_V-BSEG_BELNR TO
/ZAK/KATA_SEL-BSEG_BELNR .
MOVE /ZAK/KATA_SEL_V-BSEG_BUZEI TO
/ZAK/KATA_SEL-BSEG_BUZEI .
MOVE /ZAK/KATA_SEL_V-MANDT TO
/ZAK/KATA_SEL-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/KATA_SEL'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/KATA_SEL TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/KATA_SEL'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
