PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/AFA_SZLA_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/AFA_SZLA_V-BUKRS .
    FIELD /ZAK/AFA_SZLA_V-ADOAZON .
    FIELD /ZAK/AFA_SZLA_V-PACK .
    FIELD /ZAK/AFA_SZLA_V-BSEG_GJAHR .
    FIELD /ZAK/AFA_SZLA_V-BSEG_BELNR .
    FIELD /ZAK/AFA_SZLA_V-BSEG_BUZEI .
    FIELD /ZAK/AFA_SZLA_V-SZAMLASZA .
    FIELD /ZAK/AFA_SZLA_V-GJAHR .
    FIELD /ZAK/AFA_SZLA_V-MONAT .
    FIELD /ZAK/AFA_SZLA_V-ZINDEX .
    FIELD /ZAK/AFA_SZLA_V-BLDAT .
    FIELD /ZAK/AFA_SZLA_V-SZAMLASZ .
    FIELD /ZAK/AFA_SZLA_V-SZAMLASZE .
    FIELD /ZAK/AFA_SZLA_V-SZAMLAKELT .
    FIELD /ZAK/AFA_SZLA_V-NYLAPAZON .
    FIELD /ZAK/AFA_SZLA_V-SZLATIP .
    FIELD /ZAK/AFA_SZLA_V-LWBAS .
    FIELD /ZAK/AFA_SZLA_V-LWSTE .
    FIELD /ZAK/AFA_SZLA_V-WAERS .
    FIELD /ZAK/AFA_SZLA_V-NONEED .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/AFA_SZLA_V-BUKRS .
    FIELD /ZAK/AFA_SZLA_V-ADOAZON .
    FIELD /ZAK/AFA_SZLA_V-PACK .
    FIELD /ZAK/AFA_SZLA_V-BSEG_GJAHR .
    FIELD /ZAK/AFA_SZLA_V-BSEG_BELNR .
    FIELD /ZAK/AFA_SZLA_V-BSEG_BUZEI .
    FIELD /ZAK/AFA_SZLA_V-SZAMLASZA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
