PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/BNYLAP_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/BNYLAP_V-BUKRS .
    FIELD /ZAK/BNYLAP_V-BTYPART .
    FIELD /ZAK/BNYLAP_V-NYLAPAZON .
    FIELD /ZAK/BNYLAP_V-DATBI .
    FIELD /ZAK/BNYLAP_V-DATAB .
    FIELD /ZAK/BNYLAP_V-VPOPKI .
    FIELD /ZAK/BNYLAP_V-VPOPAR .
    FIELD /ZAK/BNYLAP_V-GET_ABEVAZ .
    FIELD /ZAK/BNYLAP_V-DATUM .
    FIELD /ZAK/BNYLAP_V-UZEIT .
    FIELD /ZAK/BNYLAP_V-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/BNYLAP_V-BUKRS .
    FIELD /ZAK/BNYLAP_V-BTYPART .
    FIELD /ZAK/BNYLAP_V-NYLAPAZON .
    FIELD /ZAK/BNYLAP_V-DATBI .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
