PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/START_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/START_V-BUKRS .
    FIELD /ZAK/START_V-ZBUDAT .
    FIELD /ZAK/START_V-ZURDAT .
    FIELD /ZAK/START_V-SELEXIT .
    FIELD /ZAK/START_V-OSTORNO .
    FIELD /ZAK/START_V-ZCOMMIT .
    FIELD /ZAK/START_V-M01VALID .
    FIELD /ZAK/START_V-REFERENZ .
    FIELD /ZAK/START_V-ELOKGEN .
    FIELD /ZAK/START_V-AS4USER .
    FIELD /ZAK/START_V-AS4DATE .
    FIELD /ZAK/START_V-AS4TIME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/START_V-BUKRS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
