*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LARANY_MVTOP.                 " Global Data
  INCLUDE /ZAK/LARANY_MVUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LARANY_MVF00                       . " subprograms
  INCLUDE /ZAK/LARANY_MVI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LARANY_MVF...                 " Subprograms
* INCLUDE /ZAK/LARANY_MVO...                 " PBO-Modules
* INCLUDE /ZAK/LARANY_MVI...                 " PAI-Modules

INCLUDE /ZAK/LARANY_MVF01.
