*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/SZJA_CUST_V.................................*
FORM GET_DATA_/ZAK/SZJA_CUST_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/SZJA_CUST WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/SZJA_CUST_V .
/ZAK/SZJA_CUST_V-MANDT =
/ZAK/SZJA_CUST-MANDT .
/ZAK/SZJA_CUST_V-BUKRS =
/ZAK/SZJA_CUST-BUKRS .
/ZAK/SZJA_CUST_V-BTYPE =
/ZAK/SZJA_CUST-BTYPE .
/ZAK/SZJA_CUST_V-BSZNUM =
/ZAK/SZJA_CUST-BSZNUM .
/ZAK/SZJA_CUST_V-ABEVAZ =
/ZAK/SZJA_CUST-ABEVAZ .
/ZAK/SZJA_CUST_V-SAKNR =
/ZAK/SZJA_CUST-SAKNR .
/ZAK/SZJA_CUST_V-AUFNR =
/ZAK/SZJA_CUST-AUFNR .
/ZAK/SZJA_CUST_V-DATAB =
/ZAK/SZJA_CUST-DATAB .
/ZAK/SZJA_CUST_V-DATBI =
/ZAK/SZJA_CUST-DATBI .
/ZAK/SZJA_CUST_V-BIDOSZ =
/ZAK/SZJA_CUST-BIDOSZ .
/ZAK/SZJA_CUST_V-ADOALAP =
/ZAK/SZJA_CUST-ADOALAP .
/ZAK/SZJA_CUST_V-SZJA_I =
/ZAK/SZJA_CUST-SZJA_I .
/ZAK/SZJA_CUST_V-SZJA_II =
/ZAK/SZJA_CUST-SZJA_II .
/ZAK/SZJA_CUST_V-SZJA_III =
/ZAK/SZJA_CUST-SZJA_III .
/ZAK/SZJA_CUST_V-SZJA_IV =
/ZAK/SZJA_CUST-SZJA_IV .
/ZAK/SZJA_CUST_V-TB_I =
/ZAK/SZJA_CUST-TB_I .
/ZAK/SZJA_CUST_V-TB_II =
/ZAK/SZJA_CUST-TB_II .
/ZAK/SZJA_CUST_V-TB_III =
/ZAK/SZJA_CUST-TB_III .
/ZAK/SZJA_CUST_V-MUNKAA =
/ZAK/SZJA_CUST-MUNKAA .
/ZAK/SZJA_CUST_V-EHO_I =
/ZAK/SZJA_CUST-EHO_I .
/ZAK/SZJA_CUST_V-EHO_II =
/ZAK/SZJA_CUST-EHO_II .
/ZAK/SZJA_CUST_V-EHO_III =
/ZAK/SZJA_CUST-EHO_III .
/ZAK/SZJA_CUST_V-SZOCHO_I =
/ZAK/SZJA_CUST-SZOCHO_I .
/ZAK/SZJA_CUST_V-SZOCHO_II =
/ZAK/SZJA_CUST-SZOCHO_II .
/ZAK/SZJA_CUST_V-SZKHJ =
/ZAK/SZJA_CUST-SZKHJ .
/ZAK/SZJA_CUST_V-/ZAK/EVES =
/ZAK/SZJA_CUST-/ZAK/EVES .
/ZAK/SZJA_CUST_V-/ZAK/WL =
/ZAK/SZJA_CUST-/ZAK/WL .
/ZAK/SZJA_CUST_V-WLBOUT =
/ZAK/SZJA_CUST-WLBOUT .
/ZAK/SZJA_CUST_V-MWSKZ =
/ZAK/SZJA_CUST-MWSKZ .
/ZAK/SZJA_CUST_V-KOSTL =
/ZAK/SZJA_CUST-KOSTL .
/ZAK/SZJA_CUST_V-/ZAK/ATKONYV =
/ZAK/SZJA_CUST-/ZAK/ATKONYV .
/ZAK/SZJA_CUST_V-ALAPKONYV =
/ZAK/SZJA_CUST-ALAPKONYV .
/ZAK/SZJA_CUST_V-DATUM =
/ZAK/SZJA_CUST-DATUM .
/ZAK/SZJA_CUST_V-UZEIT =
/ZAK/SZJA_CUST-UZEIT .
/ZAK/SZJA_CUST_V-UNAME =
/ZAK/SZJA_CUST-UNAME .
<VIM_TOTAL_STRUC> = /ZAK/SZJA_CUST_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/SZJA_CUST_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/SZJA_CUST_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/SZJA_CUST_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/SZJA_CUST WHERE
  BUKRS = /ZAK/SZJA_CUST_V-BUKRS AND
  BTYPE = /ZAK/SZJA_CUST_V-BTYPE AND
  BSZNUM = /ZAK/SZJA_CUST_V-BSZNUM AND
  ABEVAZ = /ZAK/SZJA_CUST_V-ABEVAZ AND
  SAKNR = /ZAK/SZJA_CUST_V-SAKNR AND
  AUFNR = /ZAK/SZJA_CUST_V-AUFNR AND
  DATAB = /ZAK/SZJA_CUST_V-DATAB .
    IF SY-SUBRC = 0.
    DELETE /ZAK/SZJA_CUST .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/SZJA_CUST WHERE
  BUKRS = /ZAK/SZJA_CUST_V-BUKRS AND
  BTYPE = /ZAK/SZJA_CUST_V-BTYPE AND
  BSZNUM = /ZAK/SZJA_CUST_V-BSZNUM AND
  ABEVAZ = /ZAK/SZJA_CUST_V-ABEVAZ AND
  SAKNR = /ZAK/SZJA_CUST_V-SAKNR AND
  AUFNR = /ZAK/SZJA_CUST_V-AUFNR AND
  DATAB = /ZAK/SZJA_CUST_V-DATAB .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/SZJA_CUST.
    ENDIF.
/ZAK/SZJA_CUST-MANDT =
/ZAK/SZJA_CUST_V-MANDT .
/ZAK/SZJA_CUST-BUKRS =
/ZAK/SZJA_CUST_V-BUKRS .
/ZAK/SZJA_CUST-BTYPE =
/ZAK/SZJA_CUST_V-BTYPE .
/ZAK/SZJA_CUST-BSZNUM =
/ZAK/SZJA_CUST_V-BSZNUM .
/ZAK/SZJA_CUST-ABEVAZ =
/ZAK/SZJA_CUST_V-ABEVAZ .
/ZAK/SZJA_CUST-SAKNR =
/ZAK/SZJA_CUST_V-SAKNR .
/ZAK/SZJA_CUST-AUFNR =
/ZAK/SZJA_CUST_V-AUFNR .
/ZAK/SZJA_CUST-DATAB =
/ZAK/SZJA_CUST_V-DATAB .
/ZAK/SZJA_CUST-DATBI =
/ZAK/SZJA_CUST_V-DATBI .
/ZAK/SZJA_CUST-BIDOSZ =
/ZAK/SZJA_CUST_V-BIDOSZ .
/ZAK/SZJA_CUST-ADOALAP =
/ZAK/SZJA_CUST_V-ADOALAP .
/ZAK/SZJA_CUST-SZJA_I =
/ZAK/SZJA_CUST_V-SZJA_I .
/ZAK/SZJA_CUST-SZJA_II =
/ZAK/SZJA_CUST_V-SZJA_II .
/ZAK/SZJA_CUST-SZJA_III =
/ZAK/SZJA_CUST_V-SZJA_III .
/ZAK/SZJA_CUST-SZJA_IV =
/ZAK/SZJA_CUST_V-SZJA_IV .
/ZAK/SZJA_CUST-TB_I =
/ZAK/SZJA_CUST_V-TB_I .
/ZAK/SZJA_CUST-TB_II =
/ZAK/SZJA_CUST_V-TB_II .
/ZAK/SZJA_CUST-TB_III =
/ZAK/SZJA_CUST_V-TB_III .
/ZAK/SZJA_CUST-MUNKAA =
/ZAK/SZJA_CUST_V-MUNKAA .
/ZAK/SZJA_CUST-EHO_I =
/ZAK/SZJA_CUST_V-EHO_I .
/ZAK/SZJA_CUST-EHO_II =
/ZAK/SZJA_CUST_V-EHO_II .
/ZAK/SZJA_CUST-EHO_III =
/ZAK/SZJA_CUST_V-EHO_III .
/ZAK/SZJA_CUST-SZOCHO_I =
/ZAK/SZJA_CUST_V-SZOCHO_I .
/ZAK/SZJA_CUST-SZOCHO_II =
/ZAK/SZJA_CUST_V-SZOCHO_II .
/ZAK/SZJA_CUST-SZKHJ =
/ZAK/SZJA_CUST_V-SZKHJ .
/ZAK/SZJA_CUST-/ZAK/EVES =
/ZAK/SZJA_CUST_V-/ZAK/EVES .
/ZAK/SZJA_CUST-/ZAK/WL =
/ZAK/SZJA_CUST_V-/ZAK/WL .
/ZAK/SZJA_CUST-WLBOUT =
/ZAK/SZJA_CUST_V-WLBOUT .
/ZAK/SZJA_CUST-MWSKZ =
/ZAK/SZJA_CUST_V-MWSKZ .
/ZAK/SZJA_CUST-KOSTL =
/ZAK/SZJA_CUST_V-KOSTL .
/ZAK/SZJA_CUST-/ZAK/ATKONYV =
/ZAK/SZJA_CUST_V-/ZAK/ATKONYV .
/ZAK/SZJA_CUST-ALAPKONYV =
/ZAK/SZJA_CUST_V-ALAPKONYV .
/ZAK/SZJA_CUST-DATUM =
/ZAK/SZJA_CUST_V-DATUM .
/ZAK/SZJA_CUST-UZEIT =
/ZAK/SZJA_CUST_V-UZEIT .
/ZAK/SZJA_CUST-UNAME =
/ZAK/SZJA_CUST_V-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/SZJA_CUST ##WARN_OK.
    ELSE.
    INSERT /ZAK/SZJA_CUST .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/SZJA_CUST_V-UPD_FLAG,
STATUS_/ZAK/SZJA_CUST_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/SZJA_CUST_V.
  SELECT SINGLE * FROM /ZAK/SZJA_CUST WHERE
BUKRS = /ZAK/SZJA_CUST_V-BUKRS AND
BTYPE = /ZAK/SZJA_CUST_V-BTYPE AND
BSZNUM = /ZAK/SZJA_CUST_V-BSZNUM AND
ABEVAZ = /ZAK/SZJA_CUST_V-ABEVAZ AND
SAKNR = /ZAK/SZJA_CUST_V-SAKNR AND
AUFNR = /ZAK/SZJA_CUST_V-AUFNR AND
DATAB = /ZAK/SZJA_CUST_V-DATAB .
/ZAK/SZJA_CUST_V-MANDT =
/ZAK/SZJA_CUST-MANDT .
/ZAK/SZJA_CUST_V-BUKRS =
/ZAK/SZJA_CUST-BUKRS .
/ZAK/SZJA_CUST_V-BTYPE =
/ZAK/SZJA_CUST-BTYPE .
/ZAK/SZJA_CUST_V-BSZNUM =
/ZAK/SZJA_CUST-BSZNUM .
/ZAK/SZJA_CUST_V-ABEVAZ =
/ZAK/SZJA_CUST-ABEVAZ .
/ZAK/SZJA_CUST_V-SAKNR =
/ZAK/SZJA_CUST-SAKNR .
/ZAK/SZJA_CUST_V-AUFNR =
/ZAK/SZJA_CUST-AUFNR .
/ZAK/SZJA_CUST_V-DATAB =
/ZAK/SZJA_CUST-DATAB .
/ZAK/SZJA_CUST_V-DATBI =
/ZAK/SZJA_CUST-DATBI .
/ZAK/SZJA_CUST_V-BIDOSZ =
/ZAK/SZJA_CUST-BIDOSZ .
/ZAK/SZJA_CUST_V-ADOALAP =
/ZAK/SZJA_CUST-ADOALAP .
/ZAK/SZJA_CUST_V-SZJA_I =
/ZAK/SZJA_CUST-SZJA_I .
/ZAK/SZJA_CUST_V-SZJA_II =
/ZAK/SZJA_CUST-SZJA_II .
/ZAK/SZJA_CUST_V-SZJA_III =
/ZAK/SZJA_CUST-SZJA_III .
/ZAK/SZJA_CUST_V-SZJA_IV =
/ZAK/SZJA_CUST-SZJA_IV .
/ZAK/SZJA_CUST_V-TB_I =
/ZAK/SZJA_CUST-TB_I .
/ZAK/SZJA_CUST_V-TB_II =
/ZAK/SZJA_CUST-TB_II .
/ZAK/SZJA_CUST_V-TB_III =
/ZAK/SZJA_CUST-TB_III .
/ZAK/SZJA_CUST_V-MUNKAA =
/ZAK/SZJA_CUST-MUNKAA .
/ZAK/SZJA_CUST_V-EHO_I =
/ZAK/SZJA_CUST-EHO_I .
/ZAK/SZJA_CUST_V-EHO_II =
/ZAK/SZJA_CUST-EHO_II .
/ZAK/SZJA_CUST_V-EHO_III =
/ZAK/SZJA_CUST-EHO_III .
/ZAK/SZJA_CUST_V-SZOCHO_I =
/ZAK/SZJA_CUST-SZOCHO_I .
/ZAK/SZJA_CUST_V-SZOCHO_II =
/ZAK/SZJA_CUST-SZOCHO_II .
/ZAK/SZJA_CUST_V-SZKHJ =
/ZAK/SZJA_CUST-SZKHJ .
/ZAK/SZJA_CUST_V-/ZAK/EVES =
/ZAK/SZJA_CUST-/ZAK/EVES .
/ZAK/SZJA_CUST_V-/ZAK/WL =
/ZAK/SZJA_CUST-/ZAK/WL .
/ZAK/SZJA_CUST_V-WLBOUT =
/ZAK/SZJA_CUST-WLBOUT .
/ZAK/SZJA_CUST_V-MWSKZ =
/ZAK/SZJA_CUST-MWSKZ .
/ZAK/SZJA_CUST_V-KOSTL =
/ZAK/SZJA_CUST-KOSTL .
/ZAK/SZJA_CUST_V-/ZAK/ATKONYV =
/ZAK/SZJA_CUST-/ZAK/ATKONYV .
/ZAK/SZJA_CUST_V-ALAPKONYV =
/ZAK/SZJA_CUST-ALAPKONYV .
/ZAK/SZJA_CUST_V-DATUM =
/ZAK/SZJA_CUST-DATUM .
/ZAK/SZJA_CUST_V-UZEIT =
/ZAK/SZJA_CUST-UZEIT .
/ZAK/SZJA_CUST_V-UNAME =
/ZAK/SZJA_CUST-UNAME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/SZJA_CUST_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/SZJA_CUST_V-BUKRS TO
/ZAK/SZJA_CUST-BUKRS .
MOVE /ZAK/SZJA_CUST_V-BTYPE TO
/ZAK/SZJA_CUST-BTYPE .
MOVE /ZAK/SZJA_CUST_V-BSZNUM TO
/ZAK/SZJA_CUST-BSZNUM .
MOVE /ZAK/SZJA_CUST_V-ABEVAZ TO
/ZAK/SZJA_CUST-ABEVAZ .
MOVE /ZAK/SZJA_CUST_V-SAKNR TO
/ZAK/SZJA_CUST-SAKNR .
MOVE /ZAK/SZJA_CUST_V-AUFNR TO
/ZAK/SZJA_CUST-AUFNR .
MOVE /ZAK/SZJA_CUST_V-DATAB TO
/ZAK/SZJA_CUST-DATAB .
MOVE /ZAK/SZJA_CUST_V-MANDT TO
/ZAK/SZJA_CUST-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/SZJA_CUST'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/SZJA_CUST TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/SZJA_CUST'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
