*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 2006.01.05 at 10:42:17 by user FMCTI00DBG
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LBEV_MVTOP.                   " Global Data
  INCLUDE /ZAK/LBEV_MVUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LBEV_MVF00                         . " subprograms
  INCLUDE /ZAK/LBEV_MVI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LBEV_MVF...                   " Subprograms
* INCLUDE /ZAK/LBEV_MVO...                   " PBO-Modules
* INCLUDE /ZAK/LBEV_MVI...                   " PAI-Modules
