*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/BSET_MV.....................................*
FORM GET_DATA_/ZAK/BSET_MV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/BSET WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/BSET_MV .
/ZAK/BSET_MV-MANDT =
/ZAK/BSET-MANDT .
/ZAK/BSET_MV-BUKRS =
/ZAK/BSET-BUKRS .
/ZAK/BSET_MV-BELNR =
/ZAK/BSET-BELNR .
/ZAK/BSET_MV-GJAHR =
/ZAK/BSET-GJAHR .
/ZAK/BSET_MV-BUZEI =
/ZAK/BSET-BUZEI .
/ZAK/BSET_MV-BUPER =
/ZAK/BSET-BUPER .
/ZAK/BSET_MV-ZINDEX =
/ZAK/BSET-ZINDEX .
/ZAK/BSET_MV-TTIP =
/ZAK/BSET-TTIP .
/ZAK/BSET_MV-ADODAT =
/ZAK/BSET-ADODAT .
/ZAK/BSET_MV-AD_BUKRS =
/ZAK/BSET-AD_BUKRS .
/ZAK/BSET_MV-MWSKZ =
/ZAK/BSET-MWSKZ .
/ZAK/BSET_MV-KTOSL =
/ZAK/BSET-KTOSL .
<VIM_TOTAL_STRUC> = /ZAK/BSET_MV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/BSET_MV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/BSET_MV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/BSET_MV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BSET WHERE
  BUKRS = /ZAK/BSET_MV-BUKRS AND
  BELNR = /ZAK/BSET_MV-BELNR AND
  GJAHR = /ZAK/BSET_MV-GJAHR AND
  BUZEI = /ZAK/BSET_MV-BUZEI .
    IF SY-SUBRC = 0.
    DELETE /ZAK/BSET .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BSET WHERE
  BUKRS = /ZAK/BSET_MV-BUKRS AND
  BELNR = /ZAK/BSET_MV-BELNR AND
  GJAHR = /ZAK/BSET_MV-GJAHR AND
  BUZEI = /ZAK/BSET_MV-BUZEI .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/BSET.
    ENDIF.
/ZAK/BSET-MANDT =
/ZAK/BSET_MV-MANDT .
/ZAK/BSET-BUKRS =
/ZAK/BSET_MV-BUKRS .
/ZAK/BSET-BELNR =
/ZAK/BSET_MV-BELNR .
/ZAK/BSET-GJAHR =
/ZAK/BSET_MV-GJAHR .
/ZAK/BSET-BUZEI =
/ZAK/BSET_MV-BUZEI .
/ZAK/BSET-BUPER =
/ZAK/BSET_MV-BUPER .
/ZAK/BSET-ZINDEX =
/ZAK/BSET_MV-ZINDEX .
/ZAK/BSET-TTIP =
/ZAK/BSET_MV-TTIP .
/ZAK/BSET-ADODAT =
/ZAK/BSET_MV-ADODAT .
/ZAK/BSET-AD_BUKRS =
/ZAK/BSET_MV-AD_BUKRS .
/ZAK/BSET-MWSKZ =
/ZAK/BSET_MV-MWSKZ .
/ZAK/BSET-KTOSL =
/ZAK/BSET_MV-KTOSL .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/BSET .
    ELSE.
    INSERT /ZAK/BSET .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/BSET_MV-UPD_FLAG,
STATUS_/ZAK/BSET_MV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/BSET_MV.
  SELECT SINGLE * FROM /ZAK/BSET WHERE
BUKRS = /ZAK/BSET_MV-BUKRS AND
BELNR = /ZAK/BSET_MV-BELNR AND
GJAHR = /ZAK/BSET_MV-GJAHR AND
BUZEI = /ZAK/BSET_MV-BUZEI .
/ZAK/BSET_MV-MANDT =
/ZAK/BSET-MANDT .
/ZAK/BSET_MV-BUKRS =
/ZAK/BSET-BUKRS .
/ZAK/BSET_MV-BELNR =
/ZAK/BSET-BELNR .
/ZAK/BSET_MV-GJAHR =
/ZAK/BSET-GJAHR .
/ZAK/BSET_MV-BUZEI =
/ZAK/BSET-BUZEI .
/ZAK/BSET_MV-BUPER =
/ZAK/BSET-BUPER .
/ZAK/BSET_MV-ZINDEX =
/ZAK/BSET-ZINDEX .
/ZAK/BSET_MV-TTIP =
/ZAK/BSET-TTIP .
/ZAK/BSET_MV-ADODAT =
/ZAK/BSET-ADODAT .
/ZAK/BSET_MV-AD_BUKRS =
/ZAK/BSET-AD_BUKRS .
/ZAK/BSET_MV-MWSKZ =
/ZAK/BSET-MWSKZ .
/ZAK/BSET_MV-KTOSL =
/ZAK/BSET-KTOSL .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/BSET_MV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/BSET_MV-BUKRS TO
/ZAK/BSET-BUKRS .
MOVE /ZAK/BSET_MV-BELNR TO
/ZAK/BSET-BELNR .
MOVE /ZAK/BSET_MV-GJAHR TO
/ZAK/BSET-GJAHR .
MOVE /ZAK/BSET_MV-BUZEI TO
/ZAK/BSET-BUZEI .
MOVE /ZAK/BSET_MV-MANDT TO
/ZAK/BSET-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/BSET'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/BSET TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/BSET'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
