*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/AFA_RARANYV................................*
FORM GET_DATA_/ZAK/AFA_RARANYV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/AFA_RARANY WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/AFA_RARANYV .
/ZAK/AFA_RARANYV-MANDT =
/ZAK/AFA_RARANY-MANDT .
/ZAK/AFA_RARANYV-BUKRS =
/ZAK/AFA_RARANY-BUKRS .
/ZAK/AFA_RARANYV-MWSKZ =
/ZAK/AFA_RARANY-MWSKZ .
/ZAK/AFA_RARANYV-KTOSL =
/ZAK/AFA_RARANY-KTOSL .
/ZAK/AFA_RARANYV-DATUM =
/ZAK/AFA_RARANY-DATUM .
/ZAK/AFA_RARANYV-UZEIT =
/ZAK/AFA_RARANY-UZEIT .
/ZAK/AFA_RARANYV-UNAME =
/ZAK/AFA_RARANY-UNAME .
<VIM_TOTAL_STRUC> = /ZAK/AFA_RARANYV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/AFA_RARANYV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/AFA_RARANYV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/AFA_RARANYV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_RARANY WHERE
  BUKRS = /ZAK/AFA_RARANYV-BUKRS AND
  MWSKZ = /ZAK/AFA_RARANYV-MWSKZ AND
  KTOSL = /ZAK/AFA_RARANYV-KTOSL .
    IF SY-SUBRC = 0.
    DELETE /ZAK/AFA_RARANY .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_RARANY WHERE
  BUKRS = /ZAK/AFA_RARANYV-BUKRS AND
  MWSKZ = /ZAK/AFA_RARANYV-MWSKZ AND
  KTOSL = /ZAK/AFA_RARANYV-KTOSL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/AFA_RARANY.
    ENDIF.
/ZAK/AFA_RARANY-MANDT =
/ZAK/AFA_RARANYV-MANDT .
/ZAK/AFA_RARANY-BUKRS =
/ZAK/AFA_RARANYV-BUKRS .
/ZAK/AFA_RARANY-MWSKZ =
/ZAK/AFA_RARANYV-MWSKZ .
/ZAK/AFA_RARANY-KTOSL =
/ZAK/AFA_RARANYV-KTOSL .
/ZAK/AFA_RARANY-DATUM =
/ZAK/AFA_RARANYV-DATUM .
/ZAK/AFA_RARANY-UZEIT =
/ZAK/AFA_RARANYV-UZEIT .
/ZAK/AFA_RARANY-UNAME =
/ZAK/AFA_RARANYV-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/AFA_RARANY .
    ELSE.
    INSERT /ZAK/AFA_RARANY .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/AFA_RARANYV-UPD_FLAG,
STATUS_/ZAK/AFA_RARANYV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/AFA_RARANYV.
  SELECT SINGLE * FROM /ZAK/AFA_RARANY WHERE
BUKRS = /ZAK/AFA_RARANYV-BUKRS AND
MWSKZ = /ZAK/AFA_RARANYV-MWSKZ AND
KTOSL = /ZAK/AFA_RARANYV-KTOSL .
/ZAK/AFA_RARANYV-MANDT =
/ZAK/AFA_RARANY-MANDT .
/ZAK/AFA_RARANYV-BUKRS =
/ZAK/AFA_RARANY-BUKRS .
/ZAK/AFA_RARANYV-MWSKZ =
/ZAK/AFA_RARANY-MWSKZ .
/ZAK/AFA_RARANYV-KTOSL =
/ZAK/AFA_RARANY-KTOSL .
/ZAK/AFA_RARANYV-DATUM =
/ZAK/AFA_RARANY-DATUM .
/ZAK/AFA_RARANYV-UZEIT =
/ZAK/AFA_RARANY-UZEIT .
/ZAK/AFA_RARANYV-UNAME =
/ZAK/AFA_RARANY-UNAME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/AFA_RARANYV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/AFA_RARANYV-BUKRS TO
/ZAK/AFA_RARANY-BUKRS .
MOVE /ZAK/AFA_RARANYV-MWSKZ TO
/ZAK/AFA_RARANY-MWSKZ .
MOVE /ZAK/AFA_RARANYV-KTOSL TO
/ZAK/AFA_RARANY-KTOSL .
MOVE /ZAK/AFA_RARANYV-MANDT TO
/ZAK/AFA_RARANY-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/AFA_RARANY'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/AFA_RARANY TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/AFA_RARANY'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
