PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/AFA_MWSKZSV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/AFA_MWSKZSV-MWSKZ .
    FIELD /ZAK/AFA_MWSKZSV-KTOSL .
    FIELD /ZAK/AFA_MWSKZSV-AS4USER .
    FIELD /ZAK/AFA_MWSKZSV-AS4DATE .
    FIELD /ZAK/AFA_MWSKZSV-AS4TIME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/AFA_MWSKZSV-MWSKZ .
    FIELD /ZAK/AFA_MWSKZSV-KTOSL .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
