PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/SZJA_ABEV_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/SZJA_ABEV_V-BUKRS .
    FIELD /ZAK/SZJA_ABEV_V-BTYPE .
    FIELD /ZAK/SZJA_ABEV_V-BSZNUM .
    FIELD /ZAK/SZJA_ABEV_V-FIELDNAME .
    FIELD /ZAK/SZJA_ABEV_V-ABEVAZ .
    FIELD /ZAK/SZJA_ABEV_V-TARTOZIK .
    FIELD /ZAK/SZJA_ABEV_V-KOVETEL .
    FIELD /ZAK/SZJA_ABEV_V-MWSKZ .
    FIELD /ZAK/SZJA_ABEV_V-AS4USER .
    FIELD /ZAK/SZJA_ABEV_V-AS4DATE .
    FIELD /ZAK/SZJA_ABEV_V-AS4TIME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/SZJA_ABEV_V-BUKRS .
    FIELD /ZAK/SZJA_ABEV_V-BTYPE .
    FIELD /ZAK/SZJA_ABEV_V-BSZNUM .
    FIELD /ZAK/SZJA_ABEV_V-FIELDNAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
