PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/BEVALLB_V CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/BEVALLB_V-BTYPE .
    FIELD /ZAK/BEVALLB_V-ABEVAZ .
    FIELD /ZAK/BEVALLB_V-ABEVTEXT .
    FIELD /ZAK/BEVALLB_V-MANUAL .
    FIELD /ZAK/BEVALLB_V-COLLECT .
    FIELD /ZAK/BEVALLB_V-COLLN .
    FIELD /ZAK/BEVALLB_V-ASZKOT .
    FIELD /ZAK/BEVALLB_V-ABEV_NO .
    FIELD /ZAK/BEVALLB_V-ESDAT_FLAG .
    FIELD /ZAK/BEVALLB_V-ELOJEL .
    FIELD /ZAK/BEVALLB_V-ONYBF .
    FIELD /ZAK/BEVALLB_V-ONYLAPAZON .
    FIELD /ZAK/BEVALLB_V-FOSOR .
    FIELD /ZAK/BEVALLB_V-ADONEM .
    FIELD /ZAK/BEVALLB_V-ADONEM_ONR .
    FIELD /ZAK/BEVALLB_V-ONRPOTL .
    FIELD /ZAK/BEVALLB_V-ELF_ADONSZA .
    FIELD /ZAK/BEVALLB_V-FIELDTYPE .
    FIELD /ZAK/BEVALLB_V-ROUND .
    FIELD /ZAK/BEVALLB_V-SAKNR .
    FIELD /ZAK/BEVALLB_V-SUM_ABEVAZ .
    FIELD /ZAK/BEVALLB_V-GET_ABEVAZ .
    FIELD /ZAK/BEVALLB_V-NYLAPAZON .
    FIELD /ZAK/BEVALLB_V-SORINDEX .
    FIELD /ZAK/BEVALLB_V-ALKMIN .
    FIELD /ZAK/BEVALLB_V-ACTREAD .
    FIELD /ZAK/BEVALLB_V-XMLALL .
    FIELD /ZAK/BEVALLB_V-ONYBE .
    FIELD /ZAK/BEVALLB_V-AFATYP .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/BEVALLB_V-BTYPE .
    FIELD /ZAK/BEVALLB_V-ABEVAZ .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
