*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/AFA_LIFKNMV................................*
FORM GET_DATA_/ZAK/AFA_LIFKNMV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/AFA_LIFKNM WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/AFA_LIFKNMV .
/ZAK/AFA_LIFKNMV-MANDT =
/ZAK/AFA_LIFKNM-MANDT .
/ZAK/AFA_LIFKNMV-KOART =
/ZAK/AFA_LIFKNM-KOART .
/ZAK/AFA_LIFKNMV-LIFKUN =
/ZAK/AFA_LIFKNM-LIFKUN .
/ZAK/AFA_LIFKNMV-NAME1 =
/ZAK/AFA_LIFKNM-NAME1 .
/ZAK/AFA_LIFKNMV-AS4USER =
/ZAK/AFA_LIFKNM-AS4USER .
/ZAK/AFA_LIFKNMV-AS4DATE =
/ZAK/AFA_LIFKNM-AS4DATE .
/ZAK/AFA_LIFKNMV-AS4TIME =
/ZAK/AFA_LIFKNM-AS4TIME .
<VIM_TOTAL_STRUC> = /ZAK/AFA_LIFKNMV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/AFA_LIFKNMV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/AFA_LIFKNMV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/AFA_LIFKNMV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_LIFKNM WHERE
  KOART = /ZAK/AFA_LIFKNMV-KOART AND
  LIFKUN = /ZAK/AFA_LIFKNMV-LIFKUN .
    IF SY-SUBRC = 0.
    DELETE /ZAK/AFA_LIFKNM .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/AFA_LIFKNM WHERE
  KOART = /ZAK/AFA_LIFKNMV-KOART AND
  LIFKUN = /ZAK/AFA_LIFKNMV-LIFKUN .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/AFA_LIFKNM.
    ENDIF.
/ZAK/AFA_LIFKNM-MANDT =
/ZAK/AFA_LIFKNMV-MANDT .
/ZAK/AFA_LIFKNM-KOART =
/ZAK/AFA_LIFKNMV-KOART .
/ZAK/AFA_LIFKNM-LIFKUN =
/ZAK/AFA_LIFKNMV-LIFKUN .
/ZAK/AFA_LIFKNM-NAME1 =
/ZAK/AFA_LIFKNMV-NAME1 .
/ZAK/AFA_LIFKNM-AS4USER =
/ZAK/AFA_LIFKNMV-AS4USER .
/ZAK/AFA_LIFKNM-AS4DATE =
/ZAK/AFA_LIFKNMV-AS4DATE .
/ZAK/AFA_LIFKNM-AS4TIME =
/ZAK/AFA_LIFKNMV-AS4TIME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/AFA_LIFKNM .
    ELSE.
    INSERT /ZAK/AFA_LIFKNM .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/AFA_LIFKNMV-UPD_FLAG,
STATUS_/ZAK/AFA_LIFKNMV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/AFA_LIFKNMV.
  SELECT SINGLE * FROM /ZAK/AFA_LIFKNM WHERE
KOART = /ZAK/AFA_LIFKNMV-KOART AND
LIFKUN = /ZAK/AFA_LIFKNMV-LIFKUN .
/ZAK/AFA_LIFKNMV-MANDT =
/ZAK/AFA_LIFKNM-MANDT .
/ZAK/AFA_LIFKNMV-KOART =
/ZAK/AFA_LIFKNM-KOART .
/ZAK/AFA_LIFKNMV-LIFKUN =
/ZAK/AFA_LIFKNM-LIFKUN .
/ZAK/AFA_LIFKNMV-NAME1 =
/ZAK/AFA_LIFKNM-NAME1 .
/ZAK/AFA_LIFKNMV-AS4USER =
/ZAK/AFA_LIFKNM-AS4USER .
/ZAK/AFA_LIFKNMV-AS4DATE =
/ZAK/AFA_LIFKNM-AS4DATE .
/ZAK/AFA_LIFKNMV-AS4TIME =
/ZAK/AFA_LIFKNM-AS4TIME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/AFA_LIFKNMV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/AFA_LIFKNMV-KOART TO
/ZAK/AFA_LIFKNM-KOART .
MOVE /ZAK/AFA_LIFKNMV-LIFKUN TO
/ZAK/AFA_LIFKNM-LIFKUN .
MOVE /ZAK/AFA_LIFKNMV-MANDT TO
/ZAK/AFA_LIFKNM-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/AFA_LIFKNM'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/AFA_LIFKNM TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/AFA_LIFKNM'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
