*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LUREPID_MVTOP.                " Global Data
  INCLUDE /ZAK/LUREPID_MVUXX.                " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LUREPID_MVF00                      . " subprograms
  INCLUDE /ZAK/LUREPID_MVI00                      . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LUREPID_MVF...                " Subprograms
* INCLUDE /ZAK/LUREPID_MVO...                " PBO-Modules
* INCLUDE /ZAK/LUREPID_MVI...                " PAI-Modules
