PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/ZAK/UREPI_DATAV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /ZAK/UREPI_DATAV-BUKRS .
    FIELD /ZAK/UREPI_DATAV-GJAHR .
    FIELD /ZAK/UREPI_DATAV-UREPF .
    FIELD /ZAK/UREPI_DATAV-ADOMN .
    FIELD /ZAK/UREPI_DATAV-HFORG .
    FIELD /ZAK/UREPI_DATAV-WAERS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /ZAK/UREPI_DATAV-BUKRS .
    FIELD /ZAK/UREPI_DATAV-GJAHR .
    FIELD /ZAK/UREPI_DATAV-UREPF .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
