*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ZAK/BUKRS_MV....................................*
FORM GET_DATA_/ZAK/BUKRS_MV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ZAK/BUKRS WHERE
(VIM_WHERETAB) .
    CLEAR /ZAK/BUKRS_MV .
/ZAK/BUKRS_MV-MANDT =
/ZAK/BUKRS-MANDT .
/ZAK/BUKRS_MV-FI_BUKRS =
/ZAK/BUKRS-FI_BUKRS .
/ZAK/BUKRS_MV-GSBER =
/ZAK/BUKRS-GSBER .
/ZAK/BUKRS_MV-PRCTR =
/ZAK/BUKRS-PRCTR .
/ZAK/BUKRS_MV-AD_BUKRS =
/ZAK/BUKRS-AD_BUKRS .
/ZAK/BUKRS_MV-FDATE =
/ZAK/BUKRS-FDATE .
/ZAK/BUKRS_MV-DATUM =
/ZAK/BUKRS-DATUM .
/ZAK/BUKRS_MV-UZEIT =
/ZAK/BUKRS-UZEIT .
/ZAK/BUKRS_MV-UNAME =
/ZAK/BUKRS-UNAME .
<VIM_TOTAL_STRUC> = /ZAK/BUKRS_MV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ZAK/BUKRS_MV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ZAK/BUKRS_MV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ZAK/BUKRS_MV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BUKRS WHERE
  FI_BUKRS = /ZAK/BUKRS_MV-FI_BUKRS AND
  GSBER = /ZAK/BUKRS_MV-GSBER AND
  PRCTR = /ZAK/BUKRS_MV-PRCTR .
    IF SY-SUBRC = 0.
    DELETE /ZAK/BUKRS .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ZAK/BUKRS WHERE
  FI_BUKRS = /ZAK/BUKRS_MV-FI_BUKRS AND
  GSBER = /ZAK/BUKRS_MV-GSBER AND
  PRCTR = /ZAK/BUKRS_MV-PRCTR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ZAK/BUKRS.
    ENDIF.
/ZAK/BUKRS-MANDT =
/ZAK/BUKRS_MV-MANDT .
/ZAK/BUKRS-FI_BUKRS =
/ZAK/BUKRS_MV-FI_BUKRS .
/ZAK/BUKRS-GSBER =
/ZAK/BUKRS_MV-GSBER .
/ZAK/BUKRS-PRCTR =
/ZAK/BUKRS_MV-PRCTR .
/ZAK/BUKRS-AD_BUKRS =
/ZAK/BUKRS_MV-AD_BUKRS .
/ZAK/BUKRS-FDATE =
/ZAK/BUKRS_MV-FDATE .
/ZAK/BUKRS-DATUM =
/ZAK/BUKRS_MV-DATUM .
/ZAK/BUKRS-UZEIT =
/ZAK/BUKRS_MV-UZEIT .
/ZAK/BUKRS-UNAME =
/ZAK/BUKRS_MV-UNAME .
    IF SY-SUBRC = 0.
    UPDATE /ZAK/BUKRS .
    ELSE.
    INSERT /ZAK/BUKRS .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ZAK/BUKRS_MV-UPD_FLAG,
STATUS_/ZAK/BUKRS_MV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ZAK/BUKRS_MV.
  SELECT SINGLE * FROM /ZAK/BUKRS WHERE
FI_BUKRS = /ZAK/BUKRS_MV-FI_BUKRS AND
GSBER = /ZAK/BUKRS_MV-GSBER AND
PRCTR = /ZAK/BUKRS_MV-PRCTR .
/ZAK/BUKRS_MV-MANDT =
/ZAK/BUKRS-MANDT .
/ZAK/BUKRS_MV-FI_BUKRS =
/ZAK/BUKRS-FI_BUKRS .
/ZAK/BUKRS_MV-GSBER =
/ZAK/BUKRS-GSBER .
/ZAK/BUKRS_MV-PRCTR =
/ZAK/BUKRS-PRCTR .
/ZAK/BUKRS_MV-AD_BUKRS =
/ZAK/BUKRS-AD_BUKRS .
/ZAK/BUKRS_MV-FDATE =
/ZAK/BUKRS-FDATE .
/ZAK/BUKRS_MV-DATUM =
/ZAK/BUKRS-DATUM .
/ZAK/BUKRS_MV-UZEIT =
/ZAK/BUKRS-UZEIT .
/ZAK/BUKRS_MV-UNAME =
/ZAK/BUKRS-UNAME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ZAK/BUKRS_MV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ZAK/BUKRS_MV-FI_BUKRS TO
/ZAK/BUKRS-FI_BUKRS .
MOVE /ZAK/BUKRS_MV-GSBER TO
/ZAK/BUKRS-GSBER .
MOVE /ZAK/BUKRS_MV-PRCTR TO
/ZAK/BUKRS-PRCTR .
MOVE /ZAK/BUKRS_MV-MANDT TO
/ZAK/BUKRS-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ZAK/BUKRS'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ZAK/BUKRS TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ZAK/BUKRS'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
