*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /ZAK/LARANY_FELDTOP.               " Global Data
  INCLUDE /ZAK/LARANY_FELDUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /ZAK/LARANY_FELDF00                     . " subprograms
  INCLUDE /ZAK/LARANY_FELDI00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /ZAK/LARANY_FELDF...               " Subprograms
* INCLUDE /ZAK/LARANY_FELDO...               " PBO-Modules
* INCLUDE /ZAK/LARANY_FELDI...               " PAI-Modules

INCLUDE /ZAK/LARANY_FELDF01.
